insert into GRUPOUSUARIONOTIFICACAO
select HIBERNATE_SEQUENCE.nextval, GRUPOUSUARIO_ID, 'CANCELAMENTO_NFS_ELETRONICA'
from GRUPOUSUARIONOTIFICACAO
where TIPONOTIFICACAO = 'COMUNICACAO_NFS_ELETRONICA';
