INSERT INTO RECURSOSISTEMA VALUES
    (HIBERNATE_SEQUENCE.nextval, 'TRIBUTÁRIO > SIMPLES NACIONAL > ANEXO LEI 1232006 > LISTA',
     '/tributario/simples-nacional/anexo-lei-1232006/lista.xhtml', 0, 'TRIBUTARIO');

INSERT INTO GRUPORECURSOSISTEMA VALUES (HIBERNATE_SEQUENCE.currval, 622038399);

INSERT INTO RECURSOSISTEMA VALUES
(HIBERNATE_SEQUENCE.nextval, 'TRIBUTÁRIO > SIMPLES NACIONAL > ANEXO LEI 1232006 > EDITA',
 '/tributario/simples-nacional/anexo-lei-1232006/edita.xhtml', 0, 'TRIBUTARIO');

INSERT INTO GRUPORECURSOSISTEMA VALUES (HIBERNATE_SEQUENCE.currval, 622038399);

INSERT INTO RECURSOSISTEMA VALUES
(HIBERNATE_SEQUENCE.nextval, 'TRIBUTÁRIO > SIMPLES NACIONAL > ANEXO LEI 1232006 > VISUALIZAR',
 '/tributario/simples-nacional/anexo-lei-1232006/visualizar.xhtml', 0, 'TRIBUTARIO');

INSERT INTO GRUPORECURSOSISTEMA VALUES (HIBERNATE_SEQUENCE.currval, 622038399);

INSERT INTO menu VALUES (HIBERNATE_SEQUENCE.nextval, 'SIMPLES NACIONAL',
                         NULL, (select ID from menu where LABEL = 'CADASTRO TÉCNICO MOBILIÁRIO - C.M.C.'), 75);

INSERT INTO menu VALUES (HIBERNATE_SEQUENCE.nextval, 'ANEXO LEI 123/2006',
                         NULL, (select ID from menu where LABEL = 'SIMPLES NACIONAL'), 10);
