INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES(hibernate_sequence.nextval, 'TRIBUTÁRIO > NOTA FISCAL > FALE CONOSCO (NFS-E)', '/tributario/nfse/faleconosco/listanfse.xhtml', 0, 'TRIBUTARIO');

INSERT INTO MENU (ID, LABEL, CAMINHO, PAI_ID, ORDEM)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'FALE CONOSCO (NFSE)',
'/tributario/nfse/faleconosco/listanfse.xhtml',
(SELECT ID FROM MENU WHERE LABEL = 'NOTA FISCAL' AND CAMINHO IS NULL), 200);

INSERT INTO GRUPORECURSOSISTEMA (GRUPORECURSO_ID, RECURSOSISTEMA_ID)
VALUES ((SELECT ID FROM GRUPORECURSO WHERE NOME = 'TRB - NFS-e - Gerencial'),
(SELECT ID FROM RECURSOSISTEMA WHERE NOME = 'TRIBUTÁRIO > NOTA FISCAL > FALE CONOSCO (NFS-E)'));
