CREATE OR REPLACE FUNCTION FUNC_NOTA_DECLARADA(TIPO_MOVIMENTO VARCHAR, ID_DECLARACAO NUMBER)
    RETURN NUMBER
AS
    ID_DMS NUMBER;
BEGIN
SELECT MAX(DMS.ID)
INTO ID_DMS
FROM DECLARACAOMENSALSERVICO DMS
         INNER JOIN NOTADECLARADA ND ON ND.DECLARACAOMENSALSERVICO_ID = DMS.ID
WHERE DMS.SITUACAO != 'CANCELADO'
  AND DMS.TIPOMOVIMENTO = TIPO_MOVIMENTO
  AND ND.DECLARACAOPRESTACAOSERVICO_ID = ID_DECLARACAO;
IF
(ID_DMS IS NOT NULL) THEN
        RETURN (1);
END IF;

RETURN (0);
END;
