insert into menu (ID, LABEL, CAMINHO, PAI_ID, ORDEM)
values (HIBERNATE_SEQUENCE.nextval, 'RELATÓRIOS', NULL,
(SELECT ID FROM MENU WHERE LABEL = 'ENCERRAMENTO MENSAL DE SERVIÇO'), 999);

UPDATE MENU SET LABEL = 'ENCERRAMENTO MENSAL DE SERVIÇO',
                PAI_ID = (select id from menu where label = 'RELATÓRIOS'
                and PAI_ID = (SELECT ID FROM MENU WHERE LABEL = 'ENCERRAMENTO MENSAL DE SERVIÇO'))
where LABEL = 'RELATÓRIO DE DMS';
