INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
SELECT hibernate_sequence.nextval,
       'TRIBUTÁRIO > NOTA FISCAL > NOTÍCIAS DA NFS-E > LISTA',
       '/tributario/nfse/noticia/lista.xhtml',
       0,
       'TRIBUTARIO'
FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM RECURSOSISTEMA WHERE CAMINHO = '/tributario/nfse/noticia/lista.xhtml');

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
SELECT hibernate_sequence.nextval,
       'TRIBUTÁRIO > NOTA FISCAL > NOTÍCIAS DA NFS-E > EDITA',
       '/tributario/nfse/noticia/edita.xhtml',
       0,
       'TRIBUTARIO'
FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM RECURSOSISTEMA WHERE CAMINHO = '/tributario/nfse/noticia/edita.xhtml');

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
SELECT hibernate_sequence.nextval,
       'TRIBUTÁRIO > NOTA FISCAL > NOTÍCIAS DA NFS-E > VISUALIZAR',
       '/tributario/nfse/noticia/visualizar.xhtml',
       0,
       'TRIBUTARIO'
FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM RECURSOSISTEMA WHERE CAMINHO = '/tributario/nfse/noticia/visualizar.xhtml');


INSERT INTO MENU (ID, LABEL, CAMINHO, PAI_ID, ORDEM)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'NOTÍCIAS DA NFS-E',
        '/tributario/nfse/noticia/lista.xhtml',
        (SELECT ID FROM MENU WHERE LABEL = 'NOTA FISCAL' AND CAMINHO IS NULL), 200);

INSERT INTO GRUPORECURSOSISTEMA (GRUPORECURSO_ID, RECURSOSISTEMA_ID)
VALUES ((SELECT ID FROM GRUPORECURSO WHERE NOME = 'TRB - NFS-e - Gerencial'),
        (SELECT ID FROM RECURSOSISTEMA WHERE CAMINHO LIKE '/tributario/nfse/noticia/lista.xhtml'));
INSERT INTO GRUPORECURSOSISTEMA (GRUPORECURSO_ID, RECURSOSISTEMA_ID)
VALUES ((SELECT ID FROM GRUPORECURSO WHERE NOME = 'TRB - NFS-e - Gerencial'),
        (SELECT ID FROM RECURSOSISTEMA WHERE CAMINHO LIKE '/tributario/nfse/noticia/edita.xhtml'));
INSERT INTO GRUPORECURSOSISTEMA (GRUPORECURSO_ID, RECURSOSISTEMA_ID)
VALUES ((SELECT ID FROM GRUPORECURSO WHERE NOME = 'TRB - NFS-e - Gerencial'),
        (SELECT ID FROM RECURSOSISTEMA WHERE CAMINHO LIKE '/tributario/nfse/noticia/visualizar.xhtml'));
