INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '101', 'Confecção de ficha cadastral', 'CADASTRO', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '102', 'Renovação de ficha cadastral', 'CADASTRO', 'CADA_180_DIAS');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '103', 'Consultas a serviços de proteção ao crédito', 'CADASTRO', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '201', 'Comum, para débito, saque e consultas', 'CARTAO_MAGNETICO', 'CADA_1_DIA');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '202', 'Débito, saque e garantia de cheque-anuidade do contrato',
        'CARTAO_MAGNETICO', 'CADA_1_DIA');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '203', 'Débito, saque e garantia de cheque-confecção do cartão', 'CARTAO_MAGNETICO',
        'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '204', 'Cartão multiplo-nacional-anuidade do contrato', 'CARTAO_MAGNETICO',
        'CADA_30_DIAS');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '205', 'Cartão multiplo-nacional-confecção do cartão', 'CARTAO_MAGNETICO',
        'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '206', 'Cartão multiplo-internacional-anuidade do contrato', 'CARTAO_MAGNETICO',
        'CADA_1_DIA');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '207', 'Cartão multiplo-internacional-confecção do cartão', 'CARTAO_MAGNETICO',
        'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '208', 'Cartão multiplo adicional-nacional-anuidade do contrato',
        'CARTAO_MAGNETICO', 'CADA_1_DIA');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '209', 'Cartão multiplo adicional-nacional-confecção do cartão', 'CARTAO_MAGNETICO',
        'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '210', 'Cartão multiplo adicional-intern.-anuidade do contrato', 'CARTAO_MAGNETICO',
        'CADA_1_DIA');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '211', 'Cartão multiplo adicional-Intern.-confecção do cartão', 'CARTAO_MAGNETICO',
        'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '301', 'Talão-10 folhas', 'CHEQUE', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '302', 'Talão-20 folhas (segundo talão no mês)', 'CHEQUE', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '303', 'Cheque administrativo', 'CHEQUE', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '304', 'Cheque avulso', 'CHEQUE', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '305', 'Cheque devolvido por insuficiência de fundos', 'CHEQUE', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '306', 'Oposição/sustação de pagamento de cheque', 'CHEQUE', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '308', 'Inclusão no Cadastro de Cheques sem Fundo', 'CHEQUE', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '309', 'Exclusão do Cadastro de Cheques sem Fundo', 'CHEQUE', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '310', 'Cobrança de cheque por compensação', 'CHEQUE', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '311', 'Cheque TB (Transferência Bancária sem CPMF)', 'CHEQUE', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '401', 'Abertura de conta', 'CONTA_CORRENTE', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '402', 'Manutenção de conta ativa', 'CONTA_CORRENTE', 'CADA_30_DIAS');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '403', 'Manutenção de conta inativa', 'CONTA_CORRENTE', 'CADA_1_DIA');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '404', 'Adiant. a deposit., incl. excesso limite de ch. especial', 'CONTA_CORRENTE',
        'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '405', 'Concessão de cheque especial/conta garantida', 'CONTA_CORRENTE',
        'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '406', 'Renovação de cheque especial/conta garantida', 'CONTA_CORRENTE',
        'CADA_30_DIAS');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '407', 'Débito autorizado em conta-corrente', 'CONTA_CORRENTE', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '408', 'Banco domestico-conta principal (com limite de acessos)', 'CONTA_CORRENTE',
        'CADA_1_DIA');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '409', 'Banco doméstico-conta secundária (com limite de acessos)', 'CONTA_CORRENTE',
        'CADA_1_DIA');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '501', 'Saque em caixa automática externa/banco 24 horas', 'MOVIMENTACAO_RECURSOS',
        'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '502', 'Emissão de DOC C', 'MOVIMENTACAO_RECURSOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '503', 'Emissão de DOC D', 'MOVIMENTACAO_RECURSOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '504', 'Ordem de Pagamento', 'MOVIMENTACAO_RECURSOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '505', 'Depósito em outra agência', 'MOVIMENTACAO_RECURSOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '506', 'Transferência Eletrônica Disponível - TED', 'MOVIMENTACAO_RECURSOS',
        'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '601', 'Em terminal eletrônico', 'EXTRATO_CONTA', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '602', 'Por outros meios', 'EXTRATO_CONTA', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '603', 'Cópias de microfilmes, microfichas ou assemelhados', 'EXTRATO_CONTA',
        'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '701', 'Entrada por borderô (listagem de titulos)', 'COBRANCA', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '702', 'Entrada por meio magnético', 'COBRANCA', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '703', 'Entrada sem registro - por boleto emitido pelo cliente', 'COBRANCA',
        'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '704', 'Manutenção de título vencido', 'COBRANCA', 'CADA_30_DIAS');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '705', 'Envio para protesto', 'COBRANCA', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '706', 'Sustação de protesto', 'COBRANCA', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '707', 'Devolução de título', 'COBRANCA', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '801', 'Abertura de crédito', 'CREDITOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '802', 'Renegociação de dívida', 'CREDITOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '803', 'Substituição de garantia', 'CREDITOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '804', 'Custódia de cheque pré-datado', 'CREDITOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '805', 'Rescisão Contratual (Quitação Antecipada)', 'CREDITOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '901', 'Segunda via de documento', 'OUTROS_SERVICOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '902', 'Ressarcimento de despesas-telefonema', 'OUTROS_SERVICOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '903', 'Ressarcimento de despesas-fax', 'OUTROS_SERVICOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '904', 'Envelopamento de documentos', 'OUTROS_SERVICOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '905', 'Pagamento de funcionários via relação', 'OUTROS_SERVICOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '906', 'Pagamento de funcionários via meio magnético', 'OUTROS_SERVICOS',
        'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1001', 'Exportação: Edição de Contrato de Câmbio', 'CAPITAIS_ESTRANGEIROS_CAMBIO',
        'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1002', 'Exportação: Edição de Contrato de Câmbio via Internet',
        'CAPITAIS_ESTRANGEIROS_CAMBIO', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1003', 'Exportação: Liquidação com Ordem de Pagamento',
        'CAPITAIS_ESTRANGEIROS_CAMBIO', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1004', 'Exportação: Conferência de Documentos', 'CAPITAIS_ESTRANGEIROS_CAMBIO',
        'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1005', 'Exportação: Câmbio Simplicado (todas as despesas do cliente no Banco)',
        'CAPITAIS_ESTRANGEIROS_CAMBIO', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1006', 'Importação: Edição de Contrato de Câmbio', 'CAPITAIS_ESTRANGEIROS_CAMBIO',
        'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1007', 'Importação: Emissão de Ordem de Pagamento', 'CAPITAIS_ESTRANGEIROS_CAMBIO',
        'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1008', 'Importação: Demais Tarifas (Não incluem despesas no Exteior)',
        'CAPITAIS_ESTRANGEIROS_CAMBIO', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1009', 'Importação: Câmbio Simplificado(Todas as despesas do cliente no Banco)',
        'CAPITAIS_ESTRANGEIROS_CAMBIO', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1010', 'Financeiro -Ingresso de Recursos: Edição de Contrato de Câmbio',
        'CAPITAIS_ESTRANGEIROS_CAMBIO', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1011', 'Financeiro-Ingresso de Recursos:Edição de Cont. de Câmbio Via Internet',
        'CAPITAIS_ESTRANGEIROS_CAMBIO', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1012', 'Financeiro -Ingresso de Recursos: Liquidação com Ordem de
pagamento', 'CAPITAIS_ESTRANGEIROS_CAMBIO', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1013', 'Financeiro - Ingresso de Recursos: Confecção de ROF',
        'CAPITAIS_ESTRANGEIROS_CAMBIO', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1014', 'Financeiro - Ingresso de Recursos : Confecção de esquema de ROF',
        'CAPITAIS_ESTRANGEIROS_CAMBIO', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1015', 'Financeiro - Ingresso de Recursos: Confecção de Cadastro no Cademp',
        'CAPITAIS_ESTRANGEIROS_CAMBIO', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1016', 'Financeiro -Remessa de Recursos: Edição de Contrato de Câmbio',
        'CAPITAIS_ESTRANGEIROS_CAMBIO', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1017', 'Financeiro-Remessa de Recursos: Edição de Cont. de Câmbio Via Internet',
        'CAPITAIS_ESTRANGEIROS_CAMBIO', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1018', 'Financeiro - Remessa de Recursos: Emissão de Ordem de Pagamento',
        'CAPITAIS_ESTRANGEIROS_CAMBIO', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1019', 'Financeiro - Remessa de Recursos: Alteração de ROF',
        'CAPITAIS_ESTRANGEIROS_CAMBIO', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1101', 'Confecção de cadastro para início de relacionamento - CADASTRO',
        'CADASTRO', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1201', 'CARTÃO - Fornecimento de 2º via de cartão com função débito',
        'CONTA_DEPOSITOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1202', 'CARTÃO - Fornec. de 2ª via de cartão com função mov. conta de poupança',
        'CONTA_DEPOSITOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1203', 'CHEQUE - Exclusão do Cadastro de Emitentes de Cheques sem Fundo (CCF)',
        'CONTA_DEPOSITOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1204', 'CHEQUE - Contra-ordem e oposição ao pagamento de cheque',
        'CONTA_DEPOSITOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1205', 'CHEQUE - Fornecimento de folhas de cheque', 'CONTA_DEPOSITOS',
        'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1206', 'CHEQUE - Cheque Administrativo', 'CONTA_DEPOSITOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1207', 'CHEQUE - Cheque de transferência bancária_(TB e TBG)', 'CONTA_DEPOSITOS',
        'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1208', 'CHEQUE - Cheque Visado', 'CONTA_DEPOSITOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1209', 'Saque de conta de depósitos à vista e de poupança - SAQUE pessoal',
        'CONTA_DEPOSITOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1210', 'Saque de conta de depósitos à vista e de poupança - SAQUE Terminal',
        'CONTA_DEPOSITOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1211', 'Saque de conta de dep. à vista e de poupança - SAQUE
correspondente', 'CONTA_DEPOSITOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1212', 'DEPÓSITO - Depósito Identificado', 'CONTA_DEPOSITOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1213', 'Forn. de ext. de um periodo conta dep. à vista e poup. - EXTRATO (P)',
        'CONTA_DEPOSITOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1214', 'Forn. de ext. de um periodo conta dep. à vista e poup. - EXTRATO (E)',
        'CONTA_DEPOSITOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1215', 'Forn. de ext. de um periodo conta dep. à vista e poup. - EXTRATO (C)',
        'CONTA_DEPOSITOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1216', 'Ext. mensal de conta de dep. à vista e poup. p/um período - EXTRATO(P)',
        'CONTA_DEPOSITOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1217', 'Ext. mensal de conta de dep. à vista e Poup. p/um período -
EXTRATO(E)', 'CONTA_DEPOSITOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1218', 'Ext. mensal de conta de dep. à vista e poup. p/um período -
EXTRATO(C)', 'CONTA_DEPOSITOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1219', 'Fornecimento de cópia de microfilme, microficha ou assemelhado',
        'CONTA_DEPOSITOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1301', 'Transferência por meio de DOC/TED - DOC/TED pessoal',
        'TRANSFERENCIA_RECURSOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1302', 'Transferência por meio de DOC/TED - DOC/TED eletrônico',
        'TRANSFERENCIA_RECURSOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1303', 'Transferência de recursos por meio de DOC/TED - DOC/TED internet',
        'TRANSFERENCIA_RECURSOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1304', 'Transferência agendada por meio de DOC/TED - DOC/TED
agendado(P)', 'TRANSFERENCIA_RECURSOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1305', 'Transferência agendada por meio de DOC/TED - DOC/TED
agendado(E)', 'TRANSFERENCIA_RECURSOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1306', 'Transferência agendada por meio de DOC/TED - DOC/TED agendado(I)',
        'TRANSFERENCIA_RECURSOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1307', 'Transferência entre contas na própria instituição-
TRANSF.RECURSOS(P)', 'TRANSFERENCIA_RECURSOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1308', 'Transferência entre contas na própria instituição- TRANSF.RECURSOS(E/I)',
        'TRANSFERENCIA_RECURSOS', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1309', 'Ordem de Pagamento - ORDEM PAGAMENTO', 'TRANSFERENCIA_RECURSOS',
        'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1310', 'Transferência por meio de DOC - DOC Pessoal', 'TRANSFERENCIA_RECURSOS',
        'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1311', 'Transferência por meio de DOC - DOC eletrônico', 'TRANSFERENCIA_RECURSOS',
        'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1312', 'Transferência por meio de DOC - DOC internet', 'TRANSFERENCIA_RECURSOS',
        'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1313', 'Transferência por meio de TED - TED pessoal', 'TRANSFERENCIA_RECURSOS',
        'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1314', 'Transferência por meio de TED - TED eletrônico', 'TRANSFERENCIA_RECURSOS',
        'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1315', 'Transferência por meio de TED - TED internet', 'TRANSFERENCIA_RECURSOS',
        'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1401', 'Concessão de adiantamento a depositante - ADIANT. DEPOSITANTE',
        'OPERACOES_CREDITO_ARRENDAMENTO_MERCANTIL', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1501', 'PACOTE PADRONIZADO PESSOA FÍSICA', 'PACOTE_PADRONIZADO_PESSOA_NATURAL',
        'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1601', 'Anuidade - cartão básico nacional', 'CARTAO_CREDITO', 'CADA_30_DIAS');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1602', 'Fornecimento de 2ª via de cartão com função crédito', 'CARTAO_CREDITO',
        'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1603', 'Utilização de canais de atend. para retirada em espécie - no país',
        'CARTAO_CREDITO', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1604', 'Pagamento de contas utilizando a função crédito em espécie',
        'CARTAO_CREDITO', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1605', 'Avaliação emergencial de crédito', 'CARTAO_CREDITO', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1606', 'Anuidade - cartão básico internacional', 'CARTAO_CREDITO', 'CADA_1_DIA');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1607', 'Utilização de canais de atend. para retirada em espécie - no exterior',
        'CARTAO_CREDITO', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1701', 'Venda de moeda estrangeira - espécie', 'OPERACAO_CAMBIO_MANUAL',
        'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1702', 'Venda de moeda estrangeira - cheque de viagem', 'OPERACAO_CAMBIO_MANUAL',
        'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1703', 'Venda de moeda estrangeira - cartão pré-pago - emissão e carga',
        'OPERACAO_CAMBIO_MANUAL', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1704', 'Venda de moeda estrangeira - cartão pré-pago - recarga',
        'OPERACAO_CAMBIO_MANUAL', 'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1705', 'Compra de moeda estrangeira - espécie', 'OPERACAO_CAMBIO_MANUAL',
        'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1706', 'Compra de moeda estrangeira - cheque de viagem', 'OPERACAO_CAMBIO_MANUAL',
        'POR_EVENTO');
INSERT INTO TARIFABANCARIA (ID, CODIGO, DESCRICAO, GRUPO, PERIODICIDADE)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '1707', 'Compra de moeda estrangeira - cartão pré-pago', 'OPERACAO_CAMBIO_MANUAL',
        'POR_EVENTO');
