INSERT INTO NFSE_USER_AUTHORITY (ID, USER_ID, NFSEAUTHORITY_ID)
SELECT HIBERNATE_SEQUENCE.NEXTVAL, UW.ID, NA.ID
   FROM USUARIOWEB UW
  INNER JOIN NFSE_AUTHORITY NA ON NA.NAME IN ('ROLE_CONTRIBUINTE', 'ROLE_USER')
WHERE NOT EXISTS(SELECT 1 FROM NFSE_USER_AUTHORITY A WHERE A.USER_ID = UW.ID);
