INSERT INTO TIPOINSTITUICAOFINANCEIRA (ID, CODIGO, DESCRICAO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'U', 'Bancos Múltiplos');
INSERT INTO TIPOINSTITUICAOFINANCEIRA (ID, CODIGO, DESCRICAO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'B', 'Bancos Comerciais e Banco de Câmbio');
INSERT INTO TIPOINSTITUICAOFINANCEIRA (ID, CODIGO, DESCRICAO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'D', 'Bancos de Desenvolvimento');
INSERT INTO TIPOINSTITUICAOFINANCEIRA (ID, CODIGO, DESCRICAO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'K', 'Agências de Fomento ou de Desenvolvimento');
INSERT INTO TIPOINSTITUICAOFINANCEIRA (ID, CODIGO, DESCRICAO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'I', 'Bancos de Investimentos');
INSERT INTO TIPOINSTITUICAOFINANCEIRA (ID, CODIGO, DESCRICAO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'F', 'Sociedades de Crédito, Financiamento e Investimento');
INSERT INTO TIPOINSTITUICAOFINANCEIRA (ID, CODIGO, DESCRICAO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'J', 'Sociedades de Crédito ao Microempreendedor');
INSERT INTO TIPOINSTITUICAOFINANCEIRA (ID, CODIGO, DESCRICAO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'A', 'Sociedades de Arrendamento Mercantil');
INSERT INTO TIPOINSTITUICAOFINANCEIRA (ID, CODIGO, DESCRICAO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'C', 'Sociedades Corretoras de Títulos e Valores Mobiliários e Câmbio');
INSERT INTO TIPOINSTITUICAOFINANCEIRA (ID, CODIGO, DESCRICAO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'T', 'Sociedades Distribuidoras de Títulos e Valores Mobiliários');
INSERT INTO TIPOINSTITUICAOFINANCEIRA (ID, CODIGO, DESCRICAO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'S', 'Sociedades de Crédito Imobiliário e Associações de Poupança e Empréstimo');
INSERT INTO TIPOINSTITUICAOFINANCEIRA (ID, CODIGO, DESCRICAO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'W', 'Companhias Hipotecárias');
INSERT INTO TIPOINSTITUICAOFINANCEIRA (ID, CODIGO, DESCRICAO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'E', 'Caixas Econômicas');
INSERT INTO TIPOINSTITUICAOFINANCEIRA (ID, CODIGO, DESCRICAO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'R', 'Cooperativas de Crédito');
INSERT INTO TIPOINSTITUICAOFINANCEIRA (ID, CODIGO, DESCRICAO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'L', 'Banco do Brasil S.A');
INSERT INTO TIPOINSTITUICAOFINANCEIRA (ID, CODIGO, DESCRICAO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'M', 'Caixa Econômica Federal');
INSERT INTO TIPOINSTITUICAOFINANCEIRA (ID, CODIGO, DESCRICAO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'N', 'Banco Nacional de Desenvolvimento Econômico e Social');
INSERT INTO TIPOINSTITUICAOFINANCEIRA (ID, CODIGO, DESCRICAO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'H', 'Administradoras de Consórcio');
INSERT INTO TIPOINSTITUICAOFINANCEIRA (ID, CODIGO, DESCRICAO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'Z', 'Empresas em Liquidação Extrajudicial');
