INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5101', 'Prestação de serviços de agenciamento / intermediação nas operações de repasse de
linhas de crédito com recursos internos ou externos', 'AGENCIAMENTO_INTERMEDIACAO_EM_OPERACOES_CREDITO', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5102',
        'Prestação de serviços de agenciamento / intermediação nas operações de câmbio',
        'AGENCIAMENTO_INTERMEDIACAO_EM_OPERACOES_CAMBIO', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5103', 'Prestação de serviços de agenciamento / intermediação na venda de seguros para terceiros
(empresas ligadas ou não)', 'AGENCIAMENTO_INTERMEDIACAO_VENDA_SEGUROS', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5104',
        'Prestação de serviços de agenciamento / intermediação na venda de turismo para terceiros (empresas ligadas ou não)',
        'AGENCIAMENTO_INTERMEDIACAO_VENDA_SERVICOS_TURISMO', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5105',
        'Prestação de serviços de agenciamento / intermediação na venda de cartões de crédito para terceiros (empresas ligadas ou não)',
        'AGENCIAMENTO_INTERMEDIACAO_VENDA_CARTOES_CREDITO', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5106',
        'Prestação de serviços de agenciamento na venda de títulos de capitalização para terceiros (empresas ligadas ou não)',
        'AGENCIAMENTO_INTERMEDIACAO_VENDA_TITULOS_CAPITALIZACAO', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5107',
        'Prestação de serviços de agenciamento / intermediação na venda de planos de saúde para terceiros (empresas ligadas ou não)',
        'AGENCIAMENTO_INTERMEDIACAO_VENDA_PLANOS_SAUDE', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5108',
        'Prestação de serviços de agenciamento / intermediação na venda de arrendamento mercantil - “leasing” para terceiros (empresas ligadas ou não)',
        'AGENCIAMENTO_INTERMEDIACAO_VENDA_ARRENDAMENTO_MERCANTIL', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5109',
        'Prestação de serviços de agenciamento / intermediação na venda de planos de previdência privada para terceiros (empresas ligadas ou não)',
        'AGENCIAMENTO_INTERMEDIACAO_VENDA_PREVIDENCIA_PRIVADA', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5110', 'Prestação de serviços de agenciamento / intermediação de programas diversos promovidos
por terceiros (empresas ligadas ou não), tais como programas de milhagem de cartões',
        'AGENCIAMENTO_INTERMEDIACAO_PROGRAMAS', 1);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5111',
        'Prestação de serviços de agenciamento / intermediação para terceiros não especificados nos itens anteriores',
        'AGENCIAMENTO_INTERMEDIACAO_GERAL', 1);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5201',
        'Prestação de serviços de intermediação de contratos na Bolsa de Mercadorias e Futuros',
        'INTERMEDIACAO_CONTRATOS_BMF', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5202', 'Prestação de serviços de intermediação de títulos',
        'INTERMEDIACAO_TITULOS', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5203',
        'Prestação de serviços de intermediação na venda de cotas de fundos e clubes de investimento',
        'INTERMEDIACAO_VENDA_CONTAS_FUNDOS_CLUBES_INVESTIMENTO', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5204', 'Prestação de serviços de intermediação na compra e venda de ações',
        'INTERMEDIACAO_COMPRA_VENDA_ACOES', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5205', 'Prestação de serviços de intermediação na venda de bens imóveis',
        'INTERMEDIACAO_BENS_IMOVEIS', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5206',
        'Prestação de serviços de Intermediação de bens não especificados nos itens anteriores', 'INTERMEDIACAO_BENS',
        1);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5301',
        'Prestação de serviços de colocação de títulos e valores mobiliários no mercado para companhias abertas',
        'COLOCACAO_TITULOS_VALORES_MOBILIARIOS', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5302', 'Prestação de serviços de colocação no mercado de cotas de fundos e clubes de
investimento', 'COLOCACAO_COTAS_FUNDOS_CLUBE_INVESTIMENTO', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5303',
        'Prestação de serviços de distribuição de títulos e valores mobiliários no mercado para companhias abertas',
        'DISTRIBUICAO_TITULOS_VALORES_MOBILIARIOS', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5401', 'Prestação de serviços de corretagem de câmbio', 'CORRETAGEM_CAMBIO', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5402', 'Prestação de serviços de corretagem de operações em Bolsas',
        'CORRETAGEM_OPERACOES_BOLSA', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5403', 'Prestação de serviços de corretagem no mercado de capitais',
        'CORRETAGEM_BENS', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5501',
        'Prestação de serviços de administração de Programas voltados para a constituição de fundos para o financiamento de setores e atividades específicas.',
        'ADMINISTRACAO_PROGRAMAS_OFICIAIS', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5502', 'Prestação de serviços de administração de loterias',
        'ADMINISTRACAO_LOTERIAS', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5503', 'Prestação de serviços de administração de Sociedades de Investimento',
        'ADMINISTRACAO_SOCIEDADE_INVESTIMENTO', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5504', 'Prestação de serviços de administração de Consórcios',
        'ADMINISTRACAO_CONSORCIOS', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5505',
        'Prestação de serviços de administração de dívidas das várias esferas de Governo e de órgãos governamentais',
        'ADMINISTRACAO_DIVIDAS_SETOR_PUBLICO', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5506',
        'Prestação de serviços de administração de fundos e programas do Setor Público, cujos recursos são oriundos de fundos públicos.',
        'ADMINISTRACAO_FUNDOS_PROGRAMAS_SETOR_PUBLICO', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5507', 'Prestação de serviços de administração de fundos e programas do Setor Privado, cujos
recursos são oriundos de fundos privados.', 'ADMINISTRACAO_FUNDOS_PROGRAMAS_SETOR_PRIVADO', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5508', 'Prestação de serviços de administração de sistema de negociação de ativos',
        'ADMINISTRACAO_SISTEMAS_NEGOCIACAO_ATIVOS', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5509', 'Prestação de serviços de administração da custódia de títulos',
        'ADMINISTRACAO_CUSTODIA_TITULOS', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5510', 'Prestação de serviços de administração de carteiras de clientes',
        'ADMINISTRACAO_CARTEIRA_CLIENTES', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5511', 'Prestação de serviços de administração de fundos de desenvolvimento',
        'ADMINISTRACAO_FUNDOS_DESENVOLVIMENTO', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5512',
        'Prestação de serviços de administração de repasses de recursos, tais como: FINAME, BNDES etc.',
        'ADMINISTRACAO_REPASSES', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5513', 'Prestação de serviços de administração de negócios de investidores não residentes no país,
atuando em seu nome em diversos atos negociais', 'REPRESENTACAO_INVESTIDOR_NAO_RESIDENTE', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5514',
        'Prestação de serviços de gestão de negócios de terceiros (fluxo de caixa, recebimentos, pagamentos, etc.)',
        'SERVICO_TESOURARIA_TERCEIRO', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5515', 'Prestação de serviços de administração de bens e negócios de terceiros não especificados
nos itens anteriores', 'ADMINISTRACAO_BENS_NEGOCIOS_TERCEIROS', 1);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5601', 'Prestação de serviços de assessoria e consultoria em Comércio Exterior',
        'SERVICO_ACESSORIA_CONSULTORIA_COMERCIO_EXTERIOR', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5602',
        'Prestação de serviços de assessoria e consultoria em carteiras de investimento',
        'SERVICO_ACESSORIA_CONSULTORIA_CARTEIRAS_INVESTIMENTO', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5603', 'Prestação de serviços de consultoria a clientes, na utilização de softwares específicos, tais
como de conciliação bancária, gerenciamento de contas, rotinas de pagamentos etc.',
        'SERVICO_CONSULTORIA_UTILIZACAO_SOFTWARE', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5604',
        'Prestação de serviços de assessoria financeira em operações de fusão, incorporação, reestruturação financeira, aquisições e afins',
        'SERVICO_ACESSORIA_FINANCEIRA', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5605',
        'Prestação de serviços de assessoria e consultoria não especificados nos itens anteriores',
        'SERVICO_ACESSORIA_CONSULTORIA', 1);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5701', 'Prestação de serviços de processamento de dados para terceiros (empresas ligadas ou
não)', 'PROCESSAMENTO_DADOS', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5801',
        'Prestação de serviços nas compras no exterior efetuadas com a utilização de cartões',
        'COMISSOES_COMPRAS_CARTAO_EXTERIOR', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '5901', 'Prestação de serviços de captação / repasse de recursos para terceiros (empresas ligadas
ou não)', 'CAPTACAO_REPASSE_RECURSOS', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '6001', 'Comissão sobre o valor do negócio leiloado, credenciamento',
        'COMISSAO_LEILOES_ELETRONICOS', 0);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '6101',
        'Serviços relacionados à transferência de valores, dados, pagamentos e similares tais como recarga de créditos de celulares, cartão refeição, cartão de transporte, outros',
        'SERVICOS_RELACIONADOS_TRANSFERENCIAS', 1);
INSERT INTO PRODUTOSERVICOBANCARIO (ID, CODIGO, DESCRICAO, GRUPO, OBRIGADESCRICAOCOMPLEMENTAR)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '9001', 'Outros serviços prestados não codificados nesta tabela', 'OUTROS', 1);
