INSERT INTO TIPODOCSERVICODECLARADO (ID, DESCRICAO, SERIE, SUBSERIE, ATIVO, CODIGO) VALUES (HIBERNATE_SEQUENCE.nextval, 'NFS-e', 'NFSE', null, 1, 1);
INSERT INTO TIPODOCSERVICODECLARADO (ID, DESCRICAO, SERIE, SUBSERIE, ATIVO, CODIGO) VALUES (HIBERNATE_SEQUENCE.nextval, 'NOTA FISCAL', 'NF', null, 1, 2);
INSERT INTO TIPODOCSERVICODECLARADO (ID, DESCRICAO, SERIE, SUBSERIE, ATIVO, CODIGO) VALUES (HIBERNATE_SEQUENCE.nextval, 'RPA', 'RPA', null, 1, 3);
INSERT INTO TIPODOCSERVICODECLARADO (ID, DESCRICAO, SERIE, SUBSERIE, ATIVO, CODIGO) VALUES (HIBERNATE_SEQUENCE.nextval, 'OUTROS', 'OUT', null, 1, 4);
