UPDATE DECLARACAOPRESTACAOSERVICO DEC
SET TOTALSERVICOS = (SELECT SUM(IDS.QUANTIDADE * IDS.VALORSERVICO)
						FROM ITEMDECLARACAOSERVICO IDS
					 WHERE IDS.DECLARACAOPRESTACAOSERVICO_ID = DEC.ID)
WHERE DEC.COMPETENCIA >= TO_DATE('01/02/2020');


UPDATE DECLARACAOPRESTACAOSERVICO DEC
SET TOTALNOTA = TOTALSERVICOS - COALESCE(DESCONTOSCONDICIONAIS, 0) - COALESCE(DESCONTOSINCONDICIONAIS, 0)
WHERE DEC.COMPETENCIA >= TO_DATE('01/02/2020');


UPDATE DECLARACAOPRESTACAOSERVICO DEC
SET BASECALCULO = TOTALSERVICOS - COALESCE(DESCONTOSCONDICIONAIS, 0) - COALESCE(DEDUCOESLEGAIS, 0)
WHERE DEC.COMPETENCIA >= TO_DATE('01/02/2020');

UPDATE DECLARACAOPRESTACAOSERVICO DEC
SET VALORLIQUIDO = TOTALNOTA - (SELECT COALESCE(INSS, 0) + COALESCE(COFINS, 0) + COALESCE(IRRF, 0) +
									COALESCE(CSLL, 0) + COALESCE(CPP, 0) + COALESCE(OUTRASRETENCOES, 0)
   									   FROM TRIBUTOSFEDERAIS T
   									WHERE T.ID = DEC.TRIBUTOSFEDERAIS_ID) -
   									(CASE WHEN DEC.NATUREZAOPERACAO != 'TRIBUTACAO_FORA_MUNICIPIO' AND DEC.ISSRETIDO = 1 THEN DEC.ISSCALCULADO
   									      ELSE 0 END)
WHERE DEC.COMPETENCIA >= TO_DATE('01/02/2020');
