INSERT INTO DADOSPESSOAISNFSE (ID, CPFCNPJ, NOMERAZAOSOCIAL, EMAIL, INSCRICAOESTADUALRG,
TELEFONE, CELULAR, CEP, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, MUNICIPIO, PAIS, INSCRICAOMUNICIPAL, USUARIO_ID)
SELECT
      HIBERNATE_SEQUENCE.NEXTVAL,
      COALESCE(PF.CPF, PJ.CNPJ) AS CPF_CNPJ,
      COALESCE(PF.NOME, PJ.RAZAOSOCIAL) AS NOME_RAZAO,
      P.EMAIL AS EMAIL,
      COALESCE(PJ.INSCRICAOESTADUAL, (SELECT MAX(RG.NUMERO)
                                         FROM DOCUMENTOPESSOAL DP
									    INNER JOIN RG ON RG.ID = DP.ID
								      WHERE DP.PESSOAFISICA_ID = PF.ID)) AS INSCRICAO_RG,
	  (SELECT MAX(T.TELEFONE)
	     FROM TELEFONE T
       WHERE T.PESSOA_ID = P.ID
	     AND T.TIPOFONE = 'FIXO'
	  ) AS TELEFONE,
	  (SELECT MAX(T.TELEFONE)
	      FROM TELEFONE T
       WHERE T.PESSOA_ID = P.ID
	     AND T.TIPOFONE = 'CELULAR'
	  ) AS CELULAR,
	  EC.CEP,
	  EC.LOGRADOURO,
	  EC.NUMERO,
	  EC.COMPLEMENTO,
	  EC.BAIRRO,
	  EC.LOCALIDADE,
	  EC.UF,
	  PJ.INSCRICAOMUNICIPAL,
	  UW.ID
   FROM USUARIOWEB UW
  INNER JOIN PESSOA P ON P.ID = UW.PESSOA_ID
  LEFT JOIN PESSOAFISICA PF ON PF.ID = UW.PESSOA_ID
  LEFT JOIN PESSOAJURIDICA PJ ON PJ.ID = UW.PESSOA_ID
  LEFT JOIN ENDERECOCORREIO EC ON EC.ID = P.ENDERECOPRINCIPAL_ID;

UPDATE USUARIOWEB SET DADOSPESSOAIS_ID = (SELECT MAX(ID) FROM DADOSPESSOAISNFSE WHERE USUARIO_ID = USUARIOWEB.ID);
