INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES(hibernate_sequence.nextval, 'TRIBUTÁRIO > NOTA FISCAL > NOTAS FISCAIS > EDITAR',
       '/tributario/nfse/nfse/edita.xhtml', 0, 'TRIBUTARIO');

INSERT INTO GRUPORECURSOSISTEMA (GRUPORECURSO_ID, RECURSOSISTEMA_ID)
VALUES ((SELECT ID FROM GRUPORECURSO WHERE NOME = 'TRB - NFS-e - Gerencial'),
(SELECT ID FROM RECURSOSISTEMA WHERE CAMINHO = '/tributario/nfse/nfse/edita.xhtml'));
