UPDATE FALECONOSCO SET ORIGEMFALECONOSCO = 'NFSE'
WHERE ID IN (SELECT REGEXP_REPLACE(LINK, '[^0-9]*', '') FROM NOTIFICACAO N WHERE N.TIPONOTIFICACAO = 'FALE_CONOSCO_PORTAL_NFSE');

UPDATE FALECONOSCO SET DATAENVIO = (SELECT N.CRIADOEM FROM NOTIFICACAO N
WHERE N.TIPONOTIFICACAO = 'FALE_CONOSCO_PORTAL_NFSE' AND REGEXP_REPLACE(N.LINK, '[^0-9]*', '') = FALECONOSCO.ID)
WHERE TIPOFALECONOSCO = 'NFSE';
