update pais set codigo = 76, NOME = 'Brasil', sigla = 'BRA' where lower(nome) = 'brasil';
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 533, 'Aruba', 'ABW');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 4, 'Afeganistão', 'AFG');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 24, 'Angola', 'AGO');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 660, 'Anguilla', 'AIA');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 248, 'Åland, Ilhas', 'ALA');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 8, 'Albânia', 'ALB');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 20, 'Andorra', 'AND');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 784, 'Emirados Árabes Unidos', 'ARE');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 32, 'Argentina', 'ARG');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 51, 'Armênia', 'ARM');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 16, 'Samoa Americana', 'ASM');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 10, 'Antártida', 'ATA');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 260, 'Terras Austrais e Antárticas Francesas (TAAF)', 'ATF');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 28, 'Antígua e Barbuda', 'ATG');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 36, 'Austrália', 'AUS');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 40, 'Áustria', 'AUT');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 31, 'Azerbaijão', 'AZE');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 108, 'Burundi', 'BDI');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 56, 'Bélgica', 'BEL');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 204, 'Benim', 'BEN');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 535, 'Bonaire, Santo Eustáquio e Saba', 'BES');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 854, 'Burkina Faso', 'BFA');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 50, 'Bangladesh', 'BGD');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 100, 'Bulgária', 'BGR');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 48, 'Bahrain', 'BHR');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 44, 'Bahamas', 'BHS');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 70, 'Bósnia e Herzegovina', 'BIH');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 652, 'São Bartolomeu', 'BLM');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 112, 'Bielorrússia', 'BLR');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 84, 'Belize', 'BLZ');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 60, 'Bermudas', 'BMU');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 68, 'Bolívia', 'BOL');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 52, 'Barbados', 'BRB');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 96, 'Brunei', 'BRN');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 64, 'Butão', 'BTN');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 74, 'Bouvet, Ilha', 'BVT');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 72, 'Botswana', 'BWA');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 140, 'Centro-Africana, República', 'CAF');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 124, 'Canadá', 'CAN');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 166, 'Cocos, Ilhas', 'CCK');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 756, 'Suíça', 'CHE');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 152, 'Chile', 'CHL');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 156, 'China', 'CHN');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 384, 'Costa do Marfim', 'CIV');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 120, 'Camarões', 'CMR');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 180, 'Congo, República Democrática do (antigo Zaire)', 'COD');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 178, 'Congo, República do', 'COG');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 184, 'Cook, Ilhas', 'COK');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 170, 'Colômbia', 'COL');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 174, 'Comores', 'COM');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 132, 'Cabo Verde', 'CPV');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 188, 'Costa Rica', 'CRI');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 192, 'Cuba', 'CUB');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 531, 'Curaçao', 'CUW');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 162, 'Christmas, Ilha', 'CXR');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 136, 'Cayman, Ilhas', 'CYM');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 196, 'Chipre', 'CYP');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 203, 'Checa, República', 'CZE');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 276, 'Alemanha', 'DEU');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 262, 'Djibouti', 'DJI');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 212, 'Dominica', 'DMA');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 208, 'Dinamarca', 'DNK');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 214, 'Dominicana, República', 'DOM');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 12, 'Argélia', 'DZA');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 218, 'Equador', 'ECU');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 818, 'Egito', 'EGY');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 232, 'Eritreia', 'ERI');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 732, 'Saara Ocidental', 'ESH');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 724, 'Espanha', 'ESP');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 233, 'Estónia', 'EST');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 231, 'Etiópia', 'ETH');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 246, 'Finlândia', 'FIN');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 242, 'Fiji', 'FJI');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 238, 'Malvinas, Ilhas (Falkland)', 'FLK');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 250, 'França', 'FRA');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 234, 'Feroé, Ilhas', 'FRO');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 583, 'Micronésia, Estados Federados da', 'FSM');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 266, 'Gabão', 'GAB');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 826, 'Reino Unido da Grã-Bretanha e Irlanda do Norte', 'GBR');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 268, 'Geórgia', 'GEO');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 831, 'Guernsey', 'GGY');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 288, 'Gana', 'GHA');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 292, 'Gibraltar', 'GIB');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 324, 'Guiné-Conacri', 'GIN');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 312, 'Guadalupe', 'GLP');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 270, 'Gâmbia', 'GMB');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 624, 'Guiné-Bissau', 'GNB');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 226, 'Guiné Equatorial', 'GNQ');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 300, 'Grécia', 'GRC');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 308, 'Grenada', 'GRD');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 304, 'Groenlândia', 'GRL');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 320, 'Guatemala', 'GTM');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 254, 'Guiana Francesa', 'GUF');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 316, 'Guam', 'GUM');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 328, 'Guiana', 'GUY');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 344, 'Hong Kong', 'HKG');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 334, 'Heard e Ilhas McDonald, Ilha', 'HMD');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 340, 'Honduras', 'HND');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 191, 'Croácia', 'HRV');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 332, 'Haiti', 'HTI');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 348, 'Hungria', 'HUN');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 360, 'Indonésia', 'IDN');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 833, 'Man, Ilha de', 'IMN');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 356, 'Índia', 'IND');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 86, 'Território Britânico do Oceano Índico', 'IOT');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 372, 'Irlanda', 'IRL');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 364, 'Irã', 'IRN');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 368, 'Iraque', 'IRQ');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 352, 'Islândia', 'ISL');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 376, 'Israel', 'ISR');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 380, 'Itália', 'ITA');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 388, 'Jamaica', 'JAM');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 832, 'Jersey', 'JEY');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 400, 'Jordânia', 'JOR');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 392, 'Japão', 'JPN');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 398, 'Cazaquistão', 'KAZ');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 404, 'Quênia', 'KEN');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 417, 'Quirguistão', 'KGZ');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 116, 'Cambodja', 'KHM');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 296, 'Kiribati', 'KIR');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 659, 'São Cristóvão e Névis (Saint Kitts e Nevis)', 'KNA');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 410, 'Coreia do Sul', 'KOR');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 414, 'Kuwait', 'KWT');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 418, 'Laos', 'LAO');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 422, 'Líbano', 'LBN');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 430, 'Libéria', 'LBR');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 434, 'Líbia', 'LBY');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 662, 'Santa Lúcia', 'LCA');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 438, 'Liechtenstein', 'LIE');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 144, 'Sri Lanka', 'LKA');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 426, 'Lesoto', 'LSO');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 440, 'Lituânia', 'LTU');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 442, 'Luxemburgo', 'LUX');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 428, 'Letônia', 'LVA');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 446, 'Macau', 'MAC');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 663, 'São Martinho (França)', 'MAF');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 504, 'Marrocos', 'MAR');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 492, 'Mônaco', 'MCO');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 498, 'Moldávia', 'MDA');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 450, 'Madagáscar', 'MDG');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 462, 'Maldivas', 'MDV');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 484, 'México', 'MEX');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 584, 'Marshall, Ilhas', 'MHL');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 807, 'Macedônia, República da', 'MKD');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 466, 'Mali', 'MLI');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 470, 'Malta', 'MLT');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 104, 'Myanmar (antiga Birmânia)', 'MMR');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 499, 'Montenegro', 'MNE');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 496, 'Mongólia', 'MNG');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 580, 'Marianas Setentrionais', 'MNP');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 508, 'Moçambique', 'MOZ');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 478, 'Mauritânia', 'MRT');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 500, 'Montserrat', 'MSR');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 474, 'Martinica', 'MTQ');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 480, 'Maurícia', 'MUS');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 454, 'Malawi', 'MWI');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 458, 'Malásia', 'MYS');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 175, 'Mayotte', 'MYT');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 516, 'Namíbia', 'NAM');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 540, 'Nova Caledônia', 'NCL');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 562, 'Níger', 'NER');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 574, 'Norfolk, Ilha', 'NFK');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 566, 'Nigéria', 'NGA');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 558, 'Nicarágua', 'NIC');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 570, 'Niue', 'NIU');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 528, 'Países Baixos (Holanda)', 'NLD');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 578, 'Noruega', 'NOR');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 524, 'Nepal', 'NPL');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 520, 'Nauru', 'NRU');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 554, 'Nova Zelândia (Aotearoa)', 'NZL');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 512, 'Oman', 'OMN');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 586, 'Paquistão', 'PAK');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 591, 'Panamá', 'PAN');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 612, 'Pitcairn', 'PCN');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 604, 'Peru', 'PER');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 608, 'Filipinas', 'PHL');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 585, 'Palau', 'PLW');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 598, 'Papua-Nova Guiné', 'PNG');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 616, 'Polônia', 'POL');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 630, 'Porto Rico', 'PRI');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 408, 'Coreia, República Democrática da (Coreia do Norte)', 'PRK');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 620, 'Portugal', 'PRT');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 600, 'Paraguai', 'PRY');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 275, 'Palestina', 'PSE');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 258, 'Polinésia Francesa', 'PYF');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 634, 'Qatar', 'QAT');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 638, 'Reunião', 'REU');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 642, 'Romênia', 'ROU');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 643, 'Rússia', 'RUS');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 646, 'Ruanda', 'RWA');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 682, 'Arábia Saudita', 'SAU');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 729, 'Sudão', 'SDN');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 686, 'Senegal', 'SEN');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 702, 'Singapura', 'SGP');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 239, 'Geórgia do Sul e Sandwich do Sul, Ilhas', 'SGS');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 654, 'Santa Helena', 'SHN');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 744, 'Svalbard e Jan Mayen', 'SJM');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 90, 'Salomão, Ilhas', 'SLB');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 694, 'Serra Leoa', 'SLE');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 222, 'El Salvador', 'SLV');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 674, 'San Marino', 'SMR');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 706, 'Somália', 'SOM');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 666, 'Saint Pierre et Miquelon', 'SPM');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 688, 'Sérvia', 'SRB');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 728, 'Sudão do Sul', 'SSD');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 678, 'São Tomé e Príncipe', 'STP');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 740, 'Suriname', 'SUR');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 703, 'Eslováquia', 'SVK');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 705, 'Eslovênia', 'SVN');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 752, 'Suécia', 'SWE');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 748, 'Suazilândia', 'SWZ');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 534, 'São Martinho (Países Baixos)', 'SXM');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 690, 'Seychelles', 'SYC');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 760, 'Síria', 'SYR');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 796, 'Turks e Caicos', 'TCA');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 148, 'Chade', 'TCD');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 768, 'Togo', 'TGO');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 764, 'Tailândia', 'THA');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 762, 'Tajiquistão', 'TJK');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 772, 'Toquelau', 'TKL');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 795, 'Turquemenistão', 'TKM');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 626, 'Timor-Leste', 'TLS');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 776, 'Tonga', 'TON');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 780, 'Trindade e Tobago', 'TTO');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 788, 'Tunísia', 'TUN');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 792, 'Turquia', 'TUR');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 798, 'Tuvalu', 'TUV');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 158, 'Taiwan', 'TWN');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 834, 'Tanzânia', 'TZA');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 800, 'Uganda', 'UGA');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 804, 'Ucrânia', 'UKR');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 581, 'Menores Distantes dos Estados Unidos, Ilhas', 'UMI');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 858, 'Uruguai', 'URY');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 840, 'Estados Unidos', 'USA');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 860, 'Usbequistão', 'UZB');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 336, 'Vaticano', 'VAT');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 670, 'São Vicente e Granadinas', 'VCT');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 862, 'Venezuela', 'VEN');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 92, 'Virgens Britânicas, Ilhas', 'VGB');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 850, 'Virgens Americanas, Ilhas', 'VIR');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 704, 'Vietnam', 'VNM');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 548, 'Vanuatu', 'VUT');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 876, 'Wallis e Futuna', 'WLF');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 882, 'Samoa (Samoa Ocidental)', 'WSM');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 887, 'Iémen', 'YEM');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 710, 'África do Sul', 'ZAF');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 894, 'Zâmbia', 'ZMB');
INSERT INTO pais (id, codigo, nome, sigla) VALUES (hibernate_sequence.nextval, 716, 'Zimbabwe', 'ZWE');
