DELETE FROM RECURSOSISTEMA WHERE CAMINHO = '/admin/monitoramentonode/assincrono.xhtml';

DELETE FROM MENU WHERE CAMINHO = '/admin/monitoramentonode/assincrono.xhtml';

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'GERENCIAMENTO > ACOMPANHAMENTO PROCESSOS ASSÍNCRONOS',
'/admin/monitoramentonode/assincrono.xhtml', 0, 'GERENCIAMENTO');


INSERT INTO MENU (ID, LABEL, CAMINHO, PAI_ID, ORDEM)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'PROCESSOS ASSÍNCRONOS',
'/admin/monitoramentonode/assincrono.xhtml',
(SELECT ID FROM MENU WHERE LABEL = 'GERENCIAMENTO DE RECURSOS' AND CAMINHO IS NULL), 200);

INSERT INTO GRUPORECURSOSISTEMA
SELECT ID, 83766742
   FROM RECURSOSISTEMA RS
WHERE RS.CAMINHO = '/admin/monitoramentonode/assincrono.xhtml';
