DELETE FROM RECURSOSISTEMA WHERE CAMINHO = '/admin/configuracaostorage/edita.xhtml';
DELETE FROM RECURSOSISTEMA WHERE CAMINHO = '/admin/configuracaostorage/lista.xhtml';
DELETE FROM RECURSOSISTEMA WHERE CAMINHO = '/admin/configuracaostorage/visualizar.xhtml';

DELETE FROM MENU WHERE CAMINHO = '/admin/configuracaostorage/visualizar.xhtml';
DELETE FROM MENU WHERE CAMINHO = '/admin/configuracaostorage/lista.xhtml';
DELETE FROM MENU WHERE CAMINHO = '/admin/configuracaostorage/edita.xhtml';

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'GERENCIAMENTO > CONFIGURACAO DE STORAGE',
'/admin/configuracaostorage/visualizar.xhtml', 0, 'GERENCIAMENTO');

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'GERENCIAMENTO > CONFIGURACAO DE STORAGE',
'/admin/configuracaostorage/lista.xhtml', 0, 'GERENCIAMENTO');

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'GERENCIAMENTO > CONFIGURACAO DE STORAGE',
'/admin/configuracaostorage/edita.xhtml', 0, 'GERENCIAMENTO');


INSERT INTO MENU (ID, LABEL, CAMINHO, PAI_ID, ORDEM)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'CONFIGURACAO DE STORAGE',
'/admin/configuracaostorage/lista.xhtml',
(SELECT ID FROM MENU WHERE LABEL = 'CONFIGURAÇÕES' AND CAMINHO IS NULL), 200);

INSERT INTO GRUPORECURSOSISTEMA
SELECT ID, 83766742
   FROM RECURSOSISTEMA RS
WHERE RS.CAMINHO = '/admin/configuracaostorage/lista.xhtml';

INSERT INTO GRUPORECURSOSISTEMA
SELECT ID, 83766742
   FROM RECURSOSISTEMA RS
WHERE RS.CAMINHO = '/admin/configuracaostorage/edita.xhtml';

INSERT INTO GRUPORECURSOSISTEMA
SELECT ID, 83766742
   FROM RECURSOSISTEMA RS
WHERE RS.CAMINHO = '/admin/configuracaostorage/visualizar.xhtml';
