package br.com.webpublico.enums;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

public enum PortalTipoAnexo {
    ANEXO1_RGF("ANEXO 1 - DEMONSTRATIVO DA DESPESA COM PESSOAL", PortalTransparenciaTipo.RGF),
    ANEXO2_RGF("ANEXO 2 - DEMONSTRATIVO DA DÍVIDA CONSOLIDADA LÍQUIDA", PortalTransparenciaTipo.RGF),
    ANEXO3_RGF("ANEXO 3 - DEMONSTRATIVO DAS GARANTIAS E CONTRAGARANTIAS DE VALORES", PortalTransparenciaTipo.RGF),
    ANEXO4_RGF("ANEXO 4 - DEMONSTRATIVO DAS OPERAÇÕES DE CRÉDITO", PortalTransparenciaTipo.RGF),
    ANEXO5_RGF("ANEXO 5 - DEMONSTRATIVO DA DISPONIBILIDADE DE CAIXA E DOS RESTOS A PAGAR", PortalTransparenciaTipo.RGF),
    ANEXO6_RGF("ANEXO 6 - DEMONSTRATIVO SIMPLIFICADO DO RELATÓRIO DE GESTÃO FISCAL", PortalTransparenciaTipo.RGF),

    ANEXO1_RREO("ANEXO 1 - BALANÇO ORÇAMENTÁRIO", PortalTransparenciaTipo.RREO),
    ANEXO2_RREO("ANEXO 2 - DEMONSTRATIVO DA EXECUÇÃO DAS DESPESAS POR FUNÇÃO/SUBFUNÇÃO", PortalTransparenciaTipo.RREO),
    ANEXO3_RREO("ANEXO 3 - DEMONSTRATIVO DA RECEITA CORRENTE LÍQUIDA", PortalTransparenciaTipo.RREO),
    ANEXO4_RREO("ANEXO 4 - DEMONSTRATIVO DAS RECEITAS E DESPESAS PREVIDENCIÁRIAS DO REGIME PRÓPRIO DE PREVIDÊNCIA DOS SERVIDORES", PortalTransparenciaTipo.RREO),
    ANEXO5_RREO("ANEXO 5 - DEMONSTRATIVO DO RESULTADO NOMINAL", PortalTransparenciaTipo.RREO),
    ANEXO6_RREO("ANEXO 6 - DEMONSTRATIVO DO RESULTADO PRIMÁRIO - ESTADOS, DISTRITO FEDERAL E MUNICÍPIOS", PortalTransparenciaTipo.RREO),
    ANEXO7_RREO("ANEXO 7 - DEMONSTRATIVO DOS RESTOS A PAGAR POR PODER E ÓRGÃO", PortalTransparenciaTipo.RREO),
    ANEXO8_RREO("ANEXO 8 - DEMONSTRATIVO DAS RECEITAS E DESPESAS COM MANUTENÇÃO E DESENVOLVIMENTO DO ENSINO - MDE", PortalTransparenciaTipo.RREO),
    ANEXO9_RREO("ANEXO 9 - DEMONSTRATIVO DAS RECEITAS DE OPERAÇÕES DE CRÉDITO E DESPESAS DE CAPITAL", PortalTransparenciaTipo.RREO),
    ANEXO10_RREO("ANEXO 10 - DEMONSTRATIVO DA PROJEÇÃO ATUARIAL DO REGIME PRÓPRIO DE PREVIDÊNCIA DOS SERVIDORES", PortalTransparenciaTipo.RREO),
    ANEXO11_RREO("ANEXO 11 - DEMONSTRATIVO DA RECEITA DE ALIENAÇÃO DE ATIVOS E APLICAÇÕES DOS RECURSOS", PortalTransparenciaTipo.RREO),
    ANEXO12_RREO("ANEXO 12 - DEMONSTRATIVO DA RECEITA DE IMPOSTOS LÍQUIDA E DAS DESPESAS PRÓPRIAS COM AÇÕES E SERVIÇOS PÚBLICOS DE SAÚDE", PortalTransparenciaTipo.RREO),
    ANEXO13_RREO("ANEXO 13 - DEMONSTRATIVO DAS PARCERIAS PÚBLICO PRIVADAS", PortalTransparenciaTipo.RREO),
    ANEXO14_RREO("ANEXO 14 - DEMONSTRATIVO SIMPLIFICADO DO RELATÓRIO RESUMIDO DA EXECUÇÃO ORÇAMENTÁRIA", PortalTransparenciaTipo.RREO),

    ANEXO1_LEI_4320("ANEXO 1 - DEMONSTRAÇÃO DA RECEITA E DESPESA SEGUNDO AS CATEGORIAS ECONÔMICAS", PortalTransparenciaTipo.LEI_4320),
    ANEXO2_REC_LEI_4320("ANEXO 2 - RECEITA SEGUNDO AS CATEGORIAS ECONÔMICAS", PortalTransparenciaTipo.LEI_4320),
    ANEXO2_DESP_LEI_4320("ANEXO 2 - DESPESA SEGUNDO AS CATEGORIAS ECONÔMICAS", PortalTransparenciaTipo.LEI_4320),
    ANEXO4_LEI_4320("ANEXO 4 - DESPESAS POR CATEGORIAS - CONSOLIDAÇÃO GERAL", PortalTransparenciaTipo.LEI_4320),
    ANEXO5_LEI_4320("ANEXO 5 - DESPESAS POR FUNÇÃO", PortalTransparenciaTipo.LEI_4320),
    ANEXO6_LEI_4320("ANEXO 6 - PROGRAMA DE TRABALHO", PortalTransparenciaTipo.LEI_4320),
    ANEXO7_LEI_4320("ANEXO 7 - PROGRAMA DE TRABALHO DE GOVERNO: DEMONSTRATIVO DE FUNÇÕES, SUBFUNÇÕES E PROGRAMAS POR PROJETOS E ATIVIDADES", PortalTransparenciaTipo.LEI_4320),
    ANEXO8_LEI_4320("ANEXO 8 - DEMONSTRATIVO DA DESPESA POR FUNÇÕES, SUBFUNÇÕES E PROGRAMAS CONFORME O VÍNCULO COM OS RECURSOS", PortalTransparenciaTipo.LEI_4320),
    ANEXO9_LEI_4320("ANEXO 9 - DEMONSTRATIVO DA DESPESA POR ÓRGÃOS E FUNÇÕES", PortalTransparenciaTipo.LEI_4320),
    ANEXO10_LEI_4320("ANEXO 10 - COMPARATIVO DA RECEITA ORÇADA COM A ARRECADADA", PortalTransparenciaTipo.LEI_4320),
    ANEXO11_LEI_4320("ANEXO 11 - COMPARATIVO DA DESPESA AUTORIZADA COM A REALIZADA", PortalTransparenciaTipo.LEI_4320),
    ANEXO12_LEI_4320("ANEXO 12 - BALANÇO ORÇAMENTÁRIO", PortalTransparenciaTipo.LEI_4320),
    ANEXO13_LEI_4320("ANEXO 13 - BALANÇO FINANCEIRO", PortalTransparenciaTipo.LEI_4320),
    ANEXO14_LEI_4320("ANEXO 14 - BALANÇO PATRIMONIAL", PortalTransparenciaTipo.LEI_4320),
    ANEXO15_LEI_4320("ANEXO 15 - DEMONSTRAÇÃO DAS VARIAÇÕES PATRIMONIAIS", PortalTransparenciaTipo.LEI_4320),
    ANEXO16_LEI_4320("ANEXO 16 - DEMONSTRATIVO DA DÍVIDA FUNDADA INTERNA", PortalTransparenciaTipo.LEI_4320),
    ANEXO17_LEI_4320("ANEXO 17 - DEMONSTRATIVO DA DÍVIDA FLUTUANTE", PortalTransparenciaTipo.LEI_4320),
    ANEXO18_LEI_4320("ANEXO 18 - DEMONSTRAÇÃO DOS FLUXOS DE CAIXA", PortalTransparenciaTipo.LEI_4320),
    ANEXO19_LEI_4320("ANEXO 19 - DEMONSTRAÇÃO DAS MUTAÇÕES NO PATRIMÔNIO LÍQUIDO", PortalTransparenciaTipo.LEI_4320),
    ANEXO21_LEI_4320("ANEXO 21 - DEMONSTRATIVOS DOS CRÉDITOS ADICIONAIS", PortalTransparenciaTipo.LEI_4320),
    EVOLUCAO_RECEITA("EVOLUÇÃO RECEITA", PortalTransparenciaTipo.GERAL),
    EVOLUCAO_DESPESA("EVOLUÇÃO DESPESA", PortalTransparenciaTipo.GERAL),
    DESPESA_ORCAMENTO_FISCAL_POR_FUNCAO("DESPESA DOS ORÇAMENTOS FISCAL E DA SEGURIDADE SOCIAL POR FUNÇÃO DE GOVERNO E FONTE DE RECURSO", PortalTransparenciaTipo.GERAL),
    DESPESA_ORCAMENTO_FISCAL_POR_ORGAO("DESPESA DOS ORÇAMENTOS FISCAL E DA SEGURIDADE SOCIAL POR ÓRGÃO ORÇAMENTÁRIO E FONTE DE RECURSO", PortalTransparenciaTipo.GERAL),
    RECEITA_ORCAMENTO_FISCAL("RECEITA DOS ORÇAMENTOS FISCAL E DA SEGURIDADE SOCIAL POR CATEGORIA ECONÔMICA E FONTE DE RECURSO", PortalTransparenciaTipo.GERAL);
    private String descricao;
    private PortalTransparenciaTipo tipo;

    PortalTipoAnexo(String descricao, PortalTransparenciaTipo tipo) {
        this.descricao = descricao;
        this.tipo = tipo;
    }

    public String getDescricao() {
        return descricao;
    }

    public PortalTransparenciaTipo getTipo() {
        return tipo;
    }

    public static List<PortalTipoAnexo> buscarAnexosPorTipo(PortalTransparenciaTipo tipoAnexo) {
        return Arrays.stream(PortalTipoAnexo.values()).filter(anexo -> anexo.tipo.equals(tipoAnexo)).collect(Collectors.toList());
    }

    @Override
    public String toString() {
        return descricao;
    }
}
