/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.webpublico.enums;

/**
 * @author reidocrime
 */
public enum ValoresRelatorioLOAAnexoUM {

    RECEITA_TRIBUTARIA,
    RECEITA_CONTRIBUICAO,
    RECEITA_PATRIMONIAL,
    RECEITA_AGROPECUARIA,
    RECEITA_INDUSTRIAL,
    RECEITA_SERVICO,
    TRANFERENCIA_CORRENTE,
    OUTRAS_RECEITA_CORRENTE,
    RECEITA_CORRENTE,
    OPERACAO_CREDITO,
    ALIENACAO_BENS,
    AMORTIZACAO_EMPRESTIMO,
    TRANSFERENCIA_CAPITAL,
    OUTRAS_RECEITAS_CAPITAL,
    RECEITA_CAPITAL_INTRAORCAMENTARIA,
    RENUNCIA,
    RESTITUICOES,
    DESCONTO_CONCEDIDO,
    OUTRAS_DEDUCOES,
    PESSOAL_ENCARGO_SOCIAIS,
    JUROS_ENCARGOS_DIVIDA,
    OUTRA_DESPESA_CORRENTE,
    INVESTIMENTO,
    INVERSOES_FINANCEIRA,
    AMORTIZACAO_DIVIDA,
    RESERVA_CONTIGENCIA,
    RESUMO_RECEITA_CORRENTE,
    RESUMO_RECEITA_CAPITAL,
    RESUMO_DEDUCAO_RECEITA,
    RESUMO_DESPESA_CORRENTE,
    RESUMO_DESPESA_CAPITAL,
    RESUMO_RESERVA_ORACAMENTARIA,
    RESUMO_RESERVA_CONTINGENCIA,
    TOTAL_RECEITA,
    TOTAL_DESPESA,
    SUPERAVIT
}
