package br.com.webpublico.nfse.domain.dtos.enums;

import br.com.webpublico.tributario.interfaces.NfseEnumDTO;

public enum TipoParametroNfseDTO implements NfseEnumDTO {

    OBRIGA_USO_AIDF,
    OBRIGA_SOLICITAR_RPS,
    PERMITE_EMISSAO_RETROATIVA,
    PERMITE_EMISSAO_RETROATIVA_ULTIMA_EMITIDA,
    PERGUNTA_RPS_NA_EMISSAO_NFSE,
    VALIDA_DADOS_DEDUCAO_EMISSAO_NFSE,
    FLUXO_CANCELAMENTO_NFSE,
    URL_APLICACAO_NFSE,
    URL_AUTENTICACAO_NFSE,
    URL_REST_NFSE,
    TEXTO_CABECALHO_GUIA_RECOLHIMENTO,
    VALIDA_DMS_ABERTA_MESES_ANTERIORES,
    TIPOS_RPS_PERMITIDOS,
    DIA_LIMITE_CANCELAMENTO_NOTA,
    PERMITE_SELECIONAR_SERVICO_NAO_AUTORIZADO,
    ENCERRA_COMPETENCIA_ANTERIOR_RPS,
    ISENTA_SERVICO_INCORPORACAO,
    PERMITE_EMISSAO_NFSE_ISS_FIXO_VENCIDO,
    PERMITE_SERVICO_DECLARADO_PRESTADO,
    PERMITE_ALTERAR_OPCOES_ENVIO_EMAIL_PERFIL_EMPRESA,
    ENVIA_EMAIL_HOMOLOGACAO,
    MENSAGEM_LOGIN,
    MENSAGEM_TELA_AUTENTICACAO,
    BLOQUEIA_LOGIN,
    PERMITE_EMISSAO_NFS_AVULSA,
    PERMITE_ISENCAO_ACRESCIMOS_INSTITUICAO_FINANCEIRA,
    HABILITA_PRIMEIRO_ACESSO,
    QUANTIDADE_SOLICITACAO_CANCELAMENTO,
    MENSAGEM_PRIMEIRO_ACESSO_DESABILITADO,
    DIA_LIMITE_CANCELAMENTO_ENCERRAMENTO_MENSAL,
    URL_APLICACAO_NFSE_HOMOLOGACAO,
    URL_AUTENTICACAO_NFSE_HOMOLOGACAO,
    URL_REST_NFSE_HOMOLOGACAO,
    PERMITE_CANCELAMENTO_FORA_PRAZO,
    TEXTO_BLOQUEIO_CANCELAMENTO_FORA_PRAZO,
    URL_APLICACAO_NOTA_PREMIADA;


    TipoParametroNfseDTO() {
    }
}
