/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrameGerador.java
 *
 * Created on 06/09/2011, 10:33:56
 */
package br.com.webpublico.test.integracao.util;

import org.dbunit.IDatabaseTester;
import org.dbunit.JdbcDatabaseTester;
import org.dbunit.database.IDatabaseConnection;
import org.dbunit.database.search.TablesDependencyHelper;
import org.dbunit.dataset.IDataSet;
import org.dbunit.dataset.xml.FlatXmlDataSet;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.swing.*;
import java.io.File;
import java.io.FileOutputStream;

/**
 * @author gecen
 */
public class JFrameGerador extends javax.swing.JFrame {
    private static final Logger logger = LoggerFactory.getLogger(JFrameGerador.class);
    private final JFileChooser fileChooser;

    /**
     * Creates new form JFrameGerador
     */
    public JFrameGerador() {
        initComponents();
        fileChooser = new JFileChooser();
    }

    public static IDatabaseConnection getConnection() throws Exception {
        IDatabaseTester databaseTester = new JdbcDatabaseTester("oracle.jdbc.OracleDriver",
            "jdbc:oracle:thin:@localhost:1521:ORCL",
            "webpublico",
            "senha10",
            "WEBPUBLICO");
        return databaseTester.getConnection();

    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldTabela = new javax.swing.JTextField();
        jButtonGerar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jCheckBoxDependencias = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerador der xml para carga no banco");

        jLabel1.setText("Tabela:");

        jButtonGerar.setText("Gerar");
        jButtonGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 24));
        jLabel3.setText("Gerador de xml para carga no banco");

        jCheckBoxDependencias.setText("Com depêndencia");
        jCheckBoxDependencias.setToolTipText("Muito cuidado ao utilizar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addGap(17, 17, 17)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButtonGerar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldTabela, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jCheckBoxDependencias)))
                    .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel3)
                    .addGap(34, 34, 34)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jCheckBoxDependencias))
                    .addGap(18, 18, 18)
                    .addComponent(jButtonGerar)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarActionPerformed

        try {
            IDatabaseConnection conn = getConnection();
            String[] depTableNames = null;
            if (jCheckBoxDependencias.isSelected()) {
                depTableNames = TablesDependencyHelper.getAllDependentTables(conn, jTextFieldTabela.getText());

            } else {
                depTableNames = new String[]{jTextFieldTabela.getText()};
            }
            IDataSet depDataset = conn.createDataSet(depTableNames);
            int returnVal = fileChooser.showOpenDialog(JFrameGerador.this);

            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File f = fileChooser.getSelectedFile();
                FlatXmlDataSet.write(depDataset, new FileOutputStream(f));
                JOptionPane.showMessageDialog(this, "Arquivo gerado...");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao gerar arquivo" + ex.getMessage());
        }

    }//GEN-LAST:event_jButtonGerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            logger.error("Erro: ", ex);
        } catch (InstantiationException ex) {
            logger.error("Erro: ", ex);
        } catch (IllegalAccessException ex) {
            logger.error("Erro: ", ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            logger.error("Erro: ", ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JFrameGerador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGerar;
    private javax.swing.JCheckBox jCheckBoxDependencias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldTabela;
    // End of variables declaration//GEN-END:variables
}
