package br.com.webpublico.nfse.domain.template;

import br.com.webpublico.util.trocatag.Tag;

/**
 * Created by Clovis on 16/09/2015.
 */
public enum TagNotaFiscal implements Tag {
    NUMERO_RPS,
    NUMERO_NOTA,
    CODIGO_AUTENTICIDADE,
    EMISSAO,
    DATA_FATO,
    NOME_FANTASIA_TOMADOR,
    RAZAO_SOCIAL_TOMADOR,
    CPF_CNPJ_TOMADOR,
    LOGRADOURO_TOMADOR,
    BAIRRO_TOMADOR,
    CEP_TOMADOR,
    COMPLEMENTO_TOMADOR,
    MUNICIPIO_TOMADOR,
    EMAIL_TOMADOR,
    TABELA_ITENS, PIS, COFINS, INSS, IR, CSLL, OUTRAS_RETENCOES, TOTAL, DESCONTO_CONDICIONADO, DESCONTO_INCONDICIONADO, DEDUCOES, BASE_CALCULO, VALOR_ISS, VALOR_LIQUIDO,
    DATA_SOLICITACAO,
    NOME_MUNICIPIO_CONFIGURADO, LISTA_DE_DOCUMENTOS_CONFIGURADOS,
    LOGO_EMPRESA;
}
