INSERT INTO CONFIGURACAOTRIBUTARIOBI (ID)
SELECT HIBERNATE_SEQUENCE.NEXTVAL
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM CONFIGURACAOTRIBUTARIOBI);

UPDATE CONFIGURACAOTRIBUTARIO SET CONFIGURACAOTRIBUTARIOBI_ID = (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI)
WHERE CONFIGURACAOTRIBUTARIOBI_ID IS NULL;

INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'GUIA_ISS', 363412618);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'GUIAS_TAXAS', 363412618);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'TIPOISS', 363412618);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'GUIA_ISS', 6194194);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'GUIAS_TAXAS', 6194194);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'TIPOISS', 6194194);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'GUIA_ISS', 40756709);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'GUIAS_TAXAS', 40756709);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'TIPOISS', 40756709);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'GUIA_ISS', 139772641);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'GUIAS_TAXAS', 139772641);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'TIPOISS', 139772641);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'GUIA_ISS', 903825977);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'GUIAS_TAXAS', 903825977);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'TIPOISS', 903825977);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'GUIA_ISS', 10838758684);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'GUIAS_TAXAS', 10838758684);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'TIPOISS', 10838758684);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'GUIA_ISS', 6194169);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'GUIAS_TAXAS', 6194169);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'TIPOISS', 6194169);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'GUIA_ISS', 139771280);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'GUIAS_TAXAS', 139771280);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'TIPOISS', 139771280);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'GUIA_ISS', 6194166);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'GUIAS_TAXAS', 6194166);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'TIPOISS', 6194166);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'GUIA_ISS', 10990284417);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'GUIAS_TAXAS', 10990284417);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'TIPOISS', 10990284417);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'GUIA_ISS', 10711171287);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'GUIAS_TAXAS', 10711171287);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'TIPOISS', 10711171287);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'GUIA_ISS', 6194163);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'GUIAS_TAXAS', 6194163);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'TIPOISS', 6194163);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'GUIA_ISS', 10601542669);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'GUIAS_TAXAS', 10601542669);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'TIPOISS', 10601542669);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'GUIA_ISS', 903825978);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'GUIAS_TAXAS', 903825978);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'TIPOISS', 903825978);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'GUIA_ISS', 10988074986);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'GUIAS_TAXAS', 10988074986);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'TIPOISS', 10988074986);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'GUIA_ISS', 10723296620);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'GUIAS_TAXAS', 10723296620);
INSERT INTO CONFIGURACAOTRIBUTARIOBIDIVIDA (ID, CONFIGURACAOTRIBUTARIOBI_ID, TIPOEXPORTACAOARQUIVOBI, DIVIDA_ID)  VALUES (HIBERNATE_SEQUENCE.NEXTVAL, (SELECT MAX(ID) FROM CONFIGURACAOTRIBUTARIOBI), 'TIPOISS', 10723296620);
