UPDATE PERMISSAOTRANSPORTE PERMTRANS
SET PERMTRANS.STATUSLANCAMENTO = 'BAIXADO'
where PERMTRANS.TIPOPERMISSAORBTRANS = 'TAXI'
  AND PERMTRANS.NUMERO = 623;

UPDATE PERMISSIONARIO P
SET FINALVIGENCIA = SYSDATE
WHERE P.ID IN (SELECT PERM.ID
               FROM PERMISSIONARIO PERM
               WHERE PERM.PERMISSAOTRANSPORTE_ID in (SELECT PERMTRANS.ID
                                                     FROM PERMISSAOTRANSPORTE PERMTRANS
                                                     where NUMERO in
                                                           (623)
                                                       AND TIPOPERMISSAORBTRANS = 'TAXI')
                 AND PERM.FINALVIGENCIA IS NULL);

INSERT INTO SITUACAOCADASTROECONOMICO (ID, DATAALTERACAO, DATAREGISTRO, SITUACAOCADASTRAL)
VALUES (HIBERNATE_SEQUENCE.nextval, SYSDATE, SYSDATE, 'SUSPENSO');

INSERT INTO CE_SITUACAOCADASTRAL (CADASTROECONOMICO_ID, SITUACAOCADASTROECONOMICO_ID)
VALUES (189263965, HIBERNATE_SEQUENCE.currval);
INSERT INTO CERTIDAOATIVIDADEBCE (ID, DATACADASTRO, USUARIOSISTEMA_ID, CADASTROECONOMICO_ID, MOTIVO, SITUACAO,
                                  NUMEROPROTOCOLO, ANOPROTOCOLO, DOCUMENTOOFICIAL_ID)
VALUES (HIBERNATE_SEQUENCE.nextval, SYSDATE, 367370529, 189263965,
        'Permissão cancelada de acordo com a Portaria RBTRANS Nº 0180/2022', 'SUSPENSO', null, null, null);

INSERT INTO HISTORICO (ID, DATAREGISTRO, MOTIVO, SEQUENCIA, SOLICITANTE, DATASOLICITACAO, CADASTRO_ID, DIGITADOR_ID)
VALUES (HIBERNATE_SEQUENCE.nextval, SYSDATE, 'Permissão cancelada de acordo com a Portaria RBTRANS Nº 0180/2022',
        (select max(SEQUENCIA) + 1 from historico), 'INAUARA SARAIVA LOPES MENDES', SYSDATE, 189263965, 367370529);

INSERT INTO SITUACAOPARCELAVALORDIVIDA
(ID, DATALANCAMENTO, SITUACAOPARCELA, PARCELA_ID, SALDO, INCONSISTENTE, REFERENCIA)
SELECT HIBERNATE_SEQUENCE.nextval,
       current_timestamp,
       'CANCELAMENTO',
       pvd.id as PARCELA_ID,
       spvd.SALDO,
       0,
       spvd.REFERENCIA
from parcelavalordivida pvd
         inner join valordivida vd on vd.id = pvd.valordivida_id
         inner join calculo cal on cal.id = vd.calculo_id
         left join CADASTROECONOMICO CMC ON CAL.CADASTRO_ID = CMC.ID
         inner join divida div on div.id = vd.DIVIDA_ID
         INNER JOIN SITUACAOPARCELAVALORDIVIDA SPVD ON PVD.SITUACAOATUAL_ID = SPVD.ID
WHERE SPVD.SITUACAOPARCELA = 'EM_ABERTO'
  AND CMC.id = 189263965;
