DELETE FROM PERMISSAOCMCNFSE;
INSERT INTO PERMISSAOCMCNFSE (USERNFSECADASTROECONOMICO_ID, PERMISSAO)
SELECT ID, 'ROLE_EMPRESA_ADM' FROM USERNFSECADASTROECONOMICO WHERE SITUACAO = 'APROVADO';
INSERT INTO PERMISSAOCMCNFSE (USERNFSECADASTROECONOMICO_ID, PERMISSAO)
SELECT ID, 'ROLE_AIDFE_SOLICITAR' FROM USERNFSECADASTROECONOMICO WHERE SITUACAO = 'APROVADO';
INSERT INTO PERMISSAOCMCNFSE (USERNFSECADASTROECONOMICO_ID, PERMISSAO)
SELECT ID, 'ROLE_AIDFE_CONSULTAR' FROM USERNFSECADASTROECONOMICO WHERE SITUACAO = 'APROVADO';
INSERT INTO PERMISSAOCMCNFSE (USERNFSECADASTROECONOMICO_ID, PERMISSAO)
SELECT ID, 'ROLE_PLANO_CONTAS_INTERNO_CONSULTAR' FROM USERNFSECADASTROECONOMICO WHERE SITUACAO = 'APROVADO';
INSERT INTO PERMISSAOCMCNFSE (USERNFSECADASTROECONOMICO_ID, PERMISSAO)
SELECT ID, 'ROLE_DOCUMENTOS_FISCAIS_EMITIR_NFSE' FROM USERNFSECADASTROECONOMICO WHERE SITUACAO = 'APROVADO';
INSERT INTO PERMISSAOCMCNFSE (USERNFSECADASTROECONOMICO_ID, PERMISSAO)
SELECT ID, 'ROLE_DOCUMENTOS_FISCAIS_DECLARAR_SERVICO' FROM USERNFSECADASTROECONOMICO WHERE SITUACAO = 'APROVADO';
INSERT INTO PERMISSAOCMCNFSE (USERNFSECADASTROECONOMICO_ID, PERMISSAO)
SELECT ID, 'ROLE_RPS_IMPORTAR' FROM USERNFSECADASTROECONOMICO WHERE SITUACAO = 'APROVADO';
INSERT INTO PERMISSAOCMCNFSE (USERNFSECADASTROECONOMICO_ID, PERMISSAO)
SELECT ID, 'ROLE_RPS_CONSULTAR' FROM USERNFSECADASTROECONOMICO WHERE SITUACAO = 'APROVADO';
INSERT INTO PERMISSAOCMCNFSE (USERNFSECADASTROECONOMICO_ID, PERMISSAO)
SELECT ID, 'ROLE_RPS_LOG_LOTES' FROM USERNFSECADASTROECONOMICO WHERE SITUACAO = 'APROVADO';
INSERT INTO PERMISSAOCMCNFSE (USERNFSECADASTROECONOMICO_ID, PERMISSAO)
SELECT ID, 'ROLE_ENCERRAMENTO_MENSAL_SERVICOS_PRESTADOS' FROM USERNFSECADASTROECONOMICO WHERE SITUACAO = 'APROVADO';
INSERT INTO PERMISSAOCMCNFSE (USERNFSECADASTROECONOMICO_ID, PERMISSAO)
SELECT ID, 'ROLE_ENCERRAMENTO_MENSAL_SERVICOS_TOMADOS' FROM USERNFSECADASTROECONOMICO WHERE SITUACAO = 'APROVADO';
INSERT INTO PERMISSAOCMCNFSE (USERNFSECADASTROECONOMICO_ID, PERMISSAO)
SELECT ID, 'ROLE_ENCERRAMENTO_MENSAL_INSTITUICAO_FINANCEIRA' FROM USERNFSECADASTROECONOMICO WHERE SITUACAO = 'APROVADO';
INSERT INTO PERMISSAOCMCNFSE (USERNFSECADASTROECONOMICO_ID, PERMISSAO)
SELECT ID, 'ROLE_CONTA_CORRENTE_EXTRATO' FROM USERNFSECADASTROECONOMICO WHERE SITUACAO = 'APROVADO';
INSERT INTO PERMISSAOCMCNFSE (USERNFSECADASTROECONOMICO_ID, PERMISSAO)
SELECT ID, 'ROLE_CONTA_CORRENTE_DEBITOS' FROM USERNFSECADASTROECONOMICO WHERE SITUACAO = 'APROVADO';
INSERT INTO PERMISSAOCMCNFSE (USERNFSECADASTROECONOMICO_ID, PERMISSAO)
SELECT ID, 'ROLE_CONTA_CORRENTE_GERAR_GUIA' FROM USERNFSECADASTROECONOMICO WHERE SITUACAO = 'APROVADO';
INSERT INTO PERMISSAOCMCNFSE (USERNFSECADASTROECONOMICO_ID, PERMISSAO)
SELECT ID, 'ROLE_CONTA_CORRENTE_LIVRO_FISCAL' FROM USERNFSECADASTROECONOMICO WHERE SITUACAO = 'APROVADO';
INSERT INTO PERMISSAOCMCNFSE (USERNFSECADASTROECONOMICO_ID, PERMISSAO)
SELECT ID, 'ROLE_TOMADORES_CONSULTAR' FROM USERNFSECADASTROECONOMICO WHERE SITUACAO = 'APROVADO';
INSERT INTO PERMISSAOCMCNFSE (USERNFSECADASTROECONOMICO_ID, PERMISSAO)
SELECT ID, 'ROLE_TOMADORES_INCLUIR' FROM USERNFSECADASTROECONOMICO WHERE SITUACAO = 'APROVADO';
INSERT INTO PERMISSAOCMCNFSE (USERNFSECADASTROECONOMICO_ID, PERMISSAO)
SELECT ID, 'ROLE_CONSTRUCAO_CIVIL_CONSULTAR' FROM USERNFSECADASTROECONOMICO WHERE SITUACAO = 'APROVADO';
INSERT INTO PERMISSAOCMCNFSE (USERNFSECADASTROECONOMICO_ID, PERMISSAO)
SELECT ID, 'ROLE_CONSTRUCAO_CIVIL_INCLUIR' FROM USERNFSECADASTROECONOMICO WHERE SITUACAO = 'APROVADO';

