insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_I', 10979818671, 8.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_II', 10979818671, 24.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_III', 10979818671, 47.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_IV', 10979818671, 55.000);

insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_I', 10979818672, 8.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_II', 10979818672, 24.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_III', 10979818672, 47.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_IV', 10979818672, 55.000);

insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_I', 10979818673, 10.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_II', 10979818673, 26.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_III', 10979818673, 50.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_IV', 10979818673, 57.000);

insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_I', 10979818674, 16.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_II', 10979818674, 48.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_III', 10979818674, 94.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_IV', 10979818674, 110.000);

insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_I', 10979818675, 18.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_II', 10979818675, 50.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_III', 10979818675, 97.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_IV', 10979818675, 112.000);

insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_I', 10979818676, 3.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_II', 10979818676, 5.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_III', 10979818676, 7.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_IV', 10979818676, 10.000);

insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_I', 10979818677, 13.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_II', 10979818677, 31.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_III', 10979818677, 57.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_IV', 10979818677, 67.000);

insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_I', 10979818678, 10.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_II', 10979818678, 13.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_III', 10979818678, 16.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_IV', 10979818678, 20.000);

insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_I', 10979818679, 5.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_II', 10979818679, 8.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_III', 10979818679, 12.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_IV', 10979818679, 16.000);

insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_I', 10979818680, 0.500);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_II', 10979818680, 3.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_III', 10979818680, 6.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_IV', 10979818680, 10.000);

insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_I', 10979818681, 3.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_II', 10979818681, 5.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_III', 10979818681, 7.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_IV', 10979818681, 10.000);

insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_I', 10979818682, 1.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_II', 10979818682, 3.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_III', 10979818682, 6.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_IV', 10979818682, 10.000);

insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_I', 10979818683, 3.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_II', 10979818683, 5.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_III', 10979818683, 7.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_IV', 10979818683, 10.000);

insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_I', 10979818684, 1.500);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_II', 10979818684, 1.500);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_III', 10979818684, 1.500);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_IV', 10979818684, 1.500);

insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_I', 10979818685, 1.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_II', 10979818685, 2.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_III', 10979818685, 3.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_IV', 10979818685, 4.000);

insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_I', 10979818686, 3.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_II', 10979818686, 3.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_III', 10979818686, 3.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_IV', 10979818686, 3.000);

insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_I', 10979818687, 16.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_II', 10979818687, 40.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_III', 10979818687, 79.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_IV', 10979818687, 84.000);

insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_I', 10979818688, 3.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_II', 10979818688, 5.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_III', 10979818688, 7.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_IV', 10979818688, 10.000);

insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_I', 10979818689, 2.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_II', 10979818689, 4.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_III', 10979818689, 6.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_IV', 10979818689, 8.000);

insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_I', 10979818690, 5.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_II', 10979818690, 5.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_III', 10979818690, 5.000);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'CATEGORIA_IV', 10979818690, 5.000);

insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'PEQUENO_PORTE', 10979818691, 1.250);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'MEDIO_PORTE', 10979818691, 2.250);
insert into CATEGORIAASSUNTOLICENCIAMENTOAMBIENTAL(ID, CATEGORIA, ASSUNTO_ID, VALORUFM) VALUES (HIBERNATE_SEQUENCE.nextval, 'GRANDE_PORTE', 10979818691, 3.250);
