INSERT INTO HISTORICO (ID, DATAREGISTRO, MOTIVO, SEQUENCIA, SOLICITANTE, DATASOLICITACAO, CADASTRO_ID, DIGITADOR_ID)
VALUES (HIBERNATE_SEQUENCE.nextval, SYSDATE, 'Permissão cancelada de acordo com a Portaria RBTRANS Nº 011/2007',
        (select max(SEQUENCIA) + 1 from historico), 'INAUARA SARAIVA LOPES MENDES', SYSDATE, 189256127, 367370529);

INSERT INTO HISTORICO (ID, DATAREGISTRO, MOTIVO, SEQUENCIA, SOLICITANTE, DATASOLICITACAO, CADASTRO_ID, DIGITADOR_ID)
VALUES (HIBERNATE_SEQUENCE.nextval, SYSDATE, 'Permissão cancelada de acordo com a Portaria RBTRANS Nº 028/2007',
        (select max(SEQUENCIA) + 1 from historico), 'INAUARA SARAIVA LOPES MENDES', SYSDATE, 189255361, 367370529);

INSERT INTO HISTORICO (ID, DATAREGISTRO, MOTIVO, SEQUENCIA, SOLICITANTE, DATASOLICITACAO, CADASTRO_ID, DIGITADOR_ID)
VALUES (HIBERNATE_SEQUENCE.nextval, SYSDATE, 'Permissão cancelada de acordo com a Portaria RBTRANS Nº 026/2003',
        (select max(SEQUENCIA) + 1 from historico), 'INAUARA SARAIVA LOPES MENDES', SYSDATE, 189245493, 367370529);

INSERT INTO HISTORICO (ID, DATAREGISTRO, MOTIVO, SEQUENCIA, SOLICITANTE, DATASOLICITACAO, CADASTRO_ID, DIGITADOR_ID)
VALUES (HIBERNATE_SEQUENCE.nextval, SYSDATE, 'Permissão cancelada de acordo com a Portaria RBTRANS Nº 01/2008',
        (select max(SEQUENCIA) + 1 from historico), 'INAUARA SARAIVA LOPES MENDES', SYSDATE, 189245797, 367370529);

INSERT INTO HISTORICO (ID, DATAREGISTRO, MOTIVO, SEQUENCIA, SOLICITANTE, DATASOLICITACAO, CADASTRO_ID, DIGITADOR_ID)
VALUES (HIBERNATE_SEQUENCE.nextval, SYSDATE, 'Permissão cancelada de acordo com a Portaria RBTRANS Nº 031/2003',
        (select max(SEQUENCIA) + 1 from historico), 'INAUARA SARAIVA LOPES MENDES', SYSDATE, 189245816, 367370529);

INSERT INTO HISTORICO (ID, DATAREGISTRO, MOTIVO, SEQUENCIA, SOLICITANTE, DATASOLICITACAO, CADASTRO_ID, DIGITADOR_ID)
VALUES (HIBERNATE_SEQUENCE.nextval, SYSDATE, 'Permissão cancelada de acordo com a Portaria RBTRANS Nº 034/2003',
        (select max(SEQUENCIA) + 1 from historico), 'INAUARA SARAIVA LOPES MENDES', SYSDATE, 189247000, 367370529);

INSERT INTO HISTORICO (ID, DATAREGISTRO, MOTIVO, SEQUENCIA, SOLICITANTE, DATASOLICITACAO, CADASTRO_ID, DIGITADOR_ID)
VALUES (HIBERNATE_SEQUENCE.nextval, SYSDATE, 'Permissão cancelada de acordo com a Portaria RBTRANS Nº 035/2007',
        (select max(SEQUENCIA) + 1 from historico), 'INAUARA SARAIVA LOPES MENDES', SYSDATE, 189246119, 367370529);

INSERT INTO HISTORICO (ID, DATAREGISTRO, MOTIVO, SEQUENCIA, SOLICITANTE, DATASOLICITACAO, CADASTRO_ID, DIGITADOR_ID)
VALUES (HIBERNATE_SEQUENCE.nextval, SYSDATE, 'Permissão cancelada de acordo com a Portaria RBTRANS Nº 011/2007',
        (select max(SEQUENCIA) + 1 from historico), 'INAUARA SARAIVA LOPES MENDES', SYSDATE, 189256127, 367370529);

INSERT INTO HISTORICO (ID, DATAREGISTRO, MOTIVO, SEQUENCIA, SOLICITANTE, DATASOLICITACAO, CADASTRO_ID, DIGITADOR_ID)
VALUES (HIBERNATE_SEQUENCE.nextval, SYSDATE, 'Permissão cancelada de acordo com a Portaria RBTRANS Nº 009/2004',
        (select max(SEQUENCIA) + 1 from historico), 'INAUARA SARAIVA LOPES MENDES', SYSDATE, 189248750, 367370529);

INSERT INTO HISTORICO (ID, DATAREGISTRO, MOTIVO, SEQUENCIA, SOLICITANTE, DATASOLICITACAO, CADASTRO_ID, DIGITADOR_ID)
VALUES (HIBERNATE_SEQUENCE.nextval, SYSDATE, 'Permissão cancelada de acordo com a Portaria RBTRANS Nº 27/2007',
        (select max(SEQUENCIA) + 1 from historico), 'INAUARA SARAIVA LOPES MENDES', SYSDATE, 189251312, 367370529);

INSERT INTO HISTORICO (ID, DATAREGISTRO, MOTIVO, SEQUENCIA, SOLICITANTE, DATASOLICITACAO, CADASTRO_ID, DIGITADOR_ID)
VALUES (HIBERNATE_SEQUENCE.nextval, SYSDATE, 'Permissão cancelada de acordo com a Portaria RBTRANS Nº 012/2007',
        (select max(SEQUENCIA) + 1 from historico), 'INAUARA SARAIVA LOPES MENDES', SYSDATE, 189252854, 367370529);

INSERT INTO HISTORICO (ID, DATAREGISTRO, MOTIVO, SEQUENCIA, SOLICITANTE, DATASOLICITACAO, CADASTRO_ID, DIGITADOR_ID)
VALUES (HIBERNATE_SEQUENCE.nextval, SYSDATE, 'Permissão cancelada de acordo com a Portaria RBTRANS Nº 013/2007',
        (select max(SEQUENCIA) + 1 from historico), 'INAUARA SARAIVA LOPES MENDES', SYSDATE, 189252171, 367370529);

INSERT INTO HISTORICO (ID, DATAREGISTRO, MOTIVO, SEQUENCIA, SOLICITANTE, DATASOLICITACAO, CADASTRO_ID, DIGITADOR_ID)
VALUES (HIBERNATE_SEQUENCE.nextval, SYSDATE, 'Permissão cancelada de acordo com a Portaria RBTRANS Nº 34/2007',
        (select max(SEQUENCIA) + 1 from historico), 'INAUARA SARAIVA LOPES MENDES', SYSDATE, 189256970, 367370529);

INSERT INTO HISTORICO (ID, DATAREGISTRO, MOTIVO, SEQUENCIA, SOLICITANTE, DATASOLICITACAO, CADASTRO_ID, DIGITADOR_ID)
VALUES (HIBERNATE_SEQUENCE.nextval, SYSDATE, 'Permissão cancelada de acordo com a Portaria RBTRANS Nº 34/2008',
        (select max(SEQUENCIA) + 1 from historico), 'INAUARA SARAIVA LOPES MENDES', SYSDATE, 434308823, 367370529);

INSERT INTO HISTORICO (ID, DATAREGISTRO, MOTIVO, SEQUENCIA, SOLICITANTE, DATASOLICITACAO, CADASTRO_ID, DIGITADOR_ID)
VALUES (HIBERNATE_SEQUENCE.nextval, SYSDATE, 'Permissão cancelada de acordo com a Portaria RBTRANS Nº 35/2008',
        (select max(SEQUENCIA) + 1 from historico), 'INAUARA SARAIVA LOPES MENDES', SYSDATE, 189254296, 367370529);


INSERT INTO SITUACAOPARCELAVALORDIVIDA
(ID, DATALANCAMENTO, SITUACAOPARCELA, PARCELA_ID, SALDO, INCONSISTENTE, REFERENCIA)
SELECT HIBERNATE_SEQUENCE.nextval,
       current_timestamp,
       'CANCELAMENTO',
       pvd.id as PARCELA_ID,
       spvd.SALDO,
       0,
       spvd.REFERENCIA
from parcelavalordivida pvd
         inner join valordivida vd on vd.id = pvd.valordivida_id
         inner join calculo cal on cal.id = vd.calculo_id
         left join CADASTROECONOMICO CMC ON CAL.CADASTRO_ID = CMC.ID
         inner join divida div on div.id = vd.DIVIDA_ID
         INNER JOIN SITUACAOPARCELAVALORDIVIDA SPVD ON PVD.SITUACAOATUAL_ID = SPVD.ID
WHERE SPVD.SITUACAOPARCELA = 'EM_ABERTO'
  AND CMC.id = 189254296;
