CREATE OR REPLACE TRIGGER AJUSTADATAPRESCRICAOPARCELA BEFORE INSERT
    ON PARCELAVALORDIVIDA
    FOR EACH ROW
    DECLARE ANO NUMBER;
BEGIN
    SELECT QUANTIDADEANOSPRESCRICAO * 12 INTO ANO FROM CONFIGURACAOTRIBUTARIO;
    :NEW.DATAPRESCRICAO := ADD_MONTHS(:NEW.VENCIMENTO, ANO);
END;
