INSERT INTO ASSUNTOLICAMBIENTALORIGEMPROCESSO (ID, ORIGEMPROCESSO, ASSUNTOLICENCIAMENTOAMBIENTAL_ID)
SELECT HIBERNATE_SEQUENCE.nextval, 'CAC', a.ID FROM assuntolicenciamentoambiental a WHERE a.CODIGO <= 21;

INSERT INTO ASSUNTOLICAMBIENTALORIGEMPROCESSO (ID, ORIGEMPROCESSO, ASSUNTOLICENCIAMENTOAMBIENTAL_ID)
SELECT HIBERNATE_SEQUENCE.nextval, 'REDE_SIM', a.ID FROM assuntolicenciamentoambiental a WHERE a.CODIGO <= 21;

INSERT INTO ASSUNTOLICAMBIENTALORIGEMPROCESSO (ID, ORIGEMPROCESSO, ASSUNTOLICENCIAMENTOAMBIENTAL_ID)
SELECT HIBERNATE_SEQUENCE.nextval, 'RBDOC', a.ID FROM assuntolicenciamentoambiental a WHERE a.CODIGO <= 21;

INSERT INTO ASSUNTOLICAMBIENTALORIGEMPROCESSO (ID, ORIGEMPROCESSO, ASSUNTOLICENCIAMENTOAMBIENTAL_ID)
SELECT HIBERNATE_SEQUENCE.nextval, 'EMAIL_INSTITUCIONAL', a.ID FROM assuntolicenciamentoambiental a WHERE a.CODIGO <= 21;

INSERT INTO ASSUNTOLICAMBIENTALORIGEMPROCESSO (ID, ORIGEMPROCESSO, ASSUNTOLICENCIAMENTOAMBIENTAL_ID)
SELECT HIBERNATE_SEQUENCE.nextval, 'VIA_BIANCA', a.ID FROM assuntolicenciamentoambiental a WHERE a.CODIGO <= 21;

INSERT INTO ASSUNTOLICAMBIENTALORIGEMPROCESSO (ID, ORIGEMPROCESSO, ASSUNTOLICENCIAMENTOAMBIENTAL_ID)
SELECT HIBERNATE_SEQUENCE.nextval, 'RECEPCAO', a.ID FROM assuntolicenciamentoambiental a WHERE a.CODIGO <= 21;

INSERT INTO ASSUNTOLICAMBIENTALORIGEMPROCESSO (ID, ORIGEMPROCESSO, ASSUNTOLICENCIAMENTOAMBIENTAL_ID)
SELECT HIBERNATE_SEQUENCE.nextval, 'ONLINE', a.ID FROM assuntolicenciamentoambiental a WHERE a.CODIGO <= 21;
