UPDATE TRANSMITENTESCALCULOITBI SET PERCENTUAL_TEMP = PERCENTUAL;
UPDATE ADQUIRENTESCALCULOITBI SET PERCENTUAL_TEMP = PERCENTUAL;
UPDATE PROPRIEDADESIMULACAOITBI SET PROPORCAO_TEMP = PROPORCAO;
UPDATE PROPRIEDADE SET PROPORCAO_TEMP = PROPORCAO;
UPDATE CALCULOITBI SET PERCENTUAL_TEMP = PERCENTUAL;

UPDATE TRANSMITENTESCALCULOITBI_AUD SET PERCENTUAL_TEMP = PERCENTUAL;
UPDATE ADQUIRENTESCALCULOITBI_AUD SET PERCENTUAL_TEMP = PERCENTUAL;
UPDATE PROPRIEDADESIMULACAOITBI_AUD SET PROPORCAO_TEMP = PROPORCAO;
UPDATE PROPRIEDADE_AUD SET PROPORCAO_TEMP = PROPORCAO;
UPDATE CALCULOITBI_AUD SET PERCENTUAL_TEMP = PERCENTUAL;
