    CREATE OR REPLACE
    TRIGGER AJUSTASITUACAOPARCELADELETE BEFORE
    DELETE ON SITUACAOPARCELAVALORDIVIDA FOR EACH ROW
      DECLARE
        SITUACAO_ID NUMBER;
          PRAGMA AUTONOMOUS_TRANSACTION;
    BEGIN
        SELECT ID
        INTO SITUACAO_ID
        FROM
          (SELECT ID
           FROM SITUACAOPARCELAVALORDIVIDA
           WHERE PARCELA_ID = :OLD.PARCELA_ID AND ID <> :OLD.ID
           ORDER BY DATALANCAMENTO DESC,
             ID DESC
          )
        WHERE ROWNUM = 1;
        DBMS_OUTPUT.PUT_LINE(SITUACAO_ID);
        UPDATE PARCELAVALORDIVIDA
        SET SITUACAOATUAL_ID = SITUACAO_ID
        WHERE ID             = :OLD.PARCELA_ID;
        COMMIT;
       EXCEPTION
         WHEN NO_DATA_FOUND THEN
         DBMS_OUTPUT.PUT_LINE('');
    END;
