update PROCREGULARIZACONSTRUCAO p set ARTRRTAUTORPROJETO =
                                          (select s.ARTRRTAUTORPROJETO from SOLICITACAOALVARAIMEDIATO s where s.PROCREGULARIZACONSTRUCAO_ID = p.id)
where exists (select 1 from SOLICITACAOALVARAIMEDIATO s where s.PROCREGULARIZACONSTRUCAO_ID = p.id);
update PROCREGULARIZACONSTRUCAO p set ARTRRTRESPONSAVELEXECUCAO =
                                          (select s.ARTRRTRESPONSAVELEXECUCAO from SOLICITACAOALVARAIMEDIATO s where s.PROCREGULARIZACONSTRUCAO_ID = p.id)
where exists (select 1 from SOLICITACAOALVARAIMEDIATO s where s.PROCREGULARIZACONSTRUCAO_ID = p.id);
