UPDATE CERTIDAOATIVIDADEBCE SET ANOPROTOCOLOAUX = ANOPROTOCOLO;
UPDATE CERTIDAOATIVIDADEBCE_AUD SET ANOPROTOCOLOAUX = ANOPROTOCOLO;
UPDATE CERTIDAOATIVIDADEBCE SET ANOPROTOCOLO = null;
UPDATE CERTIDAOATIVIDADEBCE_AUD SET ANOPROTOCOLO = null;
