UPDATE DIVIDA SET ORDEMAPRESENTACAO = 2 WHERE DESCRICAO LIKE '%DÍVIDA ATIVA%';
UPDATE DIVIDA SET ORDEMAPRESENTACAO = 3 WHERE DESCRICAO LIKE '%PARCELAMENTO%';
UPDATE DIVIDA SET ORDEMAPRESENTACAO = 1 WHERE  ORDEMAPRESENTACAO IS NULL;
COMMIT;
