UPDATE CALCULOISS SET NOTAELETRONICA = 1
WHERE ID IN (
SELECT C.ID FROM CALCULOISS C
INNER JOIN PROCESSOCALCULOISS PC ON PC.ID = C.PROCESSOCALCULOISS_ID
INNER JOIN DECLARACAOMENSALSERVICO DMS ON DMS.PROCESSOCALCULO_ID = PC.ID);
