create or replace
PACKAGE PACOTE_CONSULTA_DE_DEBITOS
AS
FUNCTION GETULTIMASITUACAOPARCELA(
    PARAM_PARCELA_ID IN NUMBER)
  RETURN NUMBER;
FUNCTION GETVALORJUROS(
    PARAM_DATA_OPERACAO IN DATE ,
    PARAM_ID_PARCELA    IN NUMBER,
    CALCULA_DESCONTO    IN NUMBER)
  RETURN NUMBER;
FUNCTION GETVALORMULTA(
    PARAM_DATA_OPERACAO IN DATE ,
    PARAM_ID_PARCELA    IN NUMBER,
    CALCULA_DESCONTO    IN NUMBER)
  RETURN NUMBER;
FUNCTION GETVALORCORRECAO(
    PARAM_ID_PARCELA    IN NUMBER,
    PARAM_EXERCICIO_ANO IN NUMBER,
    CALCULA_DESCONTO    IN NUMBER,
    PARAM_DATA_OPERACAO IN DATE)
  RETURN NUMBER;
FUNCTION GETVALORDESCONTO(
    PARAM_PARCELA_ID    IN NUMBER,
    PARAM_DATA_OPERACAO IN DATE)
  RETURN NUMBER;
FUNCTION GETVALORTIPOTRIBUTO(
    PARAM_PARCELA_ID   IN NUMBER,
    PARAM_TIPO_TRIBUTO IN VARCHAR2)
  RETURN NUMBER;
FUNCTION GETNUMEROPARCELA(
    PARAM_ID_VALOR_DIVIDA    IN NUMBER ,
    PARAM_ID_OPCAO_PAGAMENTO IN NUMBER ,
    PARAM_PROMOCIONAL        IN NUMBER ,
    PARAM_SEQUENCIA_PARCELA  IN VARCHAR2 )
  RETURN VARCHAR2;
FUNCTION GETVALORHONORARIOS(
    PARAM_ID_PARCELA    IN NUMBER,
    PARAM_DATA_OPERACAO IN DATE)
  RETURN NUMBER;
FUNCTION GETVALORPARCELAPAGO(
    PARAM_ID_PARCELA       IN NUMBER,
    PARAM_SITUACAO_PARCELA IN VARCHAR2)
  RETURN NUMBER;
FUNCTION GETDATAPAGAMENTOPARCELA(
    PARAM_ID_PARCELA       IN NUMBER,
    PARAM_SITUACAO_PARCELA IN VARCHAR2)
  RETURN DATE;
FUNCTION CONTEMINCIDENCIA(
    TIPO_INCIDENCIA           IN VARCHAR2,
    TIPO_ACRESCIMO            IN VARCHAR2,
    CONFIGURACAO_ACRESCIMO_ID IN NUMBER)
  RETURN NUMBER;
FUNCTION QUANTIDADEIMPRESSOESDAM(
    PARAM_PARCELA_ID IN NUMBER)
  RETURN NUMBER;
FUNCTION PGTOPARCCANCPARCELAMENTO(
    PARAM_PARCELA_ID IN NUMBER)
  RETURN NUMBER;
FUNCTION GETVALORIMPOSTO(
    PARAM_PARCELA_ID    IN NUMBER,
    CALCULA_DESCONTO    IN NUMBER,
    PARAM_DATA_OPERACAO IN DATE)
  RETURN NUMBER;
FUNCTION GETVALORTAXA(
    PARAM_PARCELA_ID    IN NUMBER,
    CALCULA_DESCONTO    IN NUMBER,
    PARAM_DATA_OPERACAO IN DATE)
  RETURN NUMBER;
END PACOTE_CONSULTA_DE_DEBITOS;