  CREATE OR REPLACE FORCE VIEW VWCONSULTAIPTU
  AS
    SELECT
      DISTINCT
      CI.ID CADASTRO_ID,
      CI.INSCRICAOCADASTRAL,
      E.ID ID_EXERCICIO,
      E.ANO EXERCICIO,
      CP.PESSOA_ID ID_PESSOA,
      COALESCE(PF.CPF, PJ.CNPJ) CPFCNPJ,
      COALESCE(PF.NOME, PJ.RAZAOSOCIAL) NOME,
      COALESCE(
      (SELECT 'PREDIAL'
      FROM CONSTRUCAO C
      WHERE C.IMOVEL_ID            = CI.ID
      AND COALESCE(C.CANCELADA, 0) = 0
      AND ROWNUM                   = 1
      ), 'TERRITORIAL') TIPOIMOVEL,
      TRIM(SETOR.CODIGO) SETOR,
      TRIM(QUADRA.CODIGO) QUADRA,
      TRIM(LOTE.CODIGOLOTE) LOTE,
      TRIM(BAIRRO.DESCRICAO) BAIRRO,
      TRIM(COALESCE(TP.DESCRICAO,''))
      ||' '
      || TRIM(COALESCE(LOGRADOURO.NOME,'')) LOGRADOURO,
      TRIM(CI.NUMERO) NUMERO,
      TRIM(CI.COMPLEMENTOENDERECO) COMPLEMENTO,
      TRIM(FACE.CEP) CEP,
      SETOR.ID ID_SETOR,
      LOGRADOURO.ID ID_LOGRADOURO,
      BAIRRO.ID ID_BAIRRO,
      C.ID ID_CALCULO,
      C.SUBDIVIDA,
      VD.ID ID_VALORDIVIDA,
      C.DATACALCULO EMISSAO,
      PVD.ID ID_PARCELA,
      PVD.OPCAOPAGAMENTO_ID ID_OPCAOPAGAMENTO,
      OP.PROMOCIONAL,
      PVD.VENCIMENTO,
      SPVD.SITUACAOPARCELA,
      SPVD.REFERENCIA,
      PACOTE_CONSULTA_DE_DEBITOS.GETNUMEROPARCELA(VD.ID, OP.ID, OP.PROMOCIONAL, PVD.SEQUENCIAPARCELA) PARCELA,
      COALESCE(ROUND(PACOTE_CONSULTA_DE_DEBITOS.GETVALORIMPOSTO(PVD.ID,1, SYSDATE), 2), 0)                                      AS VALORIMPOSTO,
      COALESCE(ROUND(PACOTE_CONSULTA_DE_DEBITOS.GETVALORTAXA(PVD.ID,1, SYSDATE), 2), 0)                                         AS VALORTAXA,
      COALESCE(ROUND(PACOTE_CONSULTA_DE_DEBITOS.GETVALORCORRECAO( PVD.ID, EXTRACT(YEAR FROM PVD.VENCIMENTO),1, SYSDATE), 2), 0) AS VALORCORRECAO,
      COALESCE(ROUND(PACOTE_CONSULTA_DE_DEBITOS.GETVALORJUROS(SYSDATE, PVD.ID,1), 2), 0)                                        AS VALORJUROS,
      COALESCE(ROUND(PACOTE_CONSULTA_DE_DEBITOS.GETVALORMULTA(SYSDATE, PVD.ID,1), 2), 0)                                        AS VALORMULTA,
      COALESCE(ROUND(PACOTE_CONSULTA_DE_DEBITOS.GETVALORHONORARIOS(PVD.ID, SYSDATE), 2), 0)                                     AS VALORHONORARIOS,
      COALESCE(ROUND(PACOTE_CONSULTA_DE_DEBITOS.GETVALORDESCONTO(PVD.ID, SYSDATE), 2), 0)                                       AS VALORDESCONTO,
      COALESCE(PACOTE_CONSULTA_DE_DEBITOS.GETVALORPARCELAPAGO(PVD.ID, SPVD.SITUACAOPARCELA), 0)                                 AS VALORPAGO
    FROM CALCULOIPTU IPTU
    INNER JOIN CALCULO C
    ON C.ID = IPTU.ID
    INNER JOIN CALCULOPESSOA CP
    ON CP.CALCULO_ID = C.ID
    LEFT JOIN PESSOAFISICA PF
    ON PF.ID = CP.PESSOA_ID
    LEFT JOIN PESSOAJURIDICA PJ
    ON PJ.ID = CP.PESSOA_ID
    INNER JOIN VALORDIVIDA VD
    ON VD.CALCULO_ID = C.ID
    INNER JOIN EXERCICIO E
    ON VD.EXERCICIO_ID = E.ID
    INNER JOIN CADASTROIMOBILIARIO CI
    ON CI.ID = IPTU.CADASTROIMOBILIARIO_ID
    INNER JOIN PARCELAVALORDIVIDA PVD
    ON PVD.VALORDIVIDA_ID = VD.ID
    INNER JOIN OPCAOPAGAMENTO OP
    ON PVD.OPCAOPAGAMENTO_ID = OP.ID
    INNER JOIN SITUACAOPARCELAVALORDIVIDA SPVD
    ON SPVD.ID = GETULTIMASITUACAO(PVD.ID)
    INNER JOIN LOTE LOTE
    ON LOTE.ID = CI.LOTE_ID
    LEFT JOIN SETOR SETOR
    ON SETOR.ID = LOTE.SETOR_ID
    LEFT JOIN QUADRA QUADRA
    ON QUADRA.ID = LOTE.QUADRA_ID
    LEFT JOIN LOTEAMENTO LOTEAMENTO
    ON LOTEAMENTO.ID = QUADRA.LOTEAMENTO_ID
    INNER JOIN TESTADA TESTADAS
    ON TESTADAS.ID =
      (SELECT MAX(S_TESTA.ID)
      FROM TESTADA S_TESTA
      WHERE S_TESTA.LOTE_ID = LOTE.ID
      AND S_TESTA.PRINCIPAL = 1
      )
    INNER JOIN FACE FACE
    ON FACE.ID = TESTADAS.FACE_ID
    INNER JOIN LOGRADOUROBAIRRO LOGBAIRRO
    ON LOGBAIRRO.ID = FACE.LOGRADOUROBAIRRO_ID
    INNER JOIN LOGRADOURO LOGRADOURO
    ON LOGRADOURO.ID = LOGBAIRRO.LOGRADOURO_ID
    INNER JOIN TIPOLOGRADOURO TP
    ON TP.ID = LOGRADOURO.TIPOLOGRADOURO_ID
    INNER JOIN BAIRRO BAIRRO
    ON BAIRRO.ID                = LOGBAIRRO.BAIRRO_ID
    WHERE SPVD.SITUACAOPARCELA <> 'ISOLAMENTO'