INSERT INTO ARQUIVOCOMPOSICAO(ID, DETENTORARQUIVOCOMPOSICAO_ID, ARQUIVO_ID, DATAUPLOAD)
VALUES (HIBERNATE_SEQUENCE.nextval, NULL, (SELECT CHANCELA.ARQUIVO_ID
                                                                 from CONFIGCREDENCIALRBTRANS CONFIG
                                                                          INNER JOIN CHANCELARBTRANS CHANCELA ON CONFIG.CHANCELARBTRANS_ID = CHANCELA.ID
                                                                 where (FINALEM is null or trunc(FINALEM) > sysdate) FETCH FIRST 1 ROW ONLY),
        SYSDATE);

INSERT INTO DETENTORARQUIVOCOMPOSICAO (ID, ARQUIVOCOMPOSICAO_ID)
VALUES (HIBERNATE_SEQUENCE.nextval, (SELECT MAX(ID) FROM ARQUIVOCOMPOSICAO));

UPDATE ARQUIVOCOMPOSICAO ARQ
SET ARQ.DETENTORARQUIVOCOMPOSICAO_ID = HIBERNATE_SEQUENCE.currval
WHERE ID = (SELECT MAX(ID) FROM ARQUIVOCOMPOSICAO);

UPDATE PARAMINFORMACOESRBTRANS SET DETENTORARQUIVOCOMPOSICAO_ID = (SELECT MAX(ID) FROM DETENTORARQUIVOCOMPOSICAO);

UPDATE CHANCELARBTRANS SET ARQUIVO_ID = NULL;
