INSERT INTO LOTACAOVISTORIADORACONFIGTRIBRENDAS (ID, LOTACAOVISTORIADORA_ID, CONFIGURACAOTRIBUTARIO_ID)
VALUES (HIBERNATE_SEQUENCE.nextval,
        (select RENDASLOTACAOVISTORIADORA_ID
         FROM CONFIGURACAOTRIBUTARIO
         WHERE VIGENCIA = (SELECT MAX(C.VIGENCIA) FROM CONFIGURACAOTRIBUTARIO C)),
        (select TO_NUMBER(ID)
         FROM CONFIGURACAOTRIBUTARIO
         WHERE VIGENCIA = (SELECT MAX(C.VIGENCIA) FROM CONFIGURACAOTRIBUTARIO C)));

INSERT INTO LOTACAOVISTORIADORA(ID, CODIGO, DESCRICAO)
SELECT 11222989169, 1006, 'SEAGRO'
FROM DUAL
WHERE NOT EXISTS(SELECT 1
                 FROM LOTACAOVISTORIADORA
                 WHERE ID = 11222989169);

INSERT INTO LOTACAOVISTORIADORACONFIGTRIBRENDAS (ID, LOTACAOVISTORIADORA_ID, CONFIGURACAOTRIBUTARIO_ID)
VALUES (HIBERNATE_SEQUENCE.nextval,
        11222989169,
        (select TO_NUMBER(ID)
         FROM CONFIGURACAOTRIBUTARIO
         WHERE VIGENCIA = (SELECT MAX(C.VIGENCIA) FROM CONFIGURACAOTRIBUTARIO C)));

UPDATE LOCALIZACAO
SET LOTACAOVISTORIADORA_ID = 11222989169
WHERE ID IN (SELECT L.ID
             FROM LOCALIZACAO L
             WHERE L.LOTACAOVISTORIADORA_ID = 23756677
               AND L.CODIGO NOT IN
                   (546, 545, 543, 540, 539, 537, 536, 535, 533, 531, 532, 529, 527, 524, 523, 522, 521, 517, 516, 514,
                    513, 500, 311, 305, 307, 400, 504, 318, 306, 501, 200, 102, 317, 322, 316, 315, 314, 313, 310, 309,
                    312, 102));

UPDATE LOTACAOTRIBUSUARIO
SET LOTACAO_ID = 11222989169
WHERE ID IN (SELECT LOTTRIB.ID
             FROM VIGENCIATRIBUSUARIO VIGTRIB
                      INNER JOIN USUARIOSISTEMA US ON VIGTRIB.USUARIOSISTEMA_ID = US.ID
                      INNER JOIN PESSOAFISICA PFUS ON US.PESSOAFISICA_ID = PFUS.ID
                      INNER JOIN LOTACAOTRIBUSUARIO LOTTRIB
                                 ON VIGTRIB.ID = LOTTRIB.VIGENCIATRIBUSUARIO_ID AND LOTTRIB.LOTACAO_ID = 23756677
             WHERE (VIGTRIB.VIGENCIAFINAL IS NULL OR TRUNC(VIGTRIB.VIGENCIAFINAL) >= TRUNC(SYSDATE))
               AND PFUS.CPF NOT IN
                   (select '83435255234'
                    from dual
                    union
                    select '82143960263'
                    from dual
                    union
                    select '44396970200'
                    from dual
                    union
                    select '04113372209'
                    from dual
                    union
                    select '06372873206'
                    from dual
                    union
                    SELECT PFUSUSIST.CPF
                    FROM USUARIOSISTEMA USUSIST
                             INNER JOIN PESSOAFISICA PFUSUSIST ON USUSIST.PESSOAFISICA_ID = PFUSUSIST.ID
                             INNER JOIN GRUPOUSUARIOSISTEMA GRUPOUSU ON USUSIST.ID = GRUPOUSU.USUARIOSISTEMA_ID
                    WHERE GRUPOUSU.GRUPOUSUARIO_ID IN (8757038, 8757052, 8757065, 8757077)));

INSERT INTO PARAMETRORENDAS (ID, EXERCICIO_ID, INDICEECONOMICO_ID, QUANTIDADEMESESVIGENCIA, DIAVENCIMENTOPARCELAS,
                             LOTACAOVISTORIADORA_ID, QUANTIDADEPARCELAS, AREATOTAL, DATAINICIOCONTRATO, DATAFIMCONTRATO)
SELECT HIBERNATE_SEQUENCE.nextval,
       EXERCICIO_ID,
       INDICEECONOMICO_ID,
       QUANTIDADEMESESVIGENCIA,
       DIAVENCIMENTOPARCELAS,
       11222989169,
       QUANTIDADEPARCELAS,
       AREATOTAL,
       DATAINICIOCONTRATO,
       DATAFIMCONTRATO
FROM PARAMETRORENDAS
WHERE EXERCICIO_ID = (SELECT ID FROM EXERCICIO WHERE ANO = 2025)
  AND LOTACAOVISTORIADORA_ID = 23756677;
