call proc_insere_unidade_medida_ambiental('Tonelada/dia','MASSA');
call proc_insere_unidade_medida_ambiental('Área Construída (m²)','COMPRIMENTO');
call proc_insere_unidade_medida_ambiental('Número médio de pessoas transportadas por mês','QUANTIDADE');
call proc_insere_unidade_medida_ambiental('Área Construída (m²)','COMPRIMENTO');
call proc_insere_unidade_medida_ambiental('Potência Distribuída (mW)','QUANTIDADE');
call proc_insere_unidade_medida_ambiental('Área de intervenção/ha','COMPRIMENTO');
call proc_insere_unidade_medida_ambiental('Potência Instalada (mW)','QUANTIDADE');
call proc_insere_unidade_medida_ambiental('Area Inundada (Hectares)','COMPRIMENTO');
call proc_insere_unidade_medida_ambiental('Produção (Número de Animais/mês)','QUANTIDADE');
call proc_insere_unidade_medida_ambiental('Área pulverizada/ha','COMPRIMENTO');
call proc_insere_unidade_medida_ambiental('Produção (tonelada/mês)','MASSA');
call proc_insere_unidade_medida_ambiental('Área útil (m²)','COMPRIMENTO');
call proc_insere_unidade_medida_ambiental('Produção (Unidade/mês)','QUANTIDADE');
call proc_insere_unidade_medida_ambiental('Área total (m²)','COMPRIMENTO');
call proc_insere_unidade_medida_ambiental('Produção Kg/mês','MASSA');
call proc_insere_unidade_medida_ambiental('Cabeças abatidas/dia','QUANTIDADE');
call proc_insere_unidade_medida_ambiental('Produção litros/dia','CAPACIDADE');
call proc_insere_unidade_medida_ambiental('Capacidade de armazenamento (m³)','VOLUME');
call proc_insere_unidade_medida_ambiental('Produção litros/mês','CAPACIDADE');
call proc_insere_unidade_medida_ambiental('Capacidade de transporte mensal (m³)','VOLUME');
call proc_insere_unidade_medida_ambiental('Produção m³/mês','VOLUME');
call proc_insere_unidade_medida_ambiental('Carga Transportada por mês (toneladas)','MASSA');
call proc_insere_unidade_medida_ambiental('Produção quilos/mês','MASSA');
call proc_insere_unidade_medida_ambiental('Coleta (tonelada/dia)','MASSA');
call proc_insere_unidade_medida_ambiental('Produção tonelada/ano','MASSA');
call proc_insere_unidade_medida_ambiental('Comprimento da linha (km)','COMPRIMENTO');
call proc_insere_unidade_medida_ambiental('Produção Tonelada/dia','MASSA');
call proc_insere_unidade_medida_ambiental('Extensão (km)','COMPRIMENTO');
call proc_insere_unidade_medida_ambiental('Tamanho da embarcação (m²)','COMPRIMENTO');
call proc_insere_unidade_medida_ambiental('Ha (Hectare)','COMPRIMENTO');
call proc_insere_unidade_medida_ambiental('Vazão de Água Tratada (litros/s)','CAPACIDADE');
call proc_insere_unidade_medida_ambiental('m³/hectare(ano)','VOLUME');
call proc_insere_unidade_medida_ambiental('Vazão Máxima Prevista (Litros/s)','CAPACIDADE');
call proc_insere_unidade_medida_ambiental('Número  de  cabeças (unidade)','QUANTIDADE');
call proc_insere_unidade_medida_ambiental('Volume de madeira serrada (m³/dia)','VOLUME');
call proc_insere_unidade_medida_ambiental('Número de aves','QUANTIDADE');
call proc_insere_unidade_medida_ambiental('Volume Estimado (m³)','VOLUME');
call proc_insere_unidade_medida_ambiental('Número de fornos','QUANTIDADE');
