create or replace TRIGGER DELETAVALORESPARCELASITUACAO
    BEFORE
    INSERT OR UPDATE OR DELETE
    ON SITUACAOPARCELAVALORDIVIDA
    FOR EACH ROW
    DECLARE PARCELA_ID NUMBER;
    BEGIN
        DELETE FROM VALORESPARCELAVALORDIVIDA WHERE PARCELA_ID = COALESCE(:NEW.PARCELA_ID, :OLD.PARCELA_ID);
    END;
