INSERT INTO PROCESSOLICENCIAMENTOAMBIENTALUNIDADEMEDIDA (ID, PROCESSOLICENCIAMENTOAMBIENTAL_ID,
                                                         UNIDADEMEDIDAAMBIENTAL_ID, VALORUNIDADEMEDIDAAMBIENTAL)
SELECT HIBERNATE_SEQUENCE.nextval, ID, UNIDADEMEDIDAAMBIENTAL_ID, VALORUNIDADEMEDIDAAMBIENTAL
FROM PROCESSOLICENCIAMENTOAMBIENTAL;
