insert into AUTORIZACAOTRIBUSUARIO (id, VIGENCIATRIBUSUARIO_ID, AUTORIZACAO)
select hibernate_sequence.nextval, VIGENCIATRIBUSUARIO_ID, 'PERMITIR_EFETIVAR_PROCESSO_BLOQUEIO_JUDICIAL' from TipoUsuarioTribUsuario where TIPOUSUARIOTRIBUTARIO = 'RESPONSAVEL_BLOQUEIO_JUDICIAL'
