UPDATE PARCELAVALORDIVIDA
SET SITUACAOATUAL_ID = (SELECT SPVD.ID
                        FROM SITUACAOPARCELAVALORDIVIDA SPVD
                        WHERE PARCELA_ID = 618793387
                          AND SPVD.SITUACAOPARCELA = 'EM_ABERTO'
                        ORDER BY SPVD.DATALANCAMENTO DESC FETCH FIRST 1 ROWS ONLY)
WHERE ID = 618793387;

UPDATE PARCELAVALORDIVIDA
SET SITUACAOATUAL_ID = (SELECT SPVD.ID
                        FROM SITUACAOPARCELAVALORDIVIDA SPVD
                        WHERE PARCELA_ID = 813502293
                          AND SPVD.SITUACAOPARCELA = 'EM_ABERTO'
                        ORDER BY SPVD.DATALANCAMENTO DESC FETCH FIRST 1 ROWS ONLY)
WHERE ID = 813502293;

UPDATE PARCELAVALORDIVIDA
SET SITUACAOATUAL_ID = (SELECT SPVD.ID
                        FROM SITUACAOPARCELAVALORDIVIDA SPVD
                        WHERE PARCELA_ID = 618793387
                          AND SPVD.SITUACAOPARCELA = 'EM_ABERTO'
                        ORDER BY SPVD.DATALANCAMENTO DESC FETCH FIRST 1 ROWS ONLY)
WHERE ID = 618793387;
