create or replace TRIGGER AJUSTASITUACAOPARCELA AFTER DELETE OR INSERT OR UPDATE
ON SITUACAOPARCELAVALORDIVIDA
FOR EACH ROW
  BEGIN
    UPDATE PARCELAVALORDIVIDA SET SITUACAOATUAL_ID = :NEW.ID
    WHERE ID = :NEW.PARCELA_ID;
  END;
