INSERT INTO MENU (ID, LABEL, CAMINHO, PAI_ID, ORDEM, ICONE)
VALUES (HIBERNATE_SEQUENCE.nextval, 'CLASSIFICAÇÃO DE CONSTRUÇÃO',
        '/tributario/classificacaoconstrucao/lista.xhtml',
        (SELECT ID FROM MENU WHERE LABEL = 'CADASTRO TÉCNICO IMOBILIÁRIO'), 100, NULL);

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.nextval, 'TRIBUTÁRIO > CADASTRO TÉCNICO IMOBILIÁRIO > CLASSIFICAÇÃO DE CONSTRUÇÃO > LISTAR',
        '/tributario/classificacaoconstrucao/lista.xhtml', 0, 'TRIBUTARIO');

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.nextval, 'TRIBUTÁRIO > CADASTRO TÉCNICO IMOBILIÁRIO > CLASSIFICAÇÃO DE CONSTRUÇÃO > EDITAR',
        '/tributario/classificacaoconstrucao/edita.xhtml', 0, 'TRIBUTARIO');

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.nextval,
        'TRIBUTÁRIO > CADASTRO TÉCNICO IMOBILIÁRIO > CLASSIFICAÇÃO DE CONSTRUÇÃO > VISUALIZAR',
        '/tributario/classificacaoconstrucao/visualizar.xhtml', 0, 'TRIBUTARIO');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES ((SELECT ID FROM RECURSOSISTEMA WHERE CAMINHO = '/tributario/classificacaoconstrucao/lista.xhtml'),
        (SELECT ID FROM GRUPORECURSO WHERE MODULOSISTEMA = 'TRIBUTARIO' AND NOME = 'ADMINISTRADOR_GERAL'));

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES ((SELECT ID FROM RECURSOSISTEMA WHERE CAMINHO = '/tributario/classificacaoconstrucao/edita.xhtml'),
        (SELECT ID FROM GRUPORECURSO WHERE MODULOSISTEMA = 'TRIBUTARIO' AND NOME = 'ADMINISTRADOR_GERAL'));

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES ((SELECT ID FROM RECURSOSISTEMA WHERE CAMINHO = '/tributario/classificacaoconstrucao/visualizar.xhtml'),
        (SELECT ID FROM GRUPORECURSO WHERE MODULOSISTEMA = 'TRIBUTARIO' AND NOME = 'ADMINISTRADOR_GERAL'));
