CREATE OR REPLACE FORCE VIEW VWMATERIAL (MAT_ID, COD_MAT, MATERIAL,
  DESCRICAOCOMPLEMENTAR, COD_OBJ, OBJETOCOMPRA,
  COD_GRUPO, GRUPO, DATAESTOQUE, FINANCEIRO, FISICO, VL_UNITARIO)
AS
  (
    SELECT
      MAT.ID        AS MAT_ID,
      MAT.CODIGO    AS COD_MAT,
      MAT.DESCRICAO AS MATERIAL,
      MAT.DESCRICAOCOMPLEMENTAR,
      OBJ.CODIGO      AS COD_OBJ,
      OBJ.DESCRICAO   AS OBJETOcOMPRA,
      GRUPO.CODIGO    AS COD_GRUPO,
      GRUPO.DESCRICAO AS GRUPO,
      ESTOQUE.DATAESTOQUE,
      ESTOQUE.FINANCEIRO,
      ESTOQUE.FISICO,
      COALESCE(ESTOQUE.FINANCEIRO / ESTOQUE.FISICO, 0) AS VL_UNITARIO
    FROM
      LOCALESTOQUE
    INNER JOIN LOCALESTOQUEORCAMENTARIO LOCAL_ORC
    ON
      LOCAL_ORC.LOCALESTOQUE_ID = LOCALESTOQUE.ID
    INNER JOIN VWHIERARQUIAORCAMENTARIA VW_ORC
    ON
      VW_ORC.SUBORDINADA_ID = LOCAL_ORC.UNIDADEORCAMENTARIA_ID
    INNER JOIN VWHIERARQUIAADMINISTRATIVA VW_ADM
    ON
      VW_ADM.SUBORDINADA_ID = LOCALESTOQUE.UNIDADEORGANIZACIONAL_ID
    INNER JOIN ESTOQUE
    ON
      ESTOQUE.LOCALESTOQUEORCAMENTARIO_ID = LOCAL_ORC.ID
    INNER JOIN MATERIAL MAT
    ON
      MAT.ID = ESTOQUE.MATERIAL_ID
    INNER JOIN OBJETOCOMPRA OBJ
    ON
      OBJ.ID = MAT.OBJETOCOMPRA_ID
    INNER JOIN GRUPOMATERIAL GRUPO
    ON
      GRUPO.ID = MAT.GRUPO_ID
    WHERE
      ESTOQUE.DATAESTOQUE BETWEEN VW_ADM.INICIOVIGENCIA AND COALESCE(
      VW_ADM.FIMVIGENCIA, ESTOQUE.DATAESTOQUE)
    AND ESTOQUE.DATAESTOQUE BETWEEN VW_ORC.INICIOVIGENCIA AND COALESCE(
      VW_ORC.FIMVIGENCIA, ESTOQUE.DATAESTOQUE)
  )
