INSERT INTO MENU (ID, LABEL, CAMINHO, PAI_ID, ORDEM, ICONE)
VALUES (HIBERNATE_SEQUENCE.nextval, 'OBRAS', NULL, (SELECT ID FROM MENU WHERE LABEL = 'TRIBUTÁRIO'), 170, NULL);

UPDATE MENU
SET PAI_ID = (SELECT ID FROM MENU WHERE LABEL = 'OBRAS' AND PAI_ID = (SELECT ID FROM MENU WHERE LABEL = 'TRIBUTÁRIO'))
WHERE LABEL IN ('LANÇAMENTO E EMISSÃO DE ALVARÁ DE CONSTRUÇÃO', 'ALVARÁ IMEDIATO')
  AND PAI_ID = (SELECT ID FROM MENU WHERE LABEL = 'CADASTRO TÉCNICO IMOBILIÁRIO');
