  CREATE OR REPLACE FORCE VIEW VWCONSULTAALVARA
  AS
    (SELECT CE.ID CADASTRO_ID,
      CE.INSCRICAOCADASTRAL,
      CP.PESSOA_ID ID_PESSOA,
      COALESCE(PF.CPF, PJ.CNPJ) CPFCNPJ,
      COALESCE(PF.NOME, PJ.RAZAOSOCIAL) NOMERAZAO,
      ALV.TIPOALVARA,
      ALV.PROVISORIO PROVISORIO,
      C.DATACALCULO DATALANCAMENTO,
      E.ID ID_EXERCICIO,
      E.ANO ANO_EXERCICIO,
      C.SUBDIVIDA SD,
      PVD.ID ID_PARCELA,
      PVD.OPCAOPAGAMENTO_ID ID_OPCAOPAGAMENTO,
      PVD.VENCIMENTO,
      SPVD.SITUACAOPARCELA,
      SPVD.REFERENCIA,
      PACOTE_CONSULTA_DE_DEBITOS.GETNUMEROPARCELA(VD.ID, OP.ID, OP.PROMOCIONAL, PVD.SEQUENCIAPARCELA) PARCELA,
      COALESCE(ROUND(PACOTE_CONSULTA_DE_DEBITOS.GETVALORIMPOSTO(PVD.ID,1, SYSDATE), 2), 0)                                      AS VALORIMPOSTO,
      COALESCE(ROUND(PACOTE_CONSULTA_DE_DEBITOS.GETVALORTAXA(PVD.ID,1, SYSDATE), 2), 0)                                         AS VALORTAXA,
      COALESCE(ROUND(PACOTE_CONSULTA_DE_DEBITOS.GETVALORCORRECAO( PVD.ID, EXTRACT(YEAR FROM PVD.VENCIMENTO),1, SYSDATE), 2), 0) AS VALORCORRECAO,
      COALESCE(ROUND(PACOTE_CONSULTA_DE_DEBITOS.GETVALORJUROS(SYSDATE, PVD.ID,1), 2), 0)                                        AS VALORJUROS,
      COALESCE(ROUND(PACOTE_CONSULTA_DE_DEBITOS.GETVALORMULTA(SYSDATE, PVD.ID,1), 2), 0)                                        AS VALORMULTA,
      COALESCE(ROUND(PACOTE_CONSULTA_DE_DEBITOS.GETVALORHONORARIOS(PVD.ID, SYSDATE), 2), 0)                                     AS VALORHONORARIOS,
      COALESCE(ROUND(PACOTE_CONSULTA_DE_DEBITOS.GETVALORDESCONTO(PVD.ID, SYSDATE), 2), 0)                                       AS VALORDESCONTO,
      COALESCE(PACOTE_CONSULTA_DE_DEBITOS.GETVALORPARCELAPAGO(PVD.ID, SPVD.SITUACAOPARCELA), 0)                                 AS VALORPAGO
     FROM CALCULO C
    INNER JOIN CADASTROECONOMICO CE  ON C.CADASTRO_ID = CE.ID
    LEFT JOIN CALCULOALVARAFUNC CF ON CF.ID = C.ID
    LEFT JOIN CALCULOALVARALOCALIZACAO CL ON CL.ID = C.ID
    LEFT JOIN CALCULOALVARASANITARIO CS ON CS.ID = C.ID
    INNER JOIN ALVARA ALV ON ALV.ID = COALESCE(CF.ALVARA_ID, COALESCE(CL.ALVARA_ID , CS.ALVARA_ID))
    INNER JOIN CALCULOPESSOA CP ON CP.CALCULO_ID = C.ID
    LEFT JOIN PESSOAJURIDICA PJ ON PJ.ID = CP.PESSOA_ID
    LEFT JOIN PESSOAFISICA PF ON PF.ID = CP.PESSOA_ID
    INNER JOIN VALORDIVIDA VD ON VD.CALCULO_ID = C.ID
    INNER JOIN EXERCICIO E ON VD.EXERCICIO_ID = E.ID
    INNER JOIN PARCELAVALORDIVIDA PVD ON PVD.VALORDIVIDA_ID = VD.ID
    INNER JOIN OPCAOPAGAMENTO OP ON OP.ID = PVD.OPCAOPAGAMENTO_ID
    INNER JOIN SITUACAOPARCELAVALORDIVIDA SPVD ON SPVD.ID                  = GETULTIMASITUACAO(PVD.ID)
    WHERE SPVD.SITUACAOPARCELA <> 'ISOLAMENTO')
