INSERT INTO ASSUNTOLICENCIAMENTOAMBIENTAL
(ID, CODIGO, DESCRICAO, ATIVO)
VALUES(HIBERNATE_SEQUENCE.nextval, 1, 'Licença Prévia (LP)', 1);

INSERT INTO ASSUNTOLICENCIAMENTOAMBIENTAL
(ID, CODIGO, DESCRICAO, ATIVO)
VALUES(HIBERNATE_SEQUENCE.nextval, 2, 'Licença de Instalação (LI)', 1);

INSERT INTO ASSUNTOLICENCIAMENTOAMBIENTAL
(ID, CODIGO, DESCRICAO, ATIVO)
VALUES(HIBERNATE_SEQUENCE.nextval, 3, 'Licença Operação (LO)', 1);

INSERT INTO ASSUNTOLICENCIAMENTOAMBIENTAL
(ID, CODIGO, DESCRICAO, ATIVO)
VALUES(HIBERNATE_SEQUENCE.nextval, 4, 'Licença Prévia e de Instalação (LPI)', 1);

INSERT INTO ASSUNTOLICENCIAMENTOAMBIENTAL
(ID, CODIGO, DESCRICAO, ATIVO)
VALUES(HIBERNATE_SEQUENCE.nextval, 5, 'Licença de Instalação e de Operação (LIO)', 1);

INSERT INTO ASSUNTOLICENCIAMENTOAMBIENTAL
(ID, CODIGO, DESCRICAO, ATIVO)
VALUES(HIBERNATE_SEQUENCE.nextval, 6, 'Licença Ambiental de Recuperação (LAR)', 1);

INSERT INTO ASSUNTOLICENCIAMENTOAMBIENTAL
(ID, CODIGO, DESCRICAO, ATIVO)
VALUES(HIBERNATE_SEQUENCE.nextval, 7, 'Licença de Operação e Recuperação (LOR)', 1);

INSERT INTO ASSUNTOLICENCIAMENTOAMBIENTAL
(ID, CODIGO, DESCRICAO, ATIVO)
VALUES(HIBERNATE_SEQUENCE.nextval, 8, 'Licença Ambiental Única (LAU)', 1);

INSERT INTO ASSUNTOLICENCIAMENTOAMBIENTAL
(ID, CODIGO, DESCRICAO, ATIVO)
VALUES(HIBERNATE_SEQUENCE.nextval, 9, 'Licença Ambiental Simplificada (LAS)', 1);

INSERT INTO ASSUNTOLICENCIAMENTOAMBIENTAL
(ID, CODIGO, DESCRICAO, ATIVO)
VALUES(HIBERNATE_SEQUENCE.nextval, 10, 'Autorização para Corte de Árvores', 1);

INSERT INTO ASSUNTOLICENCIAMENTOAMBIENTAL
(ID, CODIGO, DESCRICAO, ATIVO)
VALUES(HIBERNATE_SEQUENCE.nextval, 11, 'Autorização para Supressão Vegetal', 1);

INSERT INTO ASSUNTOLICENCIAMENTOAMBIENTAL
(ID, CODIGO, DESCRICAO, ATIVO)
VALUES(HIBERNATE_SEQUENCE.nextval, 12, 'Autorização para Utilização de Som', 1);

INSERT INTO ASSUNTOLICENCIAMENTOAMBIENTAL
(ID, CODIGO, DESCRICAO, ATIVO)
VALUES(HIBERNATE_SEQUENCE.nextval, 13, 'Autorização para Arborização Urbana', 1);

INSERT INTO ASSUNTOLICENCIAMENTOAMBIENTAL
(ID, CODIGO, DESCRICAO, ATIVO)
VALUES(HIBERNATE_SEQUENCE.nextval, 14, 'Autorizações Diversas', 1);

INSERT INTO ASSUNTOLICENCIAMENTOAMBIENTAL
(ID, CODIGO, DESCRICAO, ATIVO)
VALUES(HIBERNATE_SEQUENCE.nextval, 15, 'Certidão de Dispensa de Licenciamento Ambiental', 1);

INSERT INTO ASSUNTOLICENCIAMENTOAMBIENTAL
(ID, CODIGO, DESCRICAO, ATIVO)
VALUES(HIBERNATE_SEQUENCE.nextval, 16, 'Licença para Extração Mineral', 1);

INSERT INTO ASSUNTOLICENCIAMENTOAMBIENTAL
(ID, CODIGO, DESCRICAO, ATIVO)
VALUES(HIBERNATE_SEQUENCE.nextval, 17, 'Análise de EIA-RIMA', 1);

INSERT INTO ASSUNTOLICENCIAMENTOAMBIENTAL
(ID, CODIGO, DESCRICAO, ATIVO)
VALUES(HIBERNATE_SEQUENCE.nextval, 18, 'Análise Técnica de Estudos Ambientais', 1);

INSERT INTO ASSUNTOLICENCIAMENTOAMBIENTAL
(ID, CODIGO, DESCRICAO, ATIVO)
VALUES(HIBERNATE_SEQUENCE.nextval, 19, 'Análise Técnica de Relatórios de Auto monitoramento', 1);

INSERT INTO ASSUNTOLICENCIAMENTOAMBIENTAL
(ID, CODIGO, DESCRICAO, ATIVO)
VALUES(HIBERNATE_SEQUENCE.nextval, 20, 'Emissão de Laudos Diversos', 1);

INSERT INTO ASSUNTOLICENCIAMENTOAMBIENTAL
(ID, CODIGO, DESCRICAO, ATIVO)
VALUES(HIBERNATE_SEQUENCE.nextval, 21, 'Corte de Árvore e Retirada do Entulho ou Outro não Especificado', 1);
