INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO) VALUES
(HIBERNATE_SEQUENCE.nextval, 'TRIBUTÁRIO - CADASTRO TÉCNICO MOBILIÁRIO - INTEGRACAO REDE SIM LOTE',
'/tributario/cadastromunicipal/cadastroeconomico/redesim/integracaolote.xhtml', 0 , 'TRIBUTARIO');
INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
SELECT
 (SELECT ID FROM RECURSOSISTEMA
  WHERE CAMINHO = '/tributario/cadastromunicipal/cadastroeconomico/redesim/integracaolote.xhtml'),
 (SELECT ID FROM GRUPORECURSO
  WHERE NOME = 'ADMINISTRADOR TRIBUTÁRIO')
  FROM DUAL;
INSERT INTO MENU (ID, LABEL, CAMINHO, PAI_ID, ORDEM)
VALUES (HIBERNATE_SEQUENCE.nextval, 'INTEGRAÇÃO REDESIM EM LOTE', '/tributario/cadastromunicipal/cadastroeconomico/redesim/integracaolote.xhtml',
(SELECT ID FROM MENU WHERE LABEL = 'CADASTRO TÉCNICO MOBILIÁRIO - C.M.C.'),
45);
