INSERT INTO HIERARQUIAVIA (ID, CODIGO, DESCRICAO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 1, 'Rodovia Federal');
INSERT INTO HIERARQUIAVIA (ID, CODIGO, DESCRICAO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 2, 'Rodovia Estadual');
INSERT INTO HIERARQUIAVIA (ID, CODIGO, DESCRICAO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 3, 'Arterial');
INSERT INTO HIERARQUIAVIA (ID, CODIGO, DESCRICAO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 4, 'Coletora');
INSERT INTO HIERARQUIAVIA (ID, CODIGO, DESCRICAO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 5, 'Local Principal');
INSERT INTO HIERARQUIAVIA (ID, CODIGO, DESCRICAO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 6, 'Local Secundária');
