CREATE OR REPLACE FORCE VIEW "VWCONSULTADIVIDAATIVA" 
AS
  (
    SELECT
      COALESCE(CI.ID, COALESCE(CE.ID, COALESCE(CR.ID, COALESCE(PF.ID, PJ.ID)))) ID_CADASTRO,
      COALESCE(CI.INSCRICAOCADASTRAL, COALESCE(CE.INSCRICAOCADASTRAL, COALESCE(CR.NUMEROINCRA, COALESCE(PF.CPF, PJ.CNPJ)))) INSCRICAOCADASTRAL,
      COALESCE(PF.CPF, PJ.CNPJ) CPFCNPJ,
      COALESCE(PF.NOME, PJ.RAZAOSOCIAL) NOMERAZAO,
      D.ID ID_DIVIDA,
      D.DESCRICAO DIVIDA,
      CASE
        WHEN CDA.ID IS NOT NULL
        THEN CDA.NUMERO
          ||'/'
          ||EXCDA.ANO
      END NUMEROCERTIDAO,
      PCJ.NUMEROPROCESSOFORUM NUMEROAJUIZAMENTO,
      E.ID ID_EXERCICIO,
      E.ANO EXERCICIO,
      EXCDA.ID ID_EXCDA,
      EXCDA.ANO EXERCICIO_CDA,
      DA.DATAINSCRICAO DATALANCAMENTO,
      PVD.ID ID_PARCELA,
      PVD.OPCAOPAGAMENTO_ID ID_OPCAOPAGAMENTO,
      PVD.VENCIMENTO,
      SPVD.SITUACAOPARCELA,
      SPVD.REFERENCIA,
      PACOTE_CONSULTA_DE_DEBITOS.GETNUMEROPARCELA(VD.ID, OP.ID, OP.PROMOCIONAL,
      PVD.SEQUENCIAPARCELA) PARCELA,
      COALESCE(ROUND(PACOTE_CONSULTA_DE_DEBITOS.GETVALORIMPOSTO(PVD.ID,1,
      SYSDATE), 2), 0) AS VALORIMPOSTO,
      COALESCE(ROUND(PACOTE_CONSULTA_DE_DEBITOS.GETVALORTAXA(PVD.ID,1, SYSDATE)
      , 2), 0) AS VALORTAXA,
      COALESCE(ROUND(PACOTE_CONSULTA_DE_DEBITOS.GETVALORCORRECAO( PVD.ID,
      EXTRACT(YEAR FROM PVD.VENCIMENTO),1, SYSDATE), 2), 0) AS VALORCORRECAO,
      COALESCE(ROUND(PACOTE_CONSULTA_DE_DEBITOS.GETVALORJUROS(SYSDATE, PVD.ID,1
      ), 2), 0) AS VALORJUROS,
      COALESCE(ROUND(PACOTE_CONSULTA_DE_DEBITOS.GETVALORMULTA(SYSDATE, PVD.ID,1
      ), 2), 0) AS VALORMULTA,
      COALESCE(ROUND(PACOTE_CONSULTA_DE_DEBITOS.GETVALORHONORARIOS(PVD.ID,
      SYSDATE), 2), 0) AS VALORHONORARIOS,
      COALESCE(ROUND(PACOTE_CONSULTA_DE_DEBITOS.GETVALORDESCONTO(PVD.ID,
      SYSDATE), 2), 0) AS VALORDESCONTO,
      COALESCE(PACOTE_CONSULTA_DE_DEBITOS.GETVALORPARCELAPAGO(PVD.ID,
      SPVD.SITUACAOPARCELA), 0) AS VALORPAGO,
      CASE SPVD.SITUACAOPARCELA
        WHEN 'PAGO'
        THEN COALESCE(PACOTE_CONSULTA_DE_DEBITOS.GETVALORPARCELAPAGO(PVD.ID,
          SPVD.SITUACAOPARCELA), 0)
        ELSE COALESCE(ROUND(PACOTE_CONSULTA_DE_DEBITOS.GETVALORIMPOSTO(PVD.ID,1
          , SYSDATE), 2), 0)                                                 + COALESCE(ROUND(
          PACOTE_CONSULTA_DE_DEBITOS.GETVALORTAXA(PVD.ID,1, SYSDATE), 2), 0) +
          COALESCE(ROUND(PACOTE_CONSULTA_DE_DEBITOS.GETVALORCORRECAO( PVD.ID,
          EXTRACT(YEAR FROM PVD.VENCIMENTO),1, SYSDATE), 2), 0) + COALESCE(
          ROUND(PACOTE_CONSULTA_DE_DEBITOS.GETVALORJUROS(SYSDATE, PVD.ID,1), 2)
          , 0)                       + COALESCE(ROUND(PACOTE_CONSULTA_DE_DEBITOS.GETVALORMULTA(
          SYSDATE, PVD.ID,1), 2), 0) + COALESCE(ROUND(
          PACOTE_CONSULTA_DE_DEBITOS.GETVALORHONORARIOS(PVD.ID, SYSDATE), 2), 0
          ) - COALESCE(ROUND(PACOTE_CONSULTA_DE_DEBITOS.GETVALORDESCONTO(PVD.ID
          , SYSDATE), 2), 0)
      END AS VALORTOTAL
    FROM ITEMINSCRICAODIVIDAATIVA IDA
    INNER JOIN INSCRICAODIVIDAATIVA DA ON IDA.INSCRICAODIVIDAATIVA_ID = DA.ID
    LEFT JOIN ITEMCERTIDAODIVIDAATIVA ICDA ON ICDA.ITEMINSCRICAODIVIDAATIVA_ID = IDA.ID
    LEFT JOIN CERTIDAODIVIDAATIVA CDA ON CDA.ID = ICDA.CERTIDAO_ID
    LEFT JOIN EXERCICIO EXCDA ON EXCDA.ID = CDA.EXERCICIO_ID
    LEFT JOIN PROCESSOJUDICIALCDA PJCDA ON PJCDA.CERTIDAODIVIDAATIVA_ID = CDA.ID
    LEFT JOIN PROCESSOJUDICIAL PCJ ON PCJ.ID = PJCDA.PROCESSOJUDICIAL_ID
    INNER JOIN CALCULO C ON C.ID = IDA.ID
    INNER JOIN CALCULOPESSOA CP ON CP.CALCULO_ID = C.ID
    LEFT JOIN PESSOAJURIDICA PJ ON PJ.ID = CP.PESSOA_ID
    LEFT JOIN PESSOAFISICA PF ON PF.ID = CP.PESSOA_ID
    LEFT JOIN CADASTROECONOMICO CE ON C.CADASTRO_ID = CE.ID
    LEFT JOIN CADASTROIMOBILIARIO CI ON C.CADASTRO_ID = CI.ID
    LEFT JOIN CADASTRORURAL CR ON C.CADASTRO_ID = CR.ID
    INNER JOIN VALORDIVIDA VD ON VD.CALCULO_ID = C.ID
    INNER JOIN EXERCICIO E ON E.ID = VD.EXERCICIO_ID
    INNER JOIN DIVIDA D ON D.ID = VD.DIVIDA_ID
    INNER JOIN PARCELAVALORDIVIDA PVD ON PVD.VALORDIVIDA_ID = VD.ID
    INNER JOIN OPCAOPAGAMENTO OP ON OP.ID = PVD.OPCAOPAGAMENTO_ID
    INNER JOIN SITUACAOPARCELAVALORDIVIDA SPVD ON SPVD.ID = GETULTIMASITUACAO(PVD.ID)
    WHERE
      SPVD.SITUACAOPARCELA <> 'ISOLAMENTO'
  )
  ;