    CREATE OR REPLACE
    TRIGGER AJUSTASITUACAOPARCELAINSERT BEFORE
    INSERT ON SITUACAOPARCELAVALORDIVIDA FOR EACH ROW DECLARE SITUACAO_ID NUMBER;
    BEGIN
       UPDATE PARCELAVALORDIVIDA SET SITUACAOATUAL_ID = :NEW.ID
       WHERE ID = :NEW.PARCELA_ID;
    END;
