insert into sessaoatividade values (HIBERNATE_SEQUENCE.nextval, 'A', 'AGRICULTURA, PECUÁRIA, PRODUÇÃO FLORESTAL, PESCA E AQÜICULTURA');
insert into sessaoatividade values (HIBERNATE_SEQUENCE.nextval, 'B', 'INDÚSTRIAS EXTRATIVAS');
insert into sessaoatividade values (HIBERNATE_SEQUENCE.nextval, 'C', 'INDÚSTRIAS DE TRANSFORMAÇÃO');
insert into sessaoatividade values (HIBERNATE_SEQUENCE.nextval, 'D', 'ELETRICIDADE E GÁS');
insert into sessaoatividade values (HIBERNATE_SEQUENCE.nextval, 'E', 'ÁGUA, ESGOTO, ATIVIDADES DE GESTÃO DE RESÍDUOS E DESCONTAMINAÇÃO');
insert into sessaoatividade values (HIBERNATE_SEQUENCE.nextval, 'F', 'CONSTRUÇÃO');
insert into sessaoatividade values (HIBERNATE_SEQUENCE.nextval, 'G', 'COMÉRCIO; REPARAÇÃO DE VEÍCULOS AUTOMOTORES E MOTOCICLETAS');
insert into sessaoatividade values (HIBERNATE_SEQUENCE.nextval, 'H', 'TRANSPORTE, ARMAZENAGEM E CORREIO');
insert into sessaoatividade values (HIBERNATE_SEQUENCE.nextval, 'I', 'ALOJAMENTO E ALIMENTAÇÃO');
insert into sessaoatividade values (HIBERNATE_SEQUENCE.nextval, 'J', 'INFORMAÇÃO E COMUNICAÇÃO');
insert into sessaoatividade values (HIBERNATE_SEQUENCE.nextval, 'K', 'ATIVIDADES FINANCEIRAS, DE SEGUROS E SERVIÇOS RELACIONADOS');
insert into sessaoatividade values (HIBERNATE_SEQUENCE.nextval, 'L', 'ATIVIDADES IMOBILIÁRIAS');
insert into sessaoatividade values (HIBERNATE_SEQUENCE.nextval, 'M', 'ATIVIDADES PROFISSIONAIS, CIENTÍFICAS E TÉCNICAS');
insert into sessaoatividade values (HIBERNATE_SEQUENCE.nextval, 'N', 'ATIVIDADES ADMINISTRATIVAS E SERVIÇOS COMPLEMENTARES');
insert into sessaoatividade values (HIBERNATE_SEQUENCE.nextval, 'O', 'ADMINISTRAÇÃO PÚBLICA, DEFESA E SEGURIDADE SOCIAL');
insert into sessaoatividade values (HIBERNATE_SEQUENCE.nextval, 'P', 'EDUCAÇÃO');
insert into sessaoatividade values (HIBERNATE_SEQUENCE.nextval, 'Q', 'SAÚDE HUMANA E SERVIÇOS SOCIAIS');
insert into sessaoatividade values (HIBERNATE_SEQUENCE.nextval, 'R', 'ARTES, CULTURA, ESPORTE E RECREAÇÃO');
insert into sessaoatividade values (HIBERNATE_SEQUENCE.nextval, 'S', 'OUTRAS ATIVIDADES DE SERVIÇOS');
insert into sessaoatividade values (HIBERNATE_SEQUENCE.nextval, 'T', 'SERVIÇOS DOMÉSTICOS');
insert into sessaoatividade values (HIBERNATE_SEQUENCE.nextval, 'U', 'ORGANISMOS INTERNACIONAIS E OUTRAS INSTITUIÇÕES EXTRATERRITORIAIS');
