UPDATE ENDERECOCORREIO
SET LOCALIDADE = 'XAPURI',
    UF        = 'AC'
WHERE ID IN (select ID
             from ENDERECOCORREIO
             where UPPER(TRIM(LOCALIDADE)) <> 'XAPURI'
               AND UPPER(TRIM(LOCALIDADE)) LIKE '%XAPURI%');

UPDATE ENDERECOCORREIO
SET LOCALIDADE = 'ACRELANDIA',
    UF        = 'AC'
WHERE ID IN (select ID
             from ENDERECOCORREIO
             where UPPER(TRIM(LOCALIDADE)) <> 'ACRELANDIA'
               AND (UPPER(TRIM(LOCALIDADE)) LIKE '%ACRELANDIA%' OR UPPER(TRIM(LOCALIDADE)) LIKE '%ACRELÂNDIA%'));

UPDATE ENDERECOCORREIO
SET LOCALIDADE = 'BUJARI',
    UF        = 'AC'
WHERE ID IN (select ID
             from ENDERECOCORREIO
             where UPPER(TRIM(LOCALIDADE)) <> 'BUJARI'
               AND UPPER(TRIM(LOCALIDADE)) LIKE '%BUJARI%');

UPDATE ENDERECOCORREIO
SET LOCALIDADE = 'JORDÃO',
    UF        = 'AC'
WHERE ID IN (select ID
             from ENDERECOCORREIO
             where UPPER(TRIM(LOCALIDADE)) <> 'JORDÃO'
               AND UPPER(TRIM(LOCALIDADE)) LIKE '%JORDÃO%');

UPDATE ENDERECOCORREIO
SET LOCALIDADE = 'BRASILÉIA',
    UF        = 'AC'
WHERE ID IN (select ID
             from ENDERECOCORREIO
             where UPPER(TRIM(LOCALIDADE)) <> 'BRASILÉIA'
               AND (UPPER(TRIM(LOCALIDADE)) LIKE '%BRASILÉIA%' OR UPPER(TRIM(LOCALIDADE)) LIKE '%BASILÉIA%'));

UPDATE ENDERECOCORREIO
SET LOCALIDADE = 'SENADOR GUIOMARD',
    UF        = 'AC'
WHERE ID IN (select ID
             from ENDERECOCORREIO
             where UPPER(TRIM(LOCALIDADE)) <> 'SENADOR GUIOMARD'
               AND (UPPER(TRIM(LOCALIDADE)) LIKE '%SENADOR GUIOMARD%' OR
                    UPPER(TRIM(LOCALIDADE)) LIKE '%SENADOR GUIMARD%'));

UPDATE ENDERECOCORREIO
SET LOCALIDADE = 'PORTO ACRE',
    UF        = 'AC'
WHERE ID IN (select ID
             from ENDERECOCORREIO
             where UPPER(TRIM(LOCALIDADE)) <> 'PORTO ACRE'
               AND UPPER(TRIM(LOCALIDADE)) LIKE '%PORTO ACRE%');

UPDATE ENDERECOCORREIO
SET LOCALIDADE = 'MANCIO LIMA',
    UF        = 'AC'
WHERE ID IN (select ID
             from ENDERECOCORREIO
             where UPPER(TRIM(LOCALIDADE)) <> 'MANCIO LIMA'
               AND UPPER(TRIM(LOCALIDADE)) LIKE '%MANCIO LIMA%');

UPDATE ENDERECOCORREIO
SET LOCALIDADE = 'SENA MADUREIRA',
    UF        = 'AC'
WHERE ID IN (select ID
             from ENDERECOCORREIO
             where UPPER(TRIM(LOCALIDADE)) <> 'SENA MADUREIRA'
               AND UPPER(TRIM(LOCALIDADE)) LIKE '%SENA MADUREIRA%');

UPDATE ENDERECOCORREIO
SET LOCALIDADE = 'RIO BRANCO',
    UF        = 'AC'
WHERE ID IN (select ID
             from ENDERECOCORREIO
             WHERE UPPER(TRIM(LOCALIDADE)) <> 'RIO BRANCO'
               AND UPPER(TRIM(LOCALIDADE)) LIKE '%RIO BRANCO%'
               and UPPER(TRIM(LOCALIDADE)) NOT LIKE '%RIO BRANCO DO SUL%'
               and UPPER(TRIM(LOCALIDADE)) NOT LIKE '%RIO BRANCO DO IVAÍ%'
               and UPPER(TRIM(LOCALIDADE)) NOT LIKE '%VISCONDE DO RIO BRANCO%');
