DELETE FROM SITUACAOPARCELAVALORDIVIDA
WHERE ID = (SELECT SPVD.ID
            FROM SITUACAOPARCELAVALORDIVIDA SPVD
            WHERE SPVD.PARCELA_ID = 618793387
              AND SPVD.SITUACAOPARCELA = 'ESTORNADO'
            ORDER BY SPVD.DATALANCAMENTO DESC FETCH FIRST 1 ROWS ONLY);

DELETE FROM SITUACAOPARCELAVALORDIVIDA
WHERE ID = (SELECT SPVD.ID
            FROM SITUACAOPARCELAVALORDIVIDA SPVD
            WHERE SPVD.PARCELA_ID = 813502293
              AND SPVD.SITUACAOPARCELA = 'ESTORNADO'
            ORDER BY SPVD.DATALANCAMENTO DESC FETCH FIRST 1 ROWS ONLY);

DELETE FROM SITUACAOPARCELAVALORDIVIDA
WHERE ID = (SELECT SPVD.ID
            FROM SITUACAOPARCELAVALORDIVIDA SPVD
            WHERE SPVD.PARCELA_ID = 10798616033
              AND SPVD.SITUACAOPARCELA = 'ESTORNADO'
            ORDER BY SPVD.DATALANCAMENTO DESC FETCH FIRST 1 ROWS ONLY);
