update parcelavalordivida set vencimento = to_date('30/12/2021','dd/MM/yyyy') where id in (select pvd.id from parcelavalordivida pvd
inner join situacaoparcelavalordivida spvd on spvd.id = pvd.SITUACAOATUAL_ID
inner join valordivida vd on vd.id = pvd.valordivida_id
inner join processoparcelamento pp on pp.id = vd.calculo_id
where spvd.situacaoparcela = 'EM_ABERTO'
  and pvd.VENCIMENTO = to_date('31/12/2021','dd/MM/yyyy'));
update parcelavalordivida set vencimento = to_date('30/12/2022','dd/MM/yyyy') where id in (select pvd.id from parcelavalordivida pvd
inner join situacaoparcelavalordivida spvd on spvd.id = pvd.SITUACAOATUAL_ID
inner join valordivida vd on vd.id = pvd.valordivida_id
inner join processoparcelamento pp on pp.id = vd.calculo_id
where spvd.situacaoparcela = 'EM_ABERTO'
  and pvd.VENCIMENTO = to_date('31/12/2022','dd/MM/yyyy'));
update parcelavalordivida set vencimento = to_date('30/12/2023','dd/MM/yyyy') where id in (select pvd.id from parcelavalordivida pvd
inner join situacaoparcelavalordivida spvd on spvd.id = pvd.SITUACAOATUAL_ID
inner join valordivida vd on vd.id = pvd.valordivida_id
inner join processoparcelamento pp on pp.id = vd.calculo_id
where spvd.situacaoparcela = 'EM_ABERTO'
  and pvd.VENCIMENTO = to_date('31/12/2023','dd/MM/yyyy'));
update parcelavalordivida set vencimento = to_date('30/12/2024','dd/MM/yyyy') where id in (select pvd.id from parcelavalordivida pvd
inner join situacaoparcelavalordivida spvd on spvd.id = pvd.SITUACAOATUAL_ID
inner join valordivida vd on vd.id = pvd.valordivida_id
inner join processoparcelamento pp on pp.id = vd.calculo_id
where spvd.situacaoparcela = 'EM_ABERTO'
  and pvd.VENCIMENTO = to_date('31/12/2024','dd/MM/yyyy'));
update parcelavalordivida set vencimento = to_date('30/12/2025','dd/MM/yyyy') where id in (select pvd.id from parcelavalordivida pvd
inner join situacaoparcelavalordivida spvd on spvd.id = pvd.SITUACAOATUAL_ID
inner join valordivida vd on vd.id = pvd.valordivida_id
inner join processoparcelamento pp on pp.id = vd.calculo_id
where spvd.situacaoparcela = 'EM_ABERTO'
  and pvd.VENCIMENTO = to_date('31/12/2025','dd/MM/yyyy'));
