    CREATE OR REPLACE TRIGGER AJUSTASITUACAOPARCELAINSERT BEFORE
      INSERT ON SITUACAOPARCELAVALORDIVIDA FOR EACH ROW DECLARE SITUACAO_ID NUMBER;
      SITUACAO_DATA TIMESTAMP;
      BEGIN

        SELECT ID, DATALANCAMENTO INTO SITUACAO_ID, SITUACAO_DATA
           FROM (SELECT ID,
            DATALANCAMENTO
          FROM SITUACAOPARCELAVALORDIVIDA
          WHERE PARCELA_ID = :NEW.PARCELA_ID
          ORDER BY DATALANCAMENTO DESC,
            ID DESC
          )
        WHERE ROWNUM = 1;
        IF :NEW.DATALANCAMENTO > SITUACAO_DATA THEN
          UPDATE PARCELAVALORDIVIDA SET SITUACAOATUAL_ID = :NEW.ID
          WHERE ID = :NEW.PARCELA_ID;
        END IF;
       EXCEPTION
         WHEN NO_DATA_FOUND THEN
           UPDATE PARCELAVALORDIVIDA SET SITUACAOATUAL_ID = :NEW.ID
           WHERE ID = :NEW.PARCELA_ID;
    END;
