create or replace FUNCTION GETAREACONSTRUIDAIPTU(IPTU_ID in NUMBER)
    RETURN NUMBER
AS
    AREACONSTRUIDA NUMBER;
BEGIN
    SELECT SUM(carne.areaconstruida) INTO AREACONSTRUIDA
    FROM carneiptu carne
    WHERE carne.calculo_id = IPTU_ID;
    return AREACONSTRUIDA;
END GETAREACONSTRUIDAIPTU;
