INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.nextval,
        'TRIBUTÁRIO > CONTA CORRENTE > PROCESSO DE DÉBITOS > PROCESSO DE PRESCRIÇÃO EM LOTE> VISUALIZAR',
        '/tributario/contacorrente/processodebitosprescricaolote/visualizar.xhtml', 0, 'TRIBUTARIO');

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.nextval,
        'TRIBUTÁRIO > CONTA CORRENTE > PROCESSO DE DÉBITOS > PROCESSO DE PRESCRIÇÃO EM LOTE> LISTAR',
        '/tributario/contacorrente/processodebitosprescricaolote/lista.xhtml', 0, 'TRIBUTARIO');

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.nextval,
        'TRIBUTÁRIO > CONTA CORRENTE > PROCESSO DE DÉBITOS > PROCESSO DE PRESCRIÇÃO EM LOTE> EDITAR',
        '/tributario/contacorrente/processodebitosprescricaolote/edita.xhtml', 0, 'TRIBUTARIO');

INSERT INTO GRUPORECURSOSISTEMA GRS (GRUPORECURSO_ID, RECURSOSISTEMA_ID)
VALUES (8757021, (SELECT RS.ID FROM RECURSOSISTEMA RS WHERE RS.CAMINHO = '/tributario/contacorrente/processodebitosprescricaolote/visualizar.xhtml'));

INSERT INTO GRUPORECURSOSISTEMA GRS (GRUPORECURSO_ID, RECURSOSISTEMA_ID)
VALUES (8757021, (SELECT RS.ID FROM RECURSOSISTEMA RS WHERE RS.CAMINHO = '/tributario/contacorrente/processodebitosprescricaolote/lista.xhtml'));

INSERT INTO GRUPORECURSOSISTEMA GRS (GRUPORECURSO_ID, RECURSOSISTEMA_ID)
VALUES (8757021, (SELECT RS.ID FROM RECURSOSISTEMA RS WHERE RS.CAMINHO = '/tributario/contacorrente/processodebitosprescricaolote/edita.xhtml'));

INSERT INTO MENU (ID, LABEL, CAMINHO, PAI_ID, ORDEM, ICONE)
VALUES (HIBERNATE_SEQUENCE.nextval, 'PROCESSO DE PRESCRIÇÃO EM LOTE',
        '/tributario/contacorrente/processodebitosprescricaolote/lista.xhtml',
        (SELECT P.ID FROM MENU P WHERE P.LABEL = 'PROCESSO DE DÉBITOS'), 72, NULL);
