CREATE
OR REPLACE FUNCTION FUNC_NOTA_ESCRITURADA(ID_DECLARACAO NUMBER)
RETURN NUMBER
AS
    ISS_RETIDO NUMBER;
    ID_DMS
NUMBER;
BEGIN
SELECT COALESCE(ISSRETIDO, 0)
INTO ISS_RETIDO
FROM DECLARACAOPRESTACAOSERVICO DEC
WHERE DEC.ID = ID_DECLARACAO;

IF
(ISS_RETIDO = 0) THEN
SELECT MAX(DMS.ID)
INTO ID_DMS
FROM DECLARACAOMENSALSERVICO DMS
         INNER JOIN NOTADECLARADA ND ON ND.DECLARACAOMENSALSERVICO_ID = DMS.ID
WHERE DMS.SITUACAO != 'CANCELADO'
          AND DMS.TIPOMOVIMENTO = 'NORMAL'
          AND ND.DECLARACAOPRESTACAOSERVICO_ID = ID_DECLARACAO;
ELSE
SELECT MAX(DMS.ID)
INTO ID_DMS
FROM DECLARACAOMENSALSERVICO DMS
         INNER JOIN NOTADECLARADA ND ON ND.DECLARACAOMENSALSERVICO_ID = DMS.ID
WHERE DMS.SITUACAO != 'CANCELADO'
          AND DMS.TIPOMOVIMENTO IN ('RETENCAO', 'ISS_RETIDO')
          AND ND.DECLARACAOPRESTACAOSERVICO_ID = ID_DECLARACAO;
END IF;

    IF
(ID_DMS IS NOT NULL) THEN
        RETURN (1);
END IF;

RETURN (0);
END;
