update SOLICITACAOITBIONLINEDOCUMENTO SOLITBIDOC
set DATAREGISTRO = (SELECT SOLITBI.DATALANCAMENTO
                    FROM SOLICITACAOITBIONLINE SOLITBI
                    WHERE SOLITBIDOC.SOLICITACAOITBIONLINE_ID = SOLITBI.ID)
