insert into CDAREMESSAPROTESTO (ID, REMESSAPROTESTO_ID, CDA_ID, CODIGOPROCESSO, CADASTROPROCESSO, NOSSONUMERO, SITUACAOPROTESTO)
select hibernate_sequence.nextval, REMESSAPROTESTO_ID, CDA_ID, CODIGOPROCESSO, CADASTROPROCESSO, NOSSONUMERO, SITUACAOPROTESTO from (
SELECT distinct REMESSAPROTESTO_ID, CDA_ID, CODIGOPROCESSO, CADASTROPROCESSO, NOSSONUMERO, SITUACAOPROTESTO from PARCELAREMESSAPROTESTO)
