update PARCELAVALORDIVIDA
set VENCIMENTO=to_date('31-12-2020', 'dd-MM-yyyy')
where VALORDIVIDA_ID in (
    SELECT VW.VALORDIVIDA_ID
    FROM VWCONSULTADEDEBITOSSEMVALORES VW
             INNER JOIN CADASTROECONOMICO CMC ON CMC.ID = VW.CADASTRO_ID
             inner join PERMISSIONARIO on CMC.ID = PERMISSIONARIO.CADASTROECONOMICO_ID
             inner join PERMISSAOTRANSPORTE on PERMISSIONARIO.PERMISSAOTRANSPORTE_ID = PERMISSAOTRANSPORTE.ID
    WHERE vw.EXERCICIO = '2020'
      AND VW.SITUACAOPARCELA = 'EM_ABERTO'
      and vw.DIVIDA_ID = 6194163
);
