    CREATE OR REPLACE FORCE VIEW VWCONSULTAISSQN AS
      (SELECT DISTINCT CE.ID ID_CADASTRO,
        CE.INSCRICAOCADASTRAL INSCRICAOCADASTRAL,
        E.ANO EXERCICIO,
        CP.PESSOA_ID ID_PESSOA,
        COALESCE(PF.CPF, PJ.CNPJ) CPFCNPJ,
        COALESCE(PF.NOME, PJ.RAZAOSOCIAL) NOMERAZAO,
        COALESCE(ISS.TIPOCALCULOISS, 'MENSAL') TIPOCALCULOISS,
        COALESCE(PROC_ISS.MESREFERENCIA, NFSE.MESDEREFERENCIA) MESREFERENCIA,
        C.DATACALCULO DATALANCAMENTO,
        PVD.ID ID_PARCELA,
        PVD.OPCAOPAGAMENTO_ID ID_OPCAOPAGAMENTO,
        C.SUBDIVIDA,
        PVD.VENCIMENTO,
        SPVD.SITUACAOPARCELA,
        SPVD.REFERENCIA,
        PACOTE_CONSULTA_DE_DEBITOS.GETNUMEROPARCELA(VD.ID, OP.ID, OP.PROMOCIONAL, PVD.SEQUENCIAPARCELA) PARCELA,
        COALESCE(ROUND(PACOTE_CONSULTA_DE_DEBITOS.GETVALORIMPOSTO(PVD.ID,1, SYSDATE), 2), 0)                                      AS VALORIMPOSTO,
        COALESCE(ROUND(PACOTE_CONSULTA_DE_DEBITOS.GETVALORTAXA(PVD.ID,1, SYSDATE), 2), 0)                                         AS VALORTAXA,
        COALESCE(ROUND(PACOTE_CONSULTA_DE_DEBITOS.GETVALORCORRECAO( PVD.ID, EXTRACT(YEAR FROM PVD.VENCIMENTO),1, SYSDATE), 2), 0) AS VALORCORRECAO,
        COALESCE(ROUND(PACOTE_CONSULTA_DE_DEBITOS.GETVALORJUROS(SYSDATE, PVD.ID,1), 2), 0)                                        AS VALORJUROS,
        COALESCE(ROUND(PACOTE_CONSULTA_DE_DEBITOS.GETVALORMULTA(SYSDATE, PVD.ID,1), 2), 0)                                        AS VALORMULTA,
        COALESCE(ROUND(PACOTE_CONSULTA_DE_DEBITOS.GETVALORHONORARIOS(PVD.ID, SYSDATE), 2), 0)                                     AS VALORHONORARIOS,
        COALESCE(ROUND(PACOTE_CONSULTA_DE_DEBITOS.GETVALORDESCONTO(PVD.ID, SYSDATE), 2), 0)                                       AS VALORDESCONTO,
        COALESCE(PACOTE_CONSULTA_DE_DEBITOS.GETVALORPARCELAPAGO(PVD.ID, SPVD.SITUACAOPARCELA), 0)                                 AS VALORPAGO
       FROM CALCULO C
      INNER JOIN CADASTROECONOMICO CE ON C.CADASTRO_ID = CE.ID
      LEFT JOIN CALCULOISS ISS ON C.ID = ISS.ID
      LEFT JOIN CALCULONFSE NFSE ON C.ID = NFSE.ID
      LEFT JOIN PROCESSOCALCULOISS PROC_ISS ON PROC_ISS.ID = ISS.PROCESSOCALCULOISS_ID
      INNER JOIN CALCULOPESSOA CP ON CP.CALCULO_ID = C.ID
      LEFT JOIN PESSOAJURIDICA PJ ON PJ.ID = CP.PESSOA_ID
      LEFT JOIN PESSOAFISICA PF ON PF.ID = CP.PESSOA_ID
      INNER JOIN VALORDIVIDA VD ON VD.CALCULO_ID = C.ID
      INNER JOIN EXERCICIO E ON E.ID = VD.EXERCICIO_ID
      INNER JOIN PARCELAVALORDIVIDA PVD ON PVD.VALORDIVIDA_ID = VD.ID
      INNER JOIN OPCAOPAGAMENTO OP ON OP.ID = PVD.OPCAOPAGAMENTO_ID
      INNER JOIN SITUACAOPARCELAVALORDIVIDA SPVD ON SPVD.ID = GETULTIMASITUACAO(PVD.ID)
      WHERE SPVD.SITUACAOPARCELA <> 'ISOLAMENTO' AND C.TIPOCALCULO IN ('ISS', 'NFSE'))
