UPDATE CANCDECLAPRESTACAOSERVICO uc SET solicitante = (
SELECT coalesce(pf.CPF, pj.CNPJ)||' - '||COALESCE(pf.NOME, pj.RAZAOSOCIAL) FROM CANCDECLAPRESTACAOSERVICO c
INNER JOIN USUARIOWEB uw ON uw.id = c.USUARIOCANCELAMENTMO_ID
left JOIN PESSOAFISICA pf ON pf.id = uw.PESSOA_ID
LEFT JOIN pessoajuridica pj ON pj.id = uw.PESSOA_ID
WHERE c.id = uc.id)
