UPDATE DECLARACAOPRESTACAOSERVICO DPS SET TOTALSERVICOS =
(SELECT SUM(IDS.QUANTIDADE * IDS.VALORSERVICO)
    FROM ITEMDECLARACAOSERVICO IDS WHERE IDS.DECLARACAOPRESTACAOSERVICO_ID = DPS.ID)
WHERE DPS.ID > 0;
UPDATE DECLARACAOPRESTACAOSERVICO DPS SET VALORLIQUIDO  = TOTALSERVICOS - DESCONTOSINCONDICIONAIS  - RETENCOESFEDERAIS -
CASE WHEN ISSRETIDO = 1 THEN ISSCALCULADO ELSE 0 END
WHERE DPS.ID > 0;
