DELETE FROM PERMISSAOCMCNFSE WHERE USERNFSECADASTROECONOMICO_ID IN (
SELECT P.USERNFSECADASTROECONOMICO_ID
   FROM USUARIOWEB UW
  INNER JOIN USERNFSECADASTROECONOMICO UCE ON UCE.USUARIONFSE_ID = UW.ID
  INNER JOIN PERMISSAOCMCNFSE P ON P.USERNFSECADASTROECONOMICO_ID = UCE.ID
WHERE (COALESCE(UW.ACTIVATED, 0) = 0 OR UW.PESSOA_ID IS NULL)
  AND EXISTS(SELECT 1 FROM USUARIOWEB OUW WHERE OUW.LOGIN = UW.LOGIN AND OUW.ID != UW.ID));

DELETE FROM USERNFSECADASTROECONOMICO WHERE ID IN (
SELECT UCE.ID
   FROM USUARIOWEB UW
  INNER JOIN USERNFSECADASTROECONOMICO UCE ON UCE.USUARIONFSE_ID = UW.ID
WHERE (COALESCE(UW.ACTIVATED, 0) = 0 OR UW.PESSOA_ID IS NULL)
  AND EXISTS(SELECT 1 FROM USUARIOWEB OUW WHERE OUW.LOGIN = UW.LOGIN AND OUW.ID != UW.ID));


DELETE FROM USUARIOWEB UW
WHERE (COALESCE(UW.ACTIVATED, 0) = 0 OR UW.PESSOA_ID IS NULL)
  AND EXISTS(SELECT 1 FROM USUARIOWEB OUW WHERE OUW.LOGIN = UW.LOGIN AND OUW.ID != UW.ID);
