DELETE
FROM ITEMCREDITOCONTACORRENTE
WHERE ID = (SELECT ICCC.ID
            FROM ITEMCREDITOCONTACORRENTE ICCC
                     INNER JOIN PARCELAVALORDIVIDA PVD ON ICCC.PARCELA_ID = PVD.ID
                     inner join valordivida vd on vd.id = pvd.valordivida_id
                     INNER JOIN EXERCICIO EX ON VD.EXERCICIO_ID = EX.ID
            WHERE ICCC.CREDITOCONTACORRENTE_ID = 10979730900
              AND EX.ANO = 2023);

INSERT INTO PARCELACONTACORRENTETRIB (ID, CONTACORRENTE_ID, PARCELAVALORDIVIDA_ID, TIPODIFERENCA, VALORDIFERENCA,
                                      CALCULOCONTACORRENTE_ID, VALORDIFERENCAUTILIZADA, ORIGEM, ITEMLOTEBAIXA_ID,
                                      COMPENSADA, VALORCOMPESADO)
SELECT HIBERNATE_SEQUENCE.nextval,
       (SELECT CCT.ID
        FROM CONTACORRENTETRIBUTARIA CCT
                 INNER JOIN PESSOAFISICA PF ON CCT.PESSOA_ID = PF.ID
        WHERE PF.CPF = '02161354272'),
       ICCC.PARCELA_ID,
       'CREDITO_ARRECADACAO',
       iccc.DIFERENCACONTACORRENTE,
       null,
       null,
       'PROCESSO',
       null,
       null,
       null
FROM ITEMCREDITOCONTACORRENTE ICCC
WHERE ICCC.CREDITOCONTACORRENTE_ID = 10979730900;

UPDATE CREDITOCONTACORRENTE
SET SITUACAO = 'FINALIZADO', MOTIVOESTORNO = null, dataestorno = null
WHERE ID = 10979730900;
