insert into INCIDENCIATRIBESOCIAL values (hibernate_sequence.nextval, '00', 'Não é base de cálculo');
insert into INCIDENCIATRIBESOCIAL values (hibernate_sequence.nextval, '01', 'Não é base de cálculo em função de acordos internacionais de previdência social');
insert into INCIDENCIATRIBESOCIAL values (hibernate_sequence.nextval, '11', 'Mensal');
insert into INCIDENCIATRIBESOCIAL values (hibernate_sequence.nextval, '12', '13º Salário');
insert into INCIDENCIATRIBESOCIAL values (hibernate_sequence.nextval, '13', 'Exclusiva do Empregador - mensal');
insert into INCIDENCIATRIBESOCIAL values (hibernate_sequence.nextval, '14', 'Exclusiva do Empregador - 13° salário');
insert into INCIDENCIATRIBESOCIAL values (hibernate_sequence.nextval, '15', 'Exclusiva do segurado - mensal');
insert into INCIDENCIATRIBESOCIAL values (hibernate_sequence.nextval, '16', 'Exclusiva do segurado - 13° salário');
insert into INCIDENCIATRIBESOCIAL values (hibernate_sequence.nextval, '21', 'Salário maternidade mensal pago pelo Empregador');
insert into INCIDENCIATRIBESOCIAL values (hibernate_sequence.nextval, '22', 'Salário maternidade - 13º Salário, pago pelo Empregador');
insert into INCIDENCIATRIBESOCIAL values (hibernate_sequence.nextval, '23', 'Auxilio doença mensal - Regime Próprio de Previdência Social');
insert into INCIDENCIATRIBESOCIAL values (hibernate_sequence.nextval, '24', 'Auxilio doença 13o salário doença - Regime próprio de previdência social');
insert into INCIDENCIATRIBESOCIAL values (hibernate_sequence.nextval, '25', 'Salário maternidade mensal pago pelo INSS');
insert into INCIDENCIATRIBESOCIAL values (hibernate_sequence.nextval, '26', 'Salário maternidade - 13° salário, pago pelo INSS');
insert into INCIDENCIATRIBESOCIAL values (hibernate_sequence.nextval, '31', 'Mensal');
insert into INCIDENCIATRIBESOCIAL values (hibernate_sequence.nextval, '32', '13º Salário');
insert into INCIDENCIATRIBESOCIAL values (hibernate_sequence.nextval, '34', 'SEST');
insert into INCIDENCIATRIBESOCIAL values (hibernate_sequence.nextval, '35', 'SENAT');
insert into INCIDENCIATRIBESOCIAL values (hibernate_sequence.nextval, '51', 'Salário-família');
insert into INCIDENCIATRIBESOCIAL values (hibernate_sequence.nextval, '61', 'Complemento de salário-mínimo - Regime próprio de previdência social');
insert into INCIDENCIATRIBESOCIAL values (hibernate_sequence.nextval, '91', 'Mensal');
insert into INCIDENCIATRIBESOCIAL values (hibernate_sequence.nextval, '92', '13º Salário');
insert into INCIDENCIATRIBESOCIAL values (hibernate_sequence.nextval, '93', 'Salário maternidade');
insert into INCIDENCIATRIBESOCIAL values (hibernate_sequence.nextval, '94', 'Salário maternidade 13º salário');
insert into INCIDENCIATRIBESOCIAL values (hibernate_sequence.nextval, '95', 'Exclusiva do Empregador - mensal');
insert into INCIDENCIATRIBESOCIAL values (hibernate_sequence.nextval, '96', 'Exclusiva do Empregador - 13º salário');
insert into INCIDENCIATRIBESOCIAL values (hibernate_sequence.nextval, '97', 'Exclusiva do Empregador - Salário maternidade');
insert into INCIDENCIATRIBESOCIAL values (hibernate_sequence.nextval, '98', 'Exclusiva do Empregador - Salário maternidade 13º salário');
