insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '00', 'Rendimento não tributável');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '01', 'Rendimento não tributável em função de acordos internacionais de bitributação');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '09', 'Outras verbas não consideradas como base de cálculo ou rendimento');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '11', 'Remuneração mensal');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '12', '13ª Salário');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '13', 'Férias');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '14', 'PLR');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '15', 'Rendimentos Recebidos Acumuladamente - RRA');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '31', 'Remuneração mensal');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '32', '13º Salário');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '33', 'Férias');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '34', 'PLR');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '35', 'RRA');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '41', 'Previdência Social Oficial - PSO - Remuner. mensal');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '42', 'PSO - 13° salário');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '43', 'PSO - Férias');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '44', 'PSO - RRA');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '46', 'Previdência Privada - salário mensal');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '47', 'Previdência Privada - 13° salário');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '51', 'Pensão Alimentícia - Remuneração mensal');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '52', 'Pensão Alimentícia - 13° salário');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '53', 'Pensão Alimentícia - Férias');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '54', 'Pensão Alimentícia - PLR');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '55', 'Pensão Alimentícia - RRA');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '61', 'Fundo de Aposentadoria Programada Individual - FAPI - Remuneração mensal');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '62', 'Fundo de Aposentadoria Programada Individual - FAPI - 13° salário');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '63', 'Fundação de Previdência Complementar do Servidor Público - Funpresp - Remuneração mensal');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '64', 'Fundação de Previdência Complementar do Servidor Público - Funpresp - 13° salário');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '70', 'Parcela Isenta 65 anos - Remuneração mensal');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '71', 'Parcela Isenta 65 anos - 13° salário');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '72', 'Diárias');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '73', 'Ajuda de custo');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '74', 'Indenização e rescisão de contrato, inclusive a título de PDV e acidentes de trabalho');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '75', 'Abono pecuniário');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '76', 'Pensão, aposentadoria ou reforma por moléstia grave ou acidente em serviço - Remuneração Mensal');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '77', 'Pensão, aposentadoria ou reforma por moléstia grave ou acidente em serviço - 13° salário');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '78', 'Valores pagos a titular ou sócio de microempresa ou empresa de pequeno porte, exceto pró-labore e alugueis');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '79', 'Outras isenções (o nome da rubrica deve ser claro para identificação da natureza dos valores)');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '81', 'Depósito judicial');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '82', 'Compensação judicial do ano calendário');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '83', 'Compensação judicial de anos anteriores');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '91', 'Remuneração mensal');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '92', '13º Salário');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '93', 'Férias');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '94', 'PLR');
insert into INCIDENCIATRIBUTARIAIRRF values (hibernate_sequence.nextval, '95', 'RRA');
