insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 18, 'Vencimento Horas Afastados');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 103, 'Vencimento Cedidos com/sem ônus');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 23, 'Adiantamento de 13º Salário');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 63, 'Adiantamento de Férias');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 82, 'Adiantamento de Pensões');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 62, 'Adiantamento Salarial (Proventos Ordinário)');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 22, '13º Salário');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 81, '14º Salário');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 94, '15º Salário');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 24, 'Indenização de 13º Salário');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 79, 'Férias (Horas Normais e DSR)');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 20, 'Férias em Dobro');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 21, 'Indenização de Férias / Abono Pecuniário');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 19, 'Terço de Férias (inclui DSR sobre 1/3)');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 1, 'Auxílio Alimentação');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 84, 'Auxilio Estágio / Bolsa de Estudo');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 7, 'Auxílio Creche');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 85, 'Auxilio Fardamento');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 86, 'Auxílio Funeral');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 89, 'Auxílio Maternidade');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 3, 'Auxílio Moraria');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 2, 'Auxílio Saúde');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 4, 'Auxílio Transportes');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 5, 'Diárias');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 59, 'Acordos Judiciais / Extra-Judicias / Trabalhistas / Administrativos');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 73, 'Adicional de zona Rural / Difícil Acesso');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 53, 'Adicional Noturno');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 54, 'Aviso Prévio Indenizado');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 78, 'DSR - Descanso Semanal Remunerado');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 13, 'Horas-Extras');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 52, 'Periculosidade');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 75, 'Regência');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 98, 'SOBREAVISO');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 96, 'SUBSIDIO');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 11, 'Vencimento');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 17, 'Vencimento em Atraso / Diferença');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 58, 'Abono de Permanência');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 80, 'Adicional Diurno');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 57, 'Adicional/Gratificação de Titulação (Ensino/nível Superior)');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 61, 'Adicional por Tempo de Serviço');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 14, 'Anuênio');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 68, 'Biênio');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 60, 'Dedicação Exclusiva / Integral');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 76, 'Diferenças Salariais po Força de Lei');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 16, 'Funções Gratificadas');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 51, 'Insalubridade');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 12, 'Parcela Variável');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 102, 'Prêmios Anuais');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 88, 'Quadriênio');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 87, 'Quinquênio');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 15, 'Sexta Parte');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 91, 'TRIÊNIO');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 107, 'Acertos PDV');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 64, 'Ajuda de Custo');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 67, 'Aulas Complementares');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 90, 'Complementação De Salario');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 93, 'Diferenças Salariais');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 74, 'Incorporações');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 95, 'P.A.E');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 71, 'Plantões');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 69, 'Reembolso de Desconto Indevido');
insert into ClassificacaoVerba(id, codigo, descricao) values (hibernate_sequence.nextval, 65, 'VPNI');
