insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 105, 'Agente Comunitário de Saúde');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 106, 'Agente de Endemias');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 109, 'Agente de Zoonózes');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 168, 'Analista Epidemiológico');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 128, 'Fiscal Sanitário');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 108, 'Técnico / Inspetor Sanitário');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 62, 'Porteiro / Agente de Portaria');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 61, 'Vigia / Ronda / Sentinela / Patrulheiro');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 166, 'Segurança');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 8, 'Deputado Estadual');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 6, 'Governador');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 9, 'Secretário de Estado');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 19, 'Secretário de Estado Adjunto');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 7, 'Vice-governador');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 2, 'Prefeito');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 5, 'Secretário Municipal');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 20, 'Secretário Municipal Adjunto/SubSecretário');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 287, 'Sub-Prefeito');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 4, 'Vereador');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 3, 'Vice-prefeito');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 203, 'Almoxarife / Auxiliar de Almoxarifado');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 60, 'Analista/Técnico Administrativo');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 199, 'Arquivista');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 214, 'Assistente Técnico');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 59, 'Auxiliar de Escritório / Administrtaivo');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 246, 'Auxiliar DPE/PGE');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 103, 'Digitador / Cadastrador');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 104, 'Técnico de Cadastro');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 178, 'Técnico de Contabilidade');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 196, 'Técnico em Gestão Pública');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 58, 'Telefonista / Recepcionista / Secretária');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 170, 'Analista/Assistente/Técnico em Educação/Pedagógico');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 211, 'Auxiliar de Creche');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 45, 'Auxiliar de Sala de Aula / Escolar');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 172, 'Especialista Educacional');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 171, 'Funções Administrativas (Educação)');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 48, 'Inspetor');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 47, 'Merendenira');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 46, 'Professor Auxiliar');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 270, 'Regente');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 135, 'Atendente de Consultório');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 44, 'Auxiliar / Técnico de Enfermagem');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 245, 'Auxiliar de Nutrição');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 182, 'Auxiliar de Odontólogo / Técnico de Saúde Bucal');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 309, 'Auxiliar de Prótese e Órtese');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 36, 'Auxiliar de Veterinário');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 39, 'Auxiliar/Atendente/Técnico de Farmácia');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 38, 'Auxiliar/Técnico de Laboratório');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 41, 'Microscopista');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 43, 'Parteiras');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 89, 'Técnico em Eletrocardiograma');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 42, 'Técnico em Radiologia');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 50, 'Acompanhantes diversos');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 130, 'Agente Social');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 49, 'Cuidador Social');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 252, 'Orientador Social');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 154, 'Aposentados');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 155, 'Inativos');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 156, 'Pensionistas');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 189, 'Auxiliar/Agente Agropecuário');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 188, 'Técnico Agropecuário/Agroflorestal');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 192, 'Agente / Técnico de Comunicação Social');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 107, 'Agente de Telecomunicações / Operadores');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 190, 'Cinegrafista/Fotógrafo');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 191, 'Repórter/Jornalista/Radialista');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 92, 'Advogado');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 204, 'Analista Jurídico');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 205, 'Analista Processual');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 213, 'Assistente Jurídico');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 151, 'Procuradores Jurídicos');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 250, 'Técnico Jurídico');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 144, 'Auditor "Genérico"');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 136, 'Auditor da Receita Estadual');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 137, 'Auditor de Controle Externo');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 138, 'Auditor de Controle Interno');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 140, 'Auditor de Meio Ambiente');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 141, 'Auditor de Obras');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 143, 'Auditor de Transportes');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 12, 'Assessores');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 10, 'Cargo em Comissão Estadual');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 17, 'Cargo em Comissão Estadual (Indiretas)');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 11, 'Cargo em Comissão Estadual (Intermediário)');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 145, 'Cargo em Comissão Municipal');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 16, 'Chefe/Encarregado de Setor');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 311, 'Comandante / Sub-Comandante');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 15, 'Coordenadores');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 73, 'Diretor Pesidente');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 13, 'Diretores');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 14, 'Gerentes');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 269, 'Presidente');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 183, 'Servidor com Função Gratificada');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 112, 'Bolsista');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 110, 'Estagiários');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 111, 'Menor Aprendiz');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 51, 'Orientador / Monitor / Educador');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 56, 'Professor de Curso Profissionalizantes');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 53, 'Professor de Esportes Diversos');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 167, 'Professor de informática');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 52, 'Professor de Música');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 55, 'Professor de Programas Específicos');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 54, 'Professor Projovem');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 132, 'Agente de Polícia');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 200, 'Agentes Penitenciários');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 193, 'Alunos (Militares)');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 263, 'Aspirante Oficial');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 244, 'Assistente Militar');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 94, 'Cabo');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 99, 'Capitão');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 101, 'Coronel');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 133, 'Delegado de Polícia');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 134, 'Escrivão');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 98, 'Major');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 251, 'Peritos/Atividades Policiais');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 93, 'Sargentos');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 95, 'Soldado');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 97, 'SubTenente');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 96, 'Tenente');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 100, 'Tenente Coronel');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 142, 'Auditor/Conselheiro Substituto');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 219, 'Conselheiro');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 259, 'Defensor Público');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 148, 'Desembargadores');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 147, 'Juizes');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 268, 'Presidentes');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 150, 'Procuradores');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 160, 'Agente/Auxiliar Legislativo');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 161, 'Analista/Técnico Legislativo');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 159, 'Oficial Legislativo');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 162, 'Peritos');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 157, 'Polícia Legislativa');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 158, 'Taquígrafo');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 186, 'Cargo em Comissão CPL');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 185, 'Membro de CPL');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 72, 'Pregoeiro');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 184, 'Presidente de CPL');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 176, 'Barqueiro / Piloto');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 174, 'Motorista de Caminhão/Ônibus');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 173, 'Motorista de Veículos Leves');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 175, 'Operador de Máquinas Pesadas');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 131, 'Assistente Social (não acumulável)');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 220, 'Conselheiro Tutelar');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 71, 'Engenheiro Agrimensor');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 237, 'Engenheiro Ambiental');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 279, 'Engenheiro Cartográfico');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 68, 'Engenheiro Civil');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 163, 'Engenheiro de Segurança no Trabalho');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 280, 'Engenheiro de Telecomunicações');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 69, 'Engenheiro Elétrico');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 238, 'Engenheiro Florestal');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 116, 'Engenheiro Mecânico');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 243, 'Engenheiro Químico');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 129, 'Engenheiro Sanitário');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 255, 'Engenheiros Diversos (não listados anteriormente)');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 63, 'Administrador');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 64, 'Contador');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 223, 'Controlador Interno');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 65, 'Economista');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 231, 'Fiscal de Tributos');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 66, 'Gestor Público');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 241, 'Sociólogo');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 22, 'Assistente Social (Saúde)');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 23, 'Biólogo');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 24, 'Biomédico/Bioquímico');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 26, 'Enfermeiro');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 27, 'Farmacêutico');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 28, 'Fisioterapeuta');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 29, 'Fonoaudiologo');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 30, 'Médico');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 165, 'Médico de Segurança no Trabalho');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 31, 'Médico Verterinário');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 32, 'Nutricionista');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 33, 'Odonotólogo');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 25, 'Profissional de Educação Física (Saúde)');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 34, 'Psicólogo');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 35, 'Terapeuta Ocupacional');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 195, 'Agentes de Suporte Técnico em Informática');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 124, 'Analista de Sistemas / Programador / Desenvolvedor');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 169, 'Técnico de Informática');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 235, 'Zootecnista');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 234, 'Tratador de Animais');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 115, 'Torneiro Mecânico');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 164, 'Técnico em Segurança no Trabalho');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 290, 'Sapateiro Ortopédico');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 264, 'Pesquisador / Assist. de Pesquisa');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 229, 'Operador de ETA/ ETE');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 236, 'Monitor Ambiental');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 272, 'Mateiro');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 305, 'Leiturista');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 293, 'Historiador');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 227, 'Geologo');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 226, 'Geografo');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 224, 'Fiscal de Meio Ambiente');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 123, 'Engenheiro Agrônomo');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 146, 'Coveiro');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 258, 'Costureira');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 217, 'Cadista / Desenhista');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 67, 'Arquiteto');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 121, 'Agente de Transporte');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 120, 'Agente de Transito');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 119, 'Agente de Campo');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 122, 'Agente Ambiental');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 126, 'Agente / Técnico Cultural');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 125, 'Açougueiro');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 76, 'Coordenador de Ensino');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 75, 'Coordenador Pedagógico');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 77, 'Diretor de Escola');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 74, 'Pedagogo');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 1, 'Professor - Ensino Regular');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 83, 'Apontador');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 86, 'Armador');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 215, 'Auxiliar de Topografo');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 81, 'Carpinteiro');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 82, 'Eletricista');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 90, 'Eletrotécnico');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 180, 'Encanador');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 225, 'Fiscal de Obras');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 85, 'Marceneiro');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 261, 'Mestre de Obras');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 232, 'Oleiro');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 80, 'Pedreiro');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 152, 'Pintor');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 84, 'Servente / Auxiliar / Ajudante de Obres');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 207, 'Tecnólogo em Construção Civil');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 70, 'Topógrafo');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 78, 'Auxiliar de Serviços Gerais / Limpeza / Servente');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 228, 'Jardineiro');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 88, 'Zelador');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 79, 'Gari / Coletor de Lixo');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 233, 'Rasteleiro');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 87, 'Roçador');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 194, 'Abastecedor/Lubrificador');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 114, 'Auxiliares/Ajudantes de Manutenção de Máquinas e Veículos');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 216, 'Borracheiro');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 91, 'Eletricista de Veículos');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 260, 'Lanterneiro');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 113, 'Mecânico');
insert into ClassificacaoCargo(id, codigo, descricao) values (hibernate_sequence.nextval, 102, 'Soldador')
