update pessoafisica set ESTADOCIVIL = 'SOLTEIRO', VIVEUNIAOESTAVEL = 1 WHERE ESTADOCIVIL = 'UNIAO_ESTAVEL';
update pessoafisica set ESTADOCIVIL = 'CASADO' WHERE ESTADOCIVIL = 'SEPARADO';
update pessoafisica set ESTADOCIVIL = 'SOLTEIRO' WHERE ESTADOCIVIL = 'OUTROS';
update PESSOAFISICAPORTAL set ESTADOCIVIL = 'SOLTEIRO' WHERE ESTADOCIVIL = 'UNIAO_ESTAVEL';
update PESSOAFISICAPORTAL set ESTADOCIVIL = 'CASADO' WHERE ESTADOCIVIL = 'SEPARADO';
update PESSOAFISICAPORTAL set ESTADOCIVIL = 'SOLTEIRO' WHERE ESTADOCIVIL = 'OUTROS';
