DELETE FROM GRUPORECURSOSistema g WHERE g.RECURSOSISTEMA_ID IN ( SELECT r.id FROM RECURSOSISTEMA r WHERE r.NOME LIKE '%EXCLUSÃO DE EVENTOS%');
DELETE FROM RECURSOSISTEMA r WHERE r.NOME  LIKE '%EXCLUSÃO DE EVENTOS%';
