UPDATE PRESTADORSERVICOS p SET MATRICULAESOCIAL = (
    CASE WHEN EXISTS (SELECT 1 FROM REGISTROESOCIAL r
                      WHERE r.SITUACAO IN ('PROCESSADO_COM_ADVERTENCIA', 'PROCESSADO_COM_SUCESSO')
                        AND r.TIPOARQUIVOESOCIAL = 'S2300'
                        AND r.IDESOCIAL = p.ID)
        THEN (SELECT LPAD(pf.CPF, 11, '0') FROM PESSOAFISICA pf WHERE pf.id = p.PRESTADOR_ID)
        ELSE (SELECT LPAD(pf.CPF, 11, '0') || LPAD(p.CODIGO, 6, '0') FROM PESSOAFISICA pf WHERE pf.id = p.PRESTADOR_ID) END
    )

