update MODALIDADECONTRATOFP set PROVIMENTOESTATUTARIOESOCIAL = 'NOMEACAO_CARGO_EFETIVO' where codigo = 7;
update MODALIDADECONTRATOFP set PROVIMENTOESTATUTARIOESOCIAL = 'NOMEACAO_EXCLUSIVAMENTE_CARGO_COMISSAO' where codigo = 2;
update MODALIDADECONTRATOFP set PROVIMENTOESTATUTARIOESOCIAL = 'CONTRATACAO_TEMPO_DETERMINADO' where codigo = 4;
update MODALIDADECONTRATOFP set PROVIMENTOESTATUTARIOESOCIAL = 'NOMEACAO_EXCLUSIVAMENTE_CARGO_COMISSAO' where codigo = 3;
update MODALIDADECONTRATOFP set PROVIMENTOESTATUTARIOESOCIAL = 'NOMEACAO_EXCLUSIVAMENTE_CARGO_COMISSAO' where codigo = 6;
update MODALIDADECONTRATOFP set PROVIMENTOESTATUTARIOESOCIAL = 'NOMEACAO_EXCLUSIVAMENTE_CARGO_COMISSAO' where codigo = 8;
update MODALIDADECONTRATOFP set PROVIMENTOESTATUTARIOESOCIAL = 'NOMEACAO_EXCLUSIVAMENTE_CARGO_COMISSAO' where codigo = 9
