INSERT INTO PESSOA_PERFIL pp
(ID_PESSOA, PERFIL)
SELECT p1.PRESTADOR_ID, 'PERFIL_PRESTADOR' FROM PRESTADORSERVICOS p1
WHERE NOT EXISTS (
    SELECT 1 FROM PRESTADORSERVICOS p2
    INNER JOIN PESSOA_PERFIL pp ON pp.ID_PESSOA = p2.PRESTADOR_ID
    AND pp.PERFIL = 'PERFIL_PRESTADOR'
    AND p2.ID = p1.ID)
