insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200004300', 'Impacto de pessoa contra objeto parado');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200004600', 'Impacto de pessoa contra objeto em movimento');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200008300', 'Impacto sofrido por pessoa, de objeto que cai');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200008600', 'Impacto sofrido por pessoa, de objeto projetado');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200008900', 'Impacto sofrido por pessoa, NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200012200', 'Queda de pessoa com diferença de nível de andaime, passagem, plataforma, etc');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200012300', 'Queda de pessoa com diferença de nível de escada móvel ou fixada cujos degraus não permitem o apoio integral do pé');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200012400', 'Queda de pessoa com diferença de nível de material empilhado');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200012500', 'Queda de pessoa com diferença de nível de veículo');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200012600', 'Queda de pessoa com diferença de nível em escada permanente cujos degraus permitem apoio integral do pé');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200012700', 'Queda de pessoa com diferença de nível em poço, escavação, abertura no piso, etc. (da borda da abertura)');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200012900', 'Queda de pessoa com diferença de nível, NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200016300', 'Queda de pessoa em mesmo nível em passagem ou superfície de sustentação');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200016600', 'Queda de pessoa em mesmo nível sobre ou contra alguma coisa');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200016900', 'Queda de pessoa em mesmo nível, NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200020100', 'Aprisionamento em, sob ou entre objetos em movimento convergente (calandra) ou de encaixe');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200020300', 'Aprisionamento em, sob ou entre um objeto parado e outro em movimento');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200020500', 'Aprisionamento em, sob ou entre dois ou mais objetos em movimento (sem encaixe)');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200020700', 'Aprisionamento em, sob ou entre desabamento ou desmoronamento de edificação, barreira, etc');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200020900', 'Aprisionamento em, sob ou entre, NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200024300', 'Atrito ou abrasão por encostar, pisar, ajoelhar ou sentar em objeto (não em vibração)');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200024400', 'Atrito ou abrasão por manusear objeto (não em vibração)');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200024500', 'Atrito ou abrasão por objeto em vibração');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200024600', 'Atrito ou abrasão por corpo estranho no olho');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200024700', 'Atrito ou abrasão por compressão repetitiva');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200024900', 'Atrito ou abrasão, NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200028300', 'Reação do corpo a seus movimentos - movimento involuntário (escorregão sem queda, etc.)');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200028600', 'Reação do corpo a seus movimentos - movimento voluntário');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200032200', 'Esforço excessivo ao erguer objeto');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200032400', 'Esforço excessivo ao empurrar ou puxar objeto');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200032600', 'Esforço excessivo ao manejar, sacudir ou arremessar objeto');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200032900', 'Esforço excessivo, NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200036000', 'Exposição à energia elétrica');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200040300', 'Contato com objeto ou substância a temperatura muito alta');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200040600', 'Contato com objeto ou substância a temperatura muito baixa');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200044300', 'Exposição à temperatura ambiente elevada');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200044600', 'Exposição à temperatura ambiente baixa');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200048200', 'Inalação de substância cáustica, tóxica ou nociva');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200048400', 'Ingestão de substancia cáustica, tóxica ou nociva');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200048600', 'Absorção (por contato) de substância cáustica, tóxica ou nociva');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200048900', 'Inalação, ingestão e absorção, NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200052000', 'Imersão');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200056000', 'Exposição à radiação não ionizante');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200060000', 'Exposição à radiação ionizante');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200064000', 'Exposição ao ruído');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200068000', 'Exposição à vibração');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200072000', 'Exposição à pressão ambiente');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200072300', 'Exposição à pressão ambiente elevada');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200072600', 'Exposição à pressão ambiente baixa');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200076200', 'Exposição à poluição da água');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200076400', 'Exposição à poluição do ar');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200076600', 'Exposição à poluição do solo');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200076900', 'Exposição à poluição, NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200080200', 'Ataque de ser vivo por mordedura, picada, chifrada, coice, etc');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200080400', 'Ataque de ser vivo com peçonha');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200080600', 'Ataque de ser vivo com transmissão de doença');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200080900', 'Ataque de ser vivo (inclusive do homem), NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '200080901', 'Contato com pessoas doentes ou material infectocontagiante - agentes biológicos');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '209000000', 'Tipo, NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '209500000', 'Tipo inexistente');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '302010200', 'Rua e estrada - superfície utilizada para sustentar pessoas');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '302010250', 'Calçada ou caminho para pedestre - superfície utilizada para sustentar pessoas');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '302010300', 'Piso de edifício - superfície utilizada para sustentar pessoas');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '302010350', 'Escada permanente cujos degraus permitem apoio integral do pé, degrau - superfície utilizada para sustentar pessoas');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '302010400', 'Rampa - superfície utilizada para sustentar pessoas');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '302010450', 'Passarela ou plataforma permanentes - superfície utilizada para sustentar pessoas');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '302010500', 'Piso de mina - superfície utilizada para sustentar pessoas');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '302010550', 'Chão - superfície utilizada para sustentar pessoas');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '302010600', 'Piso de andaime e plataforma desmontável - superfície utilizada para sustentar pessoas');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '302010650', 'Piso de veiculo - superfície utilizada para sustentar pessoas');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '302010700', 'Telhado');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '302010900', 'Superfície de sustentação, NIC - superfície utilizada para sustentar pessoas');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '302030900', 'Escada móvel ou fixada, NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '302050100', 'Edifício - edifício ou estrutura');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '302050200', 'Depósito fixo (tanque, silo, paiol, etc.) - edifício ou estrutura');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '302050300', 'Cais, doca - edifício ou estrutura');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '302050400', 'Dique, barragem - edifício ou estrutura');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '302050500', 'Ponte, viaduto - edifício ou estrutura');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '302050600', 'Arquibancada, estádio - edifício ou estrutura');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '302050700', 'Andaime, plataforma - edifício ou estrutura');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '302050800', 'Torre, poste - edifício ou estrutura');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '302050900', 'Edifício ou estrutura (exceto piso, superfície de sustentação ou área de circulação), NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '302070100', 'Escavação (para edifício, estrada, etc.)');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '302070300', 'Canal, fosso');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '302070500', 'Poço, entrada, galeria, etc. de mina');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '302070700', 'Túnel');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '302070900', 'Escavação, fosso, túnel, NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '302090000', 'Superfície e estrutura, NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303010040', 'Martelo, malho, marreta - ferramenta manual sem força motriz');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303010080', 'Machadinha, enxó - ferramenta manual sem força motriz');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303010120', 'Faca, facão - ferramenta manual sem força motriz');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303010160', 'Tesoura, tesourão - ferramenta manual sem força motriz');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303010200', 'Formão, cinzel - ferramenta manual sem força motriz');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303010240', 'Serra, serrote - ferramenta manual sem força motriz');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303010280', 'Alicate, torques, tenaz - ferramenta manual sem força motriz');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303010320', 'Plaina - ferramenta manual sem força motriz');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303010360', 'Lima, grosa - ferramenta manual sem força motriz');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303010400', 'Punção, ponteiro, vazador, talhadeira - ferramenta manual sem força motriz');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303010440', 'Pua, trado, verruma, máquina de furar manual - ferramenta manual sem força motriz');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303010480', 'Chave de parafuso - ferramenta manual sem força motriz');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303010520', 'Chave de porca ou de abertura regulável, chave de boca - ferramenta manual sem força motriz');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303010560', 'Alavanca, pé-de-cabra - ferramenta manual sem força motriz');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303010600', 'Corda, cabo, corrente - ferramenta manual sem força motriz');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303010640', 'Machado - ferramenta manual sem força motriz');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303010680', 'Enxada, enxadão, sacho - ferramenta manual sem força motriz');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303010720', 'Pá, cavadeira - ferramenta manual sem força motriz');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303010760', 'Picareta - ferramenta manual sem força motriz');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303010800', 'Garfo, ancinho, forcado - ferramenta manual sem força motriz');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303010900', 'Ferramenta manual sem força motriz, NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303015050', 'Martelete, socador - ferramenta portátil com força motriz ou aquecimento');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303015100', 'Talhadeira - ferramenta portátil com força motriz ou aquecimento');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303015150', 'Cortadeira, guilhotina - ferramenta portátil com força motriz ou aquecimento');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303015200', 'Serra - ferramenta portátil com força motriz ou aquecimento');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303015250', 'Punção, ponteiro, vazador - ferramenta portátil com força motriz ou aquecimento');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303015300', 'Perfuratriz - ferramenta portátil com força motriz ou aquecimento');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303015350', 'Rebitadeira - ferramenta portátil com força motriz ou aquecimento');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303015400', 'Máquina de aparafusar - ferramenta portátil com força motriz ou aquecimento');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303015450', 'Esmeril - ferramenta portátil com força motriz ou aquecimento');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303015500', 'Politriz, enceradeira - ferramenta portátil com força motriz ou aquecimento');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303015550', 'Ferro de passar - ferramenta portátil com força motriz ou aquecimento');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303015600', 'Ferramenta de soldagem - ferramenta portátil com força motriz ou aquecimento');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303015650', 'Maçarico - ferramenta portátil com força motriz ou aquecimento');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303015700', 'Ferramenta acionada por explosivo - ferramenta portátil com força motriz ou aquecimento');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303015750', 'Jato de areia - ferramenta portátil com força motriz ou aquecimento');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303015900', 'Ferramenta portátil com força motriz ou aquecimento, NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303020040', 'Serra - máquina');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303020080', 'Tesoura, guilhotina, máquina de cortar - máquina');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303020120', 'Laminadora, calandra - máquina');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303020160', 'Furadeira, broqueadeira, torno, fresa - máquina');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303020200', 'Prensa - máquina');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303020240', 'Plaina, tupia - máquina');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303020280', 'Máquina de fundir, de forjar, de soldar');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303020320', 'Britador, moinho - máquina');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303020360', 'Misturador, batedeira, agitador - máquina');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303020400', 'Peneira mecânica, máquina separadora - máquina');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303020440', 'Politriz, lixadora, esmeril - máquina');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303020480', 'Máquina de terraplenagem e construção de estrada');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303020520', 'Máquina de mineração e perfuração (de túnel, poço, etc.)');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303020560', 'Máquina agrícola');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303020600', 'Máquina têxtil');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303020640', 'Máquina de costurar e de pespontar');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303020680', 'Máquina de imprimir');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303020720', 'Máquina de escritório');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303020760', 'Máquina de embalar ou empacotar');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303020900', 'Máquina, NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303025300', 'Transportador por gravidade');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303025600', 'Transportador com força motriz');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303025900', 'Transportador, NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303030050', 'Guindaste - equipamento de guindar');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303030100', 'Ponte rolante - equipamento de guindar');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303030150', 'Elevador - equipamento de guindar');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303030200', 'Elevador de caçamba para mineração - equipamento de guindar');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303030250', 'Pá mecânica, draga - equipamento de guindar');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303030300', 'Talha - equipamento de guindar');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303030350', 'Pau de carga - equipamento de guindar');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303030400', 'Macaco (mecânico, hidráulico, pneumático) - equipamento de guindar');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303030450', 'Guincho pneumático - equipamento de guindar');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303030500', 'Guincho elétrico - equipamento de guindar');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303030900', 'Equipamento de guindar, NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303035300', 'Correia - dispositivo de transmissão de energia mecânica');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303035400', 'Corrente, corda, cabo - dispositivo de transmissão de energia mecânica');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303035500', 'Tambor, polia, roldana - dispositivo de transmissão de energia mecânica');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303035600', 'Embreagem de fricção - dispositivo de transmissão de energia mecânica');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303035700', 'Engrenagem - dispositivo de transmissão de energia mecânica');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303035900', 'Dispositivo de transmissão de energia mecânica, NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303040100', 'Gerador - equipamento elétrico');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303040200', 'Condutor - equipamento elétrico');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303040300', 'Transformador, conversor - equipamento elétrico');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303040400', 'Painel de controle, barramento, chave, interruptor, disjuntor, fusível - equipamento elétrico');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303040500', 'Reostato, dispositivo de partida e aparelho de controle, capacitor, retificador, bateria de acumuladores - equipamento elétrico');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303040600', 'Motor elétrico - equipamento elétrico');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303040700', 'Equipamento magnético - equipamento elétrico');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303040750', 'Equipamento eletrolítico - equipamento elétrico');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303040800', 'Equipamento de aquecimento elétrico - equipamento elétrico');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303040900', 'Equipamento elétrico, NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303045200', 'Motor (combustão interna, vapor)');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303045400', 'Bomba');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303045600', 'Turbina');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303045900', 'Motor, bomba, turbina, NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303050200', 'Caldeira');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303050400', 'Vaso sob pressão (para líquido, gás ou vapor)');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303050600', 'Tubo sob pressão (mangueira ou tubo para liquido, gás ou vapor)');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303050900', 'Caldeira, vaso sob pressão, NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303055200', 'Caixão pneumático - equipamento para trabalho em ambiente de pressão anormal');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303055400', 'Escafandro - equipamento para trabalho em ambiente de pressão anormal');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303055600', 'Equipamento de mergulho - equipamento para trabalho em ambiente de pressão anormal');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303055900', 'Equipamento para trabalho em ambiente de pressão anormal, NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303060000', 'Forno, estufa, retorta, aquecedor de ambiente, fogão, etc. (exceto quando a lesão principal for choque elétrico ou eletroplessão) - equipamento de aquecimento');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303065000', 'Equipamento emissor de radiação não ionizante');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303065300', 'Equipamento de iluminação - equipamento emissor de radiação não ionizante');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303065600', 'Arco elétrico - equipamento emissor de radiação não ionizante');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303065900', 'Equipamento emissor de radiação não ionizante, NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303066300', 'Equipamento de iluminação');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303066600', 'Arco elétrico');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303070200', 'Equipamento de raios X - equipamento ou substância emissor de radiação ionizante');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303070400', 'Reator (inclui combustível e resíduo) - equipamento ou substância emissor de radiação ionizante');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303070600', 'Fonte de radioisótopo - equipamento ou substância emissor de radiação ionizante');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303070900', 'Equipamento ou substância emissor de radiação ionizante, NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303075100', 'Bicicleta');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303075150', 'Triciclo');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303075200', 'Motocicleta, motoneta');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303075250', 'Veículo rodoviário motorizado');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303075300', 'Veículo sobre trilho');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303075350', 'Veículo aquático');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303075400', 'Aeronave');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303075450', 'Empilhadeira');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303075500', 'Rebocador mecânico, mula mecânica');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303075550', 'Carro de mão');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303075600', 'Trator');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303075650', 'Veículo de terraplenagem');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303075700', 'Veículo de tração animal');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303075750', 'Veículo deslizante');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303075800', 'Veículo funicular (tração por cabo)');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303075900', 'Veículo, NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '303090000', 'Ferramenta, máquina, equipamento, veículo, NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305004100', 'Composto metálico (de chumbo, mercúrio, zinco, cadmio, cromo, etc.)');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305004150', 'Composto de arsênio');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305004200', 'Gás carbônico (dióxido de carbono, CO2)');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305004250', 'Monóxido de carbono (CO)');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305004300', 'Óxidos de nitrogênio (vapores nitrosos)');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305004350', 'Ácido');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305004400', 'Álcali');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305004450', 'Composto de fósforo');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305004500', 'Dissulfeto de carbono');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305004550', 'Cianeto ou composto de cianogênio');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305004600', 'Álcool');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305004650', 'Tetracloreto de carbono');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305004700', 'Composto orgânico halogenado (tricloretileno, percloretileno, cloreto de metilo, substâncias refrigerantes)');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305004750', 'Composto aromático (benzol, toluol, xilol, anilina, etc.)');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305004900', 'Substância química, NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305008500', 'Água (usar quando o estado líquido contribuir preponderantemente para a ocorrência)');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305008900', 'Líquido, NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305020000', 'Partículas não identificadas');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305024100', 'Pele, crina, pelo, lã (em bruto) - produto animal');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305024300', 'Pena - produto animal');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305024500', 'Couro cru ou curtido - produto animal');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305024700', 'Osso - produto animal');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305024900', 'Produto animal, NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305028000', 'Madeira (toro, madeira serrada, pranchão, poste, barrote, ripa e produto de madeira)');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305032000', 'Produto mineral metálico - produto de mineração em bruto ou beneficiado, como minério e concentrado de minério');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305032500', 'Metal (inclui liga ferrosa e não ferrosa, tubo, placa, perfil, trilho, vergalhão, arame, porca, rebite, prego, etc., metal fundido, lingote e sucata de fundição, exceto minério)');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305036000', 'Produto mineral não metálico - produto de mineração, escavação, desbarrancamento, etc., como detrito, argila, areia, cascalho, pedra, etc.');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305040100', 'Petróleo bruto, bruto reduzido');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305040150', 'Asfalto, alcatrão, piche');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305040200', 'Óleo combustível');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305040250', 'Parafina, óleo lubrificante e de corte, graxas');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305040300', 'Gasóleo, óleo diesel');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305040350', 'Querosene');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305040400', 'Nafta e solvente de nafta (éter de petróleo, álcool mineral, solvente aromático, etc.)');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305040450', 'Gasolina (exceto quando a ocorrência for causada preponderantemente por composto de chumbo)');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305040500', 'Hidrocarboneto gasoso (inclui gás liquefeito, gás encanado de nafta, gás natural)');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305040600', 'Carvão');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305040650', 'Coque');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305040700', 'Gás encanado de carvão');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305040900', 'Produto de petróleo e de carvão, NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305044000', 'Vidraria, fibra de vidro, lâmina, etc., exceto frasco, garrafa');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305048000', 'Cerâmica');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305048300', 'Tijolo e telha - cerâmica');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305048400', 'Louça de mesa e outros utensílios (de porcelana, barro, etc.) - cerâmica');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305048500', 'Tubo, manilha - cerâmica');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305048600', 'Revestimento cerâmico (azulejo, mosaico, etc.) - cerâmica');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305048700', 'Louca sanitária (pia, vaso sanitário, etc.) - cerâmica');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305048900', 'Cerâmica, NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305052000', 'Têxteis (inclui fibras animais após o primeiro desengorduramento e limpeza, fibras vegetais e sintéticas (exceto vidro), fio, linha, tecido, passamanaria, feltro e produtos têxteis em geral)');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305056000', 'Plástico (inclui pó, folha, trefilado, barra, perfil, etc.; não inclui produto a ser usado na fabricação de plástico)');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305060000', 'Papel e pasta para papel');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305064000', 'Produto alimentício (inclui carne, leite e derivados, legumes, frutas, cereais e derivados)');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305064300', 'Carne e derivados');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305064400', 'Leite e derivados');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305064500', 'Legume, verdura e derivados');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305064600', 'Fruta e derivados');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305064700', 'Cereal e derivados');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305064900', 'Produto alimentício (inclusive de origem animal), NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305068300', 'Medicamento em geral (exceto produto biológico)');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305068600', 'Produto biológico (soro, toxina, antitoxina, vacina, plasma) - medicamento');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305072000', 'Produto de limpeza, sabão, detergente');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305076000', 'Sucata, entulho, resíduo');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '305090000', 'Substância química, material, produto, NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '306020000', 'Animal vivo');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '306040000', 'Vegetal - planta, árvore, em estado natural, não beneficiada (não inclui grão debulhado, fruto colhido, toro mesmo com galho)');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '306060000', 'Agente infeccioso ou parasitário (inclui bactéria, fungo, organismo parasitário, vírus, etc.; não inclui produto químico, preparado farmacêutico ou alimento)');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '306090000', 'Ser vivo, NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '307030100', 'Cadeira banco - mobiliário e acessórios');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '307030200', 'Mesa, carteira, exceto mesa elástica desmontável - mobiliário e acessórios');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '307030250', 'Mesa elástica desmontável - mobiliário e acessórios');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '307030300', 'Balcão, bancada - mobiliário e acessórios');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '307030400', 'Arquivo, fichário, estante - mobiliário e acessórios');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '307030500', 'Tapete, forração de piso, capacho - mobiliário e acessórios');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '307030600', 'Luminária, globo, lâmpada - mobiliário e acessórios');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '307030900', 'Mobiliário e acessórios, NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '307040100', 'Caixa, engradado, caixote - embalagem, recipiente (vazio ou cheio)');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '307040300', 'Frasco, garrafa - embalagem, recipiente (vazio ou cheio)');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '307040500', 'Barril, barrica, barrilete, tambor - embalagem, recipiente (vazio ou cheio)');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '307040700', 'Tanque, cilindro (transportáveis e não sob pressão) - embalagem, recipiente (vazio ou cheio)');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '307040900', 'Embalagem, recipiente (vazio ou cheio), NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '307050900', 'Vestuário, NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '307070000', 'Área ou ambiente de trabalho (o agente do acidente ocorrido em consequência de fenômeno atmosférico, meteoro, etc., assim como da ação da radiação solar, deverá ser incluído neste item)');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '309000000', 'Agente do acidente, NIC');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '309500000', 'Agente do acidente inexistente');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '354000000', 'Energia');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '354010300', 'Pressão ambiente alta (trabalho em caixão pneumático, mergulho)');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '354010600', 'Pressão ambiente baixa (ar rarefeito)');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '354020000', 'Ruído');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '354040000', 'Fogo, chama, material incandescente ou quente, fumaça');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '354050300', 'Temperatura ambiente (não inclui a de objeto ou substância quente)');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '355016000', 'Aerodispersoides');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '355016600', 'Neblina');
insert into AgenteAcidenteTrabalho (ID, codigo, descricao) values (hibernate_sequence.nextVal, '355016800', 'Gás e vapor')
