insert into IncidenciaTributariaIRRF values (HIBERNATE_SEQUENCE.nextval, '48', 'Previdência complementar - Férias');
insert into IncidenciaTributariaIRRF values (HIBERNATE_SEQUENCE.nextval, '65', 'Fundação de previdência complementar do servidor público - Férias');
insert into IncidenciaTributariaIRRF values (HIBERNATE_SEQUENCE.nextval, '66', 'Fundo de Aposentadoria Programada Individual - FAPI - Férias');
insert into IncidenciaTributariaIRRF values (HIBERNATE_SEQUENCE.nextval, '67', 'Plano privado coletivo de assistência à saúde');
insert into IncidenciaTributariaIRRF values (HIBERNATE_SEQUENCE.nextval, '700', 'Auxílio moradia');
insert into IncidenciaTributariaIRRF values (HIBERNATE_SEQUENCE.nextval, '701', 'Parte não tributável do valor de serviço de transporte de passageiros ou cargas');
insert into IncidenciaTributariaIRRF values (HIBERNATE_SEQUENCE.nextval, '9011', 'Remuneração mensal');
insert into IncidenciaTributariaIRRF values (HIBERNATE_SEQUENCE.nextval, '9012', '13º salário');
insert into IncidenciaTributariaIRRF values (HIBERNATE_SEQUENCE.nextval, '9013', 'Férias');
insert into IncidenciaTributariaIRRF values (HIBERNATE_SEQUENCE.nextval, '9014', 'PLR');
insert into IncidenciaTributariaIRRF values (HIBERNATE_SEQUENCE.nextval, '9031', 'Remuneração mensal');
insert into IncidenciaTributariaIRRF values (HIBERNATE_SEQUENCE.nextval, '9032', '13º salário');
insert into IncidenciaTributariaIRRF values (HIBERNATE_SEQUENCE.nextval, '9033', 'Férias');
insert into IncidenciaTributariaIRRF values (HIBERNATE_SEQUENCE.nextval, '9034', 'PLR');
insert into IncidenciaTributariaIRRF values (HIBERNATE_SEQUENCE.nextval, '9831', 'Depósito judicial - Mensal');
insert into IncidenciaTributariaIRRF values (HIBERNATE_SEQUENCE.nextval, '9832', 'Depósito judicial - 13º salário');
insert into IncidenciaTributariaIRRF values (HIBERNATE_SEQUENCE.nextval, '9833', 'Depósito judicial - Férias');
insert into IncidenciaTributariaIRRF values (HIBERNATE_SEQUENCE.nextval, '9834', 'Depósito judicial - PLR');
insert into IncidenciaTributariaIRRF values (HIBERNATE_SEQUENCE.nextval, '9041', 'Previdência Social Oficial - PSO - Remuneração mensal');
insert into IncidenciaTributariaIRRF values (HIBERNATE_SEQUENCE.nextval, '9042', 'PSO - 13º salário');
insert into IncidenciaTributariaIRRF values (HIBERNATE_SEQUENCE.nextval, '9043', 'PSO - Férias');
insert into IncidenciaTributariaIRRF values (HIBERNATE_SEQUENCE.nextval, '9046', 'Previdência complementar - Salário mensal');
insert into IncidenciaTributariaIRRF values (HIBERNATE_SEQUENCE.nextval, '9047', 'Previdência complementar - 13º salário');
insert into IncidenciaTributariaIRRF values (HIBERNATE_SEQUENCE.nextval, '9048', 'Previdência complementar - Férias');
insert into IncidenciaTributariaIRRF values (HIBERNATE_SEQUENCE.nextval, '9051', 'Pensão alimentícia - Remuneração mensal');
insert into IncidenciaTributariaIRRF values (HIBERNATE_SEQUENCE.nextval, '9052', 'Pensão alimentícia - 13º salário');
insert into IncidenciaTributariaIRRF values (HIBERNATE_SEQUENCE.nextval, '9053', 'Pensão alimentícia - Férias');
insert into IncidenciaTributariaIRRF values (HIBERNATE_SEQUENCE.nextval, '9054', 'Pensão alimentícia - PLR');
insert into IncidenciaTributariaIRRF values (HIBERNATE_SEQUENCE.nextval, '9061', 'Fundo de Aposentadoria Programada Individual - FAPI - Remuneração mensal');
insert into IncidenciaTributariaIRRF values (HIBERNATE_SEQUENCE.nextval, '9062', 'Fundo de Aposentadoria Programada Individual - FAPI - 13º salário');
insert into IncidenciaTributariaIRRF values (HIBERNATE_SEQUENCE.nextval, '9063', 'Fundação de previdência complementar do servidor público - Remuneração mensal');
insert into IncidenciaTributariaIRRF values (HIBERNATE_SEQUENCE.nextval, '9064', 'Fundação de previdência complementar do servidor público - 13º salário');
insert into IncidenciaTributariaIRRF values (HIBERNATE_SEQUENCE.nextval, '9065', 'Fundação de previdência complementar do servidor público - Férias');
insert into IncidenciaTributariaIRRF values (HIBERNATE_SEQUENCE.nextval, '9066', 'Fundo de Aposentadoria Programada Individual - FAPI - Férias');
insert into IncidenciaTributariaIRRF values (HIBERNATE_SEQUENCE.nextval, '9067', 'Plano privado coletivo de assistência à saúde');
insert into IncidenciaTributariaIRRF values (HIBERNATE_SEQUENCE.nextval, '9082', 'Compensação judicial do ano-calendário');
insert into IncidenciaTributariaIRRF values (HIBERNATE_SEQUENCE.nextval, '9083', 'Compensação judicial de anos anteriores')
