INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES(hibernate_sequence.nextval, 'RECURSOS HUMANOS > RELATÓRIOS - RH > PREVIDÊNCIA > RELATÓRIO DEMONSTRATIVO DE ENCARGOS PATRONAIS E RETENÇÕES', '/rh/relatorios/demonstrativoencargospatronaisretencoes.xhtml',
       0, 'RH');

INSERT INTO MENU (ID, LABEL, CAMINHO, PAI_ID, ORDEM)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'RELATÓRIO DEMONSTRATIVO DE ENCARGOS PATRONAIS E RETENÇÕES',
        '/rh/relatorios/demonstrativoencargospatronaisretencoes.xhtml',
        (SELECT ID FROM MENU WHERE LABEL = 'PREVIDÊNCIA' AND CAMINHO IS NULL), 90);

INSERT INTO GRUPORECURSOSISTEMA (GRUPORECURSO_ID, RECURSOSISTEMA_ID)
VALUES ((SELECT ID FROM GRUPORECURSO WHERE NOME = 'Recursos Humanos'),
        (SELECT ID FROM RECURSOSISTEMA WHERE NOME = 'RECURSOS HUMANOS > RELATÓRIOS - RH > PREVIDÊNCIA > RELATÓRIO DEMONSTRATIVO DE ENCARGOS PATRONAIS E RETENÇÕES'));
