insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '753030000', 'Crânio (inclusive encéfalo)');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '753050000', 'Ouvido (externo, médio, interno, audição e equilíbrio)');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '753070100', 'Olho (inclusive nervo ótico e visão)');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '753070300', 'Nariz (inclusive fossas nasais, seios da face e olfato)');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '753070500', 'Boca (inclusive lábios, dentes, língua, garganta e paladar)');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '753070700', 'Mandíbula (inclusive queixo)');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '753070800', 'Face, partes múltiplas (qualquer combinação das partes acima)');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '753080000', 'Cabeça, partes múltiplas (qualquer combinação das partes acima)');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '753090000', 'Cabeça, NIC');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '753510000', 'Braço (entre o punho e o ombro)');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '753510200', 'Braço (acima do cotovelo)');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '754000000', 'Pescoço');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '755010400', 'Cotovelo');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '755010600', 'Antebraço (entre o punho e o cotovelo)');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '755030000', 'Punho');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '755050000', 'Mão (exceto punho ou dedos)');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '755070000', 'Dedo');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '755080000', 'Membros superiores, partes múltiplas (qualquer combinação das partes acima)');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '755090000', 'Membros superiores, NIC');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '756020000', 'Ombro');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '756030000', 'Tórax (inclusive órgãos internos)');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '756040000', 'Dorso (inclusive músculos dorsais, coluna e medula espinhal)');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '756050000', 'Abdome (inclusive órgãos internos)');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '756060000', 'Quadris (inclusive pélvis, órgãos pélvicos e nádegas)');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '756070000', 'Tronco, partes múltiplas (qualquer combinação das partes acima)');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '756090000', 'Tronco, NIC');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '757010000', 'Perna (entre o tornozelo e a pélvis)');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '757010200', 'Coxa');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '757010400', 'Joelho');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '757010600', 'Perna (do tornozelo, exclusive, ao joelho, exclusive)');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '757030000', 'Articulação do tornozelo');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '757050000', 'Pé (exceto artelhos)');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '757070000', 'Artelho');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '757080000', 'Membros inferiores, partes múltiplas (qualquer combinação das partes acima)');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '757090000', 'Membros inferiores, NIC');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '758000000', 'Partes múltiplas. (aplica-se quando mais de uma parte importante do corpo for afetada, como, por exemplo, um braço e uma perna)');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '758500000', 'Sistemas e aparelhos (aplica-se quando o funcionamento de todo um sistema ou aparelho do corpo humano for afetado, sem lesão específica de qualquer outra parte, como no caso do envenenamento, ação corrosiva que afete órgãos internos, lesão dos centros nervosos, etc.; não se aplica quando a lesão sistêmica for provocada por lesão externa, como lesão dorsal que afete nervos da medula espinhal)');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '758520000', 'Aparelho circulatório');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '758530000', 'Aparelho respiratório');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '758540000', 'Sistema nervoso');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '758550000', 'Aparelho digestivo');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '758560000', 'Aparelho gênito-urinário');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '758570000', 'Sistema musculoesquelético');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '758590000', 'Sistemas e aparelhos, NIC');
insert into ParteCorpo (ID, codigo, descricao) values (hibernate_sequence.nextVal, '759000000', 'Localização da lesão, NIC')
