insert into basefp(ID, CODIGO, DESCRICAO, DESCRICAOREDUZIDA, FILTROBASEFP)
values (HIBERNATE_SEQUENCE.nextval, 1031, 'BASE HORA EXTRA SAERB', 'BS HE SAERB', 'NORMAL');

insert into ITEMBASEFP(ID, DATAREGISTRO, OPERACAOFORMULA, BASEFP_ID, EVENTOFP_ID, TIPOVALOR, SOMAVALORRETROATIVO)
values (HIBERNATE_SEQUENCE.nextval, sysdate, 'ADICAO', (select b.id from basefp b where b.codigo = '1031'), 6190143, 'NORMAL', 0);

insert into ITEMBASEFP(ID, DATAREGISTRO, OPERACAOFORMULA, BASEFP_ID, EVENTOFP_ID, TIPOVALOR, SOMAVALORRETROATIVO)
values (HIBERNATE_SEQUENCE.nextval, sysdate, 'ADICAO', (select b.id from basefp b where b.codigo = '1031'), 6190487, 'INTEGRAL', 0);

insert into ITEMBASEFP(ID, DATAREGISTRO, OPERACAOFORMULA, BASEFP_ID, EVENTOFP_ID, TIPOVALOR, SOMAVALORRETROATIVO)
values (HIBERNATE_SEQUENCE.nextval, sysdate, 'ADICAO', (select b.id from basefp b where b.codigo = '1031'), 6190146, 'INTEGRAL', 0);

insert into ITEMBASEFP(ID, DATAREGISTRO, OPERACAOFORMULA, BASEFP_ID, EVENTOFP_ID, TIPOVALOR, SOMAVALORRETROATIVO)
values (HIBERNATE_SEQUENCE.nextval, sysdate, 'ADICAO', (select b.id from basefp b where b.codigo = '1031'), 6190303, 'INTEGRAL', 0);

insert into ITEMBASEFP(ID, DATAREGISTRO, OPERACAOFORMULA, BASEFP_ID, EVENTOFP_ID, TIPOVALOR, SOMAVALORRETROATIVO)
values (HIBERNATE_SEQUENCE.nextval, sysdate, 'ADICAO', (select b.id from basefp b where b.codigo = '1031'), 10956483715, 'INTEGRAL', 0);
