update HIERARQUIAORGANIZACIONAL
set NIVELNAENTIDADE = NIVELESTRUTURA(CODIGO, '.'),
    INDICEDONO      = NIVELESTRUTURA(CODIGO, '.')
where id in (select ho.id
             from HIERARQUIAORGANIZACIONAL ho
             where ho.NIVELNAENTIDADE != NIVELESTRUTURA(ho.CODIGO, '.')
                and ho.TIPOHIERARQUIAORGANIZACIONAL = 'ADMINISTRATIVA')
