DELETE FROM GRUPORECURSOSistema g WHERE g.RECURSOSISTEMA_ID IN ( SELECT r.id FROM RECURSOSISTEMA r WHERE r.NOME LIKE '%EVENTO PERIÓDICO%');
DELETE FROM RECURSOSISTEMA r WHERE r.NOME  LIKE '%EVENTO PERIÓDICO%';
