-- BaseFp 50000
insert into BASEFP(ID, CODIGO, DESCRICAO, DESCRICAOREDUZIDA, FILTROBASEFP, TIPOBASEFP)
values (HIBERNATE_SEQUENCE.nextval, 50000, 'BASE PRESTAÇÃO SERVIÇO NORMAL', 'BS PREST SERV', 'NORMAL',
        null);

insert into ITEMBASEFP(ID, DATAREGISTRO, OPERACAOFORMULA, BASEFP_ID, EVENTOFP_ID, TIPOVALOR, SOMAVALORRETROATIVO)
values (HIBERNATE_SEQUENCE.nextval, sysdate, 'ADICAO', (select b.id from basefp b where b.CODIGO = 50000),
        (select ev.id from EVENTOFP ev where ev.CODIGO = 4000), 'NORMAL', 1);

-- BaseFp 50010
insert into BASEFP(ID, CODIGO, DESCRICAO, DESCRICAOREDUZIDA, FILTROBASEFP, TIPOBASEFP)
values (HIBERNATE_SEQUENCE.nextval, 50010, 'BASE INSS PRESTAÇÃO SERVIÇO NORMAL', 'BS INSS PREST SERV', 'NORMAL',
        null);

insert into ITEMBASEFP(ID, DATAREGISTRO, OPERACAOFORMULA, BASEFP_ID, EVENTOFP_ID, TIPOVALOR, SOMAVALORRETROATIVO)
values (HIBERNATE_SEQUENCE.nextval, sysdate, 'ADICAO', (select b.id from basefp b where b.CODIGO = 50010),
        (select ev.id from EVENTOFP ev where ev.CODIGO = 4000), 'NORMAL', 1);

-- BaseFp 50020
insert into BASEFP(ID, CODIGO, DESCRICAO, DESCRICAOREDUZIDA, FILTROBASEFP, TIPOBASEFP)
values (HIBERNATE_SEQUENCE.nextval, 50020, 'BASE IRRF PRESTAÇÃO SERVIÇO NORMAL', 'BS IRRF PREST SERV', 'NORMAL',
        null);

insert into ITEMBASEFP(ID, DATAREGISTRO, OPERACAOFORMULA, BASEFP_ID, EVENTOFP_ID, TIPOVALOR, SOMAVALORRETROATIVO)
values (HIBERNATE_SEQUENCE.nextval, sysdate, 'ADICAO', (select b.id from basefp b where b.CODIGO = 50020),
        (select ev.id from EVENTOFP ev where ev.CODIGO = 4000), 'NORMAL', 1);

insert into ITEMBASEFP(ID, DATAREGISTRO, OPERACAOFORMULA, BASEFP_ID, EVENTOFP_ID, TIPOVALOR, SOMAVALORRETROATIVO)
values (HIBERNATE_SEQUENCE.nextval, sysdate, 'SUBTRACAO', (select b.id from basefp b where b.CODIGO = 50020),
        (select ev.id from EVENTOFP ev where ev.CODIGO = 4050), 'NORMAL', 0);

-- BaseFp 50030
insert into BASEFP(ID, CODIGO, DESCRICAO, DESCRICAOREDUZIDA, FILTROBASEFP, TIPOBASEFP)
values (HIBERNATE_SEQUENCE.nextval, 50030, 'BASE ISS PRESTAÇÃO SERVIÇO NORMAL', 'BS ISS PREST SERV', 'NORMAL',
        null);

insert into ITEMBASEFP(ID, DATAREGISTRO, OPERACAOFORMULA, BASEFP_ID, EVENTOFP_ID, TIPOVALOR, SOMAVALORRETROATIVO)
values (HIBERNATE_SEQUENCE.nextval, sysdate, 'ADICAO', (select b.id from basefp b where b.CODIGO = 50030),
        (select ev.id from EVENTOFP ev where ev.CODIGO = 4000), 'NORMAL', 1);

-- BaseFp 60000
insert into BASEFP(ID, CODIGO, DESCRICAO, DESCRICAOREDUZIDA, FILTROBASEFP, TIPOBASEFP)
values (HIBERNATE_SEQUENCE.nextval, 60000, 'BASE PRESTAÇÃO SERVIÇO TRANSPORTADOR', 'BS PREST SERV TRANSP', 'NORMAL',
        null);

insert into ITEMBASEFP(ID, DATAREGISTRO, OPERACAOFORMULA, BASEFP_ID, EVENTOFP_ID, TIPOVALOR, SOMAVALORRETROATIVO)
values (HIBERNATE_SEQUENCE.nextval, sysdate, 'ADICAO', (select b.id from basefp b where b.CODIGO = 60000),
        (select ev.id from EVENTOFP ev where ev.CODIGO = 4020), 'NORMAL', 1);

-- BaseFp 60010
insert into BASEFP(ID, CODIGO, DESCRICAO, DESCRICAOREDUZIDA, FILTROBASEFP, TIPOBASEFP)
values (HIBERNATE_SEQUENCE.nextval, 60010, 'BASE INSS PRESTAÇÃO SERVIÇO TRANSPORTADOR', 'BS INSS PREST SERV TRANSP', 'NORMAL',
        null);

insert into ITEMBASEFP(ID, DATAREGISTRO, OPERACAOFORMULA, BASEFP_ID, EVENTOFP_ID, TIPOVALOR, SOMAVALORRETROATIVO)
values (HIBERNATE_SEQUENCE.nextval, sysdate, 'ADICAO', (select b.id from basefp b where b.CODIGO = 60010),
        (select ev.id from EVENTOFP ev where ev.CODIGO = 4020), 'NORMAL', 1);

insert into ITEMBASEFP(ID, DATAREGISTRO, OPERACAOFORMULA, BASEFP_ID, EVENTOFP_ID, TIPOVALOR, SOMAVALORRETROATIVO)
values (HIBERNATE_SEQUENCE.nextval, sysdate, 'SUBTRACAO', (select b.id from basefp b where b.CODIGO = 60010),
        (select ev.id from EVENTOFP ev where ev.CODIGO = 4772), 'NORMAL', 1);

-- BaseFP 60020
insert into BASEFP(ID, CODIGO, DESCRICAO, DESCRICAOREDUZIDA, FILTROBASEFP, TIPOBASEFP)
values (HIBERNATE_SEQUENCE.nextval, 60020, 'BASE IRRF PRESTAÇÃO SERVIÇO TRANSPORTADOR', 'BS IRRF PREST SERV TRANSP', 'NORMAL',
        null);

insert into ITEMBASEFP(ID, DATAREGISTRO, OPERACAOFORMULA, BASEFP_ID, EVENTOFP_ID, TIPOVALOR, SOMAVALORRETROATIVO)
values (HIBERNATE_SEQUENCE.nextval, sysdate, 'SUBTRACAO', (select b.id from basefp b where b.CODIGO = 60020),
        (select ev.id from EVENTOFP ev where ev.CODIGO = 4070), 'NORMAL', 1);

insert into ITEMBASEFP(ID, DATAREGISTRO, OPERACAOFORMULA, BASEFP_ID, EVENTOFP_ID, TIPOVALOR, SOMAVALORRETROATIVO)
values (HIBERNATE_SEQUENCE.nextval, sysdate, 'ADICAO', (select b.id from basefp b where b.CODIGO = 60020),
        (select ev.id from EVENTOFP ev where ev.CODIGO = 4020), 'NORMAL', 1);

insert into ITEMBASEFP(ID, DATAREGISTRO, OPERACAOFORMULA, BASEFP_ID, EVENTOFP_ID, TIPOVALOR, SOMAVALORRETROATIVO)
values (HIBERNATE_SEQUENCE.nextval, sysdate, 'SUBTRACAO', (select b.id from basefp b where b.CODIGO = 60020),
        (select ev.id from EVENTOFP ev where ev.CODIGO = 4771), 'NORMAL', 1);

-- BaseFP 60030
insert into BASEFP(ID, CODIGO, DESCRICAO, DESCRICAOREDUZIDA, FILTROBASEFP, TIPOBASEFP)
values (HIBERNATE_SEQUENCE.nextval, 60030, 'BASE ISS PRESTAÇÃO SERVIÇO TRANSPORTADOR', 'BS ISS PREST SERV TRANSP', 'NORMAL',
        null);

insert into ITEMBASEFP(ID, DATAREGISTRO, OPERACAOFORMULA, BASEFP_ID, EVENTOFP_ID, TIPOVALOR, SOMAVALORRETROATIVO)
values (HIBERNATE_SEQUENCE.nextval, sysdate, 'ADICAO', (select b.id from basefp b where b.CODIGO = 60030),
        (select ev.id from EVENTOFP ev where ev.CODIGO = 4020), 'NORMAL', 1);
