INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES(hibernate_sequence.nextval, 'RECURSOS HUMANOS > RELATÓRIOS - RH >  VIDA FUNCIONAL > RELATÓRIO DE SERVIDORES E TEMPO DE EFETIVO EXERCÍCIO POR ÓRGÃO', '/rh/relatorios/relatoriotempoefetivoexercicioorgao.xhtml',
       0, 'RH');

INSERT INTO MENU (ID, LABEL, CAMINHO, PAI_ID, ORDEM)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'RELATÓRIO DE SERVIDORES E TEMPO DE EFETIVO EXERCÍCIO POR ÓRGÃO',
        '/rh/relatorios/relatoriotempoefetivoexercicioorgao.xhtml',
        (SELECT menu.id FROM MENU menu
                                 inner join MENU pai on menu.PAI_ID = pai.ID
         WHERE menu.LABEL like 'VIDA FUNCIONAL%' AND menu.CAMINHO IS NULL and pai.LABEL = 'RELATÓRIOS - RH'), 1);

INSERT INTO GRUPORECURSOSISTEMA (GRUPORECURSO_ID, RECURSOSISTEMA_ID)
VALUES ((SELECT ID FROM GRUPORECURSO WHERE NOME = 'Recursos Humanos'),
        (SELECT ID FROM RECURSOSISTEMA WHERE NOME = 'RECURSOS HUMANOS > RELATÓRIOS - RH >  VIDA FUNCIONAL > RELATÓRIO DE SERVIDORES E TEMPO DE EFETIVO EXERCÍCIO POR ÓRGÃO'));
