create global temporary table TEMP_vwhierarquiaorcamentaria (
ID	NUMBER(19),
SUPERIOR_ID	NUMBER(19),
SUBORDINADA_ID	NUMBER(19),
ENTIDADE_ID	NUMBER(19),
CODIGO	VARCHAR2(255),
DESCRICAO	VARCHAR2(255),
EXERCICIO_ID	NUMBER(19),
TIPOUNIDADE	VARCHAR2(20 CHAR),
TIPOADMINISTRACAO	VARCHAR2(20 CHAR),
ESFERADOPODER	VARCHAR2(20 CHAR),
CLASSIFICACAOUO	VARCHAR2(20 CHAR),
INICIOVIGENCIA	DATE,
FIMVIGENCIA	DATE,
ANO	NUMBER(10)
)