  CREATE OR REPLACE FORCE VIEW "VWENDERECOBCI" ("CADASTROIMOBILIARIO_ID", "LOGRADOURO", "NUMERO", "COMPLEMENTO", "BAIRRO", "LOTEAMENTO", "CEP", "SETOR", "QUADRA", "LOTE", "COMPLEMENTOLOTE", "ID_LOGRADOURO", "ID_BAIRRO")
  AS
    (SELECT CI.ID CADASTROIMOBILIARIO_ID,
      TRIM(COALESCE(TP.DESCRICAO,''))
      || ' '
      || TRIM(COALESCE(LOGRADOURO.NOME,'')) LOGRADOURO,
      TRIM(CI.NUMERO) NUMERO,
      TRIM(CI.COMPLEMENTOENDERECO) COMPLEMENTO,
      TRIM(BAIRRO.DESCRICAO) BAIRRO,
      TRIM(COALESCE(LOTEAMENTO.NOME,''))
      || ' '
      || TRIM(COALESCE(LOTE.DESCRICAOLOTEAMENTO,'')) LOTEAMENTO,
      TRIM(FACE.CEP) CEP,
      TRIM(SETOR.CODIGO) SETOR,
      TRIM(QUADRA.CODIGO) QUADRA,
      TRIM(LOTE.CODIGOLOTE) LOTE,
      TRIM(LOTE.COMPLEMENTO) COMPLEMENTOLOTE,
      LOGRADOURO.ID ID_LOGRADOURO,
      BAIRRO.ID ID_BAIRRO
    FROM CADASTROIMOBILIARIO CI
    INNER JOIN LOTE LOTE
    ON LOTE.ID = CI.LOTE_ID
    LEFT JOIN QUADRA QUADRA
    ON QUADRA.ID = LOTE.QUADRA_ID
    LEFT JOIN SETOR SETOR
    ON SETOR.ID = QUADRA.SETOR_ID
    LEFT JOIN LOTEAMENTO LOTEAMENTO
    ON LOTEAMENTO.ID = QUADRA.LOTEAMENTO_ID
    INNER JOIN TESTADA TESTADAS
    ON TESTADAS.LOTE_ID = LOTE.ID
    INNER JOIN FACE FACE
    ON FACE.ID = TESTADAS.FACE_ID
    INNER JOIN LOGRADOUROBAIRRO LOGBAIRRO
    ON LOGBAIRRO.ID = FACE.LOGRADOUROBAIRRO_ID
    INNER JOIN LOGRADOURO LOGRADOURO
    ON LOGRADOURO.ID = LOGBAIRRO.LOGRADOURO_ID
    INNER JOIN TIPOLOGRADOURO TP
    ON TP.ID = LOGRADOURO.TIPOLOGRADOURO_ID
    INNER JOIN BAIRRO BAIRRO
    ON BAIRRO.ID      = LOGBAIRRO.BAIRRO_ID
    WHERE TESTADAS.ID =
      (SELECT MAX(S_TESTA.ID)
      FROM TESTADA S_TESTA
      WHERE S_TESTA.LOTE_ID = LOTE.ID
      AND S_TESTA.PRINCIPAL = 1
      )
    )