CREATE OR REPLACE FORCE VIEW VWGRUPOOBJETOCOMPRAGRUPOBEM ("ID", "CODIGO", "SUPERIOR_ID", "DESCRICAO", "NIVEL", "GRUPOOBJETOCOMPRA_ID", "GRUPOBEM_ID")
                                                                                       AS
WITH REC(ID, CODIGO, SUPERIOR_ID, DESCRICAO, NIVEL, GRUPOOBJETOCOMPRA_ID, GRUPOBEM_ID) AS
  (SELECT GOC.ID,
    GOC.CODIGO,
    GOC.SUPERIOR_ID,
    GOC.DESCRICAO,
    1 AS NIVEL,
    VINC.GRUPOBEM_ID,
    VINC.GRUPOBEM_ID
  FROM GRUPOOBJETOCOMPRA GOC
  LEFT JOIN GRUPOOBJCOMPRAGRUPOBEM VINC
  ON VINC.GRUPOOBJETOCOMPRA_ID = GOC.ID
  WHERE SUPERIOR_ID           IS NULL
  UNION ALL
  SELECT GOC.ID,
    GOC.CODIGO,
    GOC.SUPERIOR_ID,
    GOC.DESCRICAO,
    REC.NIVEL+1 AS NIVEL,
    CASE
      WHEN REC.GRUPOOBJETOCOMPRA_ID IS NOT NULL
      THEN REC.GRUPOOBJETOCOMPRA_ID
      ELSE VINC.GRUPOOBJETOCOMPRA_ID
    END,
    CASE
      WHEN REC.GRUPOBEM_ID IS NOT NULL
      THEN REC.GRUPOBEM_ID
      ELSE VINC.GRUPOBEM_ID
    END
  FROM GRUPOOBJETOCOMPRA GOC
  INNER JOIN REC
  ON GOC.SUPERIOR_ID = REC.ID
  LEFT JOIN GRUPOOBJCOMPRAGRUPOBEM VINC
  ON VINC.GRUPOOBJETOCOMPRA_ID = GOC.ID
  WHERE GOC.SUPERIOR_ID       IS NOT NULL
  )
SELECT "ID",
  "CODIGO",
  "SUPERIOR_ID",
  "DESCRICAO",
  "NIVEL",
  "GRUPOOBJETOCOMPRA_ID",
  "GRUPOBEM_ID"
FROM REC