create or replace
FUNCTION GETPROXIMONUMERODAMASSTRING(numero in number, EXERCICIO_ID in NUMBER)
return VARCHAR2
AS 
ANO NUMBER;
BEGIN
SELECT EX.ano INTO ANO from exercicio EX where EX.id = EXERCICIO_ID;
return NUMERO || '/' || ANO;
END GETPROXIMONUMERODAMASSTRING;