UPDATE CREDITORECEBER SET OPERACAOCREDITORECEBER = 'AJUSTE_PERDAS_CREDITOS_A_RECEBER' 
WHERE OPERACAOCREDITORECEBER = 'PROVISAO_PERDAS_CREDITOS_A_RECEBER';

UPDATE CREDITORECEBER SET OPERACAOCREDITORECEBER = 'REVERSAO_AJUSTE_PERDAS_CREDITO_A_RECEBER' 
WHERE OPERACAOCREDITORECEBER = 'REVERSAO_PROVISAO_PERDAS_CREDITO_A_RECEBER';

UPDATE CREDITORECEBER SET OPERACAOCREDITORECEBER = 'BAIXA_DEDUCAO_RECONHECIMENTO_CREDITO_A_RECEBER' 
WHERE OPERACAOCREDITORECEBER = 'BAIXA_DEDUCAO_RECEITA_A_RECEBER';

COMMIT;