declare
  NUM number(10);
  cursor C1 is
    SELECT
      FID.TIPOFORMULAITEMDEMONSTRATIVO AS TIPOFORMULAITEMDEMONSTRATIVO,
      FID.ITEMDEMONSTRATIVO_ID         AS ITEMDEMONSTRATIVO_ID,
      FID.PLANODECONTAS_ID             AS PLANODECONTAS_ID,
      FID.EXERCICIO_ID                 AS EXERCICIO_ID,
      CF.OPERACAOFORMULA               AS OPERACAOFORMULA,
      FID.RELATORIOSITEMDEMONST_ID     AS RELATORIOSITEMDEMONST_ID
    FROM FORMULAITEMDEMONSTRATIVO FID
      INNER JOIN COMPONENTEFORMULA CF
        ON CF.FORMULAITEMDEMONSTRATIVO_ID = FID.ID
    WHERE NULLIF(TRIM(CF.OPERACAOFORMULA), '''') IS NOT NULL AND cf.operacaoFormula <> fid.operacaoFormula;
BEGIN
  FOR linha IN c1
  LOOP
  INSERT INTO FORMULAITEMDEMONSTRATIVO (ID, TIPOFORMULAITEMDEMONSTRATIVO, ITEMDEMONSTRATIVO_ID, PLANODECONTAS_ID, EXERCICIO_ID, OPERACAOFORMULA, RELATORIOSITEMDEMONST_ID)
    VALUES (hibernate_sequence.nextval, linha.TIPOFORMULAITEMDEMONSTRATIVO, linha.ITEMDEMONSTRATIVO_ID, linha.PLANODECONTAS_ID, linha.EXERCICIO_ID, linha.OPERACAOFORMULA, linha.RELATORIOSITEMDEMONST_ID);
    COMMIT;
  END LOOP;
  COMMIT;
END;