UPDATE CALCULOALVARAFUNC SET SITUACAOCALCULOALVARA = 'CALCULADO';
UPDATE CALCULOALVARALOCALIZACAO SET SITUACAOCALCULOALVARA = 'CALCULADO';
UPDATE CALCULOALVARASANITARIO SET SITUACAOCALCULOALVARA = 'CALCULADO';