INSERT INTO FALECONOSCONFSE (ID, SITUACAO, TIPO, ASSUNTO, DATAENVIO, NOME, MENSAGEM, EMAIL, TELEFONE, RESPOSTA, DATARESPOSTA, USUARIORESPOSTA_ID)
SELECT HIBERNATE_SEQUENCE.NEXTVAL,
       CASE WHEN DATARESPOSTA IS NOT NULL THEN 'ENCERRADO' ELSE 'ABERTO' END AS SITUACAO,
       CASE
          WHEN ASSUNTO LIKE 'Denúncia%' THEN 'DENUNCIA'
          WHEN ASSUNTO LIKE 'Reclamação%' THEN 'RECLAMACAO'
          WHEN ASSUNTO LIKE 'Solicitação%' THEN 'SOLICITACAO'
          WHEN ASSUNTO LIKE 'Sugestão%' THEN 'SUGESTAO'
          WHEN ASSUNTO LIKE 'Elogio%' THEN 'ELOGIO'
       END AS TIPO,
       ASSUNTO,
       DATAENVIO,
       NOME,
       MENSAGEM,
       EMAIL,
       TELEFONE,
       RESPOSTA,
       DATARESPOSTA,
       USUARIOSISTEMA_ID
   FROM FALECONOSCO WHERE ORIGEMFALECONOSCO = 'NFSE'
