UPDATE DECLARACAOMENSALSERVICO SET LANCADOPOR = 'CLIENTE' WHERE ID < 0;

UPDATE DECLARACAOMENSALSERVICO D SET (LANCADOPOR, USUARIODECLARACAO) = (
SELECT 'WEBPUBLICO', PF.NOME
   FROM DECLARACAOMENSALSERVICO DMS
  INNER JOIN LOTEDECMENSALSERVICOITEM ITEM ON ITEM.ID = (SELECT MAX(S.ID) FROM LOTEDECMENSALSERVICOITEM S WHERE S.DECLARACAOMENSALSERVICO_ID = DMS.ID)
  INNER JOIN LOTEDECMENSALSERVICO LOTE ON LOTE.ID = ITEM.LOTE_ID
  INNER JOIN USUARIOSISTEMA US ON US.ID = LOTE.USUARIOSISTEMA_ID
  INNER JOIN PESSOAFISICA PF ON PF.ID = US.PESSOAFISICA_ID
WHERE DMS.ID = D.ID)
WHERE ID IN (SELECT DMS.ID
   FROM DECLARACAOMENSALSERVICO DMS
  INNER JOIN LOTEDECMENSALSERVICOITEM ITEM ON ITEM.ID = (SELECT MAX(S.ID) FROM LOTEDECMENSALSERVICOITEM S WHERE S.DECLARACAOMENSALSERVICO_ID = DMS.ID)
  INNER JOIN LOTEDECMENSALSERVICO LOTE ON LOTE.ID = ITEM.LOTE_ID
  INNER JOIN USUARIOSISTEMA US ON US.ID = LOTE.USUARIOSISTEMA_ID
  INNER JOIN PESSOAFISICA PF ON PF.ID = US.PESSOAFISICA_ID);
