create or replace TRIGGER DEFINENUMERONOTAFISCAL
    BEFORE INSERT
    ON NOTAFISCAL
    FOR EACH ROW
BEGIN
    select coalesce(max(numero)+ 1,1) into :NEW.NUMERO from NOTAFISCAL where PRESTADOR_ID = :NEW.PRESTADOR_ID and HOMOLOGACAO = :NEW.HOMOLOGACAO;
END;
