CREATE OR REPLACE PROCEDURE PROC_ENQUADRAMENTOFISCAL_NFSE IS
   CURSOR NOTAS IS
   SELECT DPP.ID AS ID,
       COALESCE(EF.TIPOISSQN, EF2.TIPOISSQN) AS TIPOISSQN,
       COALESCE(EF.REGIMETRIBUTARIO, EF2.REGIMETRIBUTARIO) AS REGIMETRIBUTARIO
   FROM NOTAFISCAL NF
  INNER JOIN CADASTROECONOMICO CE ON CE.ID = NF.PRESTADOR_ID
  INNER JOIN DECLARACAOPRESTACAOSERVICO DEC ON DEC.ID = NF.DECLARACAOPRESTACAOSERVICO_ID
  INNER JOIN DADOSPESSOAISNFSE DPP ON DPP.ID = DEC.DADOSPESSOAISPRESTADOR_ID
  LEFT JOIN ENQUADRAMENTOFISCAL EF ON EF.CADASTROECONOMICO_ID = CE.ID
                                   AND NF.EMISSAO BETWEEN EF.INICIOVIGENCIA AND COALESCE(EF.FIMVIGENCIA, CURRENT_DATE)
  LEFT JOIN ENQUADRAMENTOFISCAL EF2 ON EF.CADASTROECONOMICO_ID = CE.ID
                                   AND CURRENT_DATE BETWEEN EF.INICIOVIGENCIA AND COALESCE(EF.FIMVIGENCIA, CURRENT_DATE);
   NOTA NOTAS%ROWTYPE;
BEGIN
   OPEN NOTAS;
   LOOP
      FETCH NOTAS INTO NOTA;
      EXIT WHEN NOTAS%NOTFOUND;

      UPDATE DADOSPESSOAISNFSE SET TIPOISSQN = NOTA.TIPOISSQN, REGIMETRIBUTARIO = NOTA.REGIMETRIBUTARIO
      WHERE ID = NOTA.ID;
   END LOOP;
   CLOSE NOTAS;
END;
