INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '010101000', 'Análise e desenvolvimento de sistemas',
        (SELECT ID FROM SERVICO WHERE CODIGO = '101'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '010201000', 'Programação', (SELECT ID FROM SERVICO WHERE CODIGO = '102'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '010301000', 'Processamento de dados',
        (SELECT ID FROM SERVICO WHERE CODIGO = '103'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '010501000', 'Licenciamento ou cessão de direito de uso de programas de
computação', (SELECT ID FROM SERVICO WHERE CODIGO = '105'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '010601000', 'Assessoria e consultoria em informática',
        (SELECT ID FROM SERVICO WHERE CODIGO = '106'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '010701000',
        'Suporte Técnico em Informática, inclusive instalação, configuração e manutenção de programas de computação e banco de dados',
        (SELECT ID FROM SERVICO WHERE CODIGO = '107'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '030201000', 'Cessão de direito de uso de marcas e de sinais de propaganda',
        (SELECT ID FROM SERVICO WHERE CODIGO = '302'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '071901000', 'Acompanhamento e fiscalização da execução de obras de engenharia, arquitetura e urbanismo (não vinculado a liberação de
crédito próprio)', (SELECT ID FROM SERVICO WHERE CODIGO = '719'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '080201000', 'Instrução, treinamento, avaliação de conhecimentos de qualquer
natureza', (SELECT ID FROM SERVICO WHERE CODIGO = '802'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '100101000', 'Agenciamento de câmbio',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1001'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '100102000', 'Corretagem de câmbio',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1001'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '100103000', 'Intermediação de câmbio',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1001'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '100104000', 'Agenciamento de seguros',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1001'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '100105000', 'Corretagem de seguros',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1001'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '100106000', 'Intermediação de seguros',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1001'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '100107000', 'Agenciamento de cartões de crédito',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1001'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '100108000', 'Corretagem de cartões de crédito',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1001'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '100109000', 'Intermediação de cartões de crédito',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1001'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '100110000', 'Agenciamento de planos de previdência privada',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1001'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '100111000', 'Corretagem de planos de previdência privada',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1001'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '100112000', 'Intermediação de planos de previdência privada',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1001'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '100201000', 'Agenciamento de títulos em geral',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1002'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '100202000', 'Corretagem de títulos em geral',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1002'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '100203000', 'Intermediação de títulos em geral',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1002'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '100204000', 'Agenciamento de valores mobiliários',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1002'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '100205000', 'Corretagem de valores mobiliários',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1002'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '100206000', 'Intermediação de valores mobiliários',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1002'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '100207000', 'Agenciamento de contratos quaisquer',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1002'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '100208000', 'Corretagem de contratos quaisquer',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1002'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '100209000', 'Intermediação de contratos quaisquer',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1002'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '100401000', 'Agenciamento de contratos de arrendamento mercantil (leasing)',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1004'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '100402000', 'Corretagem de contratos de arrendamento mercantil (leasing)',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1004'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '100403000', 'Intermediação de contratos de arrendamento mercantil (leasing)',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1004'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '100404000', 'Agenciamento de contratos de “faturização” (factoring)',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1004'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '100405000', 'Corretagem de contratos de “faturização” (factoring)',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1004'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '100406000', 'Intermediação de contratos de “faturização” (factoring)',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1004'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '100501000',
        'Agenciamento de bens móveis não abrangidos em outros itens / subitens.',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1005'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '100502000', 'Corretagem de bens móveis não abrangidos em outros itens / subitens.',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1005'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '100503000',
        'Intermediação de bens móveis não abrangidos em outros itens / subitens.',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1005'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '100504000',
        'Agenciamento de bens imóveis não abrangidos em outros itens / subitens.',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1005'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '100505000',
        'Corretagem de bens imóveis não abrangidos em outros itens / subitens.',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1005'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '100506000',
        'Intermediação de bens imóveis não abrangidos em outros itens / subitens.',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1005'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '100507000', 'Agenciamento no âmbito de Bolsas de Mercadorias e Futuros.',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1005'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '100508000', 'Corretagem no âmbito de Bolsas de Mercadorias e Futuros.',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1005'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '100509000', 'Intermediação no âmbito de Bolsas de Mercadorias e Futuros.',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1005'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '100901000', 'Representação de qualquer natureza, inclusive comercial',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1009'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '101001000', 'Distribuição de bens de terceiros',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1010'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '110101000', 'Guarda e estacionamento de veículos terrestres automotores',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1101'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '110102000', 'Guarda e estacionamento de aeronaves e de embarcações',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1101'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '130301000', 'Fotografia e cinematografia, inclusive revelação, ampliação, cópia,
reprodução, trucagem', (SELECT ID FROM SERVICO WHERE CODIGO = '1303'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '130401000', 'Serviços de reprografia',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1304'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '130402000', 'Serviços de microfilmagem',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1304'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '130403000', 'Serviços de digitalização',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1304'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150101000', 'Administração de fundos quaisquer',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1501'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150102000', 'Administração de consórcio',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1501'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150103000', 'Administração de cartão de crédito ou débito e congêneres',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1501'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150104000', 'Administração de carteira de clientes',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1501'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150105000', 'Administração de cheques pré-datados e congêneres',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1501'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150201000', 'Abertura de conta-corrente no país',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1502'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150202000', 'Abertura de contas de investimentos e aplicação no país',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1502'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150203000', 'Abertura de conta de poupança no país',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1502'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150204000',
        'Abertura de contas em geral no país não abrangidas em outros itens/subitens.',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1502'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150205000', 'Abertura de conta-corrente no exterior',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1502'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150206000', 'Abertura de contas de investimentos e aplicação no exterior',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1502'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150207000', 'Abertura de conta de poupança no exterior',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1502'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150208000',
        'Abertura de contas em geral no exterior não abrangidas em outros itens / subitens.',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1502'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150209000', 'Manutenção de conta-corrente no país',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1502'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150210000', 'Manutenção de contas de investimentos e aplicação no país',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1502'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150211000', 'Manutenção de conta de poupança no país',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1502'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150212000',
        'Manutenção de contas em geral no país não abrangidas em outros itens / subitens.',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1502'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150213000', 'Manutenção de conta-corrente no exterior',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1502'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150214000', 'Manutenção de contas de investimentos e aplicação no exterior',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1502'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150215000', 'Manutenção de conta de poupança no exterior',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1502'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150216000',
        'Manutenção de contas em geral no exterior não abrangidas em outros itens / subitens.',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1502'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150301000', 'Locação de cofres particulares',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1503'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150302000', 'Manutenção de cofres particulares',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1503'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150303000', 'Locação de terminais eletrônicos',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1503'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150304000', 'Manutenção de terminais eletrônicos',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1503'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150305000', 'Locação de terminais de atendimento',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1503'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150306000', 'Manutenção de terminais de atendimento',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1503'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150307000', 'Locação de bens e equipamentos em geral',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1503'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150308000', 'Manutenção de bens e equipamentos em geral',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1503'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150401000', 'Fornecimento e emissão de atestado de idoneidade',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1504'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150402000',
        'Fornecimento e emissão de atestado de capacidade financeira e congêneres',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1504'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150403000',
        'Fornecimento e emissão de atestados em geral não abrangidas em outros itens/subitens.',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1504'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150501000', 'Cadastro, elaboração e Renovação de ficha cadastral e congêneres',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1505'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150502000', 'Inclusão no cadastro de emitentes de cheques sem fundos-CCF',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1505'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150503000', 'Exclusão do cadastro de emitentes de cheques sem fundos-CCF',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1505'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150504000', 'Inclusão no cadastro de outros bancos cadastrais quaisquer',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1505'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150505000', 'Exclusão do cadastro de outros bancos cadastrais quaisquer',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1505'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150601000', 'Emissão, reemissão e fornecimento de avisos.',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1506'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150602000', 'Emissão, reemissão e fornecimento de comprovantes',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1506'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150603000', 'Emissão, reemissão e fornecimento de documentos em geral',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1506'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150604000', 'Abono de firmas', (SELECT ID FROM SERVICO WHERE CODIGO = '1506'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150605000', 'Coleta de documentos, bens e valores',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1506'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150606000', 'Entrega de documentos, bens e valores',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1506'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150607000', 'Comunicação com outra agência',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1506'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150608000', 'Comunicação com a administração central',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1506'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150609000', 'Licenciamento eletrônico de veículos',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1506'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150610000', 'Transferência de veículos',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1506'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150611000', 'Agenciamento fiduciário',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1506'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150612000', 'Agenciamento depositário',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1506'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150613000', 'Devolução de bens em custódia',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1506'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150614000', 'Baixa eletrônica de gravame para veículos',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1506'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150701000',
        'Acesso, movimentação, atendimento e consulta a contas em geral por telefone',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1507'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150702000',
        'Acesso, movimentação, atendimento e consulta a contas em geral por fac-símile',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1507'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150703000',
        'Acesso, movimentação, atendimento e consulta a contas em geral via internet',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1507'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150704000', 'Acesso, movimentação, atendimento e consulta a contas por telex',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1507'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150705000',
        'Acesso, movimentação, atendimento e consulta a contas em geral, por qualquer meio ou processo não abrangidas em outros itens / subitens.',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1507'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150706000', 'Acesso a terminais de atendimento, inclusive 24 horas',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1507'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150707000', 'Acesso a outro banco',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1507'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150708000', 'Acesso à rede compartilhada',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1507'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150709000',
        'Fornecimento de saldo, extrato e demais informações relativas a contas em geral, por qualquer meio ou processo.',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1507'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150710000', 'Pacote / cesta de serviços bancários',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1507'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150801000', 'Emissão e reemissão de contrato de crédito',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1508'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150802000', 'Alteração de contrato de crédito',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1508'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150803000', 'Cessão de contrato de crédito',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1508'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150804000', 'Substituição de contrato de crédito',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1508'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150805000', 'Cancelamento de contrato de crédito',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1508'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150806000', 'Registro de contrato de crédito',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1508'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150807000', 'Estudo, análise e avaliação de operações de crédito',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1508'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150808000', 'Emissão de aval, fiança, anuência e congêneres',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1508'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150809000', 'Concessão de aval, fiança, anuência e congêneres',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1508'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150810000', 'Alteração de aval, fiança, anuência e congêneres',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1508'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150811000', 'Contratação de aval, fiança, anuência e congêneres',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1508'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150812000',
        'Serviços relativos a abertura de crédito não abrangidas em outros itens/subitens, para quaisquer fins.',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1508'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150901000',
        'Arrendamento mercantil (leasing) de quaisquer bens, inclusive cessão de direitos e obrigações',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1509'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150902000', 'Substituição de garantia',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1509'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150903000', 'Alteração de contrato de leasing',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1509'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150904000', 'Cancelamento de contrato de leasing',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1509'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150905000', 'Registro de contrato de leasing',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1509'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '150906000', 'Demais serviços relacionados ao arrendamento mercantil (leasing)',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1509'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151001000',
        'Serviços relacionados a cobranças e recebimentos em geral de títulos quaisquer efetuados por qualquer meio',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1510'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151002000',
        'Serviços relacionados a cobranças e recebimentos de contas em geral efetuados por qualquer meio',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1510'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151003000',
        'Serviços relacionados a cobranças e recebimentos de carnês em geral efetuados por qualquer meio',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1510'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151004000',
        'Serviços relacionados a cobranças e recebimentos de câmbio em geral efetuados por qualquer meio',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1510'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151005000',
        'Serviços relacionados a recebimentos de tributos em geral efetuados por qualquer meio',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1510'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151006000',
        'Serviços relacionados a cobranças e recebimentos por conta de terceiros em geral efetuados por qualquer meio',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1510'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151007000',
        'Serviços relacionados a pagamentos em geral de títulos quaisquer efetuados por qualquer meio',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1510'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151008000',
        'Serviços relacionados a pagamentos de contas em geral efetuados por qualquer meio',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1510'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151009000',
        'Serviços relacionados a pagamentos de carnês em geral efetuados por qualquer meio',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1510'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151010000',
        'Serviços relacionados a pagamentos de câmbio em geral efetuados por qualquer meio',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1510'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151011000',
        'Serviços relacionados a pagamentos de tributos em geral efetuados por qualquer meio',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1510'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151012000',
        'Serviços relacionados a pagamentos por conta de terceiros em geral efetuados por qualquer meio',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1510'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151013000', 'Fornecimento de posição de cobrança',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1510'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151014000', 'Fornecimento de posição de recebimento',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1510'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151015000', 'Fornecimento de posição de pagamento',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1510'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151016000', 'Emissão de carnês', (SELECT ID FROM SERVICO WHERE CODIGO = '1510'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151017000', 'Emissão de fichas de compensação',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1510'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151018000', 'Emissão de impressos e documentos em geral',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1510'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151101000', 'Devolução de títulos',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1511'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151102000', 'Protesto de títulos', (SELECT ID FROM SERVICO WHERE CODIGO = '1511'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151103000', 'Sustação de protesto',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1511'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151104000', 'Manutenção de títulos',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1511'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151105000', 'Reapresentação de títulos',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1511'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151106000', 'Demais serviços relacionados a títulos em cobrança',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1511'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151201000', 'Custódia em geral, inclusive de títulos e valores mobiliários',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1512'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151301000', 'Edição de contrato de câmbio',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1513'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151302000', 'Alteração de contrato de câmbio',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1513'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151303000', 'Prorrogação de contrato de câmbio',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1513'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151304000', 'Cancelamento de contrato de câmbio',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1513'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151305000', 'Baixa de contrato de câmbio',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1513'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151306000', 'Emissão de registro de exportação',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1513'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151307000', 'Emissão de registro de crédito',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1513'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151308000', 'Cobrança no exterior',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1513'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151309000', 'Depósito no exterior',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1513'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151310000', 'Emissão e fornecimento de cheques de viagem',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1513'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151311000', 'Cancelamento de cheques de viagem',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1513'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151312000', 'Fornecimento de carta de crédito de importação',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1513'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151313000', 'Transferência de carta de crédito de importação',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1513'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151314000', 'Cancelamento de carta de crédito de importação',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1513'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151315000', 'Demais serviços relativos à carta de crédito de importação',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1513'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151316000', 'Fornecimento de carta de crédito de exportação',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1513'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151317000', 'Transferência de carta de crédito de exportação',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1513'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151318000', 'Cancelamento de carta de crédito de exportação',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1513'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151319000', 'Demais serviços relativos à carta de crédito de exportação',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1513'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151320000', 'Serviços relativos a garantias recebidas',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1513'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151321000', 'Envio de mensagens em geral relacionadas a operações de câmbio',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1513'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151322000', 'Recebimento de mensagens em geral relacionadas a operações de câmbio',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1513'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151323000', 'Demais serviços relacionados à operação de câmbio',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1513'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151401000', 'Fornecimento, emissão e reemissão de cartão magnético',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1514'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151402000', 'Renovação de cartão magnético',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1514'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151403000', 'Manutenção de cartão magnético',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1514'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151404000', 'Fornecimento, emissão e reemissão de cartão de crédito',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1514'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151405000', 'Renovação de cartão de crédito',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1514'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151406000', 'Manutenção de cartão de crédito',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1514'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151407000', 'Fornecimento, emissão e reemissão de cartão de débito',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1514'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151408000', 'Renovação de cartão de débito',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1514'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151409000', 'Manutenção de cartão de débito',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1514'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151410000', 'Fornecimento, emissão e reemissão de cartão salário',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1514'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151411000', 'Renovação de cartão salário',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1514'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151412000', 'Manutenção de cartão salário',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1514'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151413000', 'Fornecimento, emissão e reemissão de cartões congêneres',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1514'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151414000', 'Renovação de cartões congêneres',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1514'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151415000', 'Manutenção de cartões congêneres',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1514'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151501000', 'Compensação de cheques',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1515'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151502000', 'Compensação de títulos quaisquer',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1515'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151503000', 'Serviços relacionados a depósito, inclusive depósito identificado',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1515'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151504000',
        'Serviços relacionados a saque de contas quaisquer, por qualquer meio ou processo.',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1515'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151601000',
        'Emissão / reemissão de ordens de pagamento, ordens de crédito e similares, por qualquer meio ou processo',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1516'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151602000',
        'Liquidação de ordens de pagamento, ordens de crédito e similares, por qualquer meio ou processo',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1516'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151603000',
        'Alteração de ordens de pagamento, ordens de crédito e similares, por qualquer meio ou processo',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1516'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151604000',
        'Cancelamento de ordens de pagamento, ordens de crédito e similares, por qualquer meio ou processo',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1516'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151605000',
        'Baixa de ordens de pagamento, ordens de crédito e similares, por qualquer meio ou processo',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1516'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151606000',
        'Serviços relacionados à transferência de valores, dados, fundos, pagamentos e similares, inclusive entre contas em geral',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1516'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151701000', 'Emissão de cheques quaisquer, avulso ou por talão',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1517'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151702000', 'Fornecimento de cheques quaisquer, avulso ou por talão',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1517'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151703000', 'Devolução de cheques quaisquer, avulso ou por talão',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1517'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151704000', 'Sustação de cheques quaisquer, avulso ou por talão',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1517'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151705000', 'Cancelamento de cheques quaisquer, avulso ou por talão',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1517'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151706000', 'Oposição de cheques quaisquer, avulso ou por talão',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1517'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151801000', 'Avaliação de imóvel', (SELECT ID FROM SERVICO WHERE CODIGO = '1518'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151802000', 'Avaliação de obra', (SELECT ID FROM SERVICO WHERE CODIGO = '1518'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151803000', 'Vistoria de imóvel', (SELECT ID FROM SERVICO WHERE CODIGO = '1518'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151804000', 'Vistoria de obra', (SELECT ID FROM SERVICO WHERE CODIGO = '1518'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151805000', 'Análise técnica relacionada ao crédito imobiliário',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1518'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151806000', 'Análise jurídica relacionada ao crédito imobiliário',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1518'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151807000', 'Emissão / reemissão de contrato de crédito imobiliário',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1518'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151808000', 'Alteração de contrato de crédito imobiliário',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1518'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151809000', 'Transferência de contrato de crédito imobiliário',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1518'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151810000', 'Renegociação de contrato de crédito imobiliário',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1518'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151811000', 'Emissão / reemissão de termo de quitação',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1518'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '151812000', 'Outros serviços relacionados ao crédito imobiliário',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1518'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '170101000', 'Assessoria de qualquer natureza',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1701'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '170102000', 'Consultoria de qualquer natureza',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1701'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '170103000',
        'Análise, exame, fornecimento de dados e informações de qualquer natureza',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1701'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '170201000', 'Serviços de expediente',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1702'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '170202000', 'Serviços de apoio e infra-estrutura administrativa e congêneres',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1702'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '170301000',
        'Serviços de planejamento, coordenação, programação ou organização técnica',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1703'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '170302000',
        'Serviços de planejamento, coordenação, programação ou organização financeira',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1703'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '170303000',
        'Serviços de planejamento, coordenação, programação ou organização administrativa',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1703'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '170501000', 'Fornecimento de mão-de-obra, em caráter temporário ou permanente',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1705'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '170601000', 'Propaganda e publicidade, inclusive promoção de vendas, planejamento de campanhas ou sistemas de publicidade,
elaboração de desenhos, textos e demais materiais publicitários.', (SELECT ID FROM SERVICO WHERE CODIGO = '1706'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '170901000', 'Serviços de perícias',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1709'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '170902000', 'Serviços de laudos', (SELECT ID FROM SERVICO WHERE CODIGO = '1709'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '170903000', 'Serviços de exames técnicos',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1709'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '170904000', 'Serviços de análises técnicas',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1709'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '171201000', 'Administração em geral de bens e negócios de terceiros',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1712'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '171301000', 'Leilão e congêneres', (SELECT ID FROM SERVICO WHERE CODIGO = '1713'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '171601000', 'Auditoria', (SELECT ID FROM SERVICO WHERE CODIGO = '1716'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '171901000', 'Contabilidade, inclusive serviços técnicos e auxiliares',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1719'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '172001000', 'Consultoria econômica',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1720'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '172002000', 'Assessoria econômica',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1720'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '172003000', 'Consultoria financeira',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1720'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '172004000', 'Assessoria financeira',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1720'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '180101000', 'Serviços de regulação de sinistros vinculados a contratos de seguros',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1801'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '180102000', 'Serviços de inspeção e avaliação de riscos para cobertura de
contratos de seguros', (SELECT ID FROM SERVICO WHERE CODIGO = '1801'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '180103000', 'Serviços de prevenção e gerência de riscos seguráveis e congêneres.',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1801'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '190101000',
        'Serviços de distribuição de bilhetes e demais produtos de loteria, cartões, pules ou cupons de apostas, sorteios, prêmios, inclusive os decorrentes de títulos de capitalização e congêneres',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1901'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '190102000',
        'Serviços de vendas de bilhetes e demais produtos de loteria, cartões, pules ou cupons de apostas, sorteios, prêmios, inclusive os decorrentes de títulos de capitalização e congêneres',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1901'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '190103000', 'Serviços de distribuição de bilhetes e demais produtos de bingos.',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1901'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '190104000', 'Serviços de vendas de bilhetes e demais produtos de bingos.',
        (SELECT ID FROM SERVICO WHERE CODIGO = '1901'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '260101000', 'Serviços de coleta de bens ou valores',
        (SELECT ID FROM SERVICO WHERE CODIGO = '2601'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '260102000', 'Serviços de remessa de bens ou valores',
        (SELECT ID FROM SERVICO WHERE CODIGO = '2601'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '260103000', 'Serviços de entrega de bens ou valores',
        (SELECT ID FROM SERVICO WHERE CODIGO = '2601'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '260104000', 'Serviços de courrier e congêneres',
        (SELECT ID FROM SERVICO WHERE CODIGO = '2601'));
INSERT INTO CODIGOTRIBUTACAO (ID, CODIGO, DESCRICAO, SERVICO_ID)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, '280101000', 'Serviços de avaliação de bens e serviços de qualquer natureza',
        (SELECT ID FROM SERVICO WHERE CODIGO = '2801'));
