INSERT INTO RECURSOSISTEMA VALUES
    (HIBERNATE_SEQUENCE.nextval, 'TRIBUTÁRIO > NFSE > CAMPANHA > LISTA',
     '/tributario/nfse/campanha/lista.xhtml', 0, 'TRIBUTARIO');

INSERT INTO GRUPORECURSOSISTEMA VALUES (HIBERNATE_SEQUENCE.currval, 622038399);

INSERT INTO RECURSOSISTEMA VALUES
    (HIBERNATE_SEQUENCE.nextval, 'TRIBUTÁRIO > NFSE > CAMPANHA > EDITA',
     '/tributario/nfse/campanha/edita.xhtml', 0, 'TRIBUTARIO');

INSERT INTO GRUPORECURSOSISTEMA VALUES (HIBERNATE_SEQUENCE.currval, 622038399);

INSERT INTO RECURSOSISTEMA VALUES
    (HIBERNATE_SEQUENCE.nextval, 'TRIBUTÁRIO > NFSE > CAMPANHA > VISUALIZAR',
     '/tributario/nfse/campanha/visualizar.xhtml', 0, 'TRIBUTARIO');

INSERT INTO GRUPORECURSOSISTEMA VALUES (HIBERNATE_SEQUENCE.currval, 622038399);

INSERT INTO menu VALUES (HIBERNATE_SEQUENCE.nextval, 'CAMPANHA',
                         '/tributario/nfse/campanha/lista.xhtml', (select ID from menu where LABEL = 'NFS-E'), 60);
