INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (hibernate_sequence.nextval, 'TRIBUTÁRIO > NOTA FISCAL > DASHBOARD EVOLUÇÃO DE EMISSÃO',
        '/tributario/nfse/dashboard-evolucao-emissao/edita.xhtml', 0, 'TRIBUTARIO');

INSERT INTO MENU (ID, LABEL, CAMINHO, PAI_ID, ORDEM)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'DASHBOARD EVOLUÇÃO DE EMISSÃO',
        '/tributario/nfse/dashboard-evolucao-emissao/edita.xhtml',
        (SELECT ID FROM MENU WHERE LABEL = 'NOTA FISCAL' AND CAMINHO IS NULL), 300);

INSERT INTO GRUPORECURSOSISTEMA (GRUPORECURSO_ID, RECURSOSISTEMA_ID)
VALUES ((SELECT ID FROM GRUPORECURSO WHERE NOME = 'TRB - NFS-e - Gerencial'),
        (SELECT ID FROM RECURSOSISTEMA WHERE NOME = 'TRIBUTÁRIO > NOTA FISCAL > DASHBOARD EVOLUÇÃO DE EMISSÃO'));
