insert into GRUPOUSUARIONOTIFICACAO
select HIBERNATE_SEQUENCE.nextval, GRUPOUSUARIO_ID, 'RECLAMACAO_NOTA_PREMIADA'
from GRUPOUSUARIONOTIFICACAO
where TIPONOTIFICACAO in ('COMUNICACAO_NFS_ELETRONICA','FALE_CONOSCO_PORTAL_NFSE');
