INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES(hibernate_sequence.nextval, 'TRIBUTÁRIO > NOTA FISCAL > RELATÓRIOS DA NFSE > RELATÓRIO DE SERVIÇOS DECLARADOS', '/tributario/nfse/relatorio/servicos-declarados.xhtml',
 0, 'TRIBUTARIO');

INSERT INTO MENU (ID, LABEL, CAMINHO, PAI_ID, ORDEM)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'RELATÓRIO DE SERVIÇOS DECLARADOS',
'/tributario/nfse/relatorio/servicos-declarados.xhtml',
(SELECT ID FROM MENU WHERE LABEL = 'RELATÓRIOS DA NFSE' AND CAMINHO IS NULL), 180);

INSERT INTO GRUPORECURSOSISTEMA (GRUPORECURSO_ID, RECURSOSISTEMA_ID)
VALUES ((SELECT ID FROM GRUPORECURSO WHERE NOME = 'TRB - NFS-e - Gerencial'),
(SELECT ID FROM RECURSOSISTEMA WHERE NOME = 'TRIBUTÁRIO > NOTA FISCAL > RELATÓRIOS DA NFSE > RELATÓRIO DE SERVIÇOS DECLARADOS'));
