INSERT INTO DESIF (ID, CADASTROECONOMICO_ID, DECLARACAOPRESTACAOSERVICO_ID)
SELECT HIBERNATE_SEQUENCE.NEXTVAL, DMS.PRESTADOR_ID, DEC.ID
   FROM DECLARACAOPRESTACAOSERVICO DEC
  INNER JOIN NOTADECLARADA ND ON ND.DECLARACAOPRESTACAOSERVICO_ID = DEC.ID
  INNER JOIN DECLARACAOMENSALSERVICO DMS ON DMS.ID = ND.DECLARACAOMENSALSERVICO_ID
WHERE DMS.TIPOMOVIMENTO = 'INSTITUICAO_FINANCEIRA'
  AND NOT EXISTS (SELECT 1 FROM DESIF WHERE DESIF.DECLARACAOPRESTACAOSERVICO_ID = DEC.ID)
