UPDATE DECLARACAOPRESTACAOSERVICO
SET NATUREZAOPERACAO = 'SIMPLES_NACIONAL'
WHERE ID IN (
    SELECT COUNT(1)
    FROM NOTAFISCAL NF
             INNER JOIN RPS ON RPS.ID = NF.RPS_ID
             INNER JOIN DECLARACAOPRESTACAOSERVICO DEC ON DEC.ID = NF.DECLARACAOPRESTACAOSERVICO_ID
             INNER JOIN DADOSPESSOAISNFSE DPT ON DPT.ID = DEC.DADOSPESSOAISTOMADOR_ID
    WHERE DEC.NATUREZAOPERACAO = 'RETENCAO_SIMPLES_NACIONAL'
      AND NOT EXISTS(SELECT 1
                     FROM CADASTROECONOMICO CE
                              INNER JOIN PESSOAJURIDICA PJ ON PJ.ID = CE.PESSOA_ID
                     WHERE REPLACE(REPLACE(REPLACE(PJ.CNPJ, '.', ''), '-', ''), '/', '') =
                           REPLACE(REPLACE(REPLACE(DPT.CPFCNPJ, '.', ''), '-', ''), '/', '')));

UPDATE DECLARACAOPRESTACAOSERVICO
SET NATUREZAOPERACAO = 'TRIBUTACAO_MUNICIPAL'
WHERE ID IN (
    SELECT COUNT(1)
    FROM NOTAFISCAL NF
             INNER JOIN RPS ON RPS.ID = NF.RPS_ID
             INNER JOIN DECLARACAOPRESTACAOSERVICO DEC ON DEC.ID = NF.DECLARACAOPRESTACAOSERVICO_ID
             INNER JOIN DADOSPESSOAISNFSE DPT ON DPT.ID = DEC.DADOSPESSOAISTOMADOR_ID
    WHERE DEC.NATUREZAOPERACAO = 'RETENCAO'
      AND NOT EXISTS(SELECT 1
                     FROM CADASTROECONOMICO CE
                              INNER JOIN PESSOAJURIDICA PJ ON PJ.ID = CE.PESSOA_ID
                     WHERE REPLACE(REPLACE(REPLACE(PJ.CNPJ, '.', ''), '-', ''), '/', '') =
                           REPLACE(REPLACE(REPLACE(DPT.CPFCNPJ, '.', ''), '-', ''), '/', '')));
