INSERT INTO TIPODEPENDENCIADESIF (ID, CODIGO, DESCRICAO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 1, 'Agência (Matriz)');
INSERT INTO TIPODEPENDENCIADESIF (ID, CODIGO, DESCRICAO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 2, 'Agência (Filial)');
INSERT INTO TIPODEPENDENCIADESIF (ID, CODIGO, DESCRICAO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 3, 'Unidade Administrativa Desmembrada - UAD');
INSERT INTO TIPODEPENDENCIADESIF (ID, CODIGO, DESCRICAO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 4, 'Posto de Atendimento Bancário - PAB');
INSERT INTO TIPODEPENDENCIADESIF (ID, CODIGO, DESCRICAO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 5, 'Posto de Atendimento Eletrônico - PAE');
INSERT INTO TIPODEPENDENCIADESIF (ID, CODIGO, DESCRICAO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 6, 'Posto de Atendimento de Cooperativa de Crédito - PAC');
INSERT INTO TIPODEPENDENCIADESIF (ID, CODIGO, DESCRICAO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 7, 'Outros tipos de postos');
