delete from MENU
where LABEL = 'INTEGRAÇÃO - PNCP';

INSERT INTO RECURSOSISTEMA
VALUES (HIBERNATE_SEQUENCE.nextval, 'ADMINISTRATIVO > LICITAÇÃO > ENTIDADE PNCP > VISUALIZAR',
        '/administrativo/licitacao/entidade-pncp/visualizar.xhtml', 0, 'LICITACAO');
INSERT INTO GRUPORECURSOSISTEMA
VALUES (HIBERNATE_SEQUENCE.currval, 173907291);

INSERT INTO RECURSOSISTEMA
VALUES (HIBERNATE_SEQUENCE.nextval, 'ADMINISTRATIVO > LICITAÇÃO > ENTIDADE PNCP > EDITA',
        '/administrativo/licitacao/entidade-pncp/edita.xhtml', 0, 'LICITACAO');
INSERT INTO GRUPORECURSOSISTEMA
VALUES (HIBERNATE_SEQUENCE.currval, 173907291);

INSERT INTO RECURSOSISTEMA
VALUES (HIBERNATE_SEQUENCE.nextval, 'ADMINISTRATIVO > LICITAÇÃO > ENTIDADE PNCP > LISTA',
        '/administrativo/licitacao/entidade-pncp/lista.xhtml', 0, 'LICITACAO');
INSERT INTO GRUPORECURSOSISTEMA
VALUES (HIBERNATE_SEQUENCE.currval, 173907291);

INSERT INTO MENU (ID, LABEL, CAMINHO, PAI_ID, ORDEM)
VALUES (HIBERNATE_SEQUENCE.nextval, 'PNCP - PORTAL NACIONAL DE CONTRATAÇÕES PÚBLICAS', null,
        (SELECT ID FROM menu WHERE LABEL = 'COMPRAS E LICITAÇÕES'), 7);

INSERT INTO MENU (ID, LABEL, CAMINHO, PAI_ID, ORDEM)
VALUES (HIBERNATE_SEQUENCE.nextval, 'INTEGRAÇÃO - PNCP',
        '/administrativo/licitacao/pncp/integracao-pncp.xhtml',
        (SELECT ID FROM menu WHERE LABEL = 'PNCP - PORTAL NACIONAL DE CONTRATAÇÕES PÚBLICAS'), 0);

INSERT INTO MENU (ID, LABEL, CAMINHO, PAI_ID, ORDEM)
VALUES (HIBERNATE_SEQUENCE.nextval, 'ENTIDADE - PNCP',
        '/administrativo/licitacao/entidade-pncp/lista.xhtml',
        (SELECT ID FROM menu WHERE LABEL = 'PNCP - PORTAL NACIONAL DE CONTRATAÇÕES PÚBLICAS'), 10);
