 UPDATE BEM SET FORNECEDOR_ID = (SELECT LEV.FORNECEDOR_ID
                                    FROM LEVANTAMENTOBEMPATRIMONIAL LEV
                                  WHERE BEM.ID = LEV.BEM_ID
                                  )
 WHERE EXISTS(SELECT 1 FROM LEVANTAMENTOBEMPATRIMONIAL L WHERE L.BEM_ID = BEM.ID)
