INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'MATERIAIS > ALIMENTAÇÃO ESCOLAR > CARDÁPIO - SAÍDA MATERIAL>  EDITAR',
        '/administrativo/materiais/alimentacao-escolar/cardapio-saida-material/edita.xhtml', 0, 'MATERIAIS');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'MATERIAIS > ALIMENTAÇÃO ESCOLAR > CARDÁPIO - SAÍDA MATERIAL > VISUALIZAR',
        '/administrativo/materiais/alimentacao-escolar/cardapio-saida-material/visualizar.xhtml', 0, 'MATERIAIS');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);
;

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'MATERIAIS > ALIMENTAÇÃO ESCOLAR > CARDÁPIO - SAÍDA MATERIAL > LISTAR',
        '/administrativo/materiais/alimentacao-escolar/cardapio-saida-material/lista.xhtml', 0, 'MATERIAIS');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);

INSERT INTO menu (ID, LABEL, CAMINHO, PAI_ID, ORDEM, ICONE)
VALUES (HIBERNATE_SEQUENCE.nextval, 'CARDÁPIO - SAÍDA MATERIAL',
        '/administrativo/materiais/alimentacao-escolar/cardapio-saida-material/lista.xhtml',
        (select ID from menu where LABEL = 'ALIMENTAÇÃO ESCOLAR'), 40, null);
