CREATE OR REPLACE
TRIGGER AJUSTAKMVEICULOINSERT AFTER
INSERT ON KMPERCORRIDOVEICULO FOR EACH ROW DECLARE KMPERCORRIDOVEICULO_ID NUMBER;
  BEGIN
    UPDATE VEICULO SET KMPERCORRIDO_ID = :NEW.ID
    WHERE ID = :NEW.VEICULO_ID;
  END;
