INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'CONTRATOS > SOLICITAÇÃO DE EMPENHO ESTORNO > EDITAR',
        '/administrativo/contrato/solicitacao-empenho-estorno-execucao/edita.xhtml', 0, 'CONTRATOS');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 819727135);

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'CONTRATOS > SOLICITAÇÃO DE EMPENHO ESTORNO > VISUALIZAR',
        '/administrativo/contrato/solicitacao-empenho-estorno-execucao/visualizar.xhtml', 0, 'CONTRATOS');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 819727135);
;

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'CONTRATOS > SOLICITAÇÃO DE EMPENHO ESTORNO > LISTAR',
        '/administrativo/contrato/solicitacao-empenho-estorno-execucao/lista.xhtml', 0, 'CONTRATOS');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 819727135);


INSERT INTO menu
VALUES (HIBERNATE_SEQUENCE.nextval, 'SOLICITAÇÃO DE EMPENHO ESTORNO',
        '/administrativo/contrato/solicitacao-empenho-estorno-execucao/lista.xhtml',
        (select ID from menu where LABEL = 'CONTRATOS'),
        (select max(ORDEM) + 5 from menu where LABEL = 'CONTRATOS'), null);
