INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'CONTRATOS > ALTERAÇÃO ITEM CONTRATO > EDITAR',
        '/administrativo/contrato/alteracao-item-contrato/edita.xhtml', 0, 'CONTRATOS');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'CONTRATOS > ALTERAÇÃO ITEM CONTRATO > VISUALIZAR',
        '/administrativo/contrato/alteracao-item-contrato/visualizar.xhtml', 0, 'CONTRATOS');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);
;

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'CONTRATOS > ALTERAÇÃO ITEM CONTRATO > LISTAR',
        '/administrativo/contrato/alteracao-item-contrato/lista.xhtml', 0, 'CONTRATOS');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);


INSERT INTO menu
VALUES (HIBERNATE_SEQUENCE.nextval, 'ALTERAÇÃO ITEM CONTRATO',
        '/administrativo/contrato/alteracao-item-contrato/lista.xhtml',
        (select ID from menu where LABEL = 'CONTRATOS'),
        (select max(ORDEM) + 5 from menu where LABEL = 'CONTRATOS'), null);
