INSERT INTO RECURSOSISTEMA
VALUES (HIBERNATE_SEQUENCE.nextval, 'COMPRAS E LICITAÇÕES > EXECUÇÃO ATA REGISTRO DE PREÇOS > EDITA',
        '/administrativo/licitacao/execucao-ata/edita.xhtml', 0, 'LICITACAO');

INSERT INTO GRUPORECURSOSISTEMA
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);

INSERT INTO RECURSOSISTEMA
VALUES (HIBERNATE_SEQUENCE.nextval, 'COMPRAS E LICITAÇÕES > EXECUÇÃO ATA REGISTRO DE PREÇOS > VISUALIZA',
        '/administrativo/licitacao/execucao-ata/visualizar.xhtml', 0, 'LICITACAO');

INSERT INTO GRUPORECURSOSISTEMA
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);

INSERT INTO RECURSOSISTEMA
VALUES (HIBERNATE_SEQUENCE.nextval, 'COMPRAS E LICITAÇÕES > EXECUÇÃO ATA REGISTRO DE PREÇOS > LISTA',
        '/administrativo/licitacao/execucao-ata/lista.xhtml', 0, 'LICITACAO');

INSERT INTO GRUPORECURSOSISTEMA
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);

INSERT INTO menu
VALUES (HIBERNATE_SEQUENCE.nextval, 'EXECUÇÃO ATA REGISTRO DE PREÇOS',
        '/administrativo/licitacao/execucao-ata/lista.xhtml',
        (select ID from menu where LABEL = 'COMPRAS E LICITAÇÕES'), 480, null);
