UPDATE REQUISICAODECOMPRA rq SET rq.CRIADOPOR_ID = (
    SELECT u.PESSOAFISICA_ID FROM USUARIOSISTEMA u WHERE u.LOGIN = (
        SELECT r.USUARIO FROM REVISAOAUDITORIA r
                                  INNER JOIN REQUISICAODECOMPRA_AUD ra ON ra.REV = r.ID
        WHERE ra.id = rq.id
          AND ra.REVTYPE = 0)) where rq.CRIADOPOR_ID is null;
