alter table ITEMREQUISICAODECOMPRA add VALORDESCONTOUNITARIO_BK NUMBER(24,8);
alter table ITEMREQUISICAODECOMPRA_AUD add VALORDESCONTOUNITARIO_BK NUMBER(24,8);

update ITEMREQUISICAODECOMPRA set VALORDESCONTOUNITARIO_BK = VALORDESCONTOUNITARIO;
update ITEMREQUISICAODECOMPRA_aud set VALORDESCONTOUNITARIO_BK = VALORDESCONTOUNITARIO;

alter table ITEMREQUISICAODECOMPRA drop column VALORDESCONTOUNITARIO;
alter table ITEMREQUISICAODECOMPRA_aud drop column VALORDESCONTOUNITARIO;

alter table ITEMREQUISICAODECOMPRA add VALORDESCONTOUNITARIO NUMBER(24,8);
alter table ITEMREQUISICAODECOMPRA_AUD add VALORDESCONTOUNITARIO NUMBER(24,8);

update ITEMREQUISICAODECOMPRA set VALORDESCONTOUNITARIO = VALORDESCONTOUNITARIO_BK;
update ITEMREQUISICAODECOMPRA_aud set VALORDESCONTOUNITARIO = VALORDESCONTOUNITARIO_BK;

alter table ITEMREQUISICAODECOMPRA drop column VALORDESCONTOUNITARIO_BK;
alter table ITEMREQUISICAODECOMPRA_aud drop column VALORDESCONTOUNITARIO_BK;
