alter table ADITIVOCONTRATO add APOSTILAMENTOCONTRATO_ID numeric(20);
alter table MOVIMENTOADITIVOCONTRATO add MOVIMENTOASPOTILAMENTOCONT_ID numeric(20);

insert into ADITIVOCONTRATO (ID, CONTRATO_ID, NUMEROTERMO, DATAASSINATURA, JUSTIFICATIVA, DATAAPROVACAO,
                             DATADEFERIMENTO, DATALANCAMENTO, SITUACAO, NUMERO, EXERCICIO_ID, TIPOTERMO,
                             DETENTORDOCUMENTOLICITACAO_ID, APOSTILAMENTOCONTRATO_ID, TIPOALTERACAOCONTRATUAL)
select HIBERNATE_SEQUENCE.nextval,
       ap.CONTRATO_ID,
       ap.NUMEROTERMO,
       ap.DATAASSINATURA,
       ap.DESCRICAO,
       ap.DATAAPROVACAO,
       ap.DATADEFERIMENTO,
       ap.DATALANCAMENTO,
       ap.SITUACAO,
       ap.NUMEROAPOSTILAMENTO,
       ap.EXERCICIO_ID,
       case when ap.TRANSFERIRUNIDADE = 1 then 'ALTERACAO_CADASTRAL'
           when ap.TIPOTERMO = 'OUTRO' then 'NAO_APLICAVEL' else ap.TIPOTERMO end,
       ap.DETENTORDOCUMENTOLICITACAO_ID,
       ap.id,
       'APOSTILAMENTO'
from APOSTILAMENTOCONTRATO ap;

insert into MOVIMENTOADITIVOCONTRATO (ID, ADITIVOCONTRATO_ID, TIPO, FINALIDADE, TERMINOVIGENCIA, PERCENTUAL, VALOR,
                                      VALORSALDOATUAL, FONTEDESPESAORC_ID, INDICE, OPERACAO, UNIDADEORGANIZACIONAL_ID,
                                      MOVIMENTOASPOTILAMENTOCONT_ID)
select HIBERNATE_SEQUENCE.nextval,
       (select id from ADITIVOCONTRATO where APOSTILAMENTOCONTRATO_ID = mov.APOSTILAMENTOCONTRATO_ID),
       mov.TIPO,
       mov.FINALIDADE,
       mov.PERIODOCORRIGIDOFINAL,
       mov.PERCENTUAL,
       mov.VALOR,
       mov.VALORSALDOATUAL,
       mov.FONTEDESPESAORC_ID,
       mov.INDICE,
       case
           when apost.TRANSFERIRUNIDADE = 1 then 'TRANSFERENCIA_UNIDADE'
           else
               case when apost.TIPOTERMO = 'OUTRO' then 'NAO_APLICAVEL' else 'REAJUSTE_PRE_EXECUCAO' end
           end,
       apost.UNIDADEADMINISTRATIVA_ID,
       mov.id
from MOVIMENTOAPOSTILAMENTOCONT mov
         inner join apostilamentocontrato apost on apost.id = mov.APOSTILAMENTOCONTRATO_ID;


insert into MOVIMENTOADITIVOITEMCONT (ID, MOVIMENTOADITIVOCONTRATO_ID, ITEMCONTRATO_ID, QUANTIDADEAJUSTE, VALORAJUSTE,
                                      VALORTOTAL)

SELECT HIBERNATE_SEQUENCE.nextval,
       (select id
        from MOVIMENTOADITIVOCONTRATO
        where MOVIMENTOASPOTILAMENTOCONT_ID = mov.MOVIMENTOAPOSTILAMENTOCONT_ID),
       mov.ITEMCONTRATO_ID,
       mov.QUANTIDADEAJUSTE,
       mov.VALORAJUSTE,
       mov.VALORTOTAL
from MOVIMENTOAPOSTILAMITEMCONT mov;


insert into PUBLICACAOADITIVO (ID, ADITIVOCONTRATO_ID, DATAPUBLICACAO, VEICULODEPUBLICACAO_ID, NUMERO, PAGINA, OBSERVACAO)
select HIBERNATE_SEQUENCE.nextval,
       (select ad.id from ADITIVOCONTRATO ad where ad.APOSTILAMENTOCONTRATO_ID = pub.APOSTILAMENTOCONTRATO_ID),
       pub.DATAPUBLICACAO,
       pub.VEICULODEPUBLICACAO_ID,
       pub.NUMERO,
       pub.PAGINA,
       pub.OBSERVACAO
from PublicacaoApostilamento pub;


update MOVIMENTOITEMCONTRATO item
set item.IDMOVIMENTO = (select ad1.id
                        from ADITIVOCONTRATO ad1
                        where ad1.TIPOALTERACAOCONTRATUAL = 'APOSTILAMENTO'
                          and ad1.APOSTILAMENTOCONTRATO_ID = item.IDMOVIMENTO)
where item.IDMOVIMENTO in (select ad2.APOSTILAMENTOCONTRATO_ID
                           from ADITIVOCONTRATO ad2
                           where ad2.TIPOALTERACAOCONTRATUAL = 'APOSTILAMENTO')
  and item.ORIGEMMOVIMENTO = 'APOSTILAMENTO';


update EXECUCAOCONTRATOITEM item
set item.IDMOVIMENTOORIGEM = (select ad1.id
                              from ADITIVOCONTRATO ad1
                              where ad1.TIPOALTERACAOCONTRATUAL = 'APOSTILAMENTO'
                                and ad1.APOSTILAMENTOCONTRATO_ID = item.IDMOVIMENTOORIGEM)
where item.IDMOVIMENTOORIGEM in (select ad2.APOSTILAMENTOCONTRATO_ID
                                 from ADITIVOCONTRATO ad2
                                 where ad2.TIPOALTERACAOCONTRATUAL = 'APOSTILAMENTO')
  and item.ORIGEMEXECUCAOCONTRATO = 'APOSTILAMENTO';
