insert into MODELODOCTOOFICIAL (ID, TIPODOCTOOFICIAL_ID, VIGENCIAINICIAL, SEQUENCIA)
VALUES (HIBERNATE_SEQUENCE.nextval, (select tdo.id from TIPODOCTOOFICIAL tdo where tdo.CODIGO = 162 and tdo.MODULOTIPODOCTOOFICIAL = 'SOLICITACAO_MATERIAL'), sysdate, 1)
