INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'PATRIMÔNIO > PATRIMÔNIO MOBILIÁRIO > LEVANTAMENTO DE BEM MÓVEL > LEVANTAMENTO DE BEM MÓVEL - COLETA DADOS BCI > EDITAR',
        '/administrativo/patrimonio/lev-bem-imovel-coleta-dados/edita.xhtml', 0, 'PATRIMONIO');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'PATRIMÔNIO > PATRIMÔNIO MOBILIÁRIO > LEVANTAMENTO DE BEM MÓVEL > LEVANTAMENTO DE BEM MÓVEL - COLETA DADOS BCI > VISUALIZAR',
        '/administrativo/patrimonio/lev-bem-imovel-coleta-dados/visualizar.xhtml', 0, 'PATRIMONIO');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);
;

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'PATRIMÔNIO > PATRIMÔNIO MOBILIÁRIO > LEVANTAMENTO DE BEM MÓVEL > LEVANTAMENTO DE BEM MÓVEL - COLETA DADOS BCI > LISTAR',
        '/administrativo/patrimonio/lev-bem-imovel-coleta-dados/lista.xhtml', 0, 'PATRIMONIO');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);


INSERT INTO menu
VALUES (HIBERNATE_SEQUENCE.nextval, 'LEVANTAMENTO DE BEM MÓVEL - COLETA DADOS BCI',
        '/administrativo/patrimonio/lev-bem-imovel-coleta-dados/lista.xhtml',
        (select ID from menu where LABEL = 'LEVANTAMENTO DE BENS IMÓVEIS'),
        (select max(ORDEM) + 5 from menu where LABEL = 'LEVANTAMENTO DE BENS IMÓVEIS'), null);
