 UPDATE RESPONSAVELPATRIMONIO
   SET RESPONSAVELAUX_ID = (SELECT USU.PESSOAFISICA_ID
                              FROM RESPONSAVELPATRIMONIO RESP
                            INNER JOIN USUARIOSISTEMA USU ON USU.ID = RESP.RESPONSAVEL_ID
                            WHERE RESP.ID = RESPONSAVELPATRIMONIO.ID)
