insert into LANCEPREGAO (ID, RODADAPREGAO_ID, STATUSLANCEPREGAO, PROPOSTAFORNECEDOR_ID, VALOR,
                         JUSTIFICATIVACANCELAMENTO, PERCENTUALDESCONTO)
values (HIBERNATE_SEQUENCE.nextval, 10875325715, 'DECLINADO', 10875333808, 0, null, null);
