delete from AJUSTEPROCESSOCOMPRAITEM where AJUSTEPROCESSOCOMPRA_ID in (
    select id
    from AJUSTEPROCESSOCOMPRA
    where TIPOAJUSTE = 'SUBSTITUIR_OBJETO_COMPRA'
      and extract(year from DATALANCAMENTO) <= 2024);
delete
from AJUSTEPROCESSOCOMPRA
where TIPOAJUSTE = 'SUBSTITUIR_OBJETO_COMPRA'
  and extract(year from DATALANCAMENTO) <= 2024 ;
