INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'FEIRAS > ROMANERIO > EDITAR',
        '/administrativo/feiras/romaneio/edita.xhtml', 0, 'FEIRAS');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'FEIRAS > ROMANERIO > VISUALIZAR',
        '/administrativo/feiras/romaneio/visualizar.xhtml', 0, 'FEIRAS');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'FEIRAS > ROMANERIO > LISTAR',
        '/administrativo/feiras/romaneio/lista.xhtml', 0, 'FEIRAS');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);

insert into MENU (ID, LABEL, CAMINHO, PAI_ID, ORDEM, ICONE)
values (HIBERNATE_SEQUENCE.nextval, 'ROMANEIO', '/administrativo/feiras/romaneio/lista.xhtml', (select id from menu where LABEL = 'FEIRAS'), 15, null);
