INSERT INTO RECURSOSISTEMA
VALUES (HIBERNATE_SEQUENCE.nextval, 'ADMINISTRATIVO > LICITAÇÃO > ADITIVO DA ATA > VISUALIZAR',
        '/administrativo/licitacao/alteracao-contratual-ata/visualizar.xhtml', 0, 'LICITACAO');
INSERT INTO GRUPORECURSOSISTEMA
VALUES (HIBERNATE_SEQUENCE.currval, 173907291);

INSERT INTO RECURSOSISTEMA
VALUES (HIBERNATE_SEQUENCE.nextval, 'ADMINISTRATIVO > LICITAÇÃO > ADITIVO DA ATA > EDITA',
        '/administrativo/licitacao/alteracao-contratual-ata/edita.xhtml', 0, 'LICITACAO');
INSERT INTO GRUPORECURSOSISTEMA
VALUES (HIBERNATE_SEQUENCE.currval, 173907291);

INSERT INTO RECURSOSISTEMA
VALUES (HIBERNATE_SEQUENCE.nextval, 'ADMINISTRATIVO > LICITAÇÃO > ADITIVO DA ATA > LISTA',
        '/administrativo/licitacao/alteracao-contratual-ata/lista-aditivo.xhtml', 0, 'LICITACAO');
INSERT INTO GRUPORECURSOSISTEMA
VALUES (HIBERNATE_SEQUENCE.currval, 173907291);

INSERT INTO MENU (ID, LABEL, CAMINHO, PAI_ID, ORDEM)
VALUES (HIBERNATE_SEQUENCE.nextval, 'ADITIVO DE ATA', '/administrativo/licitacao/alteracao-contratual-ata/lista-aditivo.xhtml',
        (SELECT ID FROM menu WHERE LABEL = 'ATA DE REGISTRO DE PREÇO INTERNA - ARPI'), 20);


INSERT INTO RECURSOSISTEMA
VALUES (HIBERNATE_SEQUENCE.nextval, 'ADMINISTRATIVO > LICITAÇÃO > APOSTILAMENTO DA ATA > VISUALIZAR',
        '/administrativo/licitacao/alteracao-contratual-ata/visualizar.xhtml', 0, 'LICITACAO');
INSERT INTO GRUPORECURSOSISTEMA
VALUES (HIBERNATE_SEQUENCE.currval, 173907291);

INSERT INTO RECURSOSISTEMA
VALUES (HIBERNATE_SEQUENCE.nextval, 'ADMINISTRATIVO > LICITAÇÃO > APOSTILAMENTO DA ATA > EDITA',
        '/administrativo/licitacao/alteracao-contratual-ata/edita.xhtml', 0, 'LICITACAO');
INSERT INTO GRUPORECURSOSISTEMA
VALUES (HIBERNATE_SEQUENCE.currval, 173907291);

INSERT INTO RECURSOSISTEMA
VALUES (HIBERNATE_SEQUENCE.nextval, 'ADMINISTRATIVO > LICITAÇÃO > APOSTILAMENTO DA ATA > LISTA',
        '/administrativo/licitacao/alteracao-contratual-ata/lista-apostilamento.xhtml', 0, 'LICITACAO');
INSERT INTO GRUPORECURSOSISTEMA
VALUES (HIBERNATE_SEQUENCE.currval, 173907291);

INSERT INTO MENU (ID, LABEL, CAMINHO, PAI_ID, ORDEM)
VALUES (HIBERNATE_SEQUENCE.nextval, 'APOSTILAMENTO DE ATA', '/administrativo/licitacao/alteracao-contratual-ata/lista-apostilamento.xhtml',
        (SELECT ID FROM menu WHERE LABEL = 'ATA DE REGISTRO DE PREÇO INTERNA - ARPI'), 25);
