INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'PATRIMÔNIO > PATRIMÔNIO MOBILIÁRIO > EFETIVAÇÃO DE TRANSFERÊNCIA GRUPO BEM MÓVEL > EDITAR',
        '/administrativo/patrimonio/efetivacao-transf-grupo-bem/edita.xhtml', 0, 'PATRIMONIO');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'PATRIMÔNIO > PATRIMÔNIO MOBILIÁRIO > EFETIVAÇÃO DE TRANSFERÊNCIA GRUPO BEM MÓVEL > VISUALIZAR',
        '/administrativo/patrimonio/efetivacao-transf-grupo-bem/visualizar.xhtml', 0, 'PATRIMONIO');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);


INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'PATRIMÔNIO > PATRIMÔNIO MOBILIÁRIO > EFETIVAÇÃO DE TRANSFERÊNCIA GRUPO BEM MÓVEL > LISTAR',
        '/administrativo/patrimonio/efetivacao-transf-grupo-bem/lista.xhtml', 0, 'PATRIMONIO');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);


INSERT INTO menu
VALUES (HIBERNATE_SEQUENCE.nextval, 'EFETIVAÇÃO DE TRANSFERÊNCIA GRUPO BEM MÓVEL',
        '/administrativo/patrimonio/efetivacao-transf-grupo-bem/lista.xhtml',
        (select ID from menu where LABEL = 'PATRIMÔNIO MOBILIÁRIO'),
        (select max(ORDEM) + 5 from menu where LABEL = 'PATRIMÔNIO MOBILIÁRIO'), null);
