INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES(hibernate_sequence.nextval, 'LICITAÇÕES > OBJETO DE COMPRA > DERIVAÇÃO OBJETO DE COMPRA > EDITAR', '/administrativo/licitacao/derivacao-objeto-compra/edita.xhtml',
       0, 'LICITACAO');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 173907291);

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES(hibernate_sequence.nextval, 'LICITAÇÕES > OBJETO DE COMPRA > DERIVAÇÃO OBJETO DE COMPRA > VISUALIZAR', '/administrativo/licitacao/derivacao-objeto-compra/visualizar.xhtml',
       0, 'LICITACAO');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 173907291);

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES(hibernate_sequence.nextval, 'LICITAÇÕES > OBJETO DE COMPRA > DERIVAÇÃO OBJETO DE COMPRA > LISTAR', '/administrativo/licitacao/derivacao-objeto-compra/lista.xhtml',
       0, 'LICITACAO');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 173907291);

INSERT INTO MENU (ID, LABEL, CAMINHO, PAI_ID, ORDEM)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'DERIVAÇÃO OBJETO DE COMPRA',
        '/administrativo/licitacao/derivacao-objeto-compra/lista.xhtml',
        (SELECT ID FROM MENU WHERE LABEL = 'OBJETO DE COMPRA' AND CAMINHO IS NULL), 20);
