INSERT INTO CONFIGURACAODTERELATORIO (ID, SECRETARIA, DEPARTAMENTO, ENDERECO, ARQUIVOBRASAO_ID)
SELECT HIBERNATE_SEQUENCE.NEXTVAL, 'Secretaria Municipal de Finanças',
'Departamento de Tributação', 'Rua Rui Barbosa, 285 – Centro - Rio Branco/AC',	892609519 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM CONFIGURACAODTERELATORIO);

INSERT INTO CONFIGURACAODTE (ID, CIDADE_ID, CONFIGURACAODTERELATORIO_ID)
SELECT HIBERNATE_SEQUENCE.NEXTVAL, 6192053, (SELECT ID FROM CONFIGURACAODTERELATORIO)  FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM CONFIGURACAODTE);

INSERT INTO CONFIGURACAODTEPARAMETROS (ID, CONFIGURACAO_ID, TIPOPARAMETRO, VALOR)
SELECT HIBERNATE_SEQUENCE.NEXTVAL, (SELECT ID FROM CONFIGURACAODTE), 'URL_APLICACAO', 'http://localhost:8686' FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM CONFIGURACAODTEPARAMETROS WHERE TIPOPARAMETRO = 'URL_APLICACAO');

INSERT INTO USERDTECADASTROECONOMICO (ID, USUARIOWEB_ID, CADASTROECONOMICO_ID, SITUACAO)
SELECT HIBERNATE_SEQUENCE.NEXTVAL, UW.ID, CE.ID, 'APROVADO' FROM USUARIOWEB UW
INNER JOIN PESSOAJURIDICA PJ ON PJ.ID = UW.PESSOA_ID
INNER JOIN CADASTROECONOMICO CE ON CE.PESSOA_ID = PJ.ID
WHERE UW.ACTIVATED = 1
 AND NOT EXISTS(SELECT 1 FROM USERDTECADASTROECONOMICO REL WHERE REL.USUARIOWEB_ID = UW.ID  AND REL.CADASTROECONOMICO_ID = CE.ID);
