DECLARE
texto CLOB := '<div class="post-content"><hr>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-876-2024-–-RBTRANS-–-Ficam-autorizados-os-veículos-modelo-caminhonete-Pick-up-Leve-a-operarem-na-categoria-Táxi.pdf" target="_blank">DECRETO Nº 876 DE 04 DE JULHO DE 2024</a></strong></p>
<p style="text-align: justify;">“Ficam autorizados os veículos, modelo caminhonete cabine dupla /Pick-up Leve a operarem na categoria Táxi Convencional, no Sistema de Transporte de Passageiros de Rio Branco.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/RBTRANS-PORTARIA-Nº-128-2024-DOE.pdf" target="_blank">RBTRANS – PORTARIA Nº 128/2024</a></strong>&nbsp;– DOE</p>
<p style="text-align: justify;">“ESTABELECER critérios em vistoria para substituição de veículos tipo automóvel, que já operaram na categoria Táxi Convencional, no Sistema de Transporte de Passageiros de Rio Branco, nos termos da Lei Municipal n. 343 de 26/05/1982 para o modelo de veículo tipo caminhonete cabine dupla/Pick-up Leve a operarem na categoria Táxi Convencional neste Município de Rio Branco.”</p>
<hr>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-COMPLEMENTAR-Nº-267-DE-18-DE-DEZEMBRO-DE-2023-Institui-o-Programa-Domingos-da-Dignidade-no-Sistema-de-Transporte-Coletivo-Público.pdf" target="_blank">LEI COMPLEMENTAR Nº 267 DE 18 DE DEZEMBRO DE 2023</a></strong></p>
<p style="text-align: justify;">“Institui o Programa Domingos da Dignidade no Sistema de Transporte Coletivo Público de Passageiros do Município de Rio Branco, nos dias que menciona e dá outras providências”.</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-COMPLEMENTAR-Nº-260-DE-21.11.2023-Altera-a-Lei-complementar-nº-164-de-1°-de-julho-de-2022-Subsídio-dos-transportes.pdf" target="_blank">LEI COMPLEMENTAR Nº 260 DE 21 DE NOVEMBRO DE 2023</a></strong></p>
<p style="text-align: justify;">“Altera a Lei Complementar n° 164, de 1° julho de 2022”.</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-1150-2023-Torna-sem-efeito-o-Dec.-nº-1922-2022-Restituição-do-Cartão-Vale-Transporte-Meu-Cartão-e-Cartão-do-Estudante.pdf" target="_blank">DECRETO Nº 1.150 DE 12 DE JULHO DE 2023</a></strong></p>
<p style="text-align: justify;">Tornar sem efeitos o Decreto nº 1.922, de 29 de dezembro de 2022, publicado no Diário Oficial do Estado do Acre nº 13.443, de 02 de janeiro de 2023</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-MUNICIPAL-Nº-2.461-DE-27.06.2023-Dispõe-sobre-a-Campanha-“Assédio-sexual-no-ônibus-é-crime”.pdf" target="_blank">LEI MUNICIPAL Nº 2.461, DE 27 DE JUNHO DE 2023</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre a Campanha “Importunação Sexual no Ônibus é Crime”, e dá outras providências.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-MUNICIPAL-Nº-2.460-DE-27.06.2023-Dispõe-sobre-o-desembarque-de-mulheres-e-idosos-usuários-do-Sistema-de-Transporte-Coletivo.pdf" target="_blank">LEI MUNICIPAL Nº 2.460, DE 27 DE JUNHO DE 2023</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre o desembarque de mulheres usuárias do Sistema de Transporte Coletivo, e dá outras providências.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-1.005-DE-26-DE-JUNHO-DE-2023-DOE.pdf" target="_blank">DECRETO N.º 1.005 DE 26 DE JUNHO DE 2023</a></strong>&nbsp;– DOE</p>
<p style="text-align: justify;">“Autoriza o Superintendente Municipal de Transporte e Trânsito a proceder com a abertura de Licitação da concessão para a prestação de serviço público de transporte coletivo de passageiros por ônibus no Município de Rio Branco.”</p>
<hr>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-1922-2022-Utilização-de-Cartão-eletrônico-no-Sistema-Integrado-de-Transporte-Urbano.pdf" target="_blank">DECRETO Nº 1.922 DE 29 DE DEZEMBRO DE 2022</a>&nbsp;</strong><span style="color: #ff0000;">(Tornado sem Efeito pelo Decreto nº 1.150 de 12 de julho de 2023)</span></p>
<p style="text-align: justify;">“Dispõe sobre a utilização de cartão eletrônico no Sistema Integrado de Transporte Urbano no Município de Rio Branco”.</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/RBTRANS-PORTARIA-Nº-248-2022-Serviço-de-Transporte-Privado-por-Aplicativo-DOE-REP.pdf" target="_blank">PORTARIA RBTRANS Nº 248/2022</a></strong>&nbsp;– DOE</p>
<p style="text-align: justify;">“Estabelecer que o serviço de transporte remunerado privado de passageiros por meio de aplicativos será realizado somente por motoristas que estiverem cadastrados no Município de Rio Branco, conforme Art. 14 e inciso III do art. 16 da Lei 2.294/2018.”</p>
<p><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/RBTRANS-PORTARIA-Nº-187-2022-DOE.pdf" target="_blank">PORTARIA RBTRANS Nº 187/2022</a></strong>&nbsp;– DOE</p>
<p style="text-align: justify;">“Regulamentar o serviço de táxi-especial e convencional nos terminais Rodoviária Internacional de Rio Branco Jessé Santiago e Aeroporto Internacional de Rio Branco Plácido de Castro.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/RBTRANS-PORTARIA-Nº-136-2022-DOE.pdf" target="_blank">RBTRANS-PORTARIA Nº 136/2022</a></strong>&nbsp;– DOE</p>
<p style="text-align: justify;">“Regulamentar o Serviço de Táxi-lotação no Município de Rio Branco, para o transporte coletivo de passageiros entre pontos de embarque e desembarque e itinerários pré-fixados”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-COMPLEMENTAR-Nº-164-DE-01.07.2022-Criação-de-subsídio-tarifário-temporário-ao-Transporte-Público-Coletivo-Urbano.pdf" target="_blank">LEI COMPLEMENTAR Nº 164 DE 1º DE JULHO DE 2022</a>&nbsp;</strong><span style="color: #ff0000;">(Alterada pela Lei Complementar nº 260 de 21 de novembro de 2023)</span></p>
<p style="text-align: justify;">“Dispõe sobre a criação de subsídio tarifário temporário ao Transporte Público Coletivo Urbano, no valor R$ 1,45 (um real e quarenta cinco centavos) por passageiros transportados, objetivando a manutenção do valor da tarifa 3,50 (três reais e cinquenta centavos) no Sistema Integrado de Transporte Urbano de Rio Branco – SITURB, bem como adequação da remuneração tarifaria aos custos reais do serviço e dá outras providências”.</p>
<hr>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-COMPLEMENTAR-Nº-118-DE-13.10.2021-Subsídio-Tarifário-Temporário-ao-Transporte-Público-Coletivo-Urbano.pdf" target="_blank">LEI COMPLEMENTAR Nº 118 DE 13 DE OUTUBRO DE 2021</a></strong></p>
<p style="text-align: justify;">“Instituir subsídio tarifário temporário ao Transporte Público Coletivo Urbano, com o objetivo de custear até 100% (cem por cento) do valor da tarifa pública, correspondente às gratuidades elencadas nos incisos I a VII do artigo 1° da Lei Municipal n° 1.726/2008”.</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/RBTRANS-PORTARIA-RBTRANS-Nº-212-2021-DOE.pdf" target="_blank">RBTRANS-PORTARIA Nº 212/2021</a></strong>&nbsp;– DOE</p>
<p style="text-align: justify;">“Tornar obrigatório que todos os veículos novos apresentados para registro junto à RBTRANS na categoria taxi e mototáxi sejam na cor branca.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-1438-2021-Alteração-da-Tarifa-no-valor-de-R-350..pdf" target="_blank">DECRETO Nº 1.438 DE 18 DE OUTUBRO DE 2021</a></strong></p>
<p style="text-align: justify;">“Fica estabelecida a tarifa no valor de R$ 3,50 (três reais e cinquenta&nbsp;centavos), em todos os veículos que operam no Sistema Integrado de Transporte Urbano de Rio Branco – SITURB e Terminais Urbanos, conforme a Lei Complementar nº 118 de 13 de outubro de 2021.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/Lei-Nº-2.400-de-15-de-abril-de-2021-Dispões-sobre-a-revogação-do-art.-114-da-Lei-Nº-2.310-2018-Mototáxi-e-Motofrete.pdf" target="_blank">LEI Nº 2.400 DE 15 DE ABRIL DE 2021</a></strong></p>
<p style="text-align: justify;">“Revoga o art. 114 da Lei Municipal n° 2.310, de 18 dezembro de 2018.”</p>
<hr>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-201-2020-Altera-o-Decreto-n°-585-2018-Tarifa-Transporte-Urbano1.pdf" target="_blank">DECRETO Nº 201 DE 19 DE MARÇO DE 2020</a></strong></p>
<p style="text-align: justify;">“Fica estabelecida a tarifa de R$ 4,00 (quatro reais) em todos os veículos que operam no Sistema Integrado de Transporte Urbano de Rio Branco – SITURB e Terminais Urbanos para os usuários não estudantes, e de R$ 2,00 (dois reais) para os usuários estudantes, cujo benefício e condições de utilização estão previstos na Lei Municipal nº 1.726, de 18 de dezembro de 2008.”</p>
<hr>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-Nº-2.312-DE-26-de-dezembro-de-2018-Institui-o-programa-de-padronização-dos-abrigos-de-pontos-de-ônibus-táxi-e-moto-taxi.pdf" target="_blank">LEI Nº 2.312 DE 26 DE DEZEMBRO DE 2018</a></strong></p>
<p style="text-align: justify;">“Institui o programa de&nbsp;padronização dos abrigos de pontos de ônibus, táxi e moto-táxi no Município de Rio Branco.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-Nº-2.310-DE-18-de-18-de-dezembro-de-2018-Dispõe-sobre-o-serviço-de-transporte-individual-de-passageiros-e-pequenas-cargas-em-veiculo-automotor.pdf" target="_blank">LEI Nº 2.310 DE 18 DE DEZEMBRO DE 2018</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre o serviço de transporte individual de passageiros e pequenas cargas em veículo automotor tipo motocicleta, denominado mototáxi e motofrete.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2018-LEI-Nº-2.294-de-30-de-julho-de-2018-Prestação-do-Serviço-de-Transporte-Remunerado-Privado-Individual-de-passageiros.pdf" target="_blank">LEI Nº 2.294 DE 30 DE JULHO DE 2018</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre a regulamentação da prestação do serviço de transporte remunerado privado individual de passageiros por meio de aplicativo ou outra tecnologia de comunicação em rede, no Município de Rio Branco e dá outras providências.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-658-2018-Reajuste-da-Tarifa-do-Transporte-Coletivo-por-Onibus-2018.pdf" target="_blank">DECRETO Nº 658 DE 05 DE JULHO DE 2018</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre o reajuste da Tarifa do Transporte Coletivo por Ônibus.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-595-2018-Revoga-o-Decreto-585-2018-Suspensão-Tarifa-2018.pdf" target="_blank">DECRETO Nº 595 DE 13 DE JUNHO DE 2018</a></strong></p>
<p style="text-align: justify;">“Revoga o Decreto nº 585, de 08 de junho&nbsp;de 2018 e determina providências.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-585-2018-Reajuste-da-Tarifa-do-Transporte-Coletivo-por-Ônibus.pdf" target="_blank">DECRETO Nº 585 DE 08 DE JUNHO DE 2018</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre o reajuste da Tarifa do Transporte Coletivo por Ônibus.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-Nº-2.281-de-15-de-março-de-2018-Transporte-coletivo-municipal-com-deficiência-e-mobilidade-reduzida.pdf" target="_blank">LEI Nº 2.281 DE 15 DE MARÇO DE 2018</a></strong></p>
<p style="text-align: justify;">“Assegura aos usuários do transporte coletivo municipal com deficiência e mobilidade reduzida o direito de desembarcar entre as paradas obrigatórias de ônibus e de embarcar nas paradas obrigatórias de ônibus exclusivas para desembarque e dá outras providências”.</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2018-LEI-Nº-2.276-de-10-de-janeiro-de-2018-Preferência-de-idosos-grávidas-ou-com-criança-de-colo-deficiência-ou-mobilidade-reduzida-nos-assentos-de-tranporte.pdf" target="_blank">LEI Nº 2.276 DE 10 DE JANEIRO DE 2018</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre a preferência de idosos, mulheres grávidas ou com criança de colo e pessoas com deficiência ou mobilidade reduzida nos assentos de transporte coletivo.”</p>
<hr>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-2163-2017-Aplicação-de-Bandeira-I-mototaxi.pdf" target="_blank">DECRETO N.º 2.163 DE 19 DE DEZEMBRO DE 2017</a></strong></p>
<p style="text-align: justify;">“FICA MANTIDA a aplicação da Bandeira I, na Tarifa de&nbsp;mototáxi em vigência, em todos os horários, durante todo o mês de dezembro de 2017, no Município de Rio Branco.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-2081-2017-Taxi-Aplicação-de-Bandeira-I.doc">DECRETO N.º 2.081 DE 04 DE DEZEMBRO DE 2017</a></strong></p>
<p style="text-align: justify;">“Fica mantida&nbsp;a aplicação da Bandeira I, na Tarifa de Táxi em vigência, em todos os horários, durante todo o mês de dezembro de 2017, no Município de Rio Branco.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-1400-2017-Tarifas-para-o-transporte-de-passageiros-de-moto-táxi.pdf" target="_blank">DECRETO N.º 1.400 DE 13 DE JUNHO DE 2017</a></strong></p>
<p style="text-align: justify;">“Ficam definidos os seguintes valores das tarifas&nbsp;estabelecidas para o transporte de passageiros de mototáxi, que serão aferidos através do “mototaxímetro”.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-Nº-2.226-de-14-de-março-de-2017-Reserva-de-vagas-em-estacionamento-de-Shopping-Centers-para-gestantes-e-crianças-de-colo.pdf" target="_blank">LEI Nº2.226, DE 14 DE MARÇO DE 2017</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre a reserva de vagas em estacionamentos de Shopping Centers, Centros Comerciais e Supermercados para gestantes e pessoas com crianças de colo com<br>
até 02 anos, no âmbito do Município de Rio Branco”.</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2017-DECRETO-Nº-660-2017-Decreto-Reajuste-da-Tarifa-do-Transporte-Coletivo-2017.pdf" target="_blank">DECRETO Nº 660 DE 22 DE FEVEREIRO DE 2017</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre o reajuste da Tarifa do Transporte Coletivo por Ônibus.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-Nº-2.224-de-22-de-fevereiro-de-2017-Altera-a-Lei-Municipal-nº-1.964-2013-Passagens-de-ônibus.pdf" target="_blank">LEI Nº 2.224 DE 22 DE FEVEREIRO DE 2017</a></strong></p>
<p style="text-align: justify;">“Altera a Lei Municipal nº 1.964, de 26 de março de 2013.”</p>
<hr>';
    complementoTexto CLOB := '<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-Nº-2.184-de-04-de-Maio-de-2016-Desembarque-de-pessoas-do-sexo-feminino-idosas-e-deficientes-em-periodo-noturno.pdf" target="_blank">LEI Nº 2.184 DE 04 DE MAIO DE 2016</a></strong></p>
<p style="text-align: justify;">“Estabelece benefício para o desembarque de pessoas do sexo feminino, idosas e deficientes em período noturno, no transporte coletivo urbano no Município de Rio Branco.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-Nº-2.169-de-09-de-Março-de-2016-Proibição-de-abastecimento-de-veículos-após-o-travamento-automático-da-bomba..pdf" target="_blank">LEI Nº 2.169 DE 09 DE MARÇO DE 2016</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre a proibição de abastecimento de veículos após o travamento automático da bomba de segurança nos postos de combustível do município.”</p>
<hr>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-Nº-2.151-de-18-de-Dezembo-de-2015-Proibição-do-uso-de-placas-informativas-em-estacionamentos..pdf" target="_blank">LEI Nº 2.151 DE 18 DE DEZEMBRO DE 2015</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre a proibição do uso de placas informativas, impressão em bilhetes ou cupons, em estacionamentos e/ou similares com os seguintes dizeres: “Não nos responsabilizamos por danos materiais e/ou objetos deixados no interior do veículo” e dá outras providências.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-1315-2015-Dispõe-sobre-a-Tarifa-do-Transporte-Coletivo-por-Ônibus.pdf" target="_blank">DECRETO Nº 1.315 DE 11 DE DEZEMBRO DE 2015</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre a Tarifa do Transporte Coletivo por Ônibus.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-Nº-2.135-de-24-de-Setembro-de-2015-Dispõe-sobre-serviços-de-tranposrte-de-pequenas-cargas-por-motocicletas.pdf" target="_blank">LEI Nº 2.135 DE 24 DE SETEMBRO DE 2015</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre serviços de transporte de pequenas cargas, mediante a utilização de motocicletas, motonetas ou triciclo de cargas, denominado moto-frete, no Município de Rio Branco e dá outras providências.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-Nº-2.129-de-17-de-setembro-de-2015-Serviço-de-frete-de-cargas-no-Município-de-Rio-Branco.pdf" target="_blank">LEI Nº 2.129 DE 17 DE SETEMBRO DE 2015</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre serviço de frete de cargas no Município de Rio Branco e dá outras providências”.</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-467-DE-MAIO-DE-2015.pdf" target="_blank">DECRETO Nº 467 DE MAIO DE 2015</a></strong></p>
<p style="text-align: justify;">“Ficam definidos os valores de tarifas estabelecidas para o transporte de passageiros de mototáxi que se utilizam deste tipo de prestação de serviço”.</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-357-DE-13-DE-ABRIL-DE-2015.pdf" target="_blank">DECRETO Nº 357 DE 13 DE ABRIL DE 2015</a></strong></p>
<p style="text-align: justify;">“Ficam definidos os valores de tarifas estabelecidas para o transporte de passageiros de taxi”.</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-Nº-2.104-DE-12-DE-JANEIRO-DE-2015.pdf" target="_blank">LEI Nº 2.104 DE 12 DE JANEIRO DE 2015</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre o fornecimento de troco nos ônibus a serviço do Sistema de Transporte Coletivo Urbano de Rio Branco (SITURB).”</p>
<hr>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-1.401-DE-01-DE-DEZEMBRO-DE-2014.pdf" target="_blank">DECRETO Nº 1.401 DE 01 DE DEZEMBRO DE 2014</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre o reajuste da Tarifa do Transporte Coletivo por Ônibus.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-Nº-2.057-DE-16-DE-JUNHO-DE-2014.pdf" target="_blank">LEI Nº 2.057 DE 16 DE JUNHO DE 2014</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre a atividade econômica que consiste no transporte clandestino ou irregular de passageiros e cargas no Município de Rio Branco.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-Nº-2.056-DE-13.04.2014-Altera-as-Leis-dos-Mototaxitas.pdf" target="_blank">LEI Nº 2.056 DE 13 DE JUNHO DE 2014</a></strong></p>
<p style="text-align: justify;">“Altera a Lei nº 1.538, de 18 de julho de 2005, modificada pelas Leis nº 1.605, de 26 de setembro de 2006; 1.819, de 19 de outubro de 2010; 1.824, de 31 de dezembro de 2010 e 1.956, de 28 de dezembro de 2012.”</p>
<hr>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-Nº-2.002-DE-16-DE-SETEMBRO-DE-2013.pdf" target="_blank">LEI Nº 2.002 DE 16 DE SETEMBRO DE 2013</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre sinalização de caçambas estacionárias em vias e logradouros públicos no Município de Rio Branco e dá outras providências.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2013-DECRETO-Nº-1830-2013-Altera-o-Anexo-Unico-do-Decreto-1662-2013-Pontos-de-táxis-intermunicipais.pdf" target="_blank">DECRETO Nº 1.830 DE 03 DE SETEMBRO DE 2013</a></strong></p>
<p style="text-align: justify;">“Altera o Decreto Municipal nº 1.662, de 25 de julho de 2013.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/Decreto-Nº-1662-de-25.07.2013-Regulamentação-de-pontos-intermunicipais-de-táxis.pdf" target="_blank">DECRETO Nº 1.662 DE 25 DE JULHO DE 2013</a></strong></p>
<p style="text-align: justify;">“Estabelecer como pontos de parada e estacionamento para operações de embarque e desembarque de passageiros e cargas para veículos registrados na categoria aluguel de outros municípios, na forma de Anexo Único, que passa a fazer parte integrante deste Decreto”.</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2013-DECRETO-Nº-1659-2013-Altera-o-Decretp-Nº-3.926-2012-Prazo-de-carência-aos-concessionários-da-nova-rodoviária.pdf" target="_blank">DECRETO Nº 1.659 DE 24 DE JULHO DE 2013</a></strong></p>
<p style="text-align: justify;">“Altera o Decreto nº 3.926 de 31 de Agosto de 2012.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-Nº-1.975-DE-07-DE-MAIO-DE-2013.pdf" target="_blank">LEI Nº 1.975 DE 07 DE MAIO DE 2013</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre serviço de frete de passageiros e cargas no município de Rio Branco e dá outras providências”.</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-Nº-1.964-DE-26-DE-MARÇO-DE-2013.pdf" target="_blank">LEI Nº 1.964 DE 26 DE MARÇO DE 2013</a></strong></p>
<p style="text-align: justify;">“Autoriza o Poder Executivo a subvencionar até 20% (vinte por cento) do valor da passagem de ônibus dos estudantes e institui o regime especial de parcelamento para as empresas de transporte coletivo”.</p>
<hr>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-Nº-1.956-de-28.12.2012-Altera-a-Lei-nº-1.538-2005-MOTO-TAXI.pdf" target="_blank">LEI Nº 1.956 DE 28 DE DEZEMBRO DE 2012</a></strong></p>
<p style="text-align: justify;">“Altera as alíneas “a” e “b” e acrescenta a alínea “f” ao inciso “v”, acrescenta o inciso VI e VII, acrescenta os parágrafos 1º, 2º e 3º ao artigo 7º; altera o parágrafo 7º e revoga os parágrafos, 9º 10 e 11 do artigo 14; altera o inciso I do artigo 15; altera o artigo 17; revoga o artigo 24; altera o § 4º do artigo 32; acrescenta o § 3º ao artigo 36; altera o inciso XX, do artigo 41; acrescenta o inciso X e XI ao artigo 54; altera o inciso IV do artigo 55; altera o artigo 141 e revoga os artigos 79, 81, 82, 85 e 154, todos da Lei nº 1.538, de 18 de julho de 2005, e dá outras providências”.</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-Nº-1.918-de-05.07.2012-DISPÕE-SOBRE-FIXAÇÃO-DE-PLACA-INFORMATIVA-NO-INTERIOR-DOS-TRANSPORTES-COLETIVOS.pdf" target="_blank">LEI Nº 1.918 DE 05 DE JULHO DE 2012</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre a fixação de placa informativa no interior dos transportes coletivos do Município de Rio Branco-Acre”.</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/Decreto-Nº-3302-de-28.02.2012-Fixa-as-Tarifas-do-Serviço-Público-cobradas-pela-Concessionária-no-Terminal-Rodoviário.pdf" target="_blank">DECRETO N.º 3.302 DE 28 DE FEVEREIRO DE 2012</a></strong></p>
<p style="text-align: justify;">“Fixa as Tarifas do Serviço Público concedido a serem cobradas pela Concessionária no Terminal Rodoviário do Município de Rio Branco”.</p>
<hr>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-Nº-1.866-de-30.11.2011-ISENÇÃO-DA-TAXA-DE-ANUNCIO-TÁXI.pdf" target="_blank">LEI Nº 1.866 DE 30 DE NOVEMBRO DE 2011</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre a isenção da taxa de fiscalização de anúncios para os contribuintes que veicularem gratuitamente propaganda institucional nos veículos de transporte individual de passageiros, tipo táxi, pelo período de 02 (dois) meses.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-Nº-1.865-de-30.11.2011-PUBLICIDADE-E-PROPAGANDA-NOS-TÁXIS.pdf" target="_blank">LEI Nº 1.865 DE 30 DE NOVEMBRO DE 2011</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre a veiculação de publicidade e propaganda através dos veículos de transporte público individual de passageiros, do tipo táxi, no Município de Rio Branco.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-Nº-1.854-de-09.08.2011-Altera-a-Lei-nº-1.726-18.12.2008-Acessibilidade-de-transporte-publico.pdf" target="_blank">LEI Nº 1.854 DE 09 DE AGOSTO DE 2011</a></strong></p>
<p style="text-align: justify;">“Modifica os incisos e Parágrafo Único do Art. 1º, §2º do art. 2º e § 3º do art. 7º, da Lei nº 1.726 de 18 de dezembro de 2008, que trata da acessibilidade do transporte público coletivo no Município de Rio Branco e dá outras providências”.</p>
<p style="text-align: justify;"><strong><a href="/lai/wp-content/uploads/images/ARQUIVOS/202_RBTRANS/Lei%20Municipal%20nº%201.840%20de%2018.05.2011%20-%20Revoga%20o%20§%2010,%20do%20art.%202º,%20da%20Lei%20n.º%201.824.pdf" target="_blank">LEI N° 1.840 DE 18 DE MAIO DE 2011</a></strong></p>
<p style="text-align: justify;">“Revoga o § 10, do art. 2º, da Lei n.º 1.824,&nbsp;de 31 de dezembro de 2010”.</p>
<p style="text-align: justify;"><strong><a href="/lai/wp-content/uploads/images/ARQUIVOS/202_RBTRANS/Decreto%20Municipal%20n°%202383%20de%2013.04.2011%20-%20Definição%20dos%20valores%20de%20tarifas%20estabelecidas%20para%20o%20transporte%20de%20passageiros%20de%20taxi.pdf" target="_blank">DECRETO Nº 2383 DE 13 DE ABRIL DE 2011</a></strong></p>
<p style="text-align: justify;">“Ficam definidos os seguintes valores de tarifas estabelecidas para o transporte de passageiros de taxi que se utilizam deste tipo de prestação de serviço”.</p>
<p style="text-align: justify;"><strong><a href="/lai/wp-content/uploads/images/ARQUIVOS/202_RBTRANS/Decreto%20Municipal%20n°%202216%20de%2017.02.2011%20-%20Estabelece%20a%20tarifa%20para%20o%20serviço%20de%20moto-táxi%20conforme%20art.%2028%20da%20LM%20n.º%201.538.2005.pdf" target="_blank">DECRETO Nº 2216 DE 17 DE FEVEREIRO DE 2011</a></strong></p>
<p style="text-align: justify;">“Estabelece a tarifa para o serviço de moto-táxi conforme dispõe o artigo 28 da Lei Municipal n.º 1.538/2005.”</p>
<p style="text-align: justify;"><strong><a href="/lai/wp-content/uploads/images/ARQUIVOS/202_RBTRANS/Lei%20Municipal%20nº%201.828%20de%2010.02.2011%20-%20Redução%20das%20Passagens%20de%20Onibus.pdf" target="_blank">LEI MUNICIPAL Nº 1.828 DE 10 DE FEVEREIRO DE 2011</a></strong></p>
<p style="text-align: justify;">“Reduzir o valor da passagem de&nbsp;ônibus coletivo para R$ 1,00 (um&nbsp;real), nos domingos com o&nbsp;objetivo de estimular a visitação&nbsp;aos locais turísticos e históricos&nbsp;em Rio Branco”.</p>
<p style="text-align: justify;"><strong><a href="/lai/wp-content/uploads/images/ARQUIVOS/202_RBTRANS/Decreto%20Municipal%20n°%202168%20de%2007.02.2011%20-%20Dispõe%20sobre%20o%20reajuste%20da%20Tarifa%20do%20Transporte%20Coletivo%20por%20Ônibus.pdf" target="_blank">DECRETO Nº 2.168 DE 07 DE FEVEREIRO DE 2011</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre o reajuste da Tarifa do Transporte Coletivo por Ônibus”.</p>
<hr>
<p style="text-align: justify;"><strong><a href="/lai/wp-content/uploads/images/ARQUIVOS/202_RBTRANS/Lei%20Municipal%20nº%201.824%20de%2031.12.2010%20-%20Altera%20a%20Lei%20nº%201.538-2005%20RBTRAN.pdf" target="_blank">LEI N° 1.824 DE 31 DE DEZEMBRO DE 2010</a></strong></p>
<p style="text-align: justify;">“Modifica o § 1º e acrescenta os §§ 5º, 6º,&nbsp;7º, 8º, 9º e 10 ao art. 1º, modifica o inciso&nbsp;III, como também a letra “e” do inciso V&nbsp;do art. 7º, da Lei Municipal n.º 1.538, de<br>
18 de julho de 2005 e revoga a Lei n.º&nbsp;1.819, de 2010”.</p>
<hr>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-Nº-1.770-de-09.12.2009-Aplicação-de-multa-a-empresa-de-ônibus.pdf" target="_blank">LEI Nº 1.770 DE 09 DE DEZEMBRO DE 2009</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre a aplicação de multa a empresa de ônibus cujos motoristas desrespeitem os direitos das pessoas idosas e dos deficientes mentais, físicos, auditivos e visuais.”</p>
<p style="text-align: justify;"><strong><a href="/lai/wp-content/uploads/images/ARQUIVOS/202_RBTRANS/Lei%20Municipal%20nº%201.760%20de%2026.10.2009%20-%20Modifica%20o%20inciso%20VI,%20do%20art.%201º%20da%20Lei%20n.º%201.726.pdf" target="_blank">LEI Nº 1760 DE 26 DE OUTUBRO DE 2009</a></strong></p>
<p style="text-align: justify;">“Modifica o inciso VI, do art. 1º da Lei n.º&nbsp;1.726, de 18 de dezembro de 2008.”</p>
<p style="text-align: justify;"><strong><a href="/lai/wp-content/uploads/images/ARQUIVOS/202_RBTRANS/Lei%20Municipal%20nº%201.750%20de%2028.08.2009%20-%20Itinerários%20das%20linhas%20no%20interior%20dos%20coletivos%20urbanos.pdf" target="_blank">LEI Nº 1.750 DE 28 DE AGOSTO DE 2009</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre a divulgação dos&nbsp;itinerários das linhas no interior dos&nbsp;coletivos urbanos integrantes do Sistema&nbsp;de Transporte Municipal e nas principais&nbsp;paradas”.</p>
<hr>
<p style="text-align: justify;"><strong><a href="/lai/wp-content/uploads/images/ARQUIVOS/202_RBTRANS/Lei%20Municipal%20nº%201.730%20de%2022.12.2008%20-%20Altera%20a%20Lei%20n.º%20332%20-%20Regulamento%20do%20transporte%20coletivo.pdf" target="_blank">LEI Nº 1.730 DE 22 DE DEZEMBRO DE 2008</a></strong></p>
<p style="text-align: justify;">“Altera os parágrafos 1.º, 2º, 3º, 4º, 5º e 7.º, do artigo 58 e&nbsp;os parágrafos 1º ao 4º, do artigo 64 da Lei n.º 332, de 12&nbsp;de janeiro de 1982 que instituiu o Regulamento de&nbsp;Transporte Coletivo do Município de Rio Branco/AC, e dá&nbsp;outras providências.”</p>
<p style="text-align: justify;"><strong><a href="/lai/wp-content/uploads/images/ARQUIVOS/202_RBTRANS/Lei%20Municipal%20nº%201.728%20de%2018.12.2008%20-%20Altera%20os%20dispositivos%20da%20Lei%20n.%20343-1982%20-%20Serviço%20de%20Táxi.pdf" target="_blank">LEI Nº 1.728 DE 18 DE DEZEMBRO DE 2008</a></strong></p>
<p style="text-align: justify;">“Altera os dispositivos da Lei n. 343, de 26&nbsp;de maio de 1982 que instituiu o&nbsp;Regulamento do Serviço de Táxi do&nbsp;Município de Rio Branco/AC, e dá outras&nbsp;providências.”</p>
<p style="text-align: justify;"><strong><a href="/lai/wp-content/uploads/images/ARQUIVOS/202_RBTRANS/Lei%20Municipal%20nº%201.726%20de%2018.12.2008%20-%20Acessibilidade%20no%20transporte%20público%20coletivo%20no%20Município.pdf" target="_blank">LEI Nº 1.726 DE 18 DE DEZEMBRO DE 2008</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre a acessibilidade no&nbsp;transporte público coletivo no Município de&nbsp;Rio Branco e dá outras providências”.</p>
<hr>
<p style="text-align: justify;"><strong><a href="/lai/wp-content/uploads/images/ARQUIVOS/202_RBTRANS/Lei%20Municipal%20nº%201.631%20de%2029.12.2006%20-%20Dispões%20sobre%20o%20DPVAT.pdf" target="_blank">LEI Nº 1.630 DE 29 DE DEZEMBRO DE 2006</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre a afixação de orientações&nbsp;sobre o DPVAT em estabelecimentos de&nbsp;prestação de serviços de saúde&nbsp;municipais ou privados, e funerárias do&nbsp;município e dá outras providências ”.</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-Nº-1.605-de-26.09.2006-Altera-a-Lei-n.º-1.538-2005-MOTO-TAXI.pdf" target="_blank">LEI Nº 1.605 DE 26 DE SETEMBRO DE 2006</a></strong></p>
<p style="text-align: justify;">“Altera dispositivos da Lei n.º 1.538 de 18 de julho de 2005 e dá outras providências”.</p>
<hr>
<p style="text-align: justify;"><strong>&nbsp;<a href="/lai/wp-content/uploads/images/ARQUIVOS/202_RBTRANS/Lei%20Municipal%20nº%201.583%20de%2022.12.2005%20-%20Acessibilidade%20do%20tranporte%20público%20coletivo.pdf" target="_blank">LEI Nº 1.583 DE 22 DE DEZEMBRO DE 2005</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre a acessibilidade no&nbsp;transporte público coletivo e dá outras&nbsp;providências.”</p>
<p style="text-align: justify;"><strong><a href="/lai/wp-content/uploads/images/ARQUIVOS/202_RBTRANS/Lei%20Municipal%20nº%201.538%20de%2018.07.2005%20-%20Moto%20Táxi%20RBTRANS.pdf" target="_blank">LEI Nº 1.538 DE 18 DE JULHO DE 2005</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre o serviço de transporte individual&nbsp;de passageiros em veículo automotor tipo&nbsp;motocicleta, denominado moto-táxi.”</p>
<hr>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2003-LEI-Nº-1.497-de-03.06.2003-Altera-a-Lei-nº-1.446-2001-MOTO-TAXI.pdf" target="_blank">LEI Nº 1.497 DE 03 DE JUNHO DE 2003</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre a alteração da Lei nº 1.446/2001 e dá outras providências.”</p>
<hr>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2001-LEI-Nº-1.446-de-30.10.2001-Lei-do-Moto-Taxi.pdf" target="_blank">LEI Nº 1.446 DE 30 DE OUTUBRO DE 2001</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre o serviço de transporte individual de passageiro em veículo tipo motocicleta, denominado MOTO-TÁXI, nos termos do art. 175 da Constituição Federal, e dá outras providências.”</p>
</div>';
BEGIN
    dbms_lob.append(texto, complementoTexto);
update PAGINAPREFEITURAPORTAL set CONTEUDOHTML = texto where NOME = 'Transporte' and CHAVE = 'transporte';
END;
