UPDATE VALORINDICADOR SET VALOR = SALVARVALOR;
UPDATE VALORINDICADOR_AUD SET VALOR = SALVARVALOR;
UPDATE INDICADORPROGRAMAPPA SET VALORDESEJADO = SALVARVALORDESEJADO;
UPDATE INDICADORPROGRAMAPPA_AUD SET VALORDESEJADO = SALVARVALORDESEJADO
