INSERT INTO PAGINAMENUHORIZPORTAL (ID, INICIOVIGENCIA, FIMVIGENCIA)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, TO_DATE('2024-04-01', 'YYYY-MM-DD'), NULL);

INSERT INTO PAGINAMENUHPAGINAPREF (ID, NOME, TIPOATOLEGAL, PAGINAMENUHORIZONTALPORTAL_ID, PAGINAPREFEITURAPORTAL_ID)
SELECT
    HIBERNATE_SEQUENCE.NEXTVAL,
    'Decretos',
    'DECRETO',
    (SELECT MENUH.ID FROM PAGINAMENUHORIZPORTAL MENUH WHERE MENUH.INICIOVIGENCIA = TO_DATE('2024-04-01', 'YYYY-MM-DD')),
    (SELECT PREF.ID FROM PAGINAPREFEITURAPORTAL PREF WHERE PREF.CHAVE = 'ato-legal')
FROM dual ;

INSERT INTO PAGINAMENUHPAGINAPREF (ID, NOME, TIPOATOLEGAL, PAGINAMENUHORIZONTALPORTAL_ID, PAGINAPREFEITURAPORTAL_ID)
SELECT
    HIBERNATE_SEQUENCE.NEXTVAL,
    'Portarias',
    'PORTARIA',
    (SELECT MENUH.ID FROM PAGINAMENUHORIZPORTAL MENUH WHERE MENUH.INICIOVIGENCIA = TO_DATE('2024-04-01', 'YYYY-MM-DD')),
    (SELECT PREF.ID FROM PAGINAPREFEITURAPORTAL PREF WHERE PREF.CHAVE = 'ato-legal')
FROM dual ;

INSERT INTO PAGINAMENUHPAGINAPREF (ID, NOME, TIPOATOLEGAL, PAGINAMENUHORIZONTALPORTAL_ID, PAGINAPREFEITURAPORTAL_ID)
SELECT
    HIBERNATE_SEQUENCE.NEXTVAL,
    'Resoluções',
    'RESOLUCAO',
    (SELECT MENUH.ID FROM PAGINAMENUHORIZPORTAL MENUH WHERE MENUH.INICIOVIGENCIA = TO_DATE('2024-04-01', 'YYYY-MM-DD')),
    (SELECT PREF.ID FROM PAGINAPREFEITURAPORTAL PREF WHERE PREF.CHAVE = 'ato-legal')
FROM dual ;

INSERT INTO PAGINAMENUHPAGINAPREF (ID, NOME, TIPOATOLEGAL, PAGINAMENUHORIZONTALPORTAL_ID, PAGINAPREFEITURAPORTAL_ID)
SELECT
    HIBERNATE_SEQUENCE.NEXTVAL,
    'Medidas Provisórias',
    'MEDIDA_PROVISORIA',
    (SELECT MENUH.ID FROM PAGINAMENUHORIZPORTAL MENUH WHERE MENUH.INICIOVIGENCIA = TO_DATE('2024-04-01', 'YYYY-MM-DD')),
    (SELECT PREF.ID FROM PAGINAPREFEITURAPORTAL PREF WHERE PREF.CHAVE = 'ato-legal')
FROM dual ;

INSERT INTO PAGINAMENUHPAGINAPREF (ID, NOME, TIPOATOLEGAL, PAGINAMENUHORIZONTALPORTAL_ID, PAGINAPREFEITURAPORTAL_ID)
SELECT
    HIBERNATE_SEQUENCE.NEXTVAL,
    'Instrução Normativa',
    'INSTRUCAO_NORMATIVA',
    (SELECT MENUH.ID FROM PAGINAMENUHORIZPORTAL MENUH WHERE MENUH.INICIOVIGENCIA = TO_DATE('2024-04-01', 'YYYY-MM-DD')),
    (SELECT PREF.ID FROM PAGINAPREFEITURAPORTAL PREF WHERE PREF.CHAVE = 'ato-legal')
FROM dual ;

INSERT INTO PAGINAMENUHPAGINAPREF (ID, NOME, TIPOATOLEGAL, PAGINAMENUHORIZONTALPORTAL_ID, PAGINAPREFEITURAPORTAL_ID)
SELECT
    HIBERNATE_SEQUENCE.NEXTVAL,
    'Leis Municipais',
    'LEI_ORDINARIA',
    (SELECT MENUH.ID FROM PAGINAMENUHORIZPORTAL MENUH WHERE MENUH.INICIOVIGENCIA = TO_DATE('2024-04-01', 'YYYY-MM-DD')),
    (SELECT PREF.ID FROM PAGINAPREFEITURAPORTAL PREF WHERE PREF.CHAVE = 'ato-legal')
FROM dual ;
