INSERT INTO UNIDADEACOMPAFINANCEIRO
  (ID, UNIDADEORGANIZACIONAL_ID)
SELECT HIBERNATE_SEQUENCE.nextval, HO.SUBORDINADA_ID
FROM HIERARQUIAORGANIZACIONAL HO
WHERE SYSDATE BETWEEN HO.INICIOVIGENCIA AND COALESCE(HO.FIMVIGENCIA, SYSDATE)
AND HO.TIPOHIERARQUIAORGANIZACIONAL = 'ORCAMENTARIA' AND HO.INDICEDONO = 3;


INSERT INTO FILTROACOMPAFINANCEIRO
  (ID, UNIDADE_ID, TIPOLIBERACAOFINANCEIRA)
SELECT HIBERNATE_SEQUENCE.nextval, UN.ID, 'COTA'
FROM UNIDADEACOMPAFINANCEIRO UN
INNER JOIN HIERARQUIAORGANIZACIONAL HO ON HO.SUBORDINADA_ID = UN.UNIDADEORGANIZACIONAL_ID
WHERE SYSDATE BETWEEN HO.INICIOVIGENCIA AND COALESCE(HO.FIMVIGENCIA, SYSDATE)
AND HO.TIPOHIERARQUIAORGANIZACIONAL = 'ORCAMENTARIA' AND HO.INDICEDONO = 3;

INSERT INTO FILTROACOMPAFINANCEIRO
  (ID, UNIDADE_ID, TIPOLIBERACAOFINANCEIRA)
SELECT HIBERNATE_SEQUENCE.nextval, UN.ID, 'REPASSE'
FROM UNIDADEACOMPAFINANCEIRO UN
INNER JOIN HIERARQUIAORGANIZACIONAL HO ON HO.SUBORDINADA_ID = UN.UNIDADEORGANIZACIONAL_ID
WHERE SYSDATE BETWEEN HO.INICIOVIGENCIA AND COALESCE(HO.FIMVIGENCIA, SYSDATE)
AND HO.TIPOHIERARQUIAORGANIZACIONAL = 'ORCAMENTARIA' AND HO.INDICEDONO = 3;

INSERT INTO FILTROACOMPAFINANCEIRO
  (ID, UNIDADE_ID, TIPOLIBERACAOFINANCEIRA)
SELECT HIBERNATE_SEQUENCE.nextval, UN.ID, 'SUB_REPASSE'
FROM UNIDADEACOMPAFINANCEIRO UN
INNER JOIN HIERARQUIAORGANIZACIONAL HO ON HO.SUBORDINADA_ID = UN.UNIDADEORGANIZACIONAL_ID
WHERE SYSDATE BETWEEN HO.INICIOVIGENCIA AND COALESCE(HO.FIMVIGENCIA, SYSDATE)
AND HO.TIPOHIERARQUIAORGANIZACIONAL = 'ORCAMENTARIA' AND HO.INDICEDONO = 3;

INSERT INTO FILTROACOMPAFINANCEIRO
  (ID, UNIDADE_ID, TIPOLIBERACAOFINANCEIRA)
SELECT HIBERNATE_SEQUENCE.nextval, UN.ID, 'REPASSE_PARA_COBERTURA_DE_INSUFICIENCIA_FINANCEIRA'
FROM UNIDADEACOMPAFINANCEIRO UN
INNER JOIN HIERARQUIAORGANIZACIONAL HO ON HO.SUBORDINADA_ID = UN.UNIDADEORGANIZACIONAL_ID
WHERE SYSDATE BETWEEN HO.INICIOVIGENCIA AND COALESCE(HO.FIMVIGENCIA, SYSDATE)
AND HO.TIPOHIERARQUIAORGANIZACIONAL = 'ORCAMENTARIA' AND HO.INDICEDONO = 3;

INSERT INTO FILTROACOMPAFINANCEIRO
  (ID, UNIDADE_ID, TIPOLIBERACAOFINANCEIRA)
SELECT HIBERNATE_SEQUENCE.nextval, UN.ID, 'OUTROS_APORTES_PLANO_FINANCEIRO'
FROM UNIDADEACOMPAFINANCEIRO UN
INNER JOIN HIERARQUIAORGANIZACIONAL HO ON HO.SUBORDINADA_ID = UN.UNIDADEORGANIZACIONAL_ID
WHERE SYSDATE BETWEEN HO.INICIOVIGENCIA AND COALESCE(HO.FIMVIGENCIA, SYSDATE)
AND HO.TIPOHIERARQUIAORGANIZACIONAL = 'ORCAMENTARIA' AND HO.INDICEDONO = 3;

INSERT INTO FILTROACOMPAFINANCEIRO
  (ID, UNIDADE_ID, TIPOLIBERACAOFINANCEIRA)
SELECT HIBERNATE_SEQUENCE.nextval, UN.ID, 'REPASSE_PARA_COBERTURA_DE_DEFICIT_FINANCEIRO'
FROM UNIDADEACOMPAFINANCEIRO UN
INNER JOIN HIERARQUIAORGANIZACIONAL HO ON HO.SUBORDINADA_ID = UN.UNIDADEORGANIZACIONAL_ID
WHERE SYSDATE BETWEEN HO.INICIOVIGENCIA AND COALESCE(HO.FIMVIGENCIA, SYSDATE)
AND HO.TIPOHIERARQUIAORGANIZACIONAL = 'ORCAMENTARIA' AND HO.INDICEDONO = 3;

INSERT INTO FILTROACOMPAFINANCEIRO
  (ID, UNIDADE_ID, TIPOLIBERACAOFINANCEIRA)
SELECT HIBERNATE_SEQUENCE.nextval, UN.ID, 'OUTROS_APORTES_PLANO_PREVIDENCIÁRIO'
FROM UNIDADEACOMPAFINANCEIRO UN
INNER JOIN HIERARQUIAORGANIZACIONAL HO ON HO.SUBORDINADA_ID = UN.UNIDADEORGANIZACIONAL_ID
WHERE SYSDATE BETWEEN HO.INICIOVIGENCIA AND COALESCE(HO.FIMVIGENCIA, SYSDATE)
AND HO.TIPOHIERARQUIAORGANIZACIONAL = 'ORCAMENTARIA' AND HO.INDICEDONO = 3;

INSERT INTO FILTROACOMPAFINANCEIRO
  (ID, UNIDADE_ID, TIPOLIBERACAOFINANCEIRA)
SELECT HIBERNATE_SEQUENCE.nextval, UN.ID, 'TRANSFERENCIAS_DIVERSAS'
FROM UNIDADEACOMPAFINANCEIRO UN
INNER JOIN HIERARQUIAORGANIZACIONAL HO ON HO.SUBORDINADA_ID = UN.UNIDADEORGANIZACIONAL_ID
WHERE SYSDATE BETWEEN HO.INICIOVIGENCIA AND COALESCE(HO.FIMVIGENCIA, SYSDATE)
AND HO.TIPOHIERARQUIAORGANIZACIONAL = 'ORCAMENTARIA' AND HO.INDICEDONO = 3;


INSERT INTO CONTAACOMPAFINANCEIRO
  (ID, UNIDADE_ID, TIPOCONTAACOMPANHAMENTO, INTERVALOINICIAL, INTERVALOFINAL)
SELECT HIBERNATE_SEQUENCE.nextval, UN.ID, 'RECEBIDA', '2209199010', '2209199010'
FROM UNIDADEACOMPAFINANCEIRO UN
INNER JOIN HIERARQUIAORGANIZACIONAL HO ON HO.SUBORDINADA_ID = UN.UNIDADEORGANIZACIONAL_ID
WHERE SYSDATE BETWEEN HO.INICIOVIGENCIA AND COALESCE(HO.FIMVIGENCIA, SYSDATE)
AND HO.TIPOHIERARQUIAORGANIZACIONAL = 'ORCAMENTARIA' AND HO.INDICEDONO = 3
AND HO.CODIGONO = '199';

INSERT INTO CONTAACOMPAFINANCEIRO
  (ID, UNIDADE_ID, TIPOCONTAACOMPANHAMENTO, INTERVALOINICIAL, INTERVALOFINAL)
SELECT HIBERNATE_SEQUENCE.nextval, UN.ID, 'RECEBIDA', '2108199999', '2108199999'
FROM UNIDADEACOMPAFINANCEIRO UN
INNER JOIN HIERARQUIAORGANIZACIONAL HO ON HO.SUBORDINADA_ID = UN.UNIDADEORGANIZACIONAL_ID
WHERE SYSDATE BETWEEN HO.INICIOVIGENCIA AND COALESCE(HO.FIMVIGENCIA, SYSDATE)
AND HO.TIPOHIERARQUIAORGANIZACIONAL = 'ORCAMENTARIA' AND HO.INDICEDONO = 3
AND HO.CODIGONO = '199';

INSERT INTO CONTAACOMPAFINANCEIRO
  (ID, UNIDADE_ID, TIPOCONTAACOMPANHAMENTO, INTERVALOINICIAL, INTERVALOFINAL)
SELECT HIBERNATE_SEQUENCE.nextval, UN.ID, 'RECEBIDA', '1000000000', '9999999999'
FROM UNIDADEACOMPAFINANCEIRO UN
INNER JOIN HIERARQUIAORGANIZACIONAL HO ON HO.SUBORDINADA_ID = UN.UNIDADEORGANIZACIONAL_ID
WHERE SYSDATE BETWEEN HO.INICIOVIGENCIA AND COALESCE(HO.FIMVIGENCIA, SYSDATE)
AND HO.TIPOHIERARQUIAORGANIZACIONAL = 'ORCAMENTARIA' AND HO.INDICEDONO = 3
AND HO.CODIGONO <> '199';

INSERT INTO CONTAACOMPAFINANCEIRO
  (ID, UNIDADE_ID, TIPOCONTAACOMPANHAMENTO, INTERVALOINICIAL, INTERVALOFINAL)
SELECT HIBERNATE_SEQUENCE.nextval, UN.ID, 'RETIRADA', '1000000000', '9999999999'
FROM UNIDADEACOMPAFINANCEIRO UN
INNER JOIN HIERARQUIAORGANIZACIONAL HO ON HO.SUBORDINADA_ID = UN.UNIDADEORGANIZACIONAL_ID
WHERE SYSDATE BETWEEN HO.INICIOVIGENCIA AND COALESCE(HO.FIMVIGENCIA, SYSDATE)
AND HO.TIPOHIERARQUIAORGANIZACIONAL = 'ORCAMENTARIA' AND HO.INDICEDONO = 3
AND HO.CODIGONO <> '199';
