DECLARE
texto CLOB := '<div class="post-content">
<hr>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/10/DECRETO-Nº-1301-2024-–-Regulamenta-a-Lei-Municipal-nº-2.515-2024-Projeto-“Adote-Uma-Praça”.pdf" target="_blank">DECRETO Nº 1.301 DE 09 DE OUTUBRO DE 2024</a></strong></p>
<p style="text-align: justify;">“Regulamenta a Lei Municipal nº 2.515, de 05 de abril de 2024, que dispõe sobre a implantação do Projeto “Adote Uma Praça” no âmbito do Município de Rio Branco e dá outras providências”.</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/10/RESOLUÇÃO-COMDEMA-Nº-008-DE-29-DE-OUTUBRO-DE-2024-DOE.pdf" target="_blank">RESOLUÇÃO COMDEMA Nº 008, DE 29 DE OUTUBRO DE 2024</a></strong>&nbsp;– DOE</p>
<p style="text-align: justify;">“Dispõe sobre a regulamentação do licenciamento ambiental das atividades efetiva ou potencialmente causadoras de poluição sonora no âmbito do município de Rio Branco/AC.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/10/COMDEMA-RESOLUÇÃO-N°-011-DE-09-DE-SETEMBRO-DE-2024-DOE.pdf" target="_blank">RESOLUÇÃO COMDEMA N° 011, DE 09 DE SETEMBRO DE 2024</a></strong>&nbsp;– DOE</p>
<p style="text-align: justify;">“Disciplina o licenciamento ambiental para a implantação de empreendimentos e atividades de parcelamento do solo urbano no Município de Rio Branco/AC.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2021/07/LEI-MUNICIPAL-Nº-2.515-DE-05.04.2024-–-Dispõe-sobre-a-implantação-do-projeto-“Adote-Uma-Praça”-no-âmbito-do-Município-de-Rio-Branco.pdf" target="_blank">LEI MUNICIPAL Nº 2.515 DE 05 DE ABRIL DE 2024</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre a implantação do projeto “Adote Uma Praça” no âmbito do Município de Rio Branco e dá outras providências”.</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/10/2022-DECRETO-Nº-1276-2022-SEMEIA-Altera-o-Decreto-nº-044-2022-GTCA.pdf" target="_blank">DECRETO Nº 1.276 DE 24 DE AGOSTO DE 2022</a></strong></p>
<p style="text-align: justify;">“O art. 14 do Decreto nº 044, de 13 de janeiro de 2022, que estabelece diretrizes e procedimentos para aplicação da compensação ambiental de empreendimentos ou atividades efetiva ou potencialmente causadoras de impacto ambiental local.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/10/2022-LEI-Nº-2.422-DE-25-DE-JANEIRO-DE-2022-Sanções-administrativas-aplicáveis-as-condutas-lesivas-ao-meio-ambiente.pdf" target="_blank">LEI Nº 2.422 DE 25 DE JANEIRO DE 2022</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre as sanções administrativas aplicáveis às condutas e atividades lesivas ao meio ambiente, complementando a Lei nº 1.330 de 23 de setembro de 1999, com suas alterações e dá outras providências.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/10/2022-DECRETO-Nº-045-2022-Procedimentos-técnicos-a-serem-adotados-nas-execução-de-níveis-de-pressão-sonora-em-ambiente.pdf" target="_blank">DECRETO N° 045 DE 13 DE JANEIRO DE 2022</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre os procedimentos técnicos a serem adotados na execução de medições de níveis de pressão sonora em ambientes externos às edificações de empreendimentos efetivos ou potencialmente causadores de poluição, bem como limites para avaliação dos resultados em função da finalidade de uso e ocupação do solo no Município de Rio Branco.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/10/2022-DECRETO-Nº-044-2022-Diretrizes-e-procedimentos-para-aplicação-da-compensação-ambiental-de-empreendimentos.pdf" target="_blank">DECRETO Nº 044 DE 13 JANEIRO DE 2022</a></strong></p>
<p style="text-align: justify;">“Estabelece diretrizes e procedimentos para aplicação da compensação ambiental de empreendimentos ou atividades efetiva ou potencialmente causadoras de impacto ambiental local.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/10/2021-SEMEIA-IN-Nº-002-2021-Pressão-Sonora-em-ambientes-externos-causadores-de-poluição-DOE.pdf" target="_blank">INSTRUÇÃO NORMATIVA N° 002/2021</a></strong>&nbsp;– DOE</p>
<p style="text-align: justify;">“Estabelece diretrizes gerais para regulamentar os procedimentos técnicos a serem adotados na execução de medições de níveis de pressão sonora em ambientes externos às edificações de empreendimentos efetivos ou potencialmente causadores de poluição, bem como limites para avaliação dos resultados em função da finalidade de uso e ocupação do solo no Município de Rio Branco.”</p>
<p><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/10/2021-SEMEIA-IN-Nº-001-2021-Dispõe-sobre-o-licenciamento-ambiental-relativo-ao-corte-de-árvores-e-outros-DOE.pdf" target="_blank">INSTRUÇÃO NORMATIVA N° 001/2021</a></strong>&nbsp;– DOE</p>
<p>“Dispõe sobre o licenciamento ambiental relativo ao corte de árvores; à supressão de vegetação em áreas públicas e privadas e dos prestadores desses serviços no município de Rio Branco/AC.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/10/2021-SEFIN-SEMSA-SEMEIA-INSTRUÇÃO-NORMATIVA-CONJUNTA-Nº-001-2021-CNAE-DOE.pdf" target="_blank">INSTRUÇÃO NORMATIVA CONJUNTA Nº 001/2021</a>&nbsp;</strong>- DOE</p>
<p style="text-align: justify;">Dispõe sobre a classificação de risco das atividades econômicas em baixo risco ou “baixo risco A”, médio risco ou “baixo risco B” e Alto Risco para fins de aplicação pelos auditores fiscais municipais da Prefeitura de Rio Branco/AC.</p>
<p><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/10/Lei-Nº-2.396-de-04-de-janeiro-de-2021-Institui-a-política-municipal-de-controle-de-natalidade-de-cães-e-gatos.pdf" target="_blank">LEI Nº 2.396 DE 04 DE JANEIRO DE 2021</a></strong></p>
<p style="text-align: justify;">“Institui a política municipal de controle de natalidade de cães e gatos no município de Rio Branco.”</p>
<p style="text-align: justify;"><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/10/Lei-Nº-2.395-de-04-de-janeiro-de-2021-Institui-a-contribuição-voluntaria-para-o-fundo-de-proteção-e-bem-estar-do-animal.pdf" target="_blank"><strong>LEI Nº 2.395 DE 04 DE JANEIRO DE 2021</strong></a></p>
<p style="text-align: justify;">“Institui a contribuição voluntária para fundo de proteção e bem estar do animal do município de Rio Branco e dá outras providências.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/10/Lei-Nº-2.349-de-23-de-dezembro-de-2019-Institui-o-Programa-Municipal-de-Coleta-Tratamento-e-Reciclagem-de-Óleos-de-Origem-Vegetal.pdf" target="_blank">LEI Nº 2.349 DE 23 DE DEZEMBRO DE 2019</a></strong></p>
<p style="text-align: justify;">“Institui o Programa Municipal de Coleta, Tratamento e Reciclagem de Óleos de Origem Vegetal e dá outras providências.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/10/2017-SEMEIA-IN-Nº-001-2017-Regulamenta-o-procedimento-relativo-à-arborização-urbana-DOE.pdf" target="_blank">INSTRUÇÃO NORMATIVA N°. 001/2017</a></strong>&nbsp;– DOE</p>
<p style="text-align: justify;">“Regulamenta o procedimento relativo à arborização urbana, servindo como base para análise e aprovação de projetos de loteamentos, condomínios, conjuntos habitacionais, distritos industriais e arruamentos, submetidos à análise da SEMEIA.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/10/LEI-Nº-2.215-de-10-de-Novembro-de-2016-Regulamenta-e-disciplina-a-criação-de-animais-domésticos.pdf" target="_blank">LEI Nº 2.215 DE 10 DE NOVEMBRO DE 2016</a></strong></p>
<p style="text-align: justify;">“Regulamenta e disciplina a criação, guarda, utilização e transporte de animais domésticos ou de estimação no Município de Rio Branco.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/10/2016-DECRETO-Nº-018-2016-Altera-o-Decreto-n°-2.956-2008-Extração-de-Areia.pdf" target="_blank">DECRETO Nº 018 DE 12 DE JANEIRO DE 2016</a></strong></p>
<p style="text-align: justify;">“Altera o Decreto N° 2.956, de 13 de agosto de 2.008.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/10/2009-LEI-Nº-1.784-de-18.12.2009-Altera-a-Lei-nº-1.330-LICENCIAMENTO-AMBIENTAL-SIMPLIFICADO.pdf" target="_blank">LEI Nº 1.784 DE 18 DE DEZEMBRO DE 2009</a></strong></p>
<p style="text-align: justify;">“Acrescenta incisos ao art. 21, da Lei Municipal nº 1.330, de 23 de setembro de 1999; Altera o art. 51; dá nova redação ao artigo 52 para autorizar a compensação ambiental de impactos potencialmente ou efetivamente causados por empreendimentos ou atividades locais; e acrescenta parágrafos ao art. 53 para dispor sobre o Licenciamento Ambiental Simplificado, na forma que especifica.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/10/LEI-Nº-1.543-de-29.07.2005-Doação-de-Mudas-de-Arvore-para-as-Escolas.pdf" target="_blank">LEI Nº 1.543 DE 29 DE JULHO DE 2005</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre a doação de mudas de arvores às crianças matriculadas na primeira serie do 1.º grau na rede Pública Municipal.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/10/2002-LEI-Nº-1.465-de-16.01.2002-Altera-a-Lei-Nº-1.330-1999-SEMEIA.pdf" target="_blank">LEI Nº 1465 DE 16 DE JANEIRO DE 2002</a></strong></p>
<p style="text-align: justify;">“Altera índices e parâmetros referidos no artigo 50 da Lei Municipal nº1330/99,que dispõe sobre empreendimentos na zona urbana do Município de Rio Branco sujeitos à licenciamento ambiental.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/10/2002-LEI-Nº-1.459-de-16.01.2002-Sanções-Adm.-às-condutas-e-atividades-lesivas-ao-Meio-Ambiente.pdf" target="_blank">LEI Nº 1.459 DE 16 DE JANEIRO DE 2002</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre a especificação das sanções administrativas aplicáveis ás condutas e atividades lesivas ao meio ambiente, complementando a Lei nº 1.330 de 23 de setembro de 1999 e dá outras providências.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/10/1999-LEI-Nº-1.330-DE-23.09.1999-Política-Municipal-de-Meio-Ambiente-PMMA.pdf" target="_blank">LEI Nº 1.330 DE 23 DE SETEMBRO DE 1999</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre a Política Municipal de Meio Ambiente, seus fins e mecanismos de formulação e aplicação, instituindo o Sistema Municipal de Meio Ambiente e alterando as competências da SEMEIA e do COMDEMA, e dá outras providências.”</p>
</div>';
BEGIN
update PAGINAPREFEITURAPORTAL
set CONTEUDOHTML = texto
where NOME = 'Meio Ambiente' and CHAVE = 'meio-ambiente';
END;
