update itemprocesso set QUERY34 = 'select coalesce(sum(SALDOEXANTERIOR + inscricao + atualizacao - cobranca + baixa), 0) from (
SELECT
COALESCE((SUM(
(COALESCE(SALDO.INSCRICAO, 0) + COALESCE(SALDO.ATUALIZACAO, 0) + COALESCE(SALDO.REVERSAO, 0) +
COALESCE(SALDO.AUMENTATIVO, 0)) -
(COALESCE(SALDO.RECEBIMENTO, 0) + COALESCE(SALDO.PROVISAO, 0) + COALESCE(SALDO.BAIXA, 0) +
COALESCE(SALDO.diminutivo, 0)))), 0) AS SALDOEXANTERIOR,
COALESCE(SUM(SALDO.INSCRICAO), 0) * - 1 AS INSCRICAO,
(COALESCE(SUM(SALDO.ATUALIZACAO), 0) + COALESCE(SUM(SALDO.REVERSAO), 0) +
coalesce(sum(SALDO.AUMENTATIVO), 0))* - 1 AS ATUALIZACAO,
COALESCE(SUM(SALDO.RECEBIMENTO), 0)* - 1 AS COBRANCA,
(COALESCE(SUM(COALESCE(SALDO.PROVISAO, 0) + COALESCE(SALDO.BAIXA, 0)), 0) +
coalesce(sum(SALDO.DIMINUTIVO), 0))* - 1 AS BAIXA,
saldo.UNIDADEORGANIZACIONAL_ID
FROM SALDODIVIDAATIVACONTABIL SALDO
inner join CONFIGCONCCONTABILCONTA cfg on cfg.conta_id = saldo.CONTARECEITA_ID
WHERE trunc(SALDO.DATASALDO) = (SELECT trunc(MAX(sld.DATASALDO))
FROM SALDODIVIDAATIVACONTABIL sld
WHERE trunc(sld.DATASALDO) <= TO_DATE(:dataInicial, ''DD/MM/YYYY'')
and sld.UNIDADEORGANIZACIONAL_ID = saldo.UNIDADEORGANIZACIONAL_ID
and sld.CONTADEDESTINACAO_ID = saldo.CONTADEDESTINACAO_ID
and sld.INTERVALO = saldo.INTERVALO
and sld.NATUREZADIVIDAATIVA = saldo.NATUREZADIVIDAATIVA
and sld.CONTARECEITA_ID = saldo.CONTARECEITA_ID)
and cfg.configConciliacaoContabil_id = :cfgId
group by saldo.UNIDADEORGANIZACIONAL_ID
union all
SELECT
0                                     AS SALDOEXANTERIOR,
COALESCE(SUM(SALDO.INSCRICAO), 0)     AS INSCRICAO,
(COALESCE(SUM(SALDO.ATUALIZACAO), 0) + COALESCE(SUM(SALDO.REVERSAO), 0) +
coalesce(sum(SALDO.AUMENTATIVO), 0)) AS ATUALIZACAO,
COALESCE(SUM(SALDO.RECEBIMENTO), 0)   AS COBRANCA,
(COALESCE(SUM(COALESCE(SALDO.PROVISAO, 0) + COALESCE(SALDO.BAIXA, 0)), 0) +
coalesce(sum(SALDO.DIMINUTIVO), 0))  AS BAIXA,
saldo.UNIDADEORGANIZACIONAL_ID
FROM SALDODIVIDAATIVACONTABIL SALDO
inner join CONFIGCONCCONTABILCONTA cfg on cfg.conta_id = saldo.CONTARECEITA_ID
WHERE trunc(SALDO.DATASALDO) = (SELECT trunc(MAX(sld.DATASALDO))
FROM SALDODIVIDAATIVACONTABIL sld
WHERE trunc(sld.DATASALDO) <= TO_DATE(:dataFinal, ''DD/MM/YYYY'')
and sld.UNIDADEORGANIZACIONAL_ID = saldo.UNIDADEORGANIZACIONAL_ID
and sld.CONTADEDESTINACAO_ID = saldo.CONTADEDESTINACAO_ID
and sld.INTERVALO = saldo.INTERVALO
and sld.NATUREZADIVIDAATIVA = saldo.NATUREZADIVIDAATIVA
and sld.CONTARECEITA_ID = saldo.CONTARECEITA_ID)
and cfg.configConciliacaoContabil_id = :cfgId
group by saldo.UNIDADEORGANIZACIONAL_ID
) dados
inner join VWHIERARQUIAORCAMENTARIA vw on dados.UNIDADEORGANIZACIONAL_ID = vw.SUBORDINADA_ID
where to_date(:dataFinal, ''dd/mm/yyyy'') between vw.INICIOVIGENCIA and coalesce(vw.FIMVIGENCIA, to_date(:dataFinal, ''dd/mm/yyyy''))'
