insert into MODELODOCTOOFICIAL (ID, TIPODOCTOOFICIAL_ID, VIGENCIAINICIAL, SEQUENCIA)
VALUES (HIBERNATE_SEQUENCE.nextval, (select tdo.id from TIPODOCTOOFICIAL tdo where tdo.CODIGO = 148 and tdo.MODULOTIPODOCTOOFICIAL = 'NOTA_ESTORNO_PAGAMENTO'), sysdate, 1)
