UPDATE VALORINDICADOR SET SALVARVALOR = VALOR;
UPDATE VALORINDICADOR_AUD SET SALVARVALOR = VALOR;
UPDATE INDICADORPROGRAMAPPA SET SALVARVALORDESEJADO = VALORDESEJADO;
UPDATE INDICADORPROGRAMAPPA_AUD SET SALVARVALORDESEJADO = VALORDESEJADO
