UPDATE MODULOPREFEITURAPORTAL SET ICONE='fas fa-chart-column' WHERE MODULO='INDICADORES';
UPDATE MODULOPREFEITURAPORTAL SET ICONE='fas fa-person-breastfeeding' WHERE MODULO='BOLSA_FAMILIA';
UPDATE MODULOPREFEITURAPORTAL SET ICONE='fas fa-briefcase-medical' WHERE MODULO='CALAMIDADE_PUBLICA';
UPDATE MODULOPREFEITURAPORTAL SET ICONE='fas fa-sack-dollar' WHERE MODULO='BENS_PATRIMONIAIS';
UPDATE MODULOPREFEITURAPORTAL SET ORDEM=1, ICONE='fas fa-virus' WHERE MODULO='COVID_19';
UPDATE MODULOPREFEITURAPORTAL SET ORDEM=0, ICONE='fas fa-home' WHERE MODULO='PAGINA_INICIAL';
