update viagemdiaria set DATAFINALSAIDA = DATAINICIALSAIDA,
                        DATAFINALRETORNO = DATAINICIALRETORNO,
                        HORAFINALSAIDA = HORAINICIALSAIDA,
                        MINUTOFINALSAIDA = MINUTOINICIALSAIDA,
                        HORAFINALRETORNO = HORAINICIALRETORNO,
                        MINUTOFINALRETORNO = MINUTOINICIALRETORNO
