INSERT INTO PAGINAPRINCIPALPORTAL (ID, INICIOVIGENCIA, FIMVIGENCIA)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, TO_DATE('2024-03-10', 'YYYY-MM-DD'), NULL);

INSERT INTO PAGINAPRINCPAGINAPREF (ID, NOME, DESCRICAO, PAGINAPRINCIPALPORTAL_ID, PAGINAPREFEITURAPORTAL_ID)
SELECT
    HIBERNATE_SEQUENCE.NEXTVAL,
    'Despesas',
    'Execução orçamentária.',
    (SELECT PRINC.ID FROM PAGINAPRINCIPALPORTAL PRINC WHERE PRINC.INICIOVIGENCIA = TO_DATE('2024-03-10', 'YYYY-MM-DD')),
    (SELECT PREF.ID FROM PAGINAPREFEITURAPORTAL PREF WHERE PREF.CHAVE = 'despesa-por-unidade')
FROM dual ;

INSERT INTO PAGINAPRINCPAGINAPREF (ID, NOME, DESCRICAO, PAGINAPRINCIPALPORTAL_ID, PAGINAPREFEITURAPORTAL_ID)
SELECT
    HIBERNATE_SEQUENCE.NEXTVAL,
    'Receitas',
    'Arrecadação do município.',
    (SELECT PRINC.ID FROM PAGINAPRINCIPALPORTAL PRINC WHERE PRINC.INICIOVIGENCIA = TO_DATE('2024-03-10', 'YYYY-MM-DD')),
    (SELECT PREF.ID FROM PAGINAPREFEITURAPORTAL PREF WHERE PREF.CHAVE = 'arrecadacao')
FROM dual ;

INSERT INTO PAGINAPRINCPAGINAPREF (ID, NOME, DESCRICAO, PAGINAPRINCIPALPORTAL_ID, PAGINAPREFEITURAPORTAL_ID)
SELECT
    HIBERNATE_SEQUENCE.NEXTVAL,
    NULL,
    'Remuneração/Cargos.',
    (SELECT PRINC.ID FROM PAGINAPRINCIPALPORTAL PRINC WHERE PRINC.INICIOVIGENCIA = TO_DATE('2024-03-10', 'YYYY-MM-DD')),
    (SELECT PREF.ID FROM PAGINAPREFEITURAPORTAL PREF WHERE PREF.CHAVE = 'servidor')
FROM dual ;

INSERT INTO PAGINAPRINCPAGINAPREF (ID, NOME, DESCRICAO, PAGINAPRINCIPALPORTAL_ID, PAGINAPREFEITURAPORTAL_ID)
SELECT
    HIBERNATE_SEQUENCE.NEXTVAL,
    NULL,
    'Lista de contratações.',
    (SELECT PRINC.ID FROM PAGINAPRINCIPALPORTAL PRINC WHERE PRINC.INICIOVIGENCIA = TO_DATE('2024-03-10', 'YYYY-MM-DD')),
    (SELECT PREF.ID FROM PAGINAPREFEITURAPORTAL PREF WHERE PREF.CHAVE = 'contrato')
FROM dual ;

INSERT INTO PAGINAPRINCPAGINAPREF (ID, NOME, DESCRICAO, PAGINAPRINCIPALPORTAL_ID, PAGINAPREFEITURAPORTAL_ID)
SELECT
    HIBERNATE_SEQUENCE.NEXTVAL,
    NULL,
    NULL,
    (SELECT PRINC.ID FROM PAGINAPRINCIPALPORTAL PRINC WHERE PRINC.INICIOVIGENCIA = TO_DATE('2024-03-10', 'YYYY-MM-DD')),
    (SELECT PREF.ID FROM PAGINAPREFEITURAPORTAL PREF WHERE PREF.CHAVE = 'licitacao-outras')
FROM dual ;

INSERT INTO PAGINAPRINCPAGINAPREF (ID, NOME, DESCRICAO, PAGINAPRINCIPALPORTAL_ID, PAGINAPREFEITURAPORTAL_ID)
SELECT
    HIBERNATE_SEQUENCE.NEXTVAL,
    'Convênios',
    'Convênio de despesa.',
    (SELECT PRINC.ID FROM PAGINAPRINCIPALPORTAL PRINC WHERE PRINC.INICIOVIGENCIA = TO_DATE('2024-03-10', 'YYYY-MM-DD')),
    (SELECT PREF.ID FROM PAGINAPREFEITURAPORTAL PREF WHERE PREF.CHAVE = 'convenio-despesa')
FROM dual ;
