DECLARE
texto CLOB := '<div class="post-content"><hr>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/11/SEFIN-Relação-de-Serviços-e-Aliquotas.pdf" target="_blank">SEFIN – RELAÇÃO DE SERVIÇOS E ALIQUOTAS</a></strong></p>
<hr>
<p><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/11/DECRETO-Nº-742-2024-–-SEFIN-–-Alterar-o-Decreto-nº-339-2024-–-Prorrogação-dos-prazos-para-o-pagamento-do-IPTU-e-ISSQN-2.pdf" target="_blank">DECRETO Nº 742 DE 05 DE JUNHO DE 2024</a></strong></p>
<p>“Alterar o artigo 3º do Decreto Municipal nº 339 de 15 de março de 2024, que dispõe sobre a prorrogação dos prazos para o pagamento do Imposto sobre a Propriedade Predial e Territorial Urbana – IPTU, do Imposto Sobre Serviço de Qualquer Natureza – ISSQN e da Taxa de Alvará de Funcionamento referente ao exercício de 2024 e dá outras providências.”</p>
<p><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/11/DECRETO-Nº-621-2024-–-SEFIN-–-Fixa-meta-de-arrecadação-de-ISSQN-2024.pdf" target="_blank">DECRETO Nº 621 DE 13 DE MAIO DE 2024</a></strong></p>
<p>“Fica fixada como meta de arrecadação do Imposto sobre Serviços de Qualquer Natureza – ISSQN, para o exercício de 2024, o valor de R$ 131.146.998,43 (cento e trinta e um milhões, cento e quarenta e seis mil, novecentos e noventa e oito reais e quarenta e três centavos).”</p>
<p><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-339-2024-Prorrogação-dos-prazos-de-pagamento-do-IPTU-ISSQN-e-da-TAXA-DE-ALVARÁ.pdf" target="_blank">DECRETO Nº 339 DE 15 DE MARÇO DE 2024</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre a prorrogação dos prazos para o pagamento do Imposto sobre a Propriedade Predial e Territorial Urbana – IPTU, do Imposto Sobre Serviço de Qualquer Natureza – ISSQN e da Taxa de Alvará de Funcionamento referente ao exercício de 2024 e dá outras providências.”</p>
<p><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/11/DECRETO-Nº-1400-2023-Fixa-Meta-de-Arrecadação-de-ISSQN-para-o-exercício-de-2023.pdf" target="_blank">DECRETO Nº 1.400 DE 21 DE AGOSTO DE 2023</a></strong></p>
<p>“Fica fixada como meta de arrecadação do Imposto sobre Serviços de Qualquer Natureza – ISSQN, para o exercício de 2023, o valor de R$ 117.364.061,73 (cento e dezessete milhões, trezentos e sessenta e quatro mil, sessenta e um reais e setenta e três centavos).”</p>
<p><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/11/DECRETO-Nº-1068-2023-Sobre-o-parcelamento-do-ISSQN-Habite-se.pdf" target="_blank">DECRETO Nº 1.068 DE 06 DE JULHO DE 2023</a></strong></p>
<p>“Dispõe sobre o parcelamento do ISSQN – Habite-se lançado no exercício e dá outras providências.”</p>
<p><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/11/LEI-COMPLEMENTAR-Nº-221-DE-27.04.2023-Altera-a-Lei-Municipal-Nº-2.040-2014-ISSQN.pdf" target="_blank">LEI COMPLEMENTAR Nº 221 DE 27 DE ABRIL DE 2023</a></strong></p>
<p>“Altera a Lei Municipal nº 2.040 de 09 de abril de 2014, que estabelece critérios para a fixação de metas fiscais de arrecadação do Imposto Sobre Serviços de Qualquer Natureza – ISSQN e institui a bonificação por alcance de resultados, alterada pela a Lei Municipal nº 2.174 de 01 de abril de 2016”.</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-474-2023-Prorrogação-dos-prazos-do-IPTU-ISSQN-TAXA-ALVARÁ-DE-FUNCIONAMENTO-2023.pdf" target="_blank">DECRETO Nº 474 DE 03 DE ABRIL DE 2023</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre a prorrogação dos prazos para o pagamento do Imposto sobre a Propriedade Predial e Territorial Urbana – IPTU, do Imposto Sobre Serviço de Qualquer Natureza – ISSQN e da Taxa de Alvará de Funcionamento referente ao exercício de 2023 e dá outras providências.”</p>
<hr>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/11/DECRETO-Nº-1149-2022-Fixar-como-meta-de-arrecadação-do-Imposto-sobre-Serviços-de-Qualquer-Natureza-–-ISSQN-2022.pdf" target="_blank">DECRETO Nº 1.149 DE 26 DE JULHO DE 2022</a></strong></p>
<p style="text-align: justify;">“Fica fixada como meta de arrecadação do Imposto sobre Serviços de Qualquer Natureza – ISSQN, para o exercício de 2022, o valor de R$ 93.484.756.54,00 (noventa e três milhões quatrocentos e oitenta e quatro mil, setecentos e cinquenta e seis reais e cinquenta e quatro centavos).”</p>
<hr>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/11/DECRETO-Nº-1653-2021-ISSQN-e-Bonificação-da-Lei-2.040-2014.pdf" target="_blank">DECRETO Nº 1653 DE 16 DE DEZEMBRO DE 2021</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre a regulamentação dos critérios para a fixação de metas fiscais de arrecadação do Imposto Sobre Serviços de Qualquer Natureza – ISSQN, e institui a bonificação prevista na Lei n.º 2.040/2014.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/11/DECRETO-Nº-1193-2021-Altera-o-Decreto-Nº-165-2014-ISSQN.pdf" target="_blank">DECRETO Nº 1.193 DE 03 DE AGOSTO DE 2021</a></strong></p>
<p style="text-align: justify;">“Altera o Decreto n.º 165, de 12 de fevereiro de 2014.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/11/SEFIN-EDITAL-Nº-001-2021-NOTIFICAÇÃO-DE-LANÇAMENTO-DO-ISSQN-2021-PROFISSIONAL-AUTONOMO.pdf" target="_blank">SEFIN – EDITAL Nº 001/2021 – NOTIFICAÇÃO DE LANÇAMENTO DO ISSQN PROFISSIONAL AUTÔNOMO-EXERCÍCIO 2021</a></strong></p>
<p style="text-align: justify;">“A SECRETARIA MUNICIPAL DE FINANÇAS, por meio da Diretoria de Administração Tributária e da Divisão de imposto Sobre Serviços de Qualquer Natureza -ISSQN, pelo presente edital. NOTIFICA, nos termos do art. 65, §5°, da Lei Complementar n° 1.508/2003, os contribuintes enquadrados como Profissionais Autônomos e Sociedade de Profissionais Autônomos, do lançamento do ISSON fixo anual referente ao exercício 2021, com vencimento para o dia 26/02/2021. O Documento de Arrecadação Municipal – DAM para recolhimento do imposto deve ser retirado nos Centros de Atendimento ao Contribuinte – CAC’s (Anexo) ou por meio do Portal de Serviços “on-line” disponível no endereço eletrônico ou http://portalcidadao.riobranco.ac.gov.br/emissao-issqn-fixo. Após o vencimento, fica o contribuinte sujeito aos acréscimos e cominações legais. E facultado ao contribuinte, nos termos do artigo 353 da Lei Complementar n° 1.508/2003, apresentar impugnação contra o lançamento do crédito tributário, mediante petição fundamentada, instruída com as provas cabíveis, no prazo de 30 (trinta) dias contados da data da publicação deste edital, sob pena de preclusão do direito.”</p>
<hr>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/11/DECRETO-Nº-879-2020-Altera-a-meta-de-arrecadação-do-ISSQN-2020.pdf" target="_blank">DECRETO Nº 879 DE 23 DE NOVEMBRO DE 2020</a></strong></p>
<p style="text-align: justify;">Alterar para R$ 72.842.069,60 (setenta e dois milhões, oitocentos e quarenta e dois mil, sessenta e nove reais e sessenta centavos), a meta de arrecadação do Imposto sobre Serviços de Qualquer Natureza – ISSQN, para exercício de 2020</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/11/DECRETO-Nº-878-2020-Altera-o-Decreto-Municipal-nº-639-2014-ISSQN.pdf" target="_blank">DECRETO Nº 878 DE 23 DE NOVEMBRO DE 2020</a></strong></p>
<p style="text-align: justify;">“Altera o Decreto Municipal nº 639, de 16 de maio de 2014”.</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/11/DECRETO-Nº-414-2020-Fixa-a-meta-de-arrecadação-do-ISSQN-2020.pdf" target="_blank">DECRETO Nº 414 DE 26 DE JUNHO DE 2020</a></strong></p>
<p style="text-align: justify;">Fica fixada como meta de arrecadação do Imposto sobre Serviços de Qualquer Natureza – ISSQN, para o exercício de 2020, o valor de R$ 90.332.129,00 (noventa milhões, trezentos e trinta e dois mil e cento e vinte nove reais).</p>
<hr>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/11/DECRETO-Nº-1742-2019-Altera-o-Decreto-nº-652-2019-Fixa-a-meta-de-arrecadação-do-ISSQN-2019.pdf" target="_blank">DECRETO Nº 1.742 DE 25 DE NOVEMBRO DE 2019</a></strong></p>
<p style="text-align: justify;">“Alterar para R$ 82.939.972,00 (oitenta e dois milhões, novecentos e trinta e nove mil, novecentos e setenta e dois reais), a meta de arrecadação do Imposto sobre Serviços de Qualquer Natureza – ISSQN, para exercício de 2019.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/11/2019-SEFIN-IS-Nº-002-2019-Dispõe-sobre-procedimentos-de-monitoramento-fiscal-ISSQN.pdf" target="_blank">INSTRUÇÃO DE SERVIÇO Nº 02, DE 22 DE ABRIL DE 2019</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre procedimentos de monitoramento fiscal para acompanhamento, controle e avaliação das obrigações tributárias dos contribuintes de maior interesse de arrecadação. ”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/11/DECRETO-Nº-652-2019-Fixa-a-meta-de-arrecadação-do-ISSQN-2019.pdf" target="_blank">DECRETO Nº 652 DE 19 DE FEVEREIRO DE 2019</a></strong></p>
<p style="text-align: justify;">“Fica fixada como meta de arrecadação do Imposto sobre Serviços de Qualquer Natureza – ISSQN, para exercício de 2019, o valor de R$ 100.423.171,47 (cem milhões quatrocentos e vinte e três mil, cento e setenta e um reais e quarenta e sete centavos).”</p>
<hr>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/11/DECRETO-Nº-276-2018-Fixa-a-meta-de-arrecadação-do-ISSQN-2018.pdf" target="_blank">DECRETO Nº 276 DE 28 DE MARÇO DE 2018</a></strong></p>
<p style="text-align: justify;">“Fica fixada como meta de arrecadação do Imposto sobre Serviços de Qualquer Natureza – ISSQN para exercício de 2018, o valor de R$ 82.713.842,16 (oitenta e dois milhões, setecentos e treze mil, oitocentos e quarenta e dois reais e dezesseis centavos).”</p>
<hr>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/11/DECRETO-Nº-1812-2017-SEFIN-Parcelamento-de-crédito-tributário-do-exercício-2017.pdf" target="_blank">DECRETO Nº 1.812 DE 29 DE SETEMBRO DE 2017</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre o parcelamento de crédito&nbsp;tributário do exercício 2017.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/11/DECRETO-Nº-1676-2017-Fixa-a-meta-de-arrecadação-do-ISSQN-2017.pdf" target="_blank">DECRETO Nº 1.676 DE 24 DE AGOSTO DE 2017</a></strong></p>
<p style="text-align: justify;">“Fica fixada como meta de arrecadação do Imposto sobre Serviços de Qualquer Natureza – ISSQN para o ano de 2017, o valor de R$ 69.394.341,50 (sessenta e nove milhões, trezentos e noventa e quatro mil e trezentos e quarenta e um reais e cinquenta centavos).”</p>
<hr>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/portal/wp-content/uploads/2015/02/DECRETO-N%C2%BA-948-DE-07-DE-NOVEMBRO-DE-2016.pdf" target="_blank" data-slimstat="3">DECRETO Nº 948 DE 07 DE NOVEMBRO DE 2016</a></strong></p>
<p style="text-align: justify;">Fica fixada como meta de arrecadação do Imposto sobre Serviços de Qualquer Natureza – ISSQN para o ano de 2016, o valor de R$ 65.000.000,00 (sessenta e cinco milhões reais).</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/portal/wp-content/uploads/2015/02/DECRETO-N%C2%BA-449-DE-07-DE-JUNHO-DE-2016.pdf" target="_blank" data-slimstat="3">DECRETO Nº 449 DE 07 DE JUNHO DE 2016</a></strong></p>
<p style="text-align: justify;">Fica fixada como meta de arrecadação do Imposto sobre Serviços de Qualquer Natureza – ISSQN para o ano de 2016, o valor de R$ 69.500.000,00 (sessenta e nove milhões e quinhentos mil reais)</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/portal/wp-content/uploads/2015/02/LEI-N%C2%BA-2.174-de-01-de-Abirl-de-2016-Altera-a-Lei-Municipal-n%C2%BA-2.040-2014-ISSQN.pdf" target="_blank" data-slimstat="3">LEI Nº 2.174 DE 01 DE ABRIL DE 2016</a></strong></p>
<p style="text-align: justify;">“Altera a Lei Municipal nº 2.040 de 09 de Abril de 2014.”</p>
<hr>
<p><strong><a href="http://portalcgm.riobranco.ac.gov.br/portal/wp-content/uploads/2013/10/LEI-COMPLEMENTAR-N%C2%BA-17-DE-17.12.2015-Altera-a-Lei-Complementar-n%C2%BA-03-2013.pdf" target="_blank">LEI COMPLEMENTAR Nº 17 DE 17 DE DEZEMBRO DE 2015</a></strong></p>
<p>“Altera a Lei Complementar nº 03, de 17 de setembro de 2013.”</p>
<p><strong><a href="http://portalcgm.riobranco.ac.gov.br/portal/wp-content/uploads/2013/10/LEI-COMPLEMENTAR-N%C2%BA-16-DE-08.12.2015-Altera-a-Lei-Complementar-n%C2%BA-014-2015.pdf" target="_blank">LEI COMPLEMENTAR Nº 16 DE 08 DE DEZEMBRO DE 2015</a></strong></p>
<p>“Altera a Lei Complementar nº 14, de 27 de março de 2015.”</p>
<p><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/11/DECRETO-Nº-1188-2015-Revoga-o-Dec-nº-278-2015-Fixa-a-meta-de-arrecadação-do-ISSQN.pdf" target="_blank">DECRETO Nº 1.188 DE 13 DE NOVEMBRO DE 2015</a></strong></p>
<p>“Fica fixada como meta de arrecadação do Imposto sobre Serviços de Qualquer Natureza – ISSQN para o ano de 2015, o valor de R$ 63.500.000,00 (sessenta e três milhões e quinhentos mil reais).”</p>
<p><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/11/SEFIN-INSTRUÇÃO-NORMATIVA-Nº-01-Normas-para-o-recolhimento-do-ISSQN.docx" target="_blank">INSTRUÇÃO NORMATIVA Nº 01, DE 11 DE JUNHO DE 2015</a></strong></p>
<p>“Institui normas para recolhimento do ISSQN nos serviços previstos no item 8 do Art. 55 da lei nº 1.508/2003, no Município de Rio Branco/AC.”</p>
<p><strong><a href="http://portalcgm.riobranco.ac.gov.br/portal/wp-content/uploads/2013/10/LEI-COMPLEMENTAR-N%C2%BA-14-DE-27.03.2015-Concede-isen%C3%A7%C3%A3o-condicionada-do-ISSQN-as-empresas-de-transporte-coletivo.pdf" target="_blank">LEI COMPLEMENTAR Nº 14 DE 27 DE MARÇO DE 2015</a>&nbsp;</strong><span style="color: #ff0000;">(Alterada pela&nbsp;LEI COMPLEMENTAR Nº 16 DE 08 DE DEZEMBRO DE 2015)</span></p>
<p>“Concede isenção condicionada do Imposto sobre Serviços de Qualquer Natureza – ISSQN e da Outorga às empresas de transporte coletivo.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/11/DECRETO-Nº-278-2015-Fixa-a-meta-de-arrecadação-do-ISSQN.pdf" target="_blank">DECRETO Nº 278 DE 23 DE MARÇO DE 2015</a></strong></p>
<p style="text-align: justify;">“Fica fixada a meta de arrecadação do Imposto sobre Serviços de Qualquer Natureza – ISSQN para o ano de 2015, no valor de R$ 73.473.432,10 (setenta e três milhões, quatrocentos e setenta e três mil, quatrocentos e trinta e dois reais e dez centavos).”</p>
<hr>
<p><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/images/ARQUIVOS/24_Legisla%C3%A7%C3%A3o/LEIS%20COMPLEMENTARES/LEI%20COMPLEMENTAR%20N%C2%BA%2010%20DE%2010.06.2014%20-%20Altera%20a%20Lei%20Complementar%20Municipal%20n%C2%BA%2004.pdf" target="_blank">LEI COMPLEMENTAR Nº 10 DE 10 DE JUNHO DE 2014</a></strong></p>
<p>“Altera a Lei Complementar Municipal nº 04, de 16 de outubro de 2013.”</p>
<p><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/images/ARQUIVOS/24_Legisla%C3%A7%C3%A3o/LEIS%20COMPLEMENTARES/LEI%20COMPLEMENTAR%20N%C2%BA%2009%20DE%2019%20DE%20MAIO%20DE%202014.pdf" target="_blank">LEI COMPLEMENTAR Nº 09 DE 19 DE MAIO DE 2014</a></strong></p>
<p>“Altera a Lei Complementar Municipal nº 03, de 17 de setembro de 2013.”</p>
<p><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/11/DECRETO-Nº-639-2014-Regulamentãção-dos-criterios-para-fixação-das-metas-fiscais-de-arrecadação-ISSQN.pdf" target="_blank">DECRETO Nº 639 DE 16 DE MAIO DE 2014</a></strong></p>
<p>“Dispõe sobre a regulamentação dos critérios para a fixação de metas fiscais de arrecadação do Imposto Sobre Serviços de Qualquer Natureza – ISSQN e instituição da bonificação por alcance de resultados.”</p>
<p><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/11/4-LEI-Nº-2.040-DE-09-DE-ABRIL-DE-2014-critérios-para-a-fixação-de-metas-fiscais-de-arrecadação-do-ISSQN.pdf" target="_blank">LEI N.º 2.040 DE 09 DE ABRIL DE 2014</a></strong></p>
<p style="text-align: justify;">“Estabelece critérios para a fixação de metas fiscais de arrecadação do Imposto Sobre Serviços de Qualquer Natureza – ISSQN e institui a bonificação por alcance de resultados.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/11/DECRETO-Nº-165-2014-Regulamenta-o-regime-de-substituição-tributaria-do-ISSQN.pdf" target="_blank">DECRETO Nº 165 DE 12 DE FEVEREIRO DE 2014</a></strong></p>
<p style="text-align: justify;">“Regulamenta o regime de substituição tributária do Imposto Sobre Serviços de Qualquer Natureza – ISSQN, instituído pela Lei Complementar n° 03, de 17 de setembro de 2013.”</p>
<hr>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/11/DECRETO-Nº-2232-2013-Regulamenta-o-ISSQN.pdf" target="_blank">DECRETO Nº 2.232 DE 16 DE DEZEMBRO DE 2013</a></strong></p>
<p style="text-align: justify;">“Regulamenta o regime de substituição tributária do Imposto Sobre Serviços de Qualquer Natureza – ISSQN, instituído pela Lei Complementar n° 03, de 17 de setembro de 2013.”</p>
<p><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/images/ARQUIVOS/24_Legisla%C3%A7%C3%A3o/LEIS%20COMPLEMENTARES/LEI%20COMPLEMENTAR%20N%C2%BA%2004%20DE%2016.10.2013%20-%20Isen%C3%A7%C3%A3o%20Condicionada%20do%20ISSQN%20as%20empresas%20de%20Transporte%20Coletivo.pdf" target="_blank">LEI COMPLEMENTAR Nº 04 DE 16 DE OUTUBRO DE 2013</a>&nbsp;</strong><span style="color: #ff0000;">(Alterada pela&nbsp;LEI COMPLEMENTAR Nº 10 DE 10 DE JUNHO DE 2014)</span></p>
<p>“Concede isenção condicionada do Imposto sobre Serviços de Qualquer Natureza – ISSQN e da outorga às empresas de transporte coletivo.”</p>
<p><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/images/ARQUIVOS/24_Legisla%C3%A7%C3%A3o/LEIS%20COMPLEMENTARES/LEI%20COMPLEMENTAR%20N%C2%BA%2003%20DE%2017.09.2013%20-%20Institui%20a%20substitui%C3%A7%C3%A3o%20tribut%C3%A1ria%20para%20o%20ISSQN%20-%20CTN.pdf" target="_blank">LEI COMPLEMENTAR Nº 03 DE 17 DE SETEMBRO DE 2013</a>&nbsp;</strong><span style="color: #ff0000;">(Alterada pela&nbsp;LEI COMPLEMENTAR Nº 09 DE 19 DE MAIO DE 2014 e pela LEI COMPLEMENTAR Nº 17 DE 17 DE DEZEMBRO DE 2015)</span></p>
<p>“Institui a substituição tributária para o ISSQN, prevista no artigo 128 do Código Tributário Nacional e artigo 59, § 1º do Código Tributário Municipal.”</p>
<hr>
<p><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2013/11/2012-LEI-Nº-1.891-de-27.03.2012-Lei-de-Isenção-de-Impostos-devido-a-Calamidade-Publica.pdf" target="_blank">LEI Nº 1.891 DE 27 DE MARÇO DE 2012</a></strong></p>
<p>“Dispõe sobre isenção do Imposto Sobre Serviços de Qualquer Natureza – ISSQN e remissão do Imposto sobre a Propriedade Predial e Territorial Urbana – IPTU e sobre a Taxa de Remoção de Resíduos Sólidos e Entulhos, aos prestadores de serviços e proprietários de imóveis prejudicados por Calamidade Pública, e dá outras providências.”</p>
<hr>
<p><strong><a href="/lai/wp-content/uploads/images/ARQUIVOS/24_Legislação/DECRETOS/Decreto_N_2525_de_26.05.2011_-_Regulamenta_a_reteno_de_Impostos_sobre_servios_de_qualquer_natureza_-_ISSQN.pdf" target="_blank">DECRETO Nº 2.525, DE 26 DE MAIO DE 2011</a></strong></p>
<p style="text-align: justify;">“Regulamenta a retenção do Imposto Sobre Serviços de Qualquer Natureza – ISSQN, prevista no art. 61 da Lei nº 1.508, de 08 de dezembro de 2003 e dá outras providências.”</p>
</div>';
BEGIN
update PAGINAPREFEITURAPORTAL
set CONTEUDOHTML = texto
where NOME = 'Imposto sobre Serviços de Qualquer Natureza - ISSQN' and CHAVE = 'issqn';
END;
