insert into MODELODOCTOOFICIAL (ID, TIPODOCTOOFICIAL_ID, VIGENCIAINICIAL, SEQUENCIA)
VALUES (HIBERNATE_SEQUENCE.nextval, (select tdo.id from TIPODOCTOOFICIAL tdo where tdo.CODIGO = 149 and tdo.MODULOTIPODOCTOOFICIAL = 'NOTA_RECEITA_EXTRA'), sysdate, 1)
