insert into MODELODOCTOOFICIAL (ID, TIPODOCTOOFICIAL_ID, VIGENCIAINICIAL, SEQUENCIA)
VALUES (HIBERNATE_SEQUENCE.nextval, (select tdo.id from TIPODOCTOOFICIAL tdo where tdo.CODIGO = 153 and tdo.MODULOTIPODOCTOOFICIAL = 'NOTA_RECEITA_EXTRA_ESTORNO'), sysdate, 1)
