delete from CONTAACOMPAFINANCEIRO c where c.unidade_id in (
select un.id
FROM UNIDADEACOMPAFINANCEIRO UN
where un.TIPORELATORIOACOMPANHAMENTO = 'LIBERACAO_FINANCEIRA_POR_MES'
);

delete from FILTROACOMPAFINANCEIRO c where c.unidade_id in (
select un.id
FROM UNIDADEACOMPAFINANCEIRO UN
where un.TIPORELATORIOACOMPANHAMENTO = 'LIBERACAO_FINANCEIRA_POR_MES'
);

delete
FROM UNIDADEACOMPAFINANCEIRO UN
where un.TIPORELATORIOACOMPANHAMENTO = 'LIBERACAO_FINANCEIRA_POR_MES';
