DECLARE
texto            CLOB := '<div class="post-content"><hr>
<p style="text-align: justify;"><strong>ANO 2024</strong></p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-1619-2024-Declara-Situação-de-Emergência-–-ETA-1.pdf" target="_blank">DECRETO Nº 1.619 DE 30 DE DEZEMBRO DE 2024</a></strong></p>
<p style="text-align: justify;">“Declara situação anormal, caracterizada como “SITUAÇÃO DE EMERGÊNCIA” na área onde está localizada a captação de água da Estação de Tratamento – ETA I, de Rio Branco”.</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-1250-2024-Declara-Situação-de-Emergência-–-Incêndios.pdf" target="_blank">DECRETO Nº 1.250 DE 21 DE SETEMBRO DE 2024</a></strong></p>
<p style="text-align: justify;">“Declara Situação de Emergência em Saúde Pública e Ambiental no âmbito do município de Rio Branco, e dá outras providências.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-830-2024-–-Declara-Situação-de-Emergência-nas-áreas-do-município-afetadas-pelo-evento-adverso-de-ESTIAGEM-2.pdf" target="_blank">DECRETO Nº 830 DE 28 DE JUNHO DE 2024</a></strong></p>
<p style="text-align: justify;">“Declara Situação de Emergência nas áreas do município, afetadas pelo evento adverso de ESTIAGEM – COBRADE 1.4.1.1.0, conforme Instrução Normativa nº 36, de 4 de dezembro de 2020, do Ministério do Desenvolvimento Regional.”</p>
<p><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-537-2024-Declara-Situação-de-Emergência-–-Inundação.pdf" target="_blank">DECRETO Nº 537 DE 24 DE ABRIL DE 2024</a></strong></p>
<p>“Altera o Decreto nº 256 de 26 de fevereiro de 2024 que declara situação anormal, caracterizada como SITUAÇÃO de EMERGÊNCIA’’ nas áreas do Município de Rio Branco afetadas pela ocorrência de inundação”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-509-2024-–-Alterar-o-Decreto-nº-256-2024-–-Declara-Situação-de-Emergência-–-Enxurradas.pdf" target="_blank">DECRETO Nº 509 DE 19 DE ABRIL DE 2024</a></strong></p>
<p style="text-align: justify;">“Altera o Decreto nº 265 de 26 de fevereiro de 2024 que declara situação anormal, caracterizada como SITUAÇÃO de EMERGÊNCIA nas áreas do município de Rio Branco pela ocorrência de enxurradas.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-443-2024-Declara-Situação-de-Emergência-–-ETA-II.pdf" target="_blank">DECRETO Nº 443 DE 08 DE ABRIL DE 2024</a></strong></p>
<p style="text-align: justify;">“Declara situação anormal, caracterizada como “SITUAÇÃO DE EMERGÊNCIA” na área onde está localizada a captação de água da Estação de Tratamento – ETA II, de Rio Branco.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-331-2024-Comissão-de-Licitação-Especial-de-Emergência-CLEE-2.pdf" target="_blank">DECRETO Nº 331 DE 12 DE MARÇO DE 2024</a></strong></p>
<p style="text-align: justify;">“Instituir e nomear a Comissão de Licitação Especial de Emergência – CLEE, do Município de Rio Branco, para aquisição de itens essenciais e de combustível, com fito de mitigar os impactos do desastre.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/TCE-ATO-Nº-008-DE-11-DE-MARÇO-DE-2024-CONTRATOS-EMERGÊNCIAIS.pdf" target="_blank">TCE – ATO Nº 08, DE 11 DE MARÇO DE 2024</a></strong>&nbsp;– DEC 2243 – 12/03/2024</p>
<p style="text-align: justify;">“Estabelece recomendações e instruções aos jurisdicionados do Tribunal de Contas do Estado do Acre sobre processos referentes a contratações diretas com fulcro no art. 75, inciso VIII, da Lei Federal nº 14.133, de 1º de abril de 2021 (Lei de Licitações e Contratos Administrativos), que versa sobre a dispensabilidade de licitação nos casos de emergência ou de calamidade pública.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-279-2024-Declara-Situalção-de-Emergência-em-Saúde-Pública.pdf" target="_blank">DECRETO Nº 279 DE 04 DE MARÇO DE 2024</a></strong></p>
<p style="text-align: justify;">“Declara Situação de Emergência em Saúde Pública em virtude do aumento do volume das chuvas, elevação do nível dos rios da região e represamento dos Igarapés e córregos, provocando alagações em bairros e ruas da zona urbana e rural desta cidade gerando ausência de condições de atendimento às demandas por ações e serviços públicos de saúde em virtude da situação de desastre”.</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-265-2024-Declara-Situação-de-Emergência-Enxurrada.pdf" target="_blank">DECRETO Nº 265 DE 26 DE FEVEREIRO DE 2024</a></strong></p>
<p style="text-align: justify;">“Declara situação anormal, caracterizada como “SITUAÇÃO de EMERGÊNCIA” nas áreas do município de Rio Branco pela ocorrência de enxurradas”.</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-256-2024-Declara-Situação-de-Emergência-Inundação.pdf" target="_blank">DECRETO Nº 256 DE 26 DE FEVEREIRO DE 2024</a></strong></p>
<p style="text-align: justify;">“Declara a existência de anormalidade, caracterizada como “SITUAÇÃO DE EMERGÊNCIA” nas áreas do Município de Rio Branco afetadas pela ocorrência de inundação”</p>
<hr>
<p style="text-align: justify;"><strong>ANO 2023</strong></p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-1770-2023-Regularização-de-pendências-cadastro-Auxílio-Recomeço-para-Empreendedor-ARE.pdf" target="_blank">DECRETO Nº 1.770 DE 07 DE NOVEMBRO DE 2023</a></strong></p>
<p style="text-align: justify;">“Fica estabelecido o prazo excepcional de até 14 de novembro de 2023, para regularização por pendências documentais dos cadastros que foram indeferidos no projeto “Auxílio Recomeço para o empreendedor – ARE.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-1580-2023-COMDEC-Aprova-o-Plano-de-Contingências-de-Inundação-2023.pdf" target="_blank">DECRETO Nº 1.580 DE 27 DE SETEMBRO DE 2023</a>&nbsp;</strong></p>
<p style="text-align: justify;">“Fica aprovado o Plano de Contingência de Inundação do Município de Rio Branco – 2023, na forma do Anexo deste Decreto.”</p>
<p style="text-align: justify;"><a href="http://portalcgm.riobranco.ac.gov.br/portal/wp-content/uploads/2015/02/PLANO-DE-CONTING%C3%8ANCIA-DE-INUNDA%C3%87%C3%83O-2023.pdf" target="_blank">Plano de Contingência de Inundação do Município de Rio Branco 2023</a></p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-1579-2023-Altera-o-Decreto-nº-1471-2023-Auxílio-Recomeço.pdf" target="_blank">D</a></strong><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-1579-2023-Altera-o-Decreto-nº-1471-2023-Auxílio-Recomeço.pdf" target="_blank">ECRETO Nº 1.579 DE 27 DE SETEMBRO DE 2023</a>&nbsp;</strong>(Auxílio Recomeço para Empreendedor)</p>
<p style="text-align: justify;">“O §2º do art. 6º do Decreto nº 1.471 de 31 de agosto de 2023, que dispõe sobre a regulamentação do projeto “Auxílio Recomeço para o empreendedor – ARE” disciplinado pela Lei Complementar nº 222 de 05 de maio de 2023, passa a vigorar com a seguinte redação.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-1578-2023-Declara-Situação-de-Emergência-Estiagem.pdf" target="_blank">DECRETO Nº 1.578 DE 27 DE SETEMBRO DE 2023</a></strong>&nbsp;– (Estiagem)</p>
<p style="text-align: justify;">“Declara Situação de Emergência nas áreas do município, afetadas pelo evento adverso de ESTIAGEM – COBRADE 1.4.1.1.0, conforme Instrução Normativa nº 36, de 4 de dezembro de 2020, do Ministério do Desenvolvimento Regional.</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-1546-2023-Regulamenta-a-Lei-Complementar-nº-219-2023-Projeto-Recomeço-para-as-Famílias.pdf" target="_blank">DECRETO Nº 1.546 DE 22 DE SETEMBRO DE 2023</a></strong>&nbsp;(Projeto Recomeço para a Família)</p>
<p style="text-align: justify;">“Este Decreto dispõe sobre as condições e os critérios a serem atendidos pelos beneficiários para cadastramento e concessão, a catalogação dos bens e itens a serem entregues, a forma e o prazo de entrega e sua operacionalização do “Projeto Recomeço para a Família”, conforme o artigo 13 da Lei Complementar 219/2023 e dá outras providências.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/PORTARIA-FEDERAL-Nº-2.994-DE-22-DE-SETEMBRO-DE-2023-DOU.pdf" target="_blank">SECRETARIA NACIONAL DE PROTEÇÃO E DEFESA CIVIL – PORTARIA Nº 2.994 DE 22 DE SETEMBRO DE 2023</a></strong></p>
<p style="text-align: justify;">“Prorrogar o prazo de execução das ações de resposta, previsto no art. 3° da Portaria n. 1.209, de 27 de março de 2023, constante no processo administrativo n. 59052.014033/2023-79, que autorizou o empenho e a transferência de recursos ao Município de Rio Branco – AC, para ações de Defesa Civil até 23/11/2023.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-1471-2023-Regulamentação-do-projeto-Auxilio-Recomeço.pdf" target="_blank">DECRETO Nº 1.471 DE 31 DE AGOSTO DE 2023</a>&nbsp;</strong>(Auxílio Recomeço para Empreendedor)</p>
<p style="text-align: justify;">“Dispõe sobre a regulamentação do projeto “Auxílio Recomeço para o empreendedor – ARE” disciplinado pela Lei Complementar nº 222 de 05 de maio de 2023.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-COMPLEMENTAR-Nº-236-DE-20.07.2023-Remissão-do-IPTU-e-Taxa-de-remoção-de-Resíduos-Sólidos-e-Entulhos-Enchentes.pdf" target="_blank">LEI COMPLEMENTAR Nº 236 DE 20 DE JULHO DE 2023</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre a remissão do Imposto sobre Propriedade Predial e Territorial Urbana – IPTU e taxa de remoção de resíduos sólidos e entulhos, incidentes sobre os imóveis edificados atingidos por enchentes, inundações e/ou alagamentos causado pelas chuvas ocorridas no município de Rio Branco”.</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-COMPLEMENTAR-Nº-219-DE-17.04.2023-Benefício-Eventual-de-Auxílio-a-famílias-–-Projeto-Recomeço-para-a-Família.pdf" target="_blank">LEI COMPLEMENTAR Nº 219 DE 17 DE ABRIL DE 2023</a>&nbsp;</strong>(Projeto Recomeço para a Família)</p>
<p style="text-align: justify;">“Dispõe sobre a instituição do Benefício Eventual de Auxílio a famílias que se encontram em vulnerabilidade temporária – denominado “Projeto Recomeço para a Família”, que consiste na entrega de bens e itens familiares novos para substituir os que foram danificados por desastres naturais ocasionados pela enxurrada dos igarapés e/ou pela inundação do Rio Acre; e dispõe sobre abertura de crédito adicional extraordinário por anulação parcial de dotação em favor da Secretaria Municipal de Assistência Social e Direitos Humanos – SASDH, e dá outras providências”.</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-411-2023-Declara-SITUAÇÃO-DE-EMERGÊNCIA-ENXURRADA-2023-2.pdf" target="_blank">DECRETO Nº 411 DE 24 DE MARÇO DE 2023</a></strong></p>
<p style="text-align: justify;">“Declara situação anormal, caracterizada como SITUAÇÃO DE EMERGÊNCIA nas áreas do município de Rio Branco pela ocorrência de enxurradas.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-412-2023-Declara-SITUAÇÃO-DE-EMERGÊNCIA-ENCHENTES-2023-2.pdf" target="_blank">DECRETO Nº 412 DE 24 DE MARÇO DE 2023</a></strong></p>
<p style="text-align: justify;">“Declara a existência de anormalidade, caracterizada como “SITUAÇÃO DE EMERGÊNCIA” nas áreas do Município de Rio Branco afetadas pela ocorrência de inundação.”</p>
<hr>
<p style="text-align: justify;"><strong>ANO 2022</strong></p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2022-DECRETO-Nº-1779-2022-Dispõe-sobre-medidas-protetivas-excepcionais-e-temporarias-COVID-19-DOE.pdf" target="_blank">DECRETO Nº 1.779 DE 06 DE DEZEMBRO DE 2022</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre medidas protetivas excepcionais e temporárias decorrentes do agravamento da situação epidemiológica da COVID-19 no âmbito do Município de Rio Branco – Acre.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2022-DECRETO-Nº-935-2022-SEMSA-Revogar-as-normas-COVID-19.pdf" target="_blank">DECRETO Nº 935 DE 13 DE JUNHO DE 2022</a></strong></p>
<p style="text-align: justify;">“Ficam revogadas, em virtude da Portaria GM/MS nº 913, de 22&nbsp;de abril de 2022, que declarou o encerramento da Emergência em Saúde Pública de Importância Nacional (ESPIN) em decorrência da infecção humana pelo novo coronavírus (2019- nCoV), as seguintes normas.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2022-DECRETO-Nº-061-2022-Altera-o-Decreto-060-2022-Estado-de-Emergência.pdf" target="_blank">DECRETO Nº 061 DE 14 DE JANEIRO DE 2022</a></strong></p>
<p style="text-align: justify;">“O Decreto nº 060, de 13 de janeiro de 2022, passa a vigorar com as seguintes alterações.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2022-DECRETO-Nº-060-2022-Ficam-suspensas-todas-as-licenças-ou-afastamento-legais-Estado-de-Emergência-COVID-19.pdf" target="_blank">DECRETO Nº 060 DE 13 DE JANEIRO DE 2022</a></strong></p>
<p style="text-align: justify;">“Ficam suspensas todas licenças ou afastamento legais em gozo dos profissionais de saúde ou daqueles que desempenhem funções essenciais em virtude da decretação do Estado de Emergência no âmbito do Munícipio de Rio Branco.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-020-2022-Delcara-Situação-de-Emergência-em-Saúde-Pública-COVID-191.pdf" target="_blank">DECRETO Nº 020 DE 10 DE JANEIRO DE 2022</a></strong></p>
<p style="text-align: justify;">“Declara Situação de Emergência em Saúde Pública em virtude do aumento de casos de Síndrome Gripal (causada pelo Vírus SARS-CoV-2 e Vírus da Influenza) – Doença Infecciosa Viral COBRADE 1.5.1.1.0.”</p>
<hr>
<p style="text-align: justify;"><strong>ANO 2021</strong></p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-1694-2021-Situação-de-Emergência-no-Serviço-de-Transporte-Coletivo-Urbano-de-Passageiros.pdf" target="_blank">DECRETO 1.694 DE 20 DE DEZEMBRO DE 2021</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre a situação de emergência no serviço de Transporte Coletivo Urbano de Passageiros do Município de Rio Branco.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2021-DECRETO-Nº-1556-2021-Distribuição-de-merenda-escolar-aos-alunos-da-rede-pública-municipal-COVID-19-DOE.pdf" target="_blank">DECRETO Nº 1.556 DE 11 DE NOVEMBRO DE 2021</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre medidas a serem adotadas para a garantia da distribuição da merenda escolar aos alunos da rede pública municipal, em decorrência da pandemia da COVID-19.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-1257-2021-Declara-Situação-de-Emergência-ESTIAGEM.pdf" target="_blank">DECRETO Nº 1257 DE 30 DE AGOSTO DE 2021</a></strong></p>
<p style="text-align: justify;">“Declara Situação de Emergência nas áreas do município, afetadas pelo evento adverso de ESTIAGEM – COBRADE 1.4.1.1.0, conforme Instrução Normativa nº 36, de 4 de dezembro de 2020, do Ministério do Desenvolvimento Regional.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2021-DECRETO-Nº-1188-2021-Altera-o-Decreto-Nº-1000-2021-Retorno-às-Atividades-COVID-19.pdf" target="_blank">DECRETO Nº 1.188 DE 02 DE AGOSTO DE 2021</a></strong></p>
<p style="text-align: justify;">“A Alínea “a” do inciso III do art. 1º do Decreto nº 1.000 de 26 de maio de 2021, passa a vigorar com a seguinte redação.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2021-DECRETO-Nº-1000-2021-Retorno-às-Atividades-na-Adm.-Pública-Direta-e-Indireta-COVID-19.pdf" target="_blank">DECRETO Nº 1.000 DE 26 DE MAIO DE 2021</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre a retomada de atividades presenciais e do atendimento ao público pela Administração Pública Municipal.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2021-DECRETO-Nº-797-2021-Tornar-sem-efeito-o-Decreto-nº-792-2021-Igrejas-COVID-19.pdf" target="_blank">DECRETO Nº 797 DE 10 DE ABRIL DE 2021</a></strong></p>
<p style="text-align: justify;">“Tornar sem efeito o Decreto nº 792, de 09 de abril de 2021.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2021-DECRETO-Nº-792-2021-Permite-a-abertura-das-igrejas-COVID-19.pdf" target="_blank">DECRETO Nº 792 DE 09 DE ABRIL DE 2021</a></strong></p>
<p style="text-align: justify;">“Ficam permitidos, nos finais de semanas, feriados e pontos facultativos, restrito ao período de 7h às 18h, os eventos religiosos em templos ou locais públicos, de qualquer credo ou religião, desde que respeitados os protocolos definidos pelo Ministério da Saúde e de acordo com as medidas de Toque de Restrição estabelecidas pelo Comitê Estadual de Acompanhamento Especial da COVID-19.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2021-DECRETO-Nº-759-2021-Dispõe-sobre-a-Retomada-das-Atividades-nos-CACS-COVID-19.pdf" target="_blank">DECRETO N.º 759 DE 1º DE ABRIL DE 2021</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre a retomada das atividades nos Centros de Atendimento ao Cidadão.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-741-2021-Institui-e-nomeia-Comissão-Especial-de-Contratação-Emergêncial-ENCHENTE.pdf" target="_blank">DECRETO Nº 741 DE 26 DE MARÇO DE 2021</a></strong></p>
<p style="text-align: justify;">“Institui e nomeia Comissão Especial de Contratações de Emergência em decorrência da enchente do Rio Acre, em atenção ao estabelecido na Lei Federal nº 12.340 de 1º de dezembro de 2010 e na Portaria nº 334, de 26 de fevereiro de 2021, da Secretaria Nacional de Proteção e Defesa Civil.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2021-DECRETO-Nº-524-2021-Altera-o-Decreto-Nº-362-20201-Secretarias-de-natureza-essencial.pdf" target="_blank">DECRETO Nº 524 DE 19 DE FEVEREIRO DE 2021</a></strong></p>
<p style="text-align: justify;">“Altera o Decreto n° 362, de 02 de fevereiro de 2021.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-496-2021-Declara-Situação-de-Emergência-ENCHENTES.pdf" target="_blank">DECRETO Nº 496 DE 16 DE FEVEREIRO DE 2021</a></strong></p>
<p style="text-align: justify;">“Declara a existência de anormalidade, caracterizada como “SITUAÇÂO DE EMERGÊNCIA” nas áreas do Município de Rio Branco afetadas pela ocorrência de enchente do Rio Acre.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-420-2021-Declara-Situação-de-Emergência-ENXURRADAS-2021.pdf" target="_blank">DECRETO Nº 420 DE 06 DE FEVEREIRO DE 2021</a></strong></p>
<p style="text-align: justify;">“Declara situação anormal, caracterizada como SITUAÇÃO de EMERGÊNCIA nas áreas do município de Rio Branco pela ocorrência de enxurradas.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2021-DECRETO-Nº-362-2021-Estabelece-medidas-excepcionais-e-temporárias-de-expediente-administrativo-COVID-19.pdf" target="_blank">DECRETO Nº 362 DE 02 DE FEVEREIRO DE 2021</a></strong></p>
<p style="text-align: justify;">“Estabelece medidas excepcionais e temporárias de expediente administrativo e atendimento ao público no âmbito do Município de Rio Branco.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-361-2021-Situação-de-Emergência-COVID-19.pdf" target="_blank">DECRETO N 361 DE 02 DE FEVEREIRO DE 2021</a></strong></p>
<p style="text-align: justify;">“Declara SITUAÇÃO DE EMERGÊNCIA e&nbsp;cria o Comitê de Enfrentamento e Monitoramento de Emergência para infecção humana pelo novo coronavírus (COVID-19) – CEME-COVID19 e dá outras providências.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-351-2021-Situação-de-Emergência-DENGUE-CHIKUNGUNYA-E-ZIKA-VÍRUS.pdf" target="_blank">DECRETO Nº 351 DE 1º DE FEVEREIRO DE 2021</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre a decretação de Situação de Emergência Municipal em razão de Epidemia por Doença Infecciosa Viral (Dengue) COBRADE 1.5.1.1.0, e determina atividades preventivas contra o vírus da Dengue, Chikungunya e Zica Vírus.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-326-2021-Institui-o-Gabinete-de-Gerenciamento-de-Crises-do-Município-de-Rio-Branco.pdf" target="_blank">DECRETO Nº 326 DE 28 DE JANEIRO DE 2021</a></strong></p>
<p style="text-align: justify;">“Institui o Gabinete de Gerenciamento de Crises do Município de Rio Branco – Estado do Acre e estrutura as atividades da Coordenadoria Municipal de Defesa Civil, e de outros órgãos do município, no atendimento de ocorrências conjunturais do âmbito de riscos, desastres, situações de emergência, calamidade pública, inundações, alagamentos, desmoronamentos e ameaças à segurança e defesa da cidadania do Município.”</p>
<hr>';
    complementoTexto CLOB := '<p style="text-align: justify;"><strong>ANO 2020</strong></p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2020-DECRETO-Nº-888-2020-Revogação-da-proibição-de-provadores-previsto-no-Decreto-nº-488-2020.pdf" target="_blank">DECRETO Nº 888 DE 25 DE NOVEMBRO DE 2020</a></strong></p>
<p style="text-align: justify;">“Revogar a proibição da utilização de provadores previsto no decreto municipal nº 488 de 20 de julho de 2020.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2020-DECRETO-Nº-840-2020-Incluir-no-Anexo-Único-do-Decreto-nº-488-2020-Protocolo-Sanitário.pdf" target="_blank">DECRETO Nº 840 DE 04 DE NOVEMBRO DE 2020</a></strong></p>
<p style="text-align: justify;">“Incluir no Anexo Único do Decreto nº 488, de 20 de julho de 2020, o Protocolo Sanitário para o uso de piscinas nas academias de ginástica e demais locais com finalidade exclusiva para prática de atividade física.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2020-DECRETO-Nº-839-2020-Eventos-Sociais-e-Eventos-Corporativos-Congressos-e-Seminários.pdf" target="_blank">DECRETO Nº 839 DE 04 DE NOVEMBRO DE 2020</a></strong></p>
<p style="text-align: justify;">“Incluir no Anexo Único do Decreto nº 488, de 20 de julho de 2020 os Protocolos Sanitários para Eventos Sociais e Eventos Oficiais, Corporativos, Acadêmicos, Técnicos e Científicos, tais como Congressos, Simpósios, Conferências, Palestras, Assembleias, Workshops e Seminários, bem como eventos comemorativos e sociais, tais como casamentos, aniversários e outros tipos de confraternizações realizados em igrejas, cerimoniais, restaurantes e buffets nas faixas amarela e verde dos Protocolos Sanitários Municipais estabelecidos no Decreto nº 488, de 20 de julho de 2020.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2020-DECRETO-Nº-745-2020-Altera-o-Decreto-nº-228-2020-COVID-19.pdf" target="_blank">DECRETO Nº 745 DE 07 DE OUTUBRO DE 2020</a></strong></p>
<p style="text-align: justify;">“Altera o Decreto Municipal nº 228, de 24 de março de 2020.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-744-2020-Declara-Situação-de-Emergência-Captação-de-água.pdf" target="_blank">DECRETO Nº 744 DE 07 DE OUTUBRO DE 2020</a></strong></p>
<p style="text-align: justify;">“Declara situação anormal, caracterizada como “SITUAÇÃO DE EMERGÊNCIA” na área onde está localizada a captação de água da Estação de Tratamento – ETA II, de Rio Branco.”</p>
<p><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2020-DECRETO-Nº-715-2020-Altera-os-Decretos-488-e-627-de-2020-Protocolo-de-Vigilância-Sanitária.pdf" target="_blank">DECRETO Nº 715 DE 28 DE SETEMBRO DE 2020</a></strong></p>
<p>“Fica permitida a música ao vivo nas faixas amarelo e verde dos Protocolos Sanitários Municipais estabelecidos no Decreto nº 488 de 20 de julho de 2020 e Decreto 627 de 04 de setembro de 2020.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2020-DECRETO-Nº-713-2020-Altera-o-Decreto-nº-336-2020-Cômite-de-enfrentamento-ao-COVID-19.pdf" target="_blank">DECRETO Nº 713 DE 28 DE SETEMBRO DE 2020</a></strong></p>
<p style="text-align: justify;">“A alínea “a”, do inciso IX, do artigo 2º, do Decreto nº 336, de 27 de maio de 2020.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2020-DECRETO-Nº-702-2020-Altera-o-Decreto-nº-651-2020-Retomada-Atividades-Presenciais-COVID-19.pdf" target="_blank">DECRETO Nº 702 DE 22 DE SETEMBRO DE 2020</a></strong></p>
<p style="text-align: justify;">“Altera o Decreto n° 651, de 09 de setembro de 2020.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2020-DECRETO-Nº-651-2020-Dispõe-sobre-a-retomada-de-atividades-presenciais-na-Adm.-Pública.pdf" target="_blank">DECRETO Nº 651 DE 09 DE SETEMBRO DE 2020</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre a retomada de atividades presenciais e do atendimento ao público pela Administração Pública Municipal.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2020-DECRETO-Nº-627-2020-Altera-o-Decreto-nº-488-2020-Protocolo-de-Vigilância-Sanitária.pdf" target="_blank">DECRETO Nº 627 DE 04 DE SETEMBRO DE 2020</a></strong></p>
<p style="text-align: justify;">“o PROTOCOLO DE VIGILÂNCIA: BARES E SIMILARES; RESTAURANTES, PIZZARIA, LANCHONETES, SORVETERIAS E SIMILARES, que passa a vigorar conforme Anexo Único deste decreto.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2020-DECRETO-Nº-581-2020-Aprovar-o-Adendo-I-do-Protocolo-de-Vigilância-Sanitária.pdf" target="_blank">DECRETO Nº 581 DE 20 DE AGOSTO DE 2020</a></strong></p>
<p style="text-align: justify;">“Aprovar o I – ADENDO DO PROTOCOLO DE VIGILÂNCIA SANITÁRIA, que institui o Protocolo para Bares e similares e de Restaurantes, Pizzaria, Lanchonetes, Sorveterias e Similares como o do Município de Rio Branco, conforme Anexo Único deste decreto.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2020-DECRETO-Nº-518-2020-Regulamenta-o-recebimento-de-doações-de-bens-móveis-e-de-serviços-COVID-19.pdf" target="_blank">DECRETO Nº 518 DE 07 DE AGOSTO DE 2020</a></strong></p>
<p style="text-align: justify;">“Regulamenta o recebimento de doações de recursos financeiros (ou valores), de bens móveis e de serviços, sem ônus ou encargos, de pessoas físicas ou jurídicas de direito privado pelos órgãos e entidades da Administração Direta, Autárquica e Fundacional durante o estado de calamidade pública decorrente da pandemia do COVID-19.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2020-DECRETO-Nº-489-2020-Sistemas-de-Entrega-Delivery-e-outros.pdf" target="_blank">DECRETO Nº 489 DE 20 DE JULHO DE 2020</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre o processo gradual e ordenado de reabertura dos estabelecimentos comerciais do município de Rio Branco/AC por meio dos serviços de “Delivery”, Drive thru” e “Pague e Leve”, diante da Emergência de Saúde Pública, decorrente da disseminação do novo coronavírus (SARS-COV- 2), causador da COVID-19.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2020-DECRETO-Nº-488-2020-Protocolo-da-Vigilância-Sanitária.pdf">DECRETO Nº 488 DE 20 DE JULHO DE 2020</a></strong></p>
<p style="text-align: justify;">“Instituir e Aprovar o PROTOCOLO DE VIGILÂNCIA SANITÁRIA do Município de Rio Branco, conforme Anexo Único deste decreto.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2020-DECRETO-Nº-417-2020-PRORROGAÇÃO-DE-PRAZOS-COVID-19.pdf" target="_blank">DECRETO Nº 417 DE 30 DE JUNHO DE 2020</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre os prazos de vigência de medidas para enfrentamento da emergência de saúde pública decorrente da doença COVID-19 e dá outras providências.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2020-DECRETO-Nº-362-2020-Prorroga-os-prazos-fixados-nos-Decretos-nº-196-200-e-237-2020-Calamidade-Pública.pdf" target="_blank">DECRETO Nº 362 DE 10 DE JUNHO DE 2020</a></strong></p>
<p style="text-align: justify;">“Prorroga para até o dia 30 de junho de 2020 os prazos fixados nos Decretos Municipais nº 196, de 17 de março de 2020, nº 200, de 19 de março de 2020 e no nº 237, de 27 de março de 2020 e dá outras providências.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2020-DECRETO-Nº-340-2020-Prorroga-os-prazos-do-Decreto-nº-196-2020-COVID-19.pdf" target="_blank">DECRETO Nº 340 DE 29 DE MAIO DE 2020</a></strong></p>
<p style="text-align: justify;">“Prorroga para até o dia 15 de junho de 2020 os prazos fixados nos Decretos Municipais nº 196, de 17 de março de 2020, nº 200, de 19 de março de 2020 e no nº 237, de 27 de março de 2020 e dá outras providências.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2020-DECRETO-Nº-337-2020-Altera-o-Decreto-nº-228-2020-COVID-19.pdf" target="_blank">DECRETO Nº 337 DE 27 DE MAIO DE 2020</a></strong></p>
<p style="text-align: justify;">“Altera o Decreto Municipal nº 228, de 24 de março de 2020.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2020-DECRETO-Nº-336-2020-Institui-o-CEME-COVID19-e-altera-decreto-196-2020.pdf" target="_blank">DECRETO Nº 336 DE 27 DE MAIO DE 2020</a></strong></p>
<p style="text-align: justify;">“Institui o Comitê de Enfrentamento e Monitoramento de Emergência para Infecção Humana pelo Novo Coronavírus (COVID-19) – CEME-COVID19 e dá outras providências.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2020-DECRETO-Nº-319-2020-Altera-Decreto-nº-316-2020.pdf" target="_blank">DECRETO Nº 319 DE 15 DE MAIO DE 2020</a></strong></p>
<p style="text-align: justify;">“Altera o Decreto Municipal nº 316 de 14 de maio de 2020.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2020-DECRETO-Nº-318-2020-Prorroga-os-prazo-dos-Decretos-Municipais-nº-196-200-e-237-COVID-19.pdf" target="_blank">DECRETO Nº 318 DE 15 DE MAIO DE 2020</a></strong></p>
<p style="text-align: justify;">“Prorroga para até o dia 31 de maio de 2020 os prazos fixados nos Decretos Municipais nº 196, de 17 de março de 2020, nº 200, de 19 de março de 2020 e no nº 237, de 27 de março de 2020 e dá outras providências.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2020-DECRETO-Nº-316-2020-Institui-o-regime-excepecional-e-temporário-de-restrição-de-circulação-de-veículos.pdf" target="_blank">DECRETO Nº 316 DE 14 DE MAIO DE 2020</a></strong></p>
<p style="text-align: justify;">“Institui regime excepcional e temporário de restrição de circulação de veículos no Município de Rio Branco por conta da pandemia decorrente do coronavírus.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-274-2020-Prorroga-até-17-de-maio-de-2020-os-Decretos-nº-196-200-e-237-2020-CORONAVÍRUS.COVID-19.pdf" target="_blank">DECRETO Nº 274 DE 29 DE ABRIL DE 2020</a></strong></p>
<p style="text-align: justify;">“Prorroga para até o dia 17 de maio de 2020 os prazos fixados nos Decretos Municipais nº 196, de 17 de março de 2020, nº 200, de 19 de março de 2020 e no nº 237, de 27 de março de 2020 e dá outras previdências.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2020-DECRETO-Nº-273-2020-Recomendações-a-serem-adotadas-pós-óbito-durante-o-período-de-emergência-em-saúde-pública.pdf" target="_blank">DECRETO Nº 273 DE 29 DE ABRIL DE 2020</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre recomendações a serem adotadas pós-óbito durante o período de emergência em saúde pública, e dá outras providências.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2020-DECRETO-Nº-257-2020-Distribuição-de-Kit-Alimentação-CORONAVÍRUS.COVID-19.pdf">DECRETO Nº 257 DE 16 DE ABRIL DE 2020</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre medidas a serem adotadas para a garantia da distribuição da merenda escolar aos alunos da rede pública municipal, em decorrência da pandemia da COVID-19.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-252-2020-Prorrogação-do-prazo-do-Decreto-nº-196-200-237-2020-CORONAVÍRUS.COVID-19.pdf" target="_blank">DECRETO Nº 252 DE 08 DE ABRIL DE 2020</a></strong></p>
<p style="text-align: justify;">“Prorroga para até o dia 30 de abril de 2020 os prazos fixados nos Decretos Municipais nº 192, de 17 de março de 2020, nº 200, de 19 de março de 2020 e no nº 237, de 27 de março de 2020.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-237-2020-Prorroga-os-prazos-fixados-no-Decreto-nº-196-e-200-2020-CORONAVÍRUS-COVID-19.pdf" target="_blank">DECRETO Nº 237 DE 27 DE MARÇO DE 2020</a></strong></p>
<p style="text-align: justify;">“Prorroga prazos fixados nos Decretos Municipais nº 196, de 17 de março de 2020 e nº 200, de 19 de março de 2020.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-229-2020-Declara-Estado-Calamidade-Pública-CORONAVÍRUS.COVID-19.pdf" target="_blank">DECRETO Nº 229 DE 24 DE MARÇO DE 2020</a></strong></p>
<p style="text-align: justify;">“Declara estado de calamidade pública no Município de Rio Branco para enfrentamento da pandemia decorrente do COVID 19.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-228-2020-Procedimentos-Especiais-para-contratação-Pública-de-bens-serviços-e-insumos-CORONAVÍRUS.COVID-19.pdf" target="_blank">DECRETO Nº 228 DE 24 DE MARÇO DE 2020</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre os procedimentos especiais de contratação pública de bens, serviços e insumos inerentes às medidas temporárias de enfrentamento da Emergência em Saúde Pública de importância internacional decorrente do coronavírus, conforme previsto na Lei Federal nº 13.979/2020.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-223-2020-Altera-do-Decreto-Nº-196-2020-Dispensa-de-Licitação-para-aquisição-de-bens-CORONAVÍRUS.COVID-19.pdf" target="_blank">DECRETO Nº 223 DE 23 DE MARÇO DE 2020</a></strong></p>
<p style="text-align: justify;">“Fica dispensada a licitação para aquisição de bens, serviços, inclusive de engenharia, e insumos destinados ao enfrentamento da emergência de saúde pública de importância internacional decorrente do coronavírus de que trata este decreto, nos termos do art. 4º, da Lei Federal nº 13.979/2020.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-200-2020-Medidas-Excepcionais-e-temporária-de-expediente-administrativo-CORONAVÍRUS.COVID-19.pdf" target="_blank">DECRETO Nº 200 DE 19 DE MARÇO DE 2020</a></strong></p>
<p style="text-align: justify;">“Estabelece medidas excepcionais e temporárias de expediente administrativo e atendimento ao público no âmbito do Município de Rio Branco.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-196-2020-Declara-Situação-de-Emergencia-CORONAVÍRUS.COVID-19.pdf" target="_blank">DECRETO Nº 196 DE 17 DE MARÇO DE 2020</a></strong></p>
<p style="text-align: justify;">“Declara SITUAÇÃO DE EMERGÊNCIA e cria o Comitê de Enfrentamento e Monitoramento de Emergência para infecção humana pelo novo coronavírus (COVID-19) – CEME-COVID19 e dá outras providências.”</p>
<hr>
<p style="text-align: justify;"><strong>ANO 2019</strong></p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/RT-Nº-014-2019-EMERGÊNCIA-DENGUE-PORTAL.pdf" target="_blank">RECOMENDAÇÃO TÉCNICA CIRCULAR Nº 014/2019</a></strong></p>
<p style="text-align: justify;">“Realização de despesas. Decreto Municipal nº 606, de 1º de fevereiro de 2019 e suas eventuais complementações. Situação de Emergência.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-606-2019-Situação-de-Emergência-DENGUE.pdf" target="_blank">DECRETO Nº 606 DE 01 DE FEVEREIRO DE 2019</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre decretação de Situação de Emergência Municipal em razão de Epidemia por Doença Infecciosa Viral (Dengue) COBRADE 1.5.1.1.0, e determina atividades preventivas contra o vírus da Dengue, Chikungunya e Zika Vírus.”</p>
<hr>
<p style="text-align: justify;"><strong>ANO 2018</strong></p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/portal/controle-interno-e-contabilidade/situacao-de-emergencia-2018/" target="_blank">DECRETO Nº 154 DE 15 DE FEVEREIRO DE 2018</a></strong></p>
<p style="text-align: justify;">“Declara situação anormal, caracterizada como “SITUAÇÃO de EMERGÊNCIA” nas áreas do município de Rio Branco pela ocorrência de enxurradas.”</p>
<hr>
<p style="text-align: justify;"><strong>ANO 2017</strong></p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/Decreto-nº-7.485-de-24082017-SITAÇÃO-DE-EMERGÊNCIA.pdf" target="_blank">DECRETO Nº 7.485 DE 24 DE AGOSTO DE 2017</a></strong></p>
<p style="text-align: justify;">“Declara Situação de Emergência nos Municípios de Rio Branco, Brasiléia e Porto Acre, em decorrência da estiagem e dá outras providências.”</p>
<hr>
<p style="text-align: justify;"><strong>ANO 2015</strong></p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-511-2015-Prorrogar-Estado-de-Calamidade.pdf" target="_blank">DECRETO Nº 511 DE 27 DE MAIO DE 2015</a></strong></p>
<p style="text-align: justify;">“Prorroga a vigência do Decreto nº 214, de 01 de Março de 2015, que Declara situação anormal, caracterizada como ESTADO de CALAMIDADE nas áreas do município de Rio Branco afetadas pela ocorrência de enchentes.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-217-2015-Altera-o-Decreto-2014-2015-Amplia-o-Estado-de-Calamidade-Pública.pdf" target="_blank">DECRETO Nº 217 DE 04 DE MARÇO DE 2015</a></strong></p>
<p style="text-align: justify;">“Altera o Decreto n° 214 de 01 de março de 2015, para ampliar como ESTADO DE CALAMIDADE PÚBLICA toda extensão geográfica do Município de Rio Branco, abrangendo o perímetro urbano e rural, afetadas pela ocorrência de enchentes.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-215-2015-Decreta-Ponto-Facultativo-Enchente.pdf" target="_blank">DECRETO Nº 215 DE 01 DE MARÇO DE 2015</a></strong></p>
<p style="text-align: justify;">“Decreta ponto facultativo nos dias 03 e 04 de março de 2015, em virtude da situação anormal, caracterizada como ESTADO DE CALAMIDADE PÚBLICA, para os órgãos e entidades da Administração Direta e Indireta do Poder Executivo Municipal.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-214-2015-Declara-ESTADO-DE-CALAMIDADE-PÚBLICA.pdf" target="_blank">DECRETO Nº 214 DE 01 DE MARÇO DE 2015</a></strong></p>
<p style="text-align: justify;">“Declara situação anormal, caracterizada como ESTADO DE CALAMIDADE PÚBLICA nas áreas do município de Rio Branco afetadas pela ocorrência de enchentes.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-201-2015-Altera-o-Dec-193-2015-SITUAÇÃO-DE-EMERGÊNCIA.doc" target="_blank">DECRETO Nº 201 DE 25 DE FEVEREIRO DE 2015</a></strong></p>
<p style="text-align: justify;">“Altera o Decreto nº 193, de 23 de fevereiro de 2015, que declara situação anormal, caracterizada como “SITUAÇÃO DE EMERGÊNCIA” nas áreas do município de rio branco afetadas pela enchente.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-193-2015-SITUAÇÃO-DE-EMERGÊNCIA.pdf" target="_blank">DECRETO Nº 193 DE 23 DE FEVEREIRO DE 2015</a></strong></p>
<p style="text-align: justify;">“Declara situação anormal, caracterizada como “SITUAÇÃO de EMERGÊNCIA” nas áreas do município de Rio Branco afetadas pela ocorrência de enchentes.”</p>
<hr>
<p style="text-align: justify;"><strong>ANO 2014</strong></p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2014-DECRETO-Nº-855-2014-Altera-do-Dec.-3.926-2012-Cobrança-dos-preços-publicos.pdf" target="_blank">DECRETO Nº 855 DE 03 DE JULHO DE 2014</a></strong></p>
<p style="text-align: justify;">“Altera o Decreto nº 3.926, de 31 de agosto de 2012.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2014-DECRETO-Nº-575-2014-Prorrogação-a-vigencia-do-Dec.-111-2014-Situação-de-Emergência-Alagação.pdf" target="_blank">DECRETO Nº 575 DE 05 DE MAIO DE 2014</a></strong></p>
<p style="text-align: justify;">“Prorroga a vigência do Decreto nº 111, de 03 de fevereiro de 2014, que Declara situação anormal, caracterizada como SITUAÇÃO de EMERGÊNCIA nas áreas do município de Rio Branco afetadas pela ocorrência de inundações e escorregamentos de massa.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2014-DECRETO-Nº-511-2014-Altera-o-Decreto-nº-111-2014-Situação-de-Emeregência-Alagação.pdf" target="_blank">DECRETO Nº 511 DE 23 DE ABRIL DE 2014</a></strong></p>
<p style="text-align: justify;">“Altera o Decreto nº 111, de 03 de fevereiro de 2014.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2014-DECRETO-Nº-282-2014-Altera-o-Dec.-nº-111-2014-Situação-de-Emergência-Alagação.pdf" target="_blank">DECRETO Nº 282 DE 10 DE MARÇO DE 2014</a></strong></p>
<p style="text-align: justify;">“Altera o Decreto nº 111, de 03 de fevereiro de 2014, que declara situação anormal, caracterizada como situação de emergência nas áreas do município de rio branco afetadas pela ocorrência de inundações.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2014-DECRETO-Nº-111-2014-Declara-Situação-de-Emergência-Alagação.pdf" target="_blank">DECRETO Nº 111 DE 03 DE FEVEREIRO DE 2014</a></strong></p>
<p style="text-align: justify;">“Declara situação anormal, caracterizada como SITUAÇÃO de EMERGÊNCIA nas áreas do município de Rio Branco afetadas pela ocorrência de inundações e escorregamentos de massa.”</p>
<hr>
<p style="text-align: justify;"><strong>ANO 2013</strong></p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2013-DECRETO-Nº-1652-2013-Declara-Estado-de-Emergencia-Ambiental.pdf" target="_blank">DECRETO Nº 1.652 DE 23 DE JULHO DE 2013</a></strong></p>
<p style="text-align: justify;">“Declara ESTADO DE EMERGÊNCIA ambiental no Município de Rio Branco em decorrência da ameaça iminente de queimadas urbanas e dá outras providências.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2013-DECRETO-Nº-1548-2013-Prorroga-a-vigencia-do-Decreto-nº-1.103-2013-SITUAÇÂO-DE-EMERGECIA.pdf" target="_blank">DECRETO Nº 1.548 DE 24 DE JUNHO DE 2013</a></strong></p>
<p style="text-align: justify;">“Prorroga a vigência do Decreto nº 1.103, de 25 de março de 2013, que declara situação anormal caracterizada como “SITUAÇÃO de EMERGÊNCIA” nas áreas do município de Rio Branco afetadas pela ocorrência de enchentes.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2013-DECRETO-Nº-1302-2013-Prorroga-a-vigencia-do-Decreto-nº-1.103-2013-SITUAÇÃO-DE-EMERGENCIA.pdf" target="_blank">DECRETO Nº 1.302 DE 25 DE ABRIL DE 2013</a></strong></p>
<p style="text-align: justify;">“Prorroga a vigência do Decreto nº 1.103, de 25 de março de 2013, que declara situação anormal, caracterizada como “SITUAÇÃO de EMERGÊNCIA” nas áreas do município de Rio Branco afetadas pela ocorrência de enchentes.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2013-DECRETO-Nº-1136-2013-Altera-o-Art.-1º-do-Decreto-1.103-2013-Situação-de-Emergência.pdf" target="_blank">DECRETO Nº 1.136 DE 01 DE ABRIL DE 2013</a></strong></p>
<p style="text-align: justify;">“Altera o Art. 1º do Decreto nº 1.103, de 01 de Abril de 2013, que declara situação anormal, caracterizada como “SITUAÇÃO de EMERGÊNCIA” nas áreas do município de Rio Branco afetadas pela ocorrência de enchentes.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2013-DECRETO-Nº-1103-2013-Declara-Situação-Anormal-de-Emergência.pdf" target="_blank">DECRETO Nº 1.103 DE 25 DE MARÇO DE 2013</a></strong></p>
<p style="text-align: justify;">“Declara situação anormal, caracterizada como “SITUAÇÃO de EMERGÊNCIA” nas áreas do município de Rio Branco afetadas pela ocorrência de enchentes.”</p>
<hr>
<p style="text-align: justify;"><strong>ANO 2012</strong></p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2012-LEI-Nº-1.891-de-27.03.2012-Lei-de-Isenção-de-Impostos-devido-a-Calamidade-Publica.pdf" target="_blank">LEI Nº 1.891 DE 27 DE MARÇO DE 2012</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre isenção do Imposto Sobre Serviços de Qualquer Natureza – ISSQN e remissão do Imposto sobre a Propriedade Predial e Territorial Urbana – IPTU e sobre a Taxa de Remoção de Resíduos Sólidos e Entulhos, aos prestadores de serviços e proprietários de imóveis prejudicados por Calamidade Pública, e dá outras providências.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2012-DECRETO-Nº-3296-2012-Execução-de-despesas-com-a-aquisição-de-bens-e-serviços-destinados-a-emergências.pdf" target="_blank">DECRETO Nº 3.296 DE 24 DE FEVEREIRO DE 2012</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre a execução de despesas com a aquisição de bens e serviços destinados as ações de socorro, assistência às vítimas, restabelecimento de serviços essenciais e reconstrução, decorrentes do estado de emergência.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2012-DECRETO-Nº-3286-2012-Declara-situação-anormal-caracterizada-como-Situação-de-Emergência.pdf" target="_blank">DECRETO Nº 3.286 DE 15 DE FEVEREIRO DE 2012</a></strong></p>
<p style="text-align: justify;">“Declara situação anormal, caracterizada como “SITUAÇÂO de EMERGÊNCIA” nas áreas do município de Rio Branco afetadas pela ocorrência de enchentes.”</p>
</div>';
BEGIN
    dbms_lob.append(texto, complementoTexto);
update PAGINAPREFEITURAPORTAL
set CONTEUDOHTML = texto
where NOME = 'Situação de Emergência' and CHAVE = 'situacao-de-emergencia';
END;
