insert into MODELODOCTOOFICIAL (ID, TIPODOCTOOFICIAL_ID, VIGENCIAINICIAL, SEQUENCIA)
VALUES (HIBERNATE_SEQUENCE.nextval, (select tdo.id from TIPODOCTOOFICIAL tdo where tdo.CODIGO = 157 and tdo.MODULOTIPODOCTOOFICIAL = 'NOTA_RESTO_LIQUIDACAO'), sysdate, 1)
