insert into MODELODOCTOOFICIAL (ID, TIPODOCTOOFICIAL_ID, VIGENCIAINICIAL, SEQUENCIA)
VALUES (HIBERNATE_SEQUENCE.nextval, (select tdo.id from TIPODOCTOOFICIAL tdo where tdo.CODIGO = 161 and tdo.MODULOTIPODOCTOOFICIAL = 'NOTA_OBRIGACAO_A_PAGAR_ESTORNO'), sysdate, 1)
