DECLARE
texto CLOB := '<div class="post-content"><hr>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-742-DE-05-DE-JUNHO-DE-2024-DOE.pdf" target="_blank">DECRETO Nº 742 DE 05 DE JUNHO DE 2024</a></strong>&nbsp;– DOE</p>
<p style="text-align: justify;">“Alterar o artigo 3º do Decreto Municipal nº 339 de 15 de março de 2024, que dispõe sobre a prorrogação dos prazos para o pagamento do Imposto sobre a Propriedade Predial e Territorial Urbana – IPTU, do Imposto Sobre Serviço de Qualquer Natureza – ISSQN e da Taxa de Alvará de Funcionamento referente ao exercício de 2024 e dá outras providências.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-339-2024-Prorrogação-dos-prazos-de-pagamento-do-IPTU-ISSQN-e-da-TAXA-DE-ALVARÁ.pdf" target="_blank">DECRETO Nº 339 DE 15 DE MARÇO DE 2024</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre a prorrogação dos prazos para o pagamento do Imposto sobre a Propriedade Predial e Territorial Urbana – IPTU, do Imposto Sobre Serviço de Qualquer Natureza – ISSQN e da Taxa de Alvará de Funcionamento referente ao exercício de 2024 e dá outras providências.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-COMPLEMENTAR-Nº-280-DE-20-DE-DEZEMBRO-DE-2023-Altera-a-Lei-Complementar-Nº-236-2023-–-IPTU-2024.pdf" target="_blank">LEI COMPLEMENTAR Nº 280 DE 20 DE DEZEMBRO DE 2023</a></strong></p>
<p style="text-align: justify;">“Altera a Lei Complementar nº 236 de 20 de julho de 2023 que dispõe sobre a remissão do Imposto sobre Propriedade Predial e Territorial Urbana – IPTU e taxa de remoção de resíduos sólidos e entulhos, incidentes sobre os imóveis edificados atingidos por enchentes, inundações e/ou alagamentos causado pelas chuvas ocorridas no município de Rio Branco”.</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-COMPLEMENTAR-Nº-236-DE-20.07.2023-Remissão-do-IPTU-e-Taxa-de-remoção-de-Resíduos-Sólidos-e-Entulhos-Enchentes.pdf" target="_blank">LEI COMPLEMENTAR Nº 236 DE 20 DE JULHO DE 2023</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre a remissão do Imposto sobre Propriedade Predial e Territorial Urbana – IPTU e taxa de remoção de resíduos sólidos e entulhos, incidentes sobre os imóveis edificados atingidos por enchentes, inundações e/ou alagamentos causado pelas chuvas ocorridas no município de Rio Branco”.</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-474-2023-Prorrogação-dos-prazos-do-IPTU-ISSQN-TAXA-ALVARÁ-DE-FUNCIONAMENTO-2023.pdf" target="_blank">DECRETO Nº 474 DE 03 DE ABRIL DE 2023</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre a prorrogação dos prazos para o pagamento do Imposto sobre a Propriedade Predial e Territorial Urbana – IPTU, do Imposto Sobre Serviço de Qualquer Natureza – ISSQN e da Taxa de Alvará de Funcionamento referente ao exercício de 2023 e dá outras providências.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/portal/wp-content/uploads/2013/10/LEI-COMPLEMENTAR-N%C2%BA-188-DE-31.10.2022-Concede-remiss%C3%A3o-e-redu%C3%A7%C3%A3o-de-al%C3%ADquota-do-IPTU-para-empresas.pdf" target="_blank">LEI COMPLEMENTAR Nº 188 DE 31 DE OUTUBRO DE 2022</a></strong></p>
<p style="text-align: justify;">“Concede remissão e redução de alíquota do Imposto sobre a Propriedade Predial e Territorial Urbana – IPTU, para as empresas instaladas ou as que venham se instalar nas áreas localizadas nos Distritos Industriais.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-COMPLEMENTAR-Nº-124-DE-14.12.2021-Remissão-do-Imposto-sobre-a-Propriedade-Predial-e-Territorial-Urbana-–-IPTU-2021.pdf" target="_blank">LEI COMPLEMENTAR Nº 124 DE 14 DE DEZEMBRO DE 2021</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre a remissão do Imposto sobre a Propriedade Predial e Territorial Urbana – IPTU, às empresas que possuam suas sedes/edificações atingidas pelas inundações no exercício de 2021 e dá outras providências.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-COMPLEMENTAR-Nº-109-DE-19.04.2021-Concede-remissão-do-IPTU-sobre-imóveis-atingidos-pela-enchende-do-ano-de-2021.pdf" target="_blank">LEI COMPLEMENTAR Nº 109 DE 19 DE ABRIL DE 2021</a></strong></p>
<p style="text-align: justify;">“Concede remissão do imposto sobre a propriedade predial e territorial urbana (IPTU) incidente sobre os imóveis edificados atingidos pela enchente do ano de 2021.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-COMPLEMENTAR-Nº-108-DE-15.04.2021-Concede-remissão-e-redução-de-alíquota-do-IPTU.pdf" target="_blank">LEI COMPLEMENTAR Nº 108 DE 15 DE ABRIL DE 2021</a></strong></p>
<p style="text-align: justify;">“Concede remissão e redução de alíquota do Imposto sobre a Propriedade Predial e Territorial Urbana – IPTU para as empresas instaladas ou que venham a se instalar nas áreas localizadas nos Distritos Industriais.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/SEFIN-EDITAL-DE-NOTIFICAÇÃO-DE-LANÇAMENTO-DO-IPTU-2021-VENCIMENTO-1-PARCELA-E-COTA-ÚNICA.pdf" target="_blank">SEFIN – EDITAL DE NOTIFICAÇÃO DE LANÇAMENTO – RETIFICAÇÃO VENCIMENTO 1ª PARCELA E COTA ÚNICA</a></strong></p>
<p style="text-align: justify;">“O Município de Rio Branco, através da Secretaria Municipal de Finanças, notifica os proprietários, titulares de domínio útil ou posseiros de bens imóveis por natureza ou acessão física, conforme determina o art. 20, § 4°, da Lei nº 1.508/2003 – Código Tributário Municipal, quanto a retificação do lançamento do Imposto Predial Territorial Urbano e da Taxa de Coleta e Remoção de Resíduos Sólidos do exercício 2021.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/SEFIN-EDITAL-DE-NOTIFICAÇÃO-DE-LANÇAMENTO-DO-IPTU-2021.pdf" target="_blank">SEFIN – EDITAL DE NOTIFICAÇÃO DE LANÇAMENTO DE IPTU 2021 </a></strong></p>
<p style="text-align: justify;">“O Município de Rio Branco, através da Secretaria Municipal de Finanças, notifica os proprietários, titulares de domínio útil ou posseiros de bens imóveis por natureza ou acessão física, conforme determina o art. 20, §4°, da Lei nº 1.508/2003 – Código Tributário Municipal, quanto ao lançamento do Imposto Predial Territorial Urbano e da Taxa de Coleta e Remoção de Resíduos Sólidos do exercício 2021.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/DECRETO-Nº-248-2020-Prorrogação-dos-prazos-de-pagamento-do-IPTU-2020-CORONAVÍRUS.COVID-19.pdf" target="_blank">DECRETO Nº 248 DE 06 DE ABRIL DE 2020</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre a prorrogação dos prazos para pagamento do Imposto sobre a Propriedade Predial e Territorial Urbana – IPTU.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-COMPLEMENTAR-Nº-067-DE-19.07.2019-Concede-remissão-dos-créditos-tributários-decorrentes-da-identificação-de-defasagem-no-IPTU.pdf" target="_blank">LEI COMPLEMENTAR Nº 67 DE 19 DE JULHO DE 2019</a></strong></p>
<p style="text-align: justify;">“Concede remissão dos créditos tributários decorrentes da identificação de defasagem na base de cálculo do Imposto sobre a Propriedade Predial e Territorial Urbana – IPTU dos exercícios de 2014 a 2018. ”</p>
<p><strong><a href="http://portalcgm.riobranco.ac.gov.br/portal/wp-content/uploads/2013/10/LEI-COMPLEMENTAR-N%C2%BA-15-DE-04.05.2015-Disp%C3%B5e-sobre-a-remiss%C3%A3o-do-IPTU-sobre-os-im%C3%B3veis-atingidos-pelas-enchentes..pdf" target="_blank">LEI COMPLEMENTAR Nº 15 DE 04 DE MAIO DE 2015</a></strong></p>
<p>“Dispõe sobre a remissão do Imposto sobre a Propriedade Predial e Territorial Urbana – IPTU, incidente sobre os imóveis edificados atingidos pelas enchentes.”</p>
<p><strong><a href="http://portalcgm.riobranco.ac.gov.br/portal/wp-admin/post.php?post=473&amp;action=edit&amp;message=1" target="_blank">LEI COMPLEMENTAR Nº 12 DE 27 DE FEVEREIRO DE 2015</a></strong></p>
<p>“Dispõe sobre a isenção do Imposto sobre a Propriedade Predial e Territorial Urbana – IPTU para as empresas instaladas ou que venham a se instalar nas áreas localizadas nos Distritos Industriais.”</p>
<p><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/images/ARQUIVOS/24_Legisla%C3%A7%C3%A3o/LEIS%20COMPLEMENTARES/LEI%20COMPLEMENTAR%20N%C2%BA%2008%20DE%2019%20DE%20MAIO%20DE%202014.pdf" target="_blank">LEI COMPLEMENTAR Nº 08 DE 19 DE MAIO DE 2014</a></strong></p>
<p>“Dispõe sobre a remissão do Imposto sobre a Propriedade Predial e Territorial Urbana – IPTU, incidente sobre os imóveis edificados atingidos pelas enchentes.”</p>
<p><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2013-LEI-Nº-1.962-DE-20.02.2013-Dispõe-sobre-autorização-Legislativa-para-Realizar-Campanha-Municipal-de-Arrecadação-do-IPTU.pdf" target="_blank">LEI Nº 1.962 DE 20 DE FEVEREIRO DE 2013</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre autorização Legislativa, para Realizar Campanha Municipal de Arrecadação referente ao IPTU, através do concurso “IPTU em dia dá prêmios”, como meio de melhorar a arrecadação de Tributos Municipais, e dá outras providências,’’</p>
<p><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2011-LEI-Nº-1.889-de-30.12.2011-ISENÇÃO-DO-ISS-CONSTRUÇÃO-INTERESSE-SOCIAL.pdf" target="_blank">LEI Nº 1.889 DE 30 DE DEZEMBRO DE 2011</a></strong></p>
<p style="text-align: justify;">“Concede isenção do Imposto sobre Serviços de Qualquer Natureza – ISSQN – para construção no caso de empreendimentos habitacionais de interesse social vinculados ao PMCMV, do Imposto sobre a Transmissão de Bens Imóveis, realizada Inter Vivos, por ato oneroso – ITBI – para a aquisição dos correspondentes imóveis, bem como, concede isenção e autoriza a remissão do Imposto Predial e Territorial Urbano – IPTU.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-Nº-1.477-de-12.09.2002-Altera-a-Lei-º-1.472-2002-IPTU-e-ISS.pdf" target="_blank">LEI Nº 1.477 DE 12 DE SETEMBRO DE 2002</a></strong></p>
<p style="text-align: justify;">“Altera o Paragrafo Único do artigo 1º da Lei nº 1.472/02.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/LEI-Nº-1.472-de-04.07.2002-Remissão-de-acréscimo-monetário-sobre-IPTU-e-ISS-em-Divida-Ativa.pdf" target="_blank">LEI Nº 1.472 DE 04 DE JULHO DE 2002</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre a remissão de créditos de acréscimo monetário sobre créditos de IPTU e ISS inscritos em Dívida Ativa até 31 de dezembro de 2001.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/2002-LEI-Nº-1.463-de-16.01.2002-Execução-de-Créditos-de-Pequeno-Valor-IPTU.pdf" target="_blank">LEI Nº 1.463 DE 16 DE JANEIRO DE 2002</a></strong></p>
<p style="text-align: justify;">“Dispõe sobre a execução de créditos de pequeno valor e dá outras providências.”</p>
<p style="text-align: justify;"><strong><a href="http://portalcgm.riobranco.ac.gov.br/lai/wp-content/uploads/2015/06/SEFIN-EDITAL_DE_LANÇAMENTO_DO_IPTU_2015.pdf" target="_blank">EDITAL DE LANÇAMENTO DO IPTU 2015</a></strong></p>
</div>';
BEGIN
update PAGINAPREFEITURAPORTAL
set CONTEUDOHTML = texto
where NOME = 'Imposto sobre a Propriedade Predial Urbana - IPTU' and CHAVE = 'iptu';
END;
