insert into MODELODOCTOOFICIAL (ID, TIPODOCTOOFICIAL_ID, VIGENCIAINICIAL, SEQUENCIA)
VALUES (HIBERNATE_SEQUENCE.nextval, (select tdo.id from TIPODOCTOOFICIAL tdo where tdo.CODIGO = 155 and tdo.MODULOTIPODOCTOOFICIAL = 'NOTA_RESTO_PAGAMENTO'), sysdate, 1)
