INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES(hibernate_sequence.nextval, 'PORTAL DA TRANSPARÊNCIA > CONFIGURAÇÃO DE PÁGINA RELEVANTE', '/portaltransparencia/pagina-relevante/lista.xhtml',
       0, 'CONTABIL');

INSERT INTO MENU (ID, LABEL, CAMINHO, PAI_ID, ORDEM)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'CONFIGURAÇÃO DE PÁGINA RELEVANTE',
        '/portaltransparencia/pagina-relevante/lista.xhtml',
        (SELECT ID FROM MENU WHERE LABEL = 'PORTAL DA TRANSPARÊNCIA' AND CAMINHO IS NULL), 180);

INSERT INTO GRUPORECURSOSISTEMA (GRUPORECURSO_ID, RECURSOSISTEMA_ID)
VALUES ((SELECT ID FROM GRUPORECURSO WHERE NOME LIKE 'Portal Transparência%'),
        (SELECT ID FROM RECURSOSISTEMA WHERE NOME = 'PORTAL DA TRANSPARÊNCIA > CONFIGURAÇÃO DE PÁGINA RELEVANTE'));
