ALTER TABLE REGISTROEVENTORETENCAOREINF ADD (texto CLOB);
UPDATE REGISTROEVENTORETENCAOREINF SET texto = mensagem;
ALTER TABLE REGISTROEVENTORETENCAOREINF DROP COLUMN mensagem;
ALTER TABLE REGISTROEVENTORETENCAOREINF RENAME COLUMN texto TO mensagem;
