CREATE OR REPLACE FUNCTION GETPROXIMONUMERONFSAVULSA(EXERCICIO_ID in NUMBER)
return number
AS
NUMERO NUMBER;
BEGIN
SELECT COALESCE(MAX(NUMERO),0)+1 INTO NUMERO FROM NFSAvulsa WHERE EXERCICIO_ID = EXERCICIO_ID;
return numero;
END GETPROXIMONUMERONFSAVULSA;