  create or replace FUNCTION RETIRAZEROAESQUERDA (P_VALOR IN VARCHAR2)
    RETURN VARCHAR2
    AS
    P_VALOR_NOVO VARCHAR(20);
  BEGIN
    P_VALOR_NOVO := P_VALOR;
    IF (SUBSTR(P_VALOR_NOVO, 1, 1) = '0') THEN
       P_VALOR_NOVO := SUBSTR(P_VALOR_NOVO, 2, LENGTH(P_VALOR_NOVO) - 1);
       SELECT RETIRAZEROAESQUERDA(P_VALOR_NOVO) INTO P_VALOR_NOVO FROM DUAL;
    END IF;
    RETURN P_VALOR_NOVO;
  END;