update enderecocorreio set uf ='SE' where uf ='SERGIPE';
update enderecocorreio set uf ='BA'	where uf ='BAHIA';
update enderecocorreio set uf ='RN'	where uf ='RIO GRANDE DO NORTE';
update enderecocorreio set uf ='RJ' where uf ='Rio de Janeiro';
update enderecocorreio set uf ='SP'	where uf ='São Paulo';
update enderecocorreio set uf ='SP'	where uf ='SAO PAULO';
update enderecocorreio set uf ='ES'	where uf ='ESPIRITO SANTO';
update enderecocorreio set uf ='PE'	where uf ='PERNAMBUCO';
update enderecocorreio set uf ='RO'	where uf ='RONDONIA';
update enderecocorreio set uf ='MT'	where uf ='MATO GROSSO';
update enderecocorreio set uf ='RJ'	where uf ='RIO DE JANEIRO';
update enderecocorreio set uf ='DF'	where uf ='DISTRITO FEDERAL';
update enderecocorreio set uf ='PR'	where uf ='PARANA';
update enderecocorreio set uf ='GO'	where uf ='GOIAS';
update enderecocorreio set uf ='RR'	where uf ='RORAIMA';
update enderecocorreio set uf ='TO'	where uf ='TOCANTINS';
update enderecocorreio set uf ='MG'	where uf ='Minas Gerais';
update enderecocorreio set uf ='AC'	where uf ='ACRE';
update enderecocorreio set uf ='PB'	where uf ='PARAIBA';
update enderecocorreio set uf ='MG'	where uf ='MINAS GERAIS';
update enderecocorreio set uf ='PA'	where uf ='PARA';
update enderecocorreio set uf ='RS'	where uf ='RIO GRANDE DO SUL';
update enderecocorreio set uf ='CA'	where uf ='CEARA';
update enderecocorreio set uf ='AL'	where uf ='ALAGOAS';
update enderecocorreio set uf ='AC'	where uf ='Acre';
update enderecocorreio set uf ='PR'	where uf ='Paraná';
update enderecocorreio set uf ='DF'	where uf ='Distrito Federal';
update enderecocorreio set uf ='RO'	where uf ='Rondônia';
update enderecocorreio set uf ='MA'	where uf ='SAO LUIS';
update enderecocorreio set uf ='AM'	where uf ='Amazonas';
update enderecocorreio set uf ='CE'	where uf ='Ceará';
update enderecocorreio set uf ='BA'	where uf ='Bahia';
update enderecocorreio set uf ='SC'	where uf ='SANTA CATARINA';
update enderecocorreio set uf ='PI'	where uf ='PIAUI';
update enderecocorreio set uf ='AM' where uf ='AMAZONAS';
update enderecocorreio set uf ='MS'	where uf ='MATO GROSSO DO SUL';
update enderecocorreio set uf =''   where uf ='CUBA';