CREATE OR REPLACE FORCE VIEW VWHIERARQUIADESPESAORC ("ID", "ORGAO", "UNIDADE", "SUBACAO", "CONTA", "EXERCICIO", "UNIDADE_ID", "TIPOCONTADESPESA", "INICIOVIGENCIA", "FIMVIGENCIA", "CODIGOREDUZIDO")
          AS
  SELECT D.ID AS id,
    hoUo.CODIGO
    ||' - '
    ||UOORG.DESCRICAO AS ORGAO,
    HO.CODIGO
    ||' - '
    || UOUNI.DESCRICAO AS UNIDADE,
    F.CODIGO
    ||'.'
    ||SF.CODIGO
    ||'.'
    ||P.CODIGO
    ||'.'
    ||TPA.CODIGO
    ||''
    ||A.CODIGO
    ||'.'
    ||SUB.CODIGO
    ||' - '
    ||SUB.DESCRICAO AS SUBACAO,
    CON.CODIGO
    ||' - '
    ||CON.DESCRICAO     AS CONTA,
    D.EXERCICIO_ID      AS EXERCICIO,
    UOUNI.ID            AS UNIDADE_ID,
    CD.TIPOCONTADESPESA AS TIPOCONTADESPESA,
    HO.INICIOVIGENCIA   AS INICIOVIGENCIA,
    HO.FIMVIGENCIA      AS FIMVIGENCIA,
    D.CODIGOREDUZIDO    AS CODIGOREDUZIDO
  FROM DESPESAORC D
  INNER JOIN PROVISAOPPADESPESA PD ON PD.ID = D.PROVISAOPPADESPESA_ID
  INNER JOIN SUBACAOPPA SUB ON SUB.ID = PD.SUBACAOPPA_ID
  INNER JOIN ACAOPPA A ON A.ID = SUB.ACAOPPA_ID
  INNER JOIN TIPOACAOPPA TPA ON TPA.ID = A.TIPOACAOPPA_ID
  INNER JOIN PROGRAMAPPA P ON P.ID = A.PROGRAMA_ID
  INNER JOIN FUNCAO F ON F.ID = A.FUNCAO_ID
  INNER JOIN SUBFUNCAO SF ON SF.ID = A.SUBFUNCAO_ID
  INNER JOIN UNIDADEORGANIZACIONAL UOUNI ON UOUNI.ID = PD.UNIDADEORGANIZACIONAL_ID
  INNER JOIN HIERARQUIAORGANIZACIONAL HO ON HO.SUBORDINADA_ID = UOUNI.ID AND HO.TIPOHIERARQUIAORGANIZACIONAL = 'ORCAMENTARIA'
  INNER JOIN UNIDADEORGANIZACIONAL UOORG ON UOORG.ID = HO.SUPERIOR_ID
  INNER JOIN HIERARQUIAORGANIZACIONAL HOUO ON HOUO.SUBORDINADA_ID = UOORG.ID AND HOUO.TIPOHIERARQUIAORGANIZACIONAL = 'ORCAMENTARIA'
  INNER JOIN CONTA CON ON CON.ID = PD.CONTADEDESPESA_ID
  INNER JOIN CONTADESPESA CD ON CON.ID = CD.ID