INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'V', 'Vencimento');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'B', 'Salário Base');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'A', 'Vencimento Efetivo');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'P', 'Total de Proventos');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'C', 'Cargo de Carreira');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'I', 'Cargo de Comissão');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'F', 'Função Gratificada');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'N', 'Representação');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'R', 'Comissão + Representação');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'M', 'Salário Mínimo Oficial');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'E', 'Salário Mínimo Órgão');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'Q', '1ª Referência - Classe');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'T', '1ª Referência - Tabela');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'D', 'Referência - Cargo');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'O', 'Outra Verba');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, '7', 'Desconto Faltas');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, '8', 'Sexta-parte');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, '6', 'Contribuicao Sindical');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'L', 'Líquido');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'HE', 'Hora Extra');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'FE', 'Férias');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'PB', 'Pensão sobre Bruto');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'AT', 'ATS');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'IF', 'IRRF Férias');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'ID', 'IRRF 13º Salário');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'IR', 'IRRF');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'PI', 'Previdência INSS');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'PA', 'Previdência INSS 13º Salário');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'PF', 'Previdência Fundo');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'PE', 'Previdência Fundo Férias');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'PD', 'Previdência Fundo 13º Salário');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'PR', 'Previdência Saúde Férias');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'P1', 'Previdência Saúde 13º Salário');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'PS', 'Previdência Saúde');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'FG', 'FGTS');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'AB', 'Abate Teto');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'AN', 'Adicional de Inatividade');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'AR', 'Auxílio Transporte');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'AA', 'Auxílio Alimentação');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'GF', 'Gratif. de Risco de Vida');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'CS', 'Complemento Sálario Mínimo');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'CP', 'Compl. Sal. Min. Prof.');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'LP', 'Licença Prêmio');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'MC', 'Margem Consignável');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'SF', 'Salário Família');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'PL', 'Pensão sobre Líquido');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, '1', 'Base 01');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, '2', 'Base 02');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, '3', 'Base 03');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, '4', 'Base 04');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, '5', 'Base 05');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, '99', 'Nenhum');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'SD', 'Sindicato RBR');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'SI', 'SINDICATO');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, '', 'Vencimento Efetivo');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'S2', 'Assermurb-MS (614)');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'S3', 'Asfem-MS (715)');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'PU', 'Base de Produtividade');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'PT', 'Produtividade');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'S4', 'Sinfismurb (611)');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'AS', 'Adiantamento de 13 sal');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'AP', 'Anuenio');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'AF', '1/3 Const. Ferias');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, '6P', 'SEXTA PARTE APOS');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'HJ', 'Hora Extra Judicial');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'AD', 'Adicional de Titulação');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'RE', 'Representação');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'BI', 'Adicional de Formação');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'S1', 'Sindicato Geral');
INSERT INTO TipoBaseFP(ID, codigo, descricao) VALUES(hibernate_sequence.nextval, 'PG', 'Pensão Geral');