create or replace PACKAGE PACOTE_CONSULTA_DE_DEBITOS
AS
FUNCTION GETVALORJUROS(
    PARAM_DATA_VENCIMENTO IN DATE ,
    PARAM_DATA_OPERACAO   IN DATE ,
    PARAM_DIVIDA_ID       IN NUMBER ,
    PARAM_VALOR           IN NUMBER ,
    PARAM_IS_DIVIDA_ATIVA IN NUMBER )
  RETURN NUMBER;
FUNCTION GETVALORMULTA(
    PARAM_DATA_VENCIMENTO IN DATE ,
    PARAM_DATA_OPERACAO   IN DATE ,
    PARAM_DIVIDA_ID       IN NUMBER ,
    PARAM_VALOR           IN NUMBER ,
    PARAM_IS_DIVIDA_ATIVA IN NUMBER)
  RETURN NUMBER;
FUNCTION GETVALORCORRECAO(
    PARAM_SALDO                 IN NUMBER,
    PARAM_PARCELA_ID            IN NUMBER,
    PARAM_DATA_REGISTRO_PARCELA IN DATE,
    PARAM_EXERCICIO_ANO         IN NUMBER)
  RETURN NUMBER;
FUNCTION GETVALORDESCONTO(
    PARAM_PARCELA_ID IN NUMBER )
  RETURN NUMBER;
FUNCTION GETVALORIMPOSTO(
    PARAM_PARCELA_VALOR          IN NUMBER ,
    PARAM_PARCELA_ID             IN NUMBER ,
    PARAM_SITUACAO_PARCELA_SALDO IN NUMBER )
  RETURN NUMBER;
FUNCTION GETVALORTAXA(
    PARAM_PARCELA_VALOR          IN NUMBER ,
    PARAM_PARCELA_ID             IN NUMBER ,
    PARAM_SITUACAO_PARCELA_SALDO IN NUMBER)
  RETURN NUMBER;
FUNCTION GETNUMEROPARCELA(
      PARAM_ID_VALOR_DIVIDA    IN NUMBER ,
      PARAM_ID_OPCAO_PAGAMENTO IN NUMBER ,
      PARAM_PROMOCIONAL        IN NUMBER ,
      PARAM_SEQUENCIA_PARCELA  IN VARCHAR2 )
  RETURN VARCHAR2;
FUNCTION GETVALORHONORARIOS(
    PARAM_DIVIDA_ID       IN NUMBER ,
    PARAM_VALOR           IN NUMBER ,
    PARAM_IS_DIVIDA_AJUIZADA IN NUMBER )
  RETURN NUMBER;
FUNCTION  GETVALORPARCELAPAGO(
    PARAM_ID_PARCELA       IN NUMBER,
    PARAM_SITUACAO_PARCELA IN VARCHAR2)
  RETURN NUMBER;
FUNCTION GETDATAPAGAMENTOPARCELA(
    PARAM_ID_PARCELA       IN NUMBER,
    PARAM_SITUACAO_PARCELA IN VARCHAR2)
    RETURN DATE;
END PACOTE_CONSULTA_DE_DEBITOS;