update ITEMFICHAFINANCEIRAFP set BKPVALORINTEGRAL = VALORINTEGRAL
WHERE VALORINTEGRAL < VALOR
AND ANO > 2017
AND TIPOEVENTOFP = 'VANTAGEM'
AND VALORINTEGRAL > 0;

update ITEMFICHAFINANCEIRAFP iff set VALORINTEGRAL = valor
where iff.id in (select iff.id from ITEMFICHAFINANCEIRAFP iff
inner join fichafinanceirafp ff on iff.FICHAFINANCEIRAFP_ID = ff.id
where valorintegral < valor
and iff.ANO > 2017
and iff.TIPOEVENTOFP = 'VANTAGEM'
AND VALORINTEGRAL > 0);
