insert into CategoriaTrabalhador values (HIBERNATE_SEQUENCE.nextval, 101, 'Empregado - Geral, inclusive o empregado público da administração direta ou indireta contratado pela CLT', 'EMPREGADO_TRABALHADOR_TEMPORARIO' );
insert into CategoriaTrabalhador values (HIBERNATE_SEQUENCE.nextval, 102, 'Empregado - Trabalhador Rural por Pequeno Prazo da Lei 11.718/2008', 'EMPREGADO_TRABALHADOR_TEMPORARIO' );
insert into CategoriaTrabalhador values (HIBERNATE_SEQUENCE.nextval, 103, 'Empregado - Aprendiz', 'EMPREGADO_TRABALHADOR_TEMPORARIO' );
insert into CategoriaTrabalhador values (HIBERNATE_SEQUENCE.nextval, 104, 'Empregado - Doméstico', 'EMPREGADO_TRABALHADOR_TEMPORARIO' );
insert into CategoriaTrabalhador values (HIBERNATE_SEQUENCE.nextval, 105, 'Empregado - contrato a termo firmado nos termos da Lei 9601/98', 'EMPREGADO_TRABALHADOR_TEMPORARIO' );
insert into CategoriaTrabalhador values (HIBERNATE_SEQUENCE.nextval, 106, 'Trabalhador Temporário - contrato nos termos da Lei 6.019/74', 'EMPREGADO_TRABALHADOR_TEMPORARIO' );
insert into CategoriaTrabalhador values (HIBERNATE_SEQUENCE.nextval, 111, 'Empregado - contrato de trabalho intermitente', 'EMPREGADO_TRABALHADOR_TEMPORARIO' );
insert into CategoriaTrabalhador values (HIBERNATE_SEQUENCE.nextval, 201, 'Trabalhador Avulso Portuário','AVULSO' );
insert into CategoriaTrabalhador values (HIBERNATE_SEQUENCE.nextval, 202, 'Trabalhador Avulso Não Portuário','AVULSO' );
insert into CategoriaTrabalhador values (HIBERNATE_SEQUENCE.nextval, 301, 'Servidor Público Titular de Cargo Efetivo, Magistrado, Ministro de Tribunal de Contas, Conselheiro de Tribunal de Contas e Membro do Ministério Público','AGENTE_PUBLICO' );
insert into CategoriaTrabalhador values (HIBERNATE_SEQUENCE.nextval, 302, 'Servidor Público Ocupante de Cargo exclusivo em comissão','AGENTE_PUBLICO' );
insert into CategoriaTrabalhador values (HIBERNATE_SEQUENCE.nextval, 303, 'Agente Político','AGENTE_PUBLICO' );
insert into CategoriaTrabalhador values (HIBERNATE_SEQUENCE.nextval, 305, 'Servidor Público indicado para conselho ou órgão deliberativo, na condição de representante do governo, órgão ou entidade da administração pública','AGENTE_PUBLICO' );
insert into CategoriaTrabalhador values (HIBERNATE_SEQUENCE.nextval, 306, 'Servidor Público Temporário, sujeito a regime administrativo especial definido em lei própria','AGENTE_PUBLICO' );
insert into CategoriaTrabalhador values (HIBERNATE_SEQUENCE.nextval, 307, 'Militar efetivo','AGENTE_PUBLICO' );
insert into CategoriaTrabalhador values (HIBERNATE_SEQUENCE.nextval, 308, 'Conscrito','AGENTE_PUBLICO' );
insert into CategoriaTrabalhador values (HIBERNATE_SEQUENCE.nextval, 309, 'Agente Público - Outros','AGENTE_PUBLICO' );
insert into CategoriaTrabalhador values (HIBERNATE_SEQUENCE.nextval, 401, 'Dirigente Sindical - informação prestada pelo Sindicato','CESSAO' );
insert into CategoriaTrabalhador values (HIBERNATE_SEQUENCE.nextval, 410, 'Trabalhador cedido - informação prestada pelo Cessionário','CESSAO' );
insert into CategoriaTrabalhador values (HIBERNATE_SEQUENCE.nextval, 701, 'Contribuinte individual - Autônomo em geral, exceto se enquadrado em uma das demais categorias de contribuinte individual','CONTRIBUICAO_INDIVIDUAL' );
insert into CategoriaTrabalhador values (HIBERNATE_SEQUENCE.nextval, 711, 'Contribuinte individual - Transportador autônomo de passageiros','CONTRIBUICAO_INDIVIDUAL' );
insert into CategoriaTrabalhador values (HIBERNATE_SEQUENCE.nextval, 712, 'Contribuinte individual - Transportador autônomo de carga','CONTRIBUICAO_INDIVIDUAL' );
insert into CategoriaTrabalhador values (HIBERNATE_SEQUENCE.nextval, 721, 'Contribuinte individual - Diretor não empregado, com FGTS','CONTRIBUICAO_INDIVIDUAL' );
insert into CategoriaTrabalhador values (HIBERNATE_SEQUENCE.nextval, 722, 'Contribuinte individual - Diretor não empregado, sem FGTS','CONTRIBUICAO_INDIVIDUAL' );
insert into CategoriaTrabalhador values (HIBERNATE_SEQUENCE.nextval, 723, 'Contribuinte individual - empresários, sócios e membro de conselho de administração ou fiscal','CONTRIBUICAO_INDIVIDUAL' );
insert into CategoriaTrabalhador values (HIBERNATE_SEQUENCE.nextval, 731, 'Contribuinte individual - Cooperado que presta serviços por intermédio de Cooperativa de Trabalho','CONTRIBUICAO_INDIVIDUAL' );
insert into CategoriaTrabalhador values (HIBERNATE_SEQUENCE.nextval, 734, 'Contribuinte individual - Transportador Cooperado que presta serviços por intermédio de cooperativa de trabalho','CONTRIBUICAO_INDIVIDUAL' );
insert into CategoriaTrabalhador values (HIBERNATE_SEQUENCE.nextval, 738, 'Contribuinte individual - Cooperado filiado a Cooperativa de Produção','CONTRIBUICAO_INDIVIDUAL' );
insert into CategoriaTrabalhador values (HIBERNATE_SEQUENCE.nextval, 741, 'Contribuinte individual - Microempreendedor Individual','CONTRIBUICAO_INDIVIDUAL' );
insert into CategoriaTrabalhador values (HIBERNATE_SEQUENCE.nextval, 751, 'Contribuinte individual - magistrado classista temporário da Justiça do Trabalho ou da Justiça Eleitoral que seja aposentado de qualquer regime previdenciário','CONTRIBUICAO_INDIVIDUAL' );
insert into CategoriaTrabalhador values (HIBERNATE_SEQUENCE.nextval, 761, 'Contribuinte individual - Associado eleito para direção de Cooperativa, associação ou entidade de classe de qualquer natureza ou finalidade, bem como o síndico ou administrador eleito para exercer atividade de direção condominial, desde que recebam remuneração','CONTRIBUICAO_INDIVIDUAL' );
insert into CategoriaTrabalhador values (HIBERNATE_SEQUENCE.nextval, 771, 'Contribuinte individual - Membro de conselho tutelar, nos termos da Lei nº 8.069, de 13 de julho de 1990','CONTRIBUICAO_INDIVIDUAL' );
insert into CategoriaTrabalhador values (HIBERNATE_SEQUENCE.nextval, 781, 'Ministro de confissão religiosa ou membro de vida consagrada, de congregação ou de ordem religiosa','CONTRIBUICAO_INDIVIDUAL' );
insert into CategoriaTrabalhador values (HIBERNATE_SEQUENCE.nextval, 901, 'Estagiário','BOLSISTAS' );
insert into CategoriaTrabalhador values (HIBERNATE_SEQUENCE.nextval, 902, 'Médico Residente','BOLSISTAS' );
insert into CategoriaTrabalhador values (HIBERNATE_SEQUENCE.nextval, 903, 'Bolsista, nos termos da lei 8958/1994','BOLSISTAS' );
insert into CategoriaTrabalhador values (HIBERNATE_SEQUENCE.nextval, 904, 'Participante de curso de formação, como etapa de concurso público, sem vínculo de emprego/estatutário','BOLSISTAS' );
insert into CategoriaTrabalhador values (HIBERNATE_SEQUENCE.nextval, 905, 'Atleta não profissional em formação que receba bolsa','BOLSISTAS' );
