UPDATE QUALIFICACAOCADPESSOA SET PROCESSADOREJEITADO = 'QUALIFICADO' WHERE PROCESSADOREJEITADO = 'PROCESSADO';
UPDATE QUALIFICACAOCADPESSOA SET PROCESSADOREJEITADO = 'PENDENTE' WHERE PROCESSADOREJEITADO = 'REJEITADO';
