update PESSOA set CONTACORRENTEPRINCIPAL_ID = null where id in( select pessoa.id from CONTACORRENTEBANCPESSOA conta
inner join PESSOA on pessoa.CONTACORRENTEPRINCIPAL_ID = conta.id
where conta.CONTACORRENTEBANCARIA_ID = 683678614);

delete CONTACORRENTEBANCPESSOA where CONTACORRENTEBANCARIA_ID = 683678614;

update vinculofp set CONTACORRENTE_ID = null where CONTACORRENTE_ID =683678614;

delete CONTACORRENTEBANCARIA where id = 683678614;
