UPDATE VINCULOFP
SET VINCULOFP.NUMERO = 	(
    SELECT
        COALESCE((TO_NUMBER(max(v2.NUMERO)) + 1), 1)
    FROM
        VINCULOFP v2
            INNER JOIN MATRICULAFP m ON
                m.ID = v2.MATRICULAFP_ID
    WHERE
            m.ID = VINCULOFP.MATRICULAFP_ID)
WHERE NOT EXISTS (
    SELECT
        1
    FROM
        APOSENTADORIA a
    WHERE
            a.ID = VINCULOFP.ID)
  AND VINCULOFP.NUMERO IS NULL;



UPDATE VINCULOFP
SET VINCULOFP.NUMERO = 	(
    SELECT
        COALESCE(max(v2.NUMERO), '1')
    FROM
        VINCULOFP v2
            INNER JOIN MATRICULAFP m ON
                m.ID = v2.MATRICULAFP_ID
            INNER JOIN CONTRATOFP c ON c.ID = v2.ID
    WHERE
            m.ID = VINCULOFP.MATRICULAFP_ID)
WHERE VINCULOFP.ID IN (
    SELECT v.ID
    FROM
        VINCULOFP v
            INNER JOIN APOSENTADORIA a ON a.ID = v.ID
    WHERE v.NUMERO IS NULL);
