insert into EVENTOFPEMPREGADOR
(select HIBERNATE_SEQUENCE.nextval as ids, ENTIDADE_ID, INICIOVIGENCIA, FIMVIGENCIA, id, IDENTIFICACAOTABELA, NATUREZARUBRICA_ID, INCIDENCIAPREVIDENCIA_ID,
       INCIDENCIATRIBUTARIAIRRF_ID, INCIDENCIATRIBUTARIAFGTS_ID, INCIDENCIASINDICAL_ID, VERBADEFERIAS  from eventofp where NATUREZARUBRICA_ID is not null);
