update ENQUADRAMENTOFUNCIONAL e set e.CONSIDERAPARAPROGAUTOMAT = 0
WHERE EXISTS (
    SELECT 1 FROM ENQUADRAMENTOFUNCIONAL e1
                         INNER JOIN PROVIMENTOFP p ON p.ID = e1.PROVIMENTOFP_ID
                         INNER JOIN TIPOPROVIMENTO t ON t.ID = p.TIPOPROVIMENTO_ID
    WHERE t.DESCRICAO = 'PROMOÇÃO'
      AND e1.CONSIDERAPARAPROGAUTOMAT = 1
      AND e1.id = e.id
)
