INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES(hibernate_sequence.nextval, 'RECURSOS HUMANOS > ADMINISTRAÇÃO DE PAGAMENTO > COMPARATIVO DE FOLHAS DE PAGAMENTO', '/rh/administracaodepagamento/comparativofolhasdepagamento/lista.xhtml',
       0, 'RH');

INSERT INTO MENU (ID, LABEL, CAMINHO, PAI_ID, ORDEM)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'COMPARATIVO DE FOLHAS DE PAGAMENTO',
        '/rh/administracaodepagamento/comparativofolhasdepagamento/lista.xhtml',
        (SELECT ID FROM MENU WHERE LABEL = 'ADMINISTRAÇÃO DE PAGAMENTO' AND CAMINHO IS NULL), 180);
commit ;

INSERT INTO GRUPORECURSOSISTEMA (GRUPORECURSO_ID, RECURSOSISTEMA_ID)
VALUES ((SELECT ID FROM GRUPORECURSO WHERE NOME = 'Recursos Humanos'),
        (SELECT ID FROM RECURSOSISTEMA WHERE NOME = 'RECURSOS HUMANOS > ADMINISTRAÇÃO DE PAGAMENTO > COMPARATIVO DE FOLHAS DE PAGAMENTO'));
