update NIVELESCOLARIDADE set GRAUESCOLARIDADEESOCIAL = 'QUINTO_ANO_INCOMPLETO' where id = 6192023;
update NIVELESCOLARIDADE set GRAUESCOLARIDADEESOCIAL = 'FUNDAMENTAL_COMPLETO' where id = 73865971;
update NIVELESCOLARIDADE set GRAUESCOLARIDADEESOCIAL = 'SEXTO_AO_NONO_ANO' where id = 73865979;
update NIVELESCOLARIDADE set GRAUESCOLARIDADEESOCIAL = 'MEDIO_COMPLETO' where id = 73865991;
update NIVELESCOLARIDADE set GRAUESCOLARIDADEESOCIAL = 'SUPERIOR_COMPLETO' where id = 73866005;
update NIVELESCOLARIDADE set GRAUESCOLARIDADEESOCIAL = 'SUPERIOR_INCOMPLETO' where id = 73866041;
update NIVELESCOLARIDADE set GRAUESCOLARIDADEESOCIAL = 'QUINTO_ANO_COMPLETO' where id = 73866138;
update NIVELESCOLARIDADE set GRAUESCOLARIDADEESOCIAL = 'ANALFABETO' where id = 73866258;
update NIVELESCOLARIDADE set GRAUESCOLARIDADEESOCIAL = 'FUNDAMENTAL_COMPLETO' where id = 73866448;
update NIVELESCOLARIDADE set GRAUESCOLARIDADEESOCIAL = 'MESTRADO_COMPLETO' where id = 73866486;
update NIVELESCOLARIDADE set GRAUESCOLARIDADEESOCIAL = 'POS_GRADUACAO_COMPLETA' where id = 73866532;
update NIVELESCOLARIDADE set GRAUESCOLARIDADEESOCIAL = 'SUPERIOR_INCOMPLETO' where id = 73866873;
update NIVELESCOLARIDADE set GRAUESCOLARIDADEESOCIAL = 'SUPERIOR_COMPLETO' where id = 73868068;
update NIVELESCOLARIDADE set GRAUESCOLARIDADEESOCIAL = 'DOUTORADO_COMPLETO' where id = 73954337;
update NIVELESCOLARIDADE set GRAUESCOLARIDADEESOCIAL = 'ANALFABETO' where id = 329951249;

