update AVERBACAOTEMPOSERVICO av
set av.TIPOREGPREVIDENCIARIOCXATUA = null
where av.TIPOREGPREVIDENCIARIOCXATUA = 'RPPS_Atual';

update AVERBACAOTEMPOSERVICO av
set av.TIPOREGPREVIDENCIARIOCXATUA = 'RPPS_ESFERA_MUNICIPAL'
where av.TIPOREGPREVIDENCIARIOCXATUA = 'RPPS_Outro';
