update BLOQUEIODESBLOQUEIOUSUARIO set FIMVIGENCIA = null;
update BLOQUEIODESBLOQUEIOUSUARIO set BLOQUEARFERIAS = 0;
update BLOQUEIODESBLOQUEIOUSUARIO set BLOQUEARLICENSAPREMIO = 0;
update BLOQUEIODESBLOQUEIOUSUARIO set BLOQUEARCESSAOSEMONUS = 1;
delete BLOQUEIODESBUSUARIOEMAIL;
