package br.com.webpublico.consultaentidade;

public enum TAG {
    USUARIO_ID, USUARIO_LOGIN, UNIDADE_ADM_ID, UNIDADE_ORC_ID, DATA_OPERACAO, EXERCICIO_ID, EXERCICIO_ANO, TIPO_HIERARQUIA_ADM, TIPO_HIERARQUIA_ORC;
}
