INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'LICITAÇÃO > EXCLUSÃO DE DISPENSA > EDITAR',
        '/administrativo/licitacao/exclusao-dispensa-licitacao/edita.xhtml', 0, 'LICITACAO');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'LICITAÇÃO > EXCLUSÃO DE DISPENSA >  VISUALIZAR',
        '/administrativo/licitacao/exclusao-dispensa-licitacao/visualizar.xhtml', 0, 'LICITACAO');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'LICITAÇÃO > EXCLUSÃO DE DISPENSA >  LISTAR',
        '/administrativo/licitacao/exclusao-dispensa-licitacao/lista.xhtml', 0, 'LICITACAO');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);

INSERT INTO menu
VALUES (HIBERNATE_SEQUENCE.nextval, 'EXCLUSÃO DE DISPENSA',
        '/administrativo/licitacao/exclusao-dispensa-licitacao/lista.xhtml',
        (select ID from menu where LABEL = 'COMPRAS E LICITAÇÕES'),
        (select max(ORDEM) + 5 from menu where LABEL = 'COMPRAS E LICITAÇÕES'), null);
