INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'COMPRAS E LICITAÇÕES > ALTERAÇÃO FORNECEDOR LICITAÇÃO > EDITAR',
        '/administrativo/licitacao/alteracao-fornecedor-licitacao/edita.xhtml', 0, 'LICITACAO');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'COMPRAS E LICITAÇÕES > ALTERAÇÃO FORNECEDOR LICITAÇÃO > VISUALIZAR',
        '/administrativo/licitacao/alteracao-fornecedor-licitacao/visualizar.xhtml', 0, 'LICITACAO');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);
;

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'COMPRAS E LICITAÇÕES > ALTERAÇÃO FORNECEDOR LICITAÇÃO > LISTAR',
        '/administrativo/licitacao/alteracao-fornecedor-licitacao/lista.xhtml', 0, 'LICITACAO');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);


INSERT INTO menu
VALUES (HIBERNATE_SEQUENCE.nextval, 'ALTERAÇÃO FORNECEDOR LICITAÇÃO',
        '/administrativo/licitacao/alteracao-fornecedor-licitacao/lista.xhtml',
        (select ID from menu where LABEL = 'COMPRAS E LICITAÇÕES'),
        (select max(ORDEM) + 5 from menu where LABEL = 'COMPRAS E LICITAÇÕES'), null);
