INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'COMPRAS E LICITAÇÕES > CADASTROS GERAIS - LICITAÇÃO > OBJETO DE COMPRA > SUBSTITUIÇÃO DE OBJETO DE COMPRA > EDITAR',
        '/administrativo/licitacao/substituicao-objeto-compra/edita.xhtml', 0, 'LICITACAO');

INSERT INTO GRUPORECURSOSISTEMA
VALUES (HIBERNATE_SEQUENCE.currval, 173907291);

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'COMPRAS E LICITAÇÕES > CADASTROS GERAIS - LICITAÇÃO > OBJETO DE COMPRA > SUBSTITUIÇÃO DE OBJETO DE COMPRA > LISTAR',
        '/administrativo/licitacao/substituicao-objeto-compra/lista.xhtml', 0, 'LICITACAO');

INSERT INTO GRUPORECURSOSISTEMA
VALUES (HIBERNATE_SEQUENCE.currval, 173907291);

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'COMPRAS E LICITAÇÕES > CADASTROS GERAIS - LICITAÇÃO > OBJETO DE COMPRA > SUBSTITUIÇÃO DE OBJETO DE COMPRA > VISUALIZAR',
        '/administrativo/licitacao/substituicao-objeto-compra/visualizar.xhtml', 0, 'LICITACAO');

INSERT INTO GRUPORECURSOSISTEMA
VALUES (HIBERNATE_SEQUENCE.currval, 173907291);

INSERT INTO menu
VALUES (HIBERNATE_SEQUENCE.nextval, 'SUBSTITUIÇÃO DE OBJETO DE COMPRA',
        '/administrativo/licitacao/substituicao-objeto-compra/lista.xhtml',
        (select ID from menu where LABEL = 'OBJETO DE COMPRA'),
        (select max(ORDEM) + 5 from menu where LABEL = 'OBJETO DE COMPRA'), null);
