INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'FEIRAS > FEIRANTE >  EDITAR',
        '/administrativo/feiras/feirante/edita.xhtml', 0, 'FEIRAS');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'FEIRAS > FEIRANTE > VISUALIZAR',
        '/administrativo/feiras/feirante/visualizar.xhtml', 0, 'FEIRAS');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'FEIRAS > FEIRANTE > LISTAR',
        '/administrativo/feiras/feirante/lista.xhtml', 0, 'FEIRAS');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);

insert into MENU (ID, LABEL, CAMINHO, PAI_ID, ORDEM, ICONE)
values (HIBERNATE_SEQUENCE.nextval, 'FEIRANTE', '/administrativo/feiras/feirante/lista.xhtml', (select id from menu where LABEL = 'FEIRAS'), 10, null);
