INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'LICITACAO > AMPARO LEGAL > EDITAR',
        '/administrativo/licitacao/amparo-legal/edita.xhtml', 0, 'LICITACAO');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'LICITACAO > AMPARO LEGAL > VISUALIZAR',
        '/administrativo/licitacao/amparo-legal/visualizar.xhtml', 0, 'LICITACAO');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'LICITACAO > AMPARO LEGAL > LISTAR',
        '/administrativo/licitacao/amparo-legal/lista.xhtml', 0, 'LICITACAO');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);


INSERT INTO menu
VALUES (HIBERNATE_SEQUENCE.nextval, 'AMPARO LEGAL',
        '/administrativo/licitacao/amparo-legal/lista.xhtml',
        (select ID from menu where LABEL = 'LICITACAO'),
        (select max(ORDEM) + 5 from menu where LABEL = 'LICITACAO'), null);
