merge into ITEMINTENCAOREGISTROPRECO item
using LOTEINTENCAOREGISTROPRECO lote on (lote.INTENCAOREGISTROPRECO_ID = item.INTENCAOREGISTROPRECO_ID and lote.TIPOOBJETOCOMPRA = item.TIPOOBJETOCOMPRA)
when matched then update set item.LOTEINTENCAOREGISTROPRECO_ID = lote.ID
