insert into MENU (ID, LABEL, CAMINHO, PAI_ID, ORDEM, ICONE)
values (HIBERNATE_SEQUENCE.nextval, 'FEIRAS', null, null, 55, null);

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'FEIRAS > PRODUTO >  EDITAR',
        '/administrativo/feiras/produto/edita.xhtml', 0, 'FEIRAS');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'FEIRAS > PRODUTO > VISUALIZAR',
        '/administrativo/feiras/produto/visualizar.xhtml', 0, 'FEIRAS');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'FEIRAS > PRODUTO > LISTAR',
        '/administrativo/feiras/produto/lista.xhtml', 0, 'FEIRAS');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);

insert into MENU (ID, LABEL, CAMINHO, PAI_ID, ORDEM, ICONE)
values (HIBERNATE_SEQUENCE.nextval, 'PRODUTOS', '/administrativo/feiras/produto/lista.xhtml', (select id from menu where LABEL = 'FEIRAS'), 1, null);
