alter table ITEMSAIDAMATERIAL add VALORTOTALDECIMAL NUMBER(19,2);
alter table ITEMSAIDAMATERIAL_AUD add VALORTOTALDECIMAL NUMBER(19,2);

update ITEMSAIDAMATERIAL set VALORTOTALDECIMAL = round(VALORTOTAL,2);
update ITEMSAIDAMATERIAL_AUD set VALORTOTALDECIMAL = round(VALORTOTAL,2);

alter table ITEMSAIDAMATERIAL drop column VALORTOTAL;
alter table ITEMSAIDAMATERIAL_AUD drop column VALORTOTAL;

alter table ITEMSAIDAMATERIAL rename column VALORTOTALDECIMAL TO VALORTOTAL;
alter table ITEMSAIDAMATERIAL_AUD rename column VALORTOTALDECIMAL TO VALORTOTAL;


alter table ITEMSAIDAMATERIAL add VALORUNITARIOMONETARIO NUMBER(24,8);
alter table ITEMSAIDAMATERIAL_AUD add VALORUNITARIOMONETARIO NUMBER(24,8);

update ITEMSAIDAMATERIAL set VALORUNITARIOMONETARIO = VALORUNITARIO;
update ITEMSAIDAMATERIAL_AUD set VALORUNITARIOMONETARIO = VALORUNITARIO;

alter table ITEMSAIDAMATERIAL drop column VALORUNITARIO;
alter table ITEMSAIDAMATERIAL_AUD drop column VALORUNITARIO;

alter table ITEMSAIDAMATERIAL rename column VALORUNITARIOMONETARIO TO VALORUNITARIO;
alter table ITEMSAIDAMATERIAL_AUD rename column VALORUNITARIOMONETARIO TO VALORUNITARIO;
