 UPDATE BEM SET REGISTROANTERIOR = (SELECT LEV.CODIGOPATRIMONIO
                                    FROM LEVANTAMENTOBEMPATRIMONIAL LEV
                                  WHERE BEM.ID = LEV.BEM_ID
                                  )
 WHERE EXISTS(SELECT 1 FROM LEVANTAMENTOBEMPATRIMONIAL L WHERE L.BEM_ID = BEM.ID)
