UPDATE LOTECOTACAO
SET TIPOBENEFICIO = 'PARTICIPACAO_EXCLUSIVA'
WHERE EXISTS (
          SELECT 1
          FROM cotacao c
                   INNER JOIN SOLICITACAOMATERIAL sol ON c.ID = sol.COTACAO_ID
                   INNER JOIN PROCESSODECOMPRA pc ON sol.ID = pc.SOLICITACAOMATERIAL_ID
                   INNER JOIN LICITACAO l ON pc.ID = l.PROCESSODECOMPRA_ID
          WHERE LOTECOTACAO.COTACAO_ID = c.ID
            AND l.EXCLUSIVAMICPEQEMPRESA = 1
          );
