INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'MATERIAIS > ALIMENTAÇÃO ESCOLAR > CARDÁPIO >  EDITAR',
        '/administrativo/materiais/alimentacao-escolar/cardapio/edita.xhtml', 0, 'MATERIAIS');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'MATERIAIS > ALIMENTAÇÃO ESCOLAR > CARDÁPIO > VISUALIZAR',
        '/administrativo/materiais/alimentacao-escolar/cardapio/visualizar.xhtml', 0, 'MATERIAIS');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);
;

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'MATERIAIS > ALIMENTAÇÃO ESCOLAR > CARDÁPIO > LISTAR',
        '/administrativo/materiais/alimentacao-escolar/cardapio/lista.xhtml', 0, 'MATERIAIS');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);

INSERT INTO menu (ID, LABEL, CAMINHO, PAI_ID, ORDEM, ICONE)
VALUES (HIBERNATE_SEQUENCE.nextval, 'CARDÁPIO',
        '/administrativo/materiais/alimentacao-escolar/cardapio/lista.xhtml',
        (select ID from menu where LABEL = 'ALIMENTAÇÃO ESCOLAR'), 20, null);
