INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'CONTRATOS > LANÇAMENTO DE DÉBITOS PARA CONTRATO CONCESSÃO > EDITAR',
        '/tributario/contrato-concessao/edita.xhtml', 0, 'CONTRATOS');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'CONTRATOS > LANÇAMENTO DE DÉBITOS PARA CONTRATO CONCESSÃO > VISUALIZAR',
        '/tributario/contrato-concessao/visualizar.xhtml', 0, 'CONTRATOS');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);
;

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'CONTRATOS > LANÇAMENTO DE DÉBITOS PARA CONTRATO CONCESSÃO > LISTAR',
        '/tributario/contrato-concessao/lista.xhtml', 0, 'CONTRATOS');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);


INSERT INTO menu
VALUES (HIBERNATE_SEQUENCE.nextval, 'LANCAMENTO DE DÉBITO PARA CONTRATO DE CONCESSÃO',
        '/tributario/contrato-concessao/lista.xhtml',
        (select ID from menu where LABEL = 'OBJETO DE COMPRA'),
        (select max(ORDEM) + 5 from menu where LABEL = 'CONTRATOS'), null);
