update SOLICITACAOMATERIAL set MODOSOLICITACAO  = 'LICITACAO'
where MODOSOLICITACAO = 'MODALIDADE';

update SOLICITACAOMATERIAL set MODOSOLICITACAO  = 'DISPENSA_INEXIGIBILIDADE'
where MODALIDADELICITACAO IN ('DISPENSA_LICITACAO', 'INEXIGIBILIDADE');

update SOLICITACAOMATERIAL set MODOSOLICITACAO  = 'PROCEDIMENTO_AUXILIARES'
where MODALIDADELICITACAO IN ('CREDENCIAMENTO', 'MANIFESTACAO_INTERESSE', 'PRE_QUALIFICACAO');

update SOLICITACAOMATERIAL set INSTRUMENTOCONVOCATORIO  = 'ATO_AUTORIZA_CONTRATACAO_DIRETA'
where MODALIDADELICITACAO IN ('DISPENSA_LICITACAO', 'INEXIGIBILIDADE');

update SOLICITACAOMATERIAL set INSTRUMENTOCONVOCATORIO  = 'EDITAL'
where MODALIDADELICITACAO NOT IN ('DISPENSA_LICITACAO', 'INEXIGIBILIDADE');
