insert into movimentoaditivocontrato (ID, ADITIVOCONTRATO_ID, TIPO, FINALIDADE,OBJETO, OPERACAO, UNIDADEORGANIZACIONAL_ID)
select HIBERNATE_SEQUENCE.nextval,
       id,
       'NAO_SE_APLICA',
       'NAO_SE_APLICA',
       JUSTIFICATIVA,
       'TRANSFERENCIA_UNIDADE',
       UNIDADEADMINISTRATIVA_ID
from ADITIVOCONTRATO
where TRANSFERIRUNIDADE = 1;
