INSERT INTO AJUSTECONTRATO (ID, CONTRATO_ID, UNIDADEORGANIZACIONAL_ID, DETENTORARQUIVOCOMPOSICAO_ID, NUMEROTERMO,
                            DATALANCAMENTO, DATAAPROVACAO, DATADEFERIMENTO, DATAASSINATURA, HISTORICO, SITUACAO,
                            TIPOTERMO, TIPOAJUSTE, NUMEROAJUSTE, EXERCICIO_ID)
SELECT HIBERNATE_SEQUENCE.nextval,
       CONTRATO_ID,
       (SELECT UN.UNIDADEADMINISTRATIVA_ID
        FROM UNIDADECONTRATO UN
        WHERE UN.CONTRATO_ID = ALT.CONTRATO_ID fetch first 1 rows only),
       NULL,
       '0001',
       TO_DATE(ALT.DATALANCAMENTO, 'dd/MM/yyyy'),
       TO_DATE(ALT.DATALANCAMENTO, 'dd/MM/yyyy'),
       TO_DATE(ALT.DATALANCAMENTO, 'dd/MM/yyyy'),
       TO_DATE(ALT.DATALANCAMENTO, 'dd/MM/yyyy'),
       SUBSTR(ALT.HISTORICOPROCESSO, 0, 3000),
       'DEFERIDO',
       'ALTERACAO_CADASTRAL',
       'CONTROLE_EXECUCAO',
       '0001',
       C.EXERCICIOCONTRATO_ID
FROM ALTERACAOITEMPROCESSO ALT
         INNER JOIN CONTRATO C ON ALT.CONTRATO_ID = C.ID;
