INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'MATERIAIS > ALIMENTAÇÃO ESCOLAR > PROGRAMA DE ALIMENTAÇÃO >  EDITAR',
        '/administrativo/materiais/alimentacao-escolar/programa-alimentacao/edita.xhtml', 0, 'MATERIAIS');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'MATERIAIS > ALIMENTAÇÃO ESCOLAR > PROGRAMA DE ALIMENTAÇÃO > VISUALIZAR',
        '/administrativo/materiais/alimentacao-escolar/programa-alimentacao/visualizar.xhtml', 0, 'MATERIAIS');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);
;

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'MATERIAIS > ALIMENTAÇÃO ESCOLAR > PROGRAMA DE ALIMENTAÇÃO > LISTAR',
        '/administrativo/materiais/alimentacao-escolar/programa-alimentacao/lista.xhtml', 0, 'MATERIAIS');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);


INSERT INTO menu (ID, LABEL, CAMINHO, PAI_ID, ORDEM, ICONE)
VALUES (HIBERNATE_SEQUENCE.nextval, 'ALIMENTAÇÃO ESCOLAR', null,
        (select ID from menu where LABEL = 'MATERIAIS'),
        (select max(ORDEM) + 5 from menu where LABEL = 'ROTINAS'), null);

INSERT INTO menu (ID, LABEL, CAMINHO, PAI_ID, ORDEM, ICONE)
VALUES (HIBERNATE_SEQUENCE.nextval, 'PROGRAMA DE ALIMENTAÇÃO',
        '/administrativo/materiais/alimentacao-escolar/programa-alimentacao/lista.xhtml',
        (select ID from menu where LABEL = 'ALIMENTAÇÃO ESCOLAR'), 1, null);
