INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'LICITAÇÃO > COMPRAS E LICITAÇÕES > PLANO ANUAL DE CONTRATAÇÕES > EDITAR',
        '/administrativo/licitacao/pac/edita.xhtml', 0, 'LICITACAO');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'LICITAÇÃO > COMPRAS E LICITAÇÕES > PLANO ANUAL DE CONTRATAÇÕES > VISUALIZAR',
        '/administrativo/licitacao/pac/visualizar.xhtml', 0, 'LICITACAO');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);


INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'LICITAÇÃO > COMPRAS E LICITAÇÕES > PLANO ANUAL DE CONTRATAÇÕES > LISTAR',
        '/administrativo/licitacao/pac/lista.xhtml', 0, 'LICITACAO');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);


INSERT INTO menu
VALUES (HIBERNATE_SEQUENCE.nextval, 'PLANO ANUAL DE CONTRATAÇÕES - PAC',
        '/administrativo/licitacao/pac/lista.xhtml',
        (select ID from menu where LABEL = 'COMPRAS E LICITAÇÕES'),
        (select max(ORDEM) + 2 from menu where LABEL = 'CADASTROS GERAIS - LICITAÇÃO'), null);
