insert into TIPODOCTOOFICIAL (ID, CODIGO, DESCRICAO, GRUPODOCTOOFICIAL_ID, TIPOCADASTRODOCTOOFICIAL, VALIDADEDOCTO,
                              TIPOVALIDACAODOCTOOFICIAL, CONTROLEENVIORECEBIMENTO, MODULOTIPODOCTOOFICIAL,
                              IMPRIMIRDIRETOPDF, DISPONIVELSOLICITACAOWEB, EXIGIRASSINATURA,
                              PERMITIRIMPRESSAOSEMASSINATURA)
VALUES (HIBERNATE_SEQUENCE.nextval, 168, 'DFD - DOCUMENTO DE FORMALIZAÇÃO DE DEMANDA', 6494687, 'NENHUM', 365, 'SEMVALIDACAO', 0, 'DFD', 0, 0, 0, 0)
