INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'MATERIAIS > ALIMENTAÇÃO ESCOLAR > REFEIÇÃO >  EDITAR',
        '/administrativo/materiais/alimentacao-escolar/refeicao/edita.xhtml', 0, 'MATERIAIS');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'MATERIAIS > ALIMENTAÇÃO ESCOLAR > REFEIÇÃO > VISUALIZAR',
        '/administrativo/materiais/alimentacao-escolar/refeicao/visualizar.xhtml', 0, 'MATERIAIS');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);
;

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'MATERIAIS > ALIMENTAÇÃO ESCOLAR > REFEIÇÃO > LISTAR',
        '/administrativo/materiais/alimentacao-escolar/refeicao/lista.xhtml', 0, 'MATERIAIS');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);

INSERT INTO menu (ID, LABEL, CAMINHO, PAI_ID, ORDEM, ICONE)
VALUES (HIBERNATE_SEQUENCE.nextval, 'REFEIÇÃO',
        '/administrativo/materiais/alimentacao-escolar/refeicao/lista.xhtml',
        (select ID from menu where LABEL = 'ALIMENTAÇÃO ESCOLAR'), 10, null);
