update PARTICIPANTEIRP set INTENCAOREGISTRODEPRECO_ID = 10643203203
where id = 10643800859;

insert into UnidadeParticipanteIRP (id, PARTICIPANTEIRP_ID, UNIDADEPARTICIPANTE_ID, INICIOVIGENCIA)
select hibernate_sequence.nextval as id_nn, id, UNIDADEORGANIZACIONAL_ID, DATAINTERESSE from PARTICIPANTEIRP
where UNIDADEORGANIZACIONAL_ID is not null;
