INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'FEIRAS > FEIRA >  EDITAR',
        '/administrativo/feiras/feira/edita.xhtml', 0, 'FEIRAS');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'FEIRAS > FEIRA > VISUALIZAR',
        '/administrativo/feiras/feira/visualizar.xhtml', 0, 'FEIRAS');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);

INSERT INTO RECURSOSISTEMA (ID, NOME, CAMINHO, CADASTRO, MODULO)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'FEIRAS > FEIRA > LISTAR',
        '/administrativo/feiras/feira/lista.xhtml', 0, 'FEIRAS');

INSERT INTO GRUPORECURSOSISTEMA (RECURSOSISTEMA_ID, GRUPORECURSO_ID)
VALUES (HIBERNATE_SEQUENCE.currval, 75756874);

insert into MENU (ID, LABEL, CAMINHO, PAI_ID, ORDEM, ICONE)
values (HIBERNATE_SEQUENCE.nextval, 'FEIRA', '/administrativo/feiras/produto/lista.xhtml', (select id from menu where LABEL = 'FEIRAS'), 5, null);
