"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ABASTECIMENTOS.png  ABASTECIMENTOS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ABERTURA_E_FECHAMENTO_DE_EXERCICIO.png  ABERTURA_E_FECHAMENTO_DE_EXERCICIO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ACAO.png  ACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ACAO_FISCAL.png  ACAO_FISCAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ACESSO_A_CARGO_DE_COMISSAO.png  ACESSO_A_CARGO_DE_COMISSAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ACESSO_A_FUNCAO_GRATIFICADA.png  ACESSO_A_FUNCAO_GRATIFICADA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ADJUDICACAO_E_HOMOLOGACAO.png  ADJUDICACAO_E_HOMOLOGACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o AFASTAMENTO.png  AFASTAMENTO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o AGENCIA_BANCARIA.png  AGENCIA_BANCARIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o AGENDAMENTO_DE_TAREFAS.png  AGENDAMENTO_DE_TAREFAS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o AGENTE_CAUSADOR.png  AGENTE_CAUSADOR.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o AGENTE_CAUSADOR_DOENCA_PROFISSIONAL.png  AGENTE_CAUSADOR_DOENCA_PROFISSIONAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o AGENTE_DOENCA_PROFISSIONAL.png  AGENTE_DOENCA_PROFISSIONAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o AGENTE_DO_ACIDENTE_DE_TRABALHO.png  AGENTE_DO_ACIDENTE_DE_TRABALHO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o AGRUPAMENTO_DE_RECURSOS.png  AGRUPAMENTO_DE_RECURSOS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o AIDF.png  AIDF.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o AJUSTES_DE_PERDA_DE_BEM_INTANGIVEL.png  AJUSTES_DE_PERDA_DE_BEM_INTANGIVEL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o AJUSTES_DE_PERDA_DE_BENS_IMOVEIS.png  AJUSTES_DE_PERDA_DE_BENS_IMOVEIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o AJUSTES_DE_PERDA_DE_BENS_MOVEIS.png  AJUSTES_DE_PERDA_DE_BENS_MOVEIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o AJUSTE_EM_ATIVO_DISPONIVEL.png  AJUSTE_EM_ATIVO_DISPONIVEL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o AJUSTE_EM_DEPOSITO.png  AJUSTE_EM_DEPOSITO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ALTERACAO_DE_CONSERVACAO_DE_BENS_IMOVEIS.png  ALTERACAO_DE_CONSERVACAO_DE_BENS_IMOVEIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ALTERACAO_DE_CONSERVACAO_DE_BENS_MOVEIS.png  ALTERACAO_DE_CONSERVACAO_DE_BENS_MOVEIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ALTERACAO_DE_NOTA_FISCAL_AVULSA.png  ALTERACAO_DE_NOTA_FISCAL_AVULSA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ALTERACAO_ORCAMENTARIA.png  ALTERACAO_ORCAMENTARIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ALTERAR_SITUACAO_DE_CDA.png  ALTERAR_SITUACAO_DE_CDA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ALVARA_DE_FUNCIONAMENTO.png  ALVARA_DE_FUNCIONAMENTO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ALVARA_DE_FUNCIONAMENTO_PROVISORIO.png  ALVARA_DE_FUNCIONAMENTO_PROVISORIO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ALVARA_DE_LOCALIZACAO.png  ALVARA_DE_LOCALIZACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ALVARA_DE_VIGILANCIA_SANITARIA.png  ALVARA_DE_VIGILANCIA_SANITARIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ALVARA_DE_VIGILANCIA_SANITARIO_PROVISORIO.png  ALVARA_DE_VIGILANCIA_SANITARIO_PROVISORIO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ANEXOS.png  ANEXOS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o APOSENTADORIA.png  APOSENTADORIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o APRESENTACAO.png  APRESENTACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o APROVACAO_DE_LEVANTAMENTO_DE_BENS_MOVEIS.png  APROVACAO_DE_LEVANTAMENTO_DE_BENS_MOVEIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o APROVACAO_DE_RESPONSAVEL_TECNICOFISCAL.png  APROVACAO_DE_RESPONSAVEL_TECNICOFISCAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o APROVACAO_DE_SOLICITACAO_DE_ALIENACAO_DE_BEM_MOVEL.png  APROVACAO_DE_SOLICITACAO_DE_ALIENACAO_DE_BEM_MOVEL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o APROVACAO_DE_SOLICITACAO_DE_INCORPORACAO_MOVEL.png  APROVACAO_DE_SOLICITACAO_DE_INCORPORACAO_MOVEL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o APROVAR_PROGRAMACAO_DE_FERIAS.png  APROVAR_PROGRAMACAO_DE_FERIAS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o AQUISICAO_DE_BENS_IMOVEIS.png  AQUISICAO_DE_BENS_IMOVEIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o AQUISICAO_DE_BENS_MOVEIS.png  AQUISICAO_DE_BENS_MOVEIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o AREA_DE_FORMACAO.png  AREA_DE_FORMACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ARQUIVO_CAGED.png  ARQUIVO_CAGED.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ARQUIVO_DIRF.png  ARQUIVO_DIRF.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ARQUIVO_PISPASEP.png  ARQUIVO_PISPASEP.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ARQUIVO_RAIS.png  ARQUIVO_RAIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ARQUIVO__OBN600.png  ARQUIVO__OBN600.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ARQUIVO___OBN350.png  ARQUIVO___OBN350.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ASSOCIACAO.png  ASSOCIACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ASSOCIACAO_GRUPO_DE_OBJETO_DE_COMPRA_E_GRUPO_DE_MATERIAL.png  ASSOCIACAO_GRUPO_DE_OBJETO_DE_COMPRA_E_GRUPO_DE_MATERIAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ASSOCIACAO_GRUPO_DE_OBJETO_DE_COMPRA_E_GRUPO_PATRIMONIAL.png  ASSOCIACAO_GRUPO_DE_OBJETO_DE_COMPRA_E_GRUPO_PATRIMONIAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ASSUNTO.png  ASSUNTO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ATA_DA_LICITACAO.png  ATA_DA_LICITACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ATA_DE_REGISTRO_DE_PRECOS.png  ATA_DE_REGISTRO_DE_PRECOS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ATA_DE_REGISTRO_DE_PRECO_EXTERNO.png  ATA_DE_REGISTRO_DE_PRECO_EXTERNO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ATIVIDADE_DOS_PONTOS_COMERCIAIS.png  ATIVIDADE_DOS_PONTOS_COMERCIAIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ATIVIDADE_ECONOMICA.png  ATIVIDADE_ECONOMICA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ATOS_LEGAIS_(LEI).png  ATOS_LEGAIS_(LEI).dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ATO_DE_PESSOAL.png  ATO_DE_PESSOAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ATRIBUTOS_GENERICOS.png  ATRIBUTOS_GENERICOS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o AUTO_DE_INFRACAO.png  AUTO_DE_INFRACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o AVALIACAO.png  AVALIACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o AVALIACAO_DA_PRORROGACAO_DE_CESSAO_DE_BEM_MOVEL.png  AVALIACAO_DA_PRORROGACAO_DE_CESSAO_DE_BEM_MOVEL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o AVALIACAO_DE_REQUISICAO.png  AVALIACAO_DE_REQUISICAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o AVALIACAO_DE_SOLICITACAO_DE_COMPRA.png  AVALIACAO_DE_SOLICITACAO_DE_COMPRA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o AVALIACAO_PROVAS.png  AVALIACAO_PROVAS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o AVALIACAO_RECURSO.png  AVALIACAO_RECURSO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o AVERBACAO_TEMPO_DE_CONTRIBUICAO.png  AVERBACAO_TEMPO_DE_CONTRIBUICAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o AVISONOTIFICACAO_DE_COBRANCA.png  AVISONOTIFICACAO_DE_COBRANCA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o BAIRRO.png  BAIRRO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o BAIXA.png  BAIXA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o BAIXA_DE_ATIVIDADE.png  BAIXA_DE_ATIVIDADE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o BAIXA_DE_NOTIFICACAO.png  BAIXA_DE_NOTIFICACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o BANCA_EXAMINADORA.png  BANCA_EXAMINADORA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o BANCO.png  BANCO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o BASES_FP.png  BASES_FP.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o BASE_PERIODO_AQUISITIVO.png  BASE_PERIODO_AQUISITIVO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o BENEFICIARIOS_DE_PENSAO_JUDICIAL_TRAMITADA_E_JULGADA.png  BENEFICIARIOS_DE_PENSAO_JUDICIAL_TRAMITADA_E_JULGADA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o BENS_DE_ESTOQUE.png  BENS_DE_ESTOQUE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o BENS_IMOVEIS.png  BENS_IMOVEIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o BENS_INTANGIVEIS.png  BENS_INTANGIVEIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o BENS_MOVEIS.png  BENS_MOVEIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o BLOQUEIO_DE_BENEFICIO.png  BLOQUEIO_DE_BENEFICIO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o BLOQUEIO_DE_PAGAMENTO.png  BLOQUEIO_DE_PAGAMENTO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CABECALHO_DE_RELATORIO.png  CABECALHO_DE_RELATORIO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CADASTRO_DE_LEVANTAMENTO_DE_BENS_IMOVEIS.png  CADASTRO_DE_LEVANTAMENTO_DE_BENS_IMOVEIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CADASTRO_DE_LEVANTAMENTO_DE_BENS_MOVEIS.png  CADASTRO_DE_LEVANTAMENTO_DE_BENS_MOVEIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CADASTRO_DE_OUTORGA_DE_EMPRESA.png  CADASTRO_DE_OUTORGA_DE_EMPRESA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CADASTRO_DE_PESSOA_FISICA_(PERFIL_TRIBUTARIO).png  CADASTRO_DE_PESSOA_FISICA_(PERFIL_TRIBUTARIO).dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CADASTRO_DE_PESSOA_JURIDICA_(PERFIL_TRIBUTARIO).png  CADASTRO_DE_PESSOA_JURIDICA_(PERFIL_TRIBUTARIO).dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CADASTRO_DE_PRESTADOR_DE_SERVICOS.png  CADASTRO_DE_PRESTADOR_DE_SERVICOS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CADASTRO_DE_TIPO_DE_DOCUMENTO_ANEXO.png  CADASTRO_DE_TIPO_DE_DOCUMENTO_ANEXO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CADASTRO_ECONOMICO__CMC.png  CADASTRO_ECONOMICO__CMC.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CADASTRO_RURAL__BCR.png  CADASTRO_RURAL__BCR.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CAIXA_ATUARIAL.png  CAIXA_ATUARIAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CALCULO_DE_IPTU.png  CALCULO_DE_IPTU.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CALCULO_DE_PRESTACAO_DE_SERVICOS.png  CALCULO_DE_PRESTACAO_DE_SERVICOS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CALCULO_REAJUSTE_POR_MEDIA.png  CALCULO_REAJUSTE_POR_MEDIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CALENDARIO_FP.png  CALENDARIO_FP.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CANCELAMENTO_DE_DIVIDAS_DIVERSAS.png  CANCELAMENTO_DE_DIVIDAS_DIVERSAS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CANCELAMENTO_DE_ISENCAO_DE_IPTU.png  CANCELAMENTO_DE_ISENCAO_DE_IPTU.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CANCELAMENTO_DE_NOTA_FISCAL_AVULSA.png  CANCELAMENTO_DE_NOTA_FISCAL_AVULSA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CANCELAMENTO_DE_PROCESSO_FISCAL.png  CANCELAMENTO_DE_PROCESSO_FISCAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CANCELAMENTO_DE_RESERVA_DE_DOTACAO.png  CANCELAMENTO_DE_RESERVA_DE_DOTACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CANCELAMENTO_DE_RESTO_A_PAGAR.png  CANCELAMENTO_DE_RESTO_A_PAGAR.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CANCELAMENTO_DE_SOLICITACAO_E_EMISSAO_DE_CERTIDAO_E_DOCUMENTO_OFICIAL.png  CANCELAMENTO_DE_SOLICITACAO_E_EMISSAO_DE_CERTIDAO_E_DOCUMENTO_OFICIAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CANCELAMENTO_DE_TAXAS_DIVERSAS.png  CANCELAMENTO_DE_TAXAS_DIVERSAS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CARACTERISTICA_DE_FUNCIONAMENTO.png  CARACTERISTICA_DE_FUNCIONAMENTO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CARGO.png  CARGO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CARTORIO.png  CARTORIO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CAT.png  CAT.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CATEGORIA_DE_DESPESA.png  CATEGORIA_DE_DESPESA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CATEGORIA_DE_ISENCAO.png  CATEGORIA_DE_ISENCAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CATEGORIA_PCCR.png  CATEGORIA_PCCR.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CATEGORIA_SEFIP.png  CATEGORIA_SEFIP.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CEDENCIAS.png  CEDENCIAS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CEDULA_DE_INFORMACAO.png  CEDULA_DE_INFORMACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CID.png  CID.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CLASSE_DE_PESSOA.png  CLASSE_DE_PESSOA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CLASSIFICACAO_CONCURSO.png  CLASSIFICACAO_CONCURSO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CLAUSULAS_BENEFICIARIAS.png  CLAUSULAS_BENEFICIARIAS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CLP.png  CLP.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CNAE.png  CNAE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CODIGOS_DE_PAGAMENTO_DO_GPS.png  CODIGOS_DE_PAGAMENTO_DO_GPS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CODIGOS_DE_RECOLHIMENTO.png  CODIGOS_DE_RECOLHIMENTO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CODIGO_DE_RECOLHIMENTO_SEFIP.png  CODIGO_DE_RECOLHIMENTO_SEFIP.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o COMBUSTIVEIS.png  COMBUSTIVEIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o COMPETENCIA.png  COMPETENCIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONCESSAO_DE_FERIAS.png  CONCESSAO_DE_FERIAS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONCESSAO_DE_LICENCA_PREMIO.png  CONCESSAO_DE_LICENCA_PREMIO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONCESSAO_DE_SUPRIMENTO_DE_FUNDO.png  CONCESSAO_DE_SUPRIMENTO_DE_FUNDO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONCURSOS.png  CONCURSOS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONDICAO_DE_OCUPACAO.png  CONDICAO_DE_OCUPACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONDOMINIO.png  CONDOMINIO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFERIR_FALTAS.png  CONFERIR_FALTAS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFERIR_FALTAS_POR_SERVIDOR.png  CONFERIR_FALTAS_POR_SERVIDOR.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_ARQUIVO_OBN.png  CONFIGURACAO_ARQUIVO_OBN.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_CONTABIL.png  CONFIGURACAO_CONTABIL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_CONTA_DE_DESPESAGRUPO_BEM.png  CONFIGURACAO_CONTA_DE_DESPESAGRUPO_BEM.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_CONTA_DE_DESPESAGRUPO_MATERIAL.png  CONFIGURACAO_CONTA_DE_DESPESAGRUPO_MATERIAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_CONTA_DE_DESPESATIPO_DE_PESSOA.png  CONFIGURACAO_CONTA_DE_DESPESATIPO_DE_PESSOA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_CONTA_DE_DESPESATIPO_DE_VIAGEM.png  CONFIGURACAO_CONTA_DE_DESPESATIPO_DE_VIAGEM.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_ACRESCIMOS.png  CONFIGURACAO_DE_ACRESCIMOS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_AJUSTE_EM_ATIVO_DISPONIVEL.png  CONFIGURACAO_DE_AJUSTE_EM_ATIVO_DISPONIVEL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_AJUSTE_EM_DEPOSITO.png  CONFIGURACAO_DE_AJUSTE_EM_DEPOSITO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_ALTERACAO_ORCAMENTARIA.png  CONFIGURACAO_DE_ALTERACAO_ORCAMENTARIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_BENS_DE_ESTOQUE.png  CONFIGURACAO_DE_BENS_DE_ESTOQUE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_BENS_IMOVEIS.png  CONFIGURACAO_DE_BENS_IMOVEIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_BENS_INTANGIVEIS.png  CONFIGURACAO_DE_BENS_INTANGIVEIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_BENS_MOVEIS.png  CONFIGURACAO_DE_BENS_MOVEIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_CALCULO_DE_IPTU.png  CONFIGURACAO_DE_CALCULO_DE_IPTU.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_CANCELAMENTO_DE_RESTOS_A_PAGAR.png  CONFIGURACAO_DE_CANCELAMENTO_DE_RESTOS_A_PAGAR.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_CREDENCIAL.png  CONFIGURACAO_DE_CREDENCIAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_CREDITOS_A_RECEBER.png  CONFIGURACAO_DE_CREDITOS_A_RECEBER.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_DAM.png  CONFIGURACAO_DE_DAM.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_DESPESA_EXTRAORCAMENTARIA.png  CONFIGURACAO_DE_DESPESA_EXTRAORCAMENTARIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_DIARIA_CIVIL.png  CONFIGURACAO_DE_DIARIA_CIVIL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_DIARIA_DE_CAMPO.png  CONFIGURACAO_DE_DIARIA_DE_CAMPO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_DIVIDA_ATIVA.png  CONFIGURACAO_DE_DIVIDA_ATIVA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_EMPENHO.png  CONFIGURACAO_DE_EMPENHO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_ENTIDADES_PARA_DECLARACOES_E_PRESTACOES_DE_CONTAS.png  CONFIGURACAO_DE_ENTIDADES_PARA_DECLARACOES_E_PRESTACOES_DE_CONTAS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_LIBERACAO_FINANCEIRA.png  CONFIGURACAO_DE_LIBERACAO_FINANCEIRA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_LICITACAO.png  CONFIGURACAO_DE_LICITACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_LIQUIDACAO.png  CONFIGURACAO_DE_LIQUIDACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_LIQUIDACAO_DE_RESTO_A_PAGAR.png  CONFIGURACAO_DE_LIQUIDACAO_DE_RESTO_A_PAGAR.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_MODALIDADES_DE_CONTRATO.png  CONFIGURACAO_DE_MODALIDADES_DE_CONTRATO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_MOVIMENTO_DA_DIVIDA_PUBLICA.png  CONFIGURACAO_DE_MOVIMENTO_DA_DIVIDA_PUBLICA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_PAGAMENTO.png  CONFIGURACAO_DE_PAGAMENTO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_PAGAMENTO_DE_RESTO_A_PAGAR.png  CONFIGURACAO_DE_PAGAMENTO_DE_RESTO_A_PAGAR.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_PESSOA_CLASSE_E_CONTA_BANCARIA.png  CONFIGURACAO_DE_PESSOA_CLASSE_E_CONTA_BANCARIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_PROCURADORES_DA_DIVIDA_PUBLICA.png  CONFIGURACAO_DE_PROCURADORES_DA_DIVIDA_PUBLICA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_PROVISAO_MATEMATICA.png  CONFIGURACAO_DE_PROVISAO_MATEMATICA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_RECEITA_EXTRAORCAMENTARIA.png  CONFIGURACAO_DE_RECEITA_EXTRAORCAMENTARIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_RECEITA_REALIZADA.png  CONFIGURACAO_DE_RECEITA_REALIZADA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_RESTO_A_PAGAR.png  CONFIGURACAO_DE_RESTO_A_PAGAR.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_SUPRIMENTO_DE_FUNDOS.png  CONFIGURACAO_DE_SUPRIMENTO_DE_FUNDOS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_TRANSFERENCIA_DE_BENS_DE_ESTOQUE.png  CONFIGURACAO_DE_TRANSFERENCIA_DE_BENS_DE_ESTOQUE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_TRANSFERENCIA_DE_BENS_IMOVEIS.png  CONFIGURACAO_DE_TRANSFERENCIA_DE_BENS_IMOVEIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_TRANSFERENCIA_DE_BENS_INTANGIVEIS.png  CONFIGURACAO_DE_TRANSFERENCIA_DE_BENS_INTANGIVEIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_TRANSFERENCIA_DE_BENS_MOVEIS.png  CONFIGURACAO_DE_TRANSFERENCIA_DE_BENS_MOVEIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_TRANSFERENCIA_FINANCEIRA.png  CONFIGURACAO_DE_TRANSFERENCIA_FINANCEIRA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DE_TRANSFERENCIA_FINANCEIRA_MESMA_UNIDADE.png  CONFIGURACAO_DE_TRANSFERENCIA_FINANCEIRA_MESMA_UNIDADE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_DO_RELATORIO_DE_CALCULO_DE_IPTU.png  CONFIGURACAO_DO_RELATORIO_DE_CALCULO_DE_IPTU.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_GERAL_RH.png  CONFIGURACAO_GERAL_RH.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_LISTARELATORIO.png  CONFIGURACAO_LISTARELATORIO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_REGRA_APOSENTADORIA.png  CONFIGURACAO_REGRA_APOSENTADORIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACAO_TIPO_DE_DESPESACLASSE_CREDOR.png  CONFIGURACAO_TIPO_DE_DESPESACLASSE_CREDOR.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONFIGURACOES_DO_TRIBUTARIO.png  CONFIGURACOES_DO_TRIBUTARIO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONSELHO_DE_CLASSEORDEM.png  CONSELHO_DE_CLASSEORDEM.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONSULTA_DE_LEVANTAMENTO_DE_BENS_MOVEIS.png  CONSULTA_DE_LEVANTAMENTO_DE_BENS_MOVEIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONSULTA_DE_PROVIMENTOS_POR_SERVIDOR.png  CONSULTA_DE_PROVIMENTOS_POR_SERVIDOR.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONSULTA_DE_TAXAS_DO_RBTRANS.png  CONSULTA_DE_TAXAS_DO_RBTRANS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONSULTA_EXCEPTIONS.png  CONSULTA_EXCEPTIONS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONSULTA_LOCAL_DE_ESTOQUE.png  CONSULTA_LOCAL_DE_ESTOQUE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONSULTA_VAGAS_OCUPADAS_POR_UNIDADE.png  CONSULTA_VAGAS_OCUPADAS_POR_UNIDADE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONTABILIZACAO_DE_DIARIA.png  CONTABILIZACAO_DE_DIARIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONTABILIZACAO_DE_SUPRIMENTO_DE_FUNDOS.png  CONTABILIZACAO_DE_SUPRIMENTO_DE_FUNDOS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONTA_BANCARIA.png  CONTA_BANCARIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONTA_CORRENTE_BANCARIA.png  CONTA_CORRENTE_BANCARIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONTA_FINANCEIRA__CADASTRO.png  CONTA_FINANCEIRA__CADASTRO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONTRATOS.png  CONTRATOS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONTRATO_(NOMEACAO).png  CONTRATO_(NOMEACAO).dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONTRATO_DE_CEASA.png  CONTRATO_DE_CEASA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONTRATO_DE_RENDAS_PATRIMONIAIS.png  CONTRATO_DE_RENDAS_PATRIMONIAIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONTRIBUICAO.png  CONTRIBUICAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONVENIO_DE_DESPESA__LANCAMENTO.png  CONVENIO_DE_DESPESA__LANCAMENTO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONVENIO_DE_RECEITA__LANCAMENTO.png  CONVENIO_DE_RECEITA__LANCAMENTO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CONVOCACAO.png  CONVOCACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o COR.png  COR.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o COTACAO.png  COTACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o COTAS_PARA_ABASTECIMENTO.png  COTAS_PARA_ABASTECIMENTO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o COTA_ORCAMENTARIA.png  COTA_ORCAMENTARIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CREDITOS_A_RECEBER.png  CREDITOS_A_RECEBER.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o CREDITO_DE_SALARIO.png  CREDITO_DE_SALARIO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o DENUNCIA.png  DENUNCIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o DEPARA.png  DEPARA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o DEPENDENTE.png  DEPENDENTE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o DESMEMBRAMENTO.png  DESMEMBRAMENTO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o DESPESA_EXTRAORCAMENTARIA.png  DESPESA_EXTRAORCAMENTARIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o DETALHAMENTO_DE_FONTE_DE_RECURSOS.png  DETALHAMENTO_DE_FONTE_DE_RECURSOS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o DIARIA.png  DIARIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o DIARIA_DE_CAMPO_(AGRUPADOR).png  DIARIA_DE_CAMPO_(AGRUPADOR).dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o DIARIA_GRUPO.png  DIARIA_GRUPO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o DIARIO_DE_TRAFEGO.png  DIARIO_DE_TRAFEGO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o DIAS_NAO_UTEIS.png  DIAS_NAO_UTEIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o DISPENSAINEXIGIBILIDADE.png  DISPENSAINEXIGIBILIDADE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o DISTRITO.png  DISTRITO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o DIVIDA.png  DIVIDA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o DIVIDA_ATIVA__CONTABIL.png  DIVIDA_ATIVA__CONTABIL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o DOCUMENTO.png  DOCUMENTO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o DOCUMENTOS_COMPROBATORIOS.png  DOCUMENTOS_COMPROBATORIOS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o DOCUMENTOS_NECESSARIOS_QUE_DEVEM_SER_ANEXADOS.png  DOCUMENTOS_NECESSARIOS_QUE_DEVEM_SER_ANEXADOS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o DOCUMENTO_DE_HABILITACAO.png  DOCUMENTO_DE_HABILITACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o DOCUMENTO_PORTAL_SERVIDOR.png  DOCUMENTO_PORTAL_SERVIDOR.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o EDITAL_CONTRIBUICAO_DE_MELHORIAS.png  EDITAL_CONTRIBUICAO_DE_MELHORIAS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o EFETIVACAO_DA_ALIENACAO_DE_BEM_MOVEL.png  EFETIVACAO_DA_ALIENACAO_DE_BEM_MOVEL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o EFETIVACAO_DA_BAIXA_DE_BEM_IMOVEL.png  EFETIVACAO_DA_BAIXA_DE_BEM_IMOVEL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o EFETIVACAO_DA_BAIXA_DE_BEM_MOVEL.png  EFETIVACAO_DA_BAIXA_DE_BEM_MOVEL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o EFETIVACAO_DE_CESSAO_DE_BEM_MOVEL.png  EFETIVACAO_DE_CESSAO_DE_BEM_MOVEL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o EFETIVACAO_DE_ESTORNO_DE_TRANSFERENCIA_DE_BENS_IMOVEIS.png  EFETIVACAO_DE_ESTORNO_DE_TRANSFERENCIA_DE_BENS_IMOVEIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o EFETIVACAO_DE_ESTORNO_DE_TRANSFERENCIA_DE_BENS_MOVEIS.png  EFETIVACAO_DE_ESTORNO_DE_TRANSFERENCIA_DE_BENS_MOVEIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o EFETIVACAO_DE_LEVANTAMENTO_DE_BENS_IMOVEIS.png  EFETIVACAO_DE_LEVANTAMENTO_DE_BENS_IMOVEIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o EFETIVACAO_DE_LEVANTAMENTO_DE_BENS_MOVEIS.png  EFETIVACAO_DE_LEVANTAMENTO_DE_BENS_MOVEIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o EFETIVACAO_DE_LEVANTAMENTO_DE_ESTOQUE.png  EFETIVACAO_DE_LEVANTAMENTO_DE_ESTOQUE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o EFETIVACAO_DE_MATERIAL.png  EFETIVACAO_DE_MATERIAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o EFETIVACAO_DE_REAVALIACAO_DE_BENS_IMOVEIS.png  EFETIVACAO_DE_REAVALIACAO_DE_BENS_IMOVEIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o EFETIVACAO_DE_REAVALIACAO_DE_BENS_MOVEIS.png  EFETIVACAO_DE_REAVALIACAO_DE_BENS_MOVEIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o EFETIVACAO_DE_SOLICITACAO_DE_INCORPORACAO_MOVEL.png  EFETIVACAO_DE_SOLICITACAO_DE_INCORPORACAO_MOVEL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o EFETIVACAO_DE_TRANSFERENCIA_DE_BENS_IMOVEIS.png  EFETIVACAO_DE_TRANSFERENCIA_DE_BENS_IMOVEIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o EFETIVACAO_DE_TRANSFERENCIA_DE_BENS_MOVEIS.png  EFETIVACAO_DE_TRANSFERENCIA_DE_BENS_MOVEIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o EMISSAO_DE_CREDENCIAIS.png  EMISSAO_DE_CREDENCIAIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o EMISSAO_DE_NOTA_FISCAL_AVULSA.png  EMISSAO_DE_NOTA_FISCAL_AVULSA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o EMPENHO.png  EMPENHO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o EMPENHO_DE_RESTO_A_PAGAR.png  EMPENHO_DE_RESTO_A_PAGAR.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ENCERRAMENTO_DE_PROCESSO_FISCAL.png  ENCERRAMENTO_DE_PROCESSO_FISCAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ENCERRAMENTO_FUNCAO_GRATIFICADA.png  ENCERRAMENTO_FUNCAO_GRATIFICADA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ENQUADRAMENTO_DE_EXERCICIO_DE_REFERENCIA_DE_TRIBUTOS_COM_CONTAS_DE_RECEITA.png  ENQUADRAMENTO_DE_EXERCICIO_DE_REFERENCIA_DE_TRIBUTOS_COM_CONTAS_DE_RECEITA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ENQUADRAMENTO_FUNCIONAL.png  ENQUADRAMENTO_FUNCIONAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ENQUADRAMENTO_PCCR.png  ENQUADRAMENTO_PCCR.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ENTIDADE.png  ENTIDADE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ENTIDADE_BENEFICIARIA.png  ENTIDADE_BENEFICIARIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ENTIDADE_CONCEDENTE.png  ENTIDADE_CONCEDENTE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ENTIDADE_CONSIGNATARIA.png  ENTIDADE_CONSIGNATARIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o EQUIPAMENTOS.png  EQUIPAMENTOS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o EQUIPAMENTO_EPI.png  EQUIPAMENTO_EPI.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ESCRITORIO_CONTABIL_EOU_CONTADOR.png  ESCRITORIO_CONTABIL_EOU_CONTADOR.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ESFERA_DE_GOVERNO.png  ESFERA_DE_GOVERNO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ESTADO.png  ESTADO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ESTAGIARIOS.png  ESTAGIARIOS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ESTORNO_DESPESA_EXTRAORCAMENTARIA.png  ESTORNO_DESPESA_EXTRAORCAMENTARIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ESTORNO_DE_ALTERACAO_ORCAMENTARIA.png  ESTORNO_DE_ALTERACAO_ORCAMENTARIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ESTORNO_DE_EMPENHO.png  ESTORNO_DE_EMPENHO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ESTORNO_DE_LANCAMENTO_DE_ISS_ESTIMADO.png  ESTORNO_DE_LANCAMENTO_DE_ISS_ESTIMADO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ESTORNO_DE_LANCAMENTO_DE_ISS_FIXO.png  ESTORNO_DE_LANCAMENTO_DE_ISS_FIXO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ESTORNO_DE_LANCAMENTO_DE_ISS_MENSAL.png  ESTORNO_DE_LANCAMENTO_DE_ISS_MENSAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ESTORNO_DE_LIBERACAO_FINANCEIRA.png  ESTORNO_DE_LIBERACAO_FINANCEIRA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ESTORNO_DE_LIQUIDACAO.png  ESTORNO_DE_LIQUIDACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ESTORNO_DE_LIQUIDACAO_DE_RESTO_A_PAGAR.png  ESTORNO_DE_LIQUIDACAO_DE_RESTO_A_PAGAR.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ESTORNO_DE_ORDEM_BANCARIA.png  ESTORNO_DE_ORDEM_BANCARIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ESTORNO_DE_PAGAMENTO.png  ESTORNO_DE_PAGAMENTO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ESTORNO_DE_PAGAMENTO_DE_RESTO_A_PAGAR.png  ESTORNO_DE_PAGAMENTO_DE_RESTO_A_PAGAR.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ESTORNO_DE_RECEITA_REALIZADA.png  ESTORNO_DE_RECEITA_REALIZADA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ESTORNO_DE_TRANSFERENCIA_FINANCEIRA.png  ESTORNO_DE_TRANSFERENCIA_FINANCEIRA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ESTORNO_DE_TRANSFERENCIA_FINANCEIRA_MESMA_UNIDADE.png  ESTORNO_DE_TRANSFERENCIA_FINANCEIRA_MESMA_UNIDADE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ESTORNO_RECEITA_EXTRAORCAMENTARIA.png  ESTORNO_RECEITA_EXTRAORCAMENTARIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o EVENTO_CONTABIL.png  EVENTO_CONTABIL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o EVENTO_DE_CALCULO.png  EVENTO_DE_CALCULO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o EVENTO_DE_CAPACITACAO.png  EVENTO_DE_CAPACITACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o EVENTO_FP_(VERBAS).png  EVENTO_FP_(VERBAS).dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o EXERCICIO.png  EXERCICIO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o EXONERACAORESCISAO.png  EXONERACAORESCISAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o EXPORTAR_ARQUIVO_DE_MARGEM.png  EXPORTAR_ARQUIVO_DE_MARGEM.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o EXPORTAR_ARQUIVO_DE_RETORNO_ECONSIG.png  EXPORTAR_ARQUIVO_DE_RETORNO_ECONSIG.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o EXTENSAO_DA_FONTE_DE_RECURSO.png  EXTENSAO_DA_FONTE_DE_RECURSO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o EXTINCAO_DE_CARGOS.png  EXTINCAO_DE_CARGOS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o EXTINCAO_DO_PROCESSO_JUDICIAL.png  EXTINCAO_DO_PROCESSO_JUDICIAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o FAIXA_DE_ALVARA.png  FAIXA_DE_ALVARA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o FALTAS.png  FALTAS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o FAQ__PERGUNTAS_E_RESPOSTAS.png  FAQ__PERGUNTAS_E_RESPOSTAS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o FASE.png  FASE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o FASES.png  FASES.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o FATOR_DE_CORRECAO_E_PONTUACAO_IMOBILIARIA.png  FATOR_DE_CORRECAO_E_PONTUACAO_IMOBILIARIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o FATOR_DE_RISCO.png  FATOR_DE_RISCO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o FICHARIOS.png  FICHARIOS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o FINALIDADE.png  FINALIDADE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o FINALIDADE_DO_PAGAMENTO.png  FINALIDADE_DO_PAGAMENTO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o FISCALIZACAO_DE_TRANSITOTRANSPORTE.png  FISCALIZACAO_DE_TRANSITOTRANSPORTE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o FIXACAO_DA_DESPESA.png  FIXACAO_DA_DESPESA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o FONTE_DE_RECURSOS.png  FONTE_DE_RECURSOS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o FORMULARIO_DE_COTACAO.png  FORMULARIO_DE_COTACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o FORMULA_PADRAO_DA_FOLHA_DE_PAGAMENTO.png  FORMULA_PADRAO_DA_FOLHA_DE_PAGAMENTO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o FUNCAO.png  FUNCAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o FUNCIONAMENTO.png  FUNCIONAMENTO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o GERACAO_DE_CREDENCIAIS.png  GERACAO_DE_CREDENCIAIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o GERACAO_DO_ARQUIVO_DE_PERMISSIONARIOS_E_CONCESSIONARIOS.png  GERACAO_DO_ARQUIVO_DE_PERMISSIONARIOS_E_CONCESSIONARIOS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o GERACAO_E_EMISSAO_DE_LIVRO_DE_DIVIDA_ATIVA.png  GERACAO_E_EMISSAO_DE_LIVRO_DE_DIVIDA_ATIVA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o GERAR_ARQUIVO_SEFIP.png  GERAR_ARQUIVO_SEFIP.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o GERAR_PROGRESSOES_AUTOMATICAS.png  GERAR_PROGRESSOES_AUTOMATICAS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o GERAR__ATUARIAL.png  GERAR__ATUARIAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o GERIR_PROCESSOS.png  GERIR_PROCESSOS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o GRAFICA.png  GRAFICA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o GRAU_DE_PARENTESCO.png  GRAU_DE_PARENTESCO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o GRAU_DE_PARENTESCO_PARA_PENSIONISTA.png  GRAU_DE_PARENTESCO_PARA_PENSIONISTA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o GRUPO_DE_DOCUMENTO_OFICIAL.png  GRUPO_DE_DOCUMENTO_OFICIAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o GRUPO_DE_EXPORTACAO.png  GRUPO_DE_EXPORTACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o GRUPO_DE_MATERIAIS.png  GRUPO_DE_MATERIAIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o GRUPO_DE_OBJETO_DE_COMPRA.png  GRUPO_DE_OBJETO_DE_COMPRA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o GRUPO_DE_RECURSOS.png  GRUPO_DE_RECURSOS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o GRUPO_DE_SERVICO.png  GRUPO_DE_SERVICO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o GRUPO_DE_USUARIO.png  GRUPO_DE_USUARIO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o GRUPO_ORCAMENTARIO.png  GRUPO_ORCAMENTARIO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o GRUPO_PATRIMONIAL.png  GRUPO_PATRIMONIAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o GRUPO_PESSOA.png  GRUPO_PESSOA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o HABILIDADES.png  HABILIDADES.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o HABILITACAO_DE_FORNECEDORES.png  HABILITACAO_DE_FORNECEDORES.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o HISTORICO_CONTABIL.png  HISTORICO_CONTABIL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o HISTORICO_CONTABIL_CLP.png  HISTORICO_CONTABIL_CLP.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o HISTORICO_DA_FISCALIZACAO.png  HISTORICO_DA_FISCALIZACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o HISTORICO_DA_OUTORGA.png  HISTORICO_DA_OUTORGA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o HISTORICO_DE_INFORMACOES_DO_RBTRANS.png  HISTORICO_DE_INFORMACOES_DO_RBTRANS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o HISTORICO_DE_OCORRENCIAS.png  HISTORICO_DE_OCORRENCIAS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o HOMOLOGACAO.png  HOMOLOGACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o HORARIO_DE_FUNCIONAMENTO.png  HORARIO_DE_FUNCIONAMENTO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o HORARIO_DE_TRABALHO.png  HORARIO_DE_TRABALHO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o HORA_EXTRA.png  HORA_EXTRA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o IMPORTAR_ARQUIVO_DE_RETORNO.png  IMPORTAR_ARQUIVO_DE_RETORNO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o IMPORTAR_MOVIMENTO_FINANCEIRO_ECONSIG.png  IMPORTAR_MOVIMENTO_FINANCEIRO_ECONSIG.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o INDICADOR.png  INDICADOR.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o INDICADOR_ECONOMICO.png  INDICADOR_ECONOMICO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o INFORMACOES_DE_DECLARACOES.png  INFORMACOES_DE_DECLARACOES.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o INFORMACOES_GERAIS__RBTRANS.png  INFORMACOES_GERAIS__RBTRANS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o INFRACAO_FISCAL.png  INFRACAO_FISCAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o INFRACOES_E_PENALIDADES.png  INFRACOES_E_PENALIDADES.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o INSCRICAO.png  INSCRICAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o INSCRICAO_DE_DEBITOS_EM_DIVIDA_ATIVA.png  INSCRICAO_DE_DEBITOS_EM_DIVIDA_ATIVA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o INSCRICAO_PARA_EVENTO_DE_CAPACITACAO.png  INSCRICAO_PARA_EVENTO_DE_CAPACITACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o INTEGRACAO_ESTORNO_DE_RECEITA_REALIZADAARRECADACAO.png  INTEGRACAO_ESTORNO_DE_RECEITA_REALIZADAARRECADACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o INTEGRACAO_RECEITA_REALIZADAARRECADACAO.png  INTEGRACAO_RECEITA_REALIZADAARRECADACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o INTERVENIENTE.png  INTERVENIENTE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o INVENTARIO_DE_ESTOQUE.png  INVENTARIO_DE_ESTOQUE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o IRREGULARIDADE.png  IRREGULARIDADE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ISENCAO.png  ISENCAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o JORNADA_DE_TRABALHO.png  JORNADA_DE_TRABALHO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o JUSTIFICATIVA_DE_FALTAS.png  JUSTIFICATIVA_DE_FALTAS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o LANCAMENTOFP_POR_LOTES.png  LANCAMENTOFP_POR_LOTES.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o LANCAMENTOS_DE_TAXAS_PARA_VEICULOS.png  LANCAMENTOS_DE_TAXAS_PARA_VEICULOS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o LANCAMENTOS_FP.png  LANCAMENTOS_FP.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o LANCAMENTO_DE_CONTRIBUICAO_DE_MELHORIA.png  LANCAMENTO_DE_CONTRIBUICAO_DE_MELHORIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o LANCAMENTO_DE_DESCONTO.png  LANCAMENTO_DE_DESCONTO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o LANCAMENTO_DE_DIVIDAS_DIVERSAS.png  LANCAMENTO_DE_DIVIDAS_DIVERSAS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o LANCAMENTO_DE_ISS_FIXO__GERAL.png  LANCAMENTO_DE_ISS_FIXO__GERAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o LANCAMENTO_DE_ISS_FIXO__GERAL__EFETIVACAO.png  LANCAMENTO_DE_ISS_FIXO__GERAL__EFETIVACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o LANCAMENTO_DE_ITBI.png  LANCAMENTO_DE_ITBI.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o LANCAMENTO_DE_OUTORGA.png  LANCAMENTO_DE_OUTORGA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o LANCAMENTO_DE_TAXAS_DIVERSAS.png  LANCAMENTO_DE_TAXAS_DIVERSAS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o LAUDO.png  LAUDO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o LAYOUT_DE_ARQUIVO_BANCARIO.png  LAYOUT_DE_ARQUIVO_BANCARIO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o LDO.png  LDO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o LEVANTAMENTO_DE_ESTOQUE.png  LEVANTAMENTO_DE_ESTOQUE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o LIBERACAO_DE_COTA_ORCAMENTARIA.png  LIBERACAO_DE_COTA_ORCAMENTARIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o LIBERACAO_FINANCEIRA.png  LIBERACAO_FINANCEIRA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o LICITACAO.png  LICITACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o LIQUIDACAO.png  LIQUIDACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o LIQUIDACAO_DE_RESTO_A_PAGAR.png  LIQUIDACAO_DE_RESTO_A_PAGAR.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o LISTA_DE_PRECO.png  LISTA_DE_PRECO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o LISTA_DE_SERVICOS_(LEI_COMPLEMENTAR_1162003).png  LISTA_DE_SERVICOS_(LEI_COMPLEMENTAR_1162003).dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o LOA.png  LOA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o LOCALIZACAO.png  LOCALIZACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o LOCALIZACAO_DE_PROCESSOS.png  LOCALIZACAO_DE_PROCESSOS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o LOCALIZACAO_DE_PROTOCOLOS.png  LOCALIZACAO_DE_PROTOCOLOS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o LOCALIZACAO_E_PONTOS_COMERCIAIS.png  LOCALIZACAO_E_PONTOS_COMERCIAIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o LOCAL_DE_ESTOQUE.png  LOCAL_DE_ESTOQUE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o LOCAL_DE_EVENTO.png  LOCAL_DE_EVENTO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o LOGRADOURO.png  LOGRADOURO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o LOTACAO.png  LOTACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o LOTEAMENTO.png  LOTEAMENTO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o LOTE_DE_MATERIAL.png  LOTE_DE_MATERIAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o LOTE_PROCESSAMENTO.png  LOTE_PROCESSAMENTO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o MALA_DIRETA.png  MALA_DIRETA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o MALA_DIRETA__RBTRANS.png  MALA_DIRETA__RBTRANS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o MANUTENCOES.png  MANUTENCOES.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o MAPA_COMPARATIVO.png  MAPA_COMPARATIVO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o MAPA_COMPARATIVO_TECNICA_E_PRECO.png  MAPA_COMPARATIVO_TECNICA_E_PRECO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o MARCA.png  MARCA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o MATERIAL.png  MATERIAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o MATERIAL_PERMANENTE.png  MATERIAL_PERMANENTE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o MATRICULA.png  MATRICULA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o MEDICO.png  MEDICO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o MEDIDAS_ADMINISTRATIVAS.png  MEDIDAS_ADMINISTRATIVAS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o MENU.png  MENU.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o METAS_FISCAIS.png  METAS_FISCAIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o METODOLOGIA.png  METODOLOGIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o METODO_CIENTIFICO.png  METODO_CIENTIFICO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o MODALIDADE_DE_BENEFICIOS.png  MODALIDADE_DE_BENEFICIOS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o MODALIDADE_DE_CONTRATOS.png  MODALIDADE_DE_CONTRATOS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o MODELO.png  MODELO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o MODELO_DE_DOCUMENTO.png  MODELO_DE_DOCUMENTO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o MODULOS_PARA_EXPORTACAO.png  MODULOS_PARA_EXPORTACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o MONITORAMENTO_LOGIN__NODE.png  MONITORAMENTO_LOGIN__NODE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o MOTIVOS_DE_REJEICAO.png  MOTIVOS_DE_REJEICAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o MOTIVO_DE_DESLIGAMENTO_DA_RAIS.png  MOTIVO_DE_DESLIGAMENTO_DA_RAIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o MOTIVO_DE_DESLIGAMENTO_PARA_FGTS.png  MOTIVO_DE_DESLIGAMENTO_PARA_FGTS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o MOTIVO_DE_EXONERACAORESCISAO.png  MOTIVO_DE_EXONERACAORESCISAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o MOTORISTA.png  MOTORISTA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o MOVIMENTO_CAGED.png  MOVIMENTO_CAGED.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o MOVIMENTO_DIVIDA_PUBLICA.png  MOVIMENTO_DIVIDA_PUBLICA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o MOVIMENTO_SEFIP.png  MOVIMENTO_SEFIP.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o MULTAS.png  MULTAS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o MULTA_DO_PROCESSO_FISCAL.png  MULTA_DO_PROCESSO_FISCAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o MUNICIPIO.png  MUNICIPIO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o NACIONALIDADE.png  NACIONALIDADE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o NATUREZA_DA_DIVIDA.png  NATUREZA_DA_DIVIDA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o NATUREZA_DE_RENDIMENTO_PARA_A_DIRF.png  NATUREZA_DE_RENDIMENTO_PARA_A_DIRF.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o NATUREZA_JURIDICA__RH.png  NATUREZA_JURIDICA__RH.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o NATUREZA_JURIDICA__TRIBUTARIO.png  NATUREZA_JURIDICA__TRIBUTARIO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o NFSE__INTEGRACAO.png  NFSE__INTEGRACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o NIVEL_DE_ESCOLARIDADE.png  NIVEL_DE_ESCOLARIDADE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o OBJETO_DE_COMPRA__CADASTRO.png  OBJETO_DE_COMPRA__CADASTRO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o OBRAS__CADASTRO.png  OBRAS__CADASTRO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o OCC__CLASSE_DE_PESSOA.png  OCC__CLASSE_DE_PESSOA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o OCC__CONTA_DE_DESPESA.png  OCC__CONTA_DE_DESPESA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o OCC__CONTA_DE_DESTINACAO.png  OCC__CONTA_DE_DESTINACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o OCC__CONTA_DE_RECEITA.png  OCC__CONTA_DE_RECEITA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o OCC__CONTA_EXTRAORCAMENTARIA.png  OCC__CONTA_EXTRAORCAMENTARIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o OCC__CONTA_FINANCEIRA.png  OCC__CONTA_FINANCEIRA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o OCC__GRUPO_DE_MATERIAL.png  OCC__GRUPO_DE_MATERIAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o OCC__GRUPO_PATRIMONIAL__CONTABIL.png  OCC__GRUPO_PATRIMONIAL__CONTABIL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o OCC__NATUREZA_DA_DIVIDA_PUBLICA.png  OCC__NATUREZA_DA_DIVIDA_PUBLICA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o OCC__ORIGEM_DE_RECURSO.png  OCC__ORIGEM_DE_RECURSO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o OCC__TIPO_PASSIVO_ATUARIAL__CONTABIL.png  OCC__TIPO_PASSIVO_ATUARIAL__CONTABIL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o OCORRENCIAS.png  OCORRENCIAS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o OCORRENCIAS_CONVENIOS.png  OCORRENCIAS_CONVENIOS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o OCORRENCIAS__CONTABIL.png  OCORRENCIAS__CONTABIL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o OCORRENCIA_SEFIP.png  OCORRENCIA_SEFIP.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o OPCAO_DE_PAGAMENTO.png  OPCAO_DE_PAGAMENTO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o OPCAO_SALARIAL_CC.png  OPCAO_SALARIAL_CC.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o ORDEM_BANCARIA.png  ORDEM_BANCARIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PAGAMENTO.png  PAGAMENTO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PAGAMENTO_DE_RESTO_A_PAGAR.png  PAGAMENTO_DE_RESTO_A_PAGAR.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PAIS.png  PAIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PARAMETROS_DA_LICENCA_PREMIO.png  PARAMETROS_DA_LICENCA_PREMIO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PARAMETROS_DE_ITBI.png  PARAMETROS_DE_ITBI.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PARAMETROS_DE_MATERIAIS.png  PARAMETROS_DE_MATERIAIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PARAMETROS_DE_RENDAS_PATRIMONIAIS__CEASA.png  PARAMETROS_DE_RENDAS_PATRIMONIAIS__CEASA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PARAMETROS_DE_SUBVENCAO.png  PARAMETROS_DE_SUBVENCAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PARAMETROS_DE_TRANSITO_E_TRANSPORTE.png  PARAMETROS_DE_TRANSITO_E_TRANSPORTE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PARAMETROS_DIVIDA_ATIVA.png  PARAMETROS_DIVIDA_ATIVA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PARAMETROS_DO_PARCELAMENTO.png  PARAMETROS_DO_PARCELAMENTO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PARAMETROS_DO_PATRIMONIO.png  PARAMETROS_DO_PATRIMONIO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PARAMETROS_DO_TIPO_DE_DIVIDAS_DIVERSAS.png  PARAMETROS_DO_TIPO_DE_DIVIDAS_DIVERSAS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PARAMETROS_FROTA.png  PARAMETROS_FROTA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PARAMETROS_LDO.png  PARAMETROS_LDO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PARAMETROS_PROCURADORIA.png  PARAMETROS_PROCURADORIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PARAMETRO_DE_CALCULO_DA_INDENIZACAO.png  PARAMETRO_DE_CALCULO_DA_INDENIZACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PARAMETRO_DE_COBRANCA_ADMINISTRATIVA.png  PARAMETRO_DE_COBRANCA_ADMINISTRATIVA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PARAMETRO_DE_EXPORTACAO_DE_IPTU.png  PARAMETRO_DE_EXPORTACAO_DE_IPTU.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PARCELAMENTO.png  PARCELAMENTO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PARECER_DA_LICITACAO.png  PARECER_DA_LICITACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PARECER_DA_TRANSFERENCIA_DE_MOVIMENTOS_DA_PESSOA.png  PARECER_DA_TRANSFERENCIA_DE_MOVIMENTOS_DA_PESSOA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PARECER_DE_BAIXA_DE_BEM_IMOVEL.png  PARECER_DE_BAIXA_DE_BEM_IMOVEL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PARECER_DE_BAIXA_DE_BEM_MOVEL.png  PARECER_DE_BAIXA_DE_BEM_MOVEL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PARTE_DO_CORPO.png  PARTE_DO_CORPO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PARTICIPANTES_DE_LICITACAO.png  PARTICIPANTES_DE_LICITACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PCMSO.png  PCMSO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PECAS.png  PECAS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PENALIDADE.png  PENALIDADE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PENALIDADE_FISCAL.png  PENALIDADE_FISCAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PENDENCIA_DA_CONCILIACAO.png  PENDENCIA_DA_CONCILIACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PENHORA.png  PENHORA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PENSAO_ALIMENTICIA.png  PENSAO_ALIMENTICIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PENSAO_PREVIDENCIARIA.png  PENSAO_PREVIDENCIARIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PERIODICIDADE.png  PERIODICIDADE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PERIODO_DA_FASE.png  PERIODO_DA_FASE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PERMISSAO_DE_TRANSPORTE.png  PERMISSAO_DE_TRANSPORTE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PESSOA_(CORRECAO_DE_DADOS).png  PESSOA_(CORRECAO_DE_DADOS).dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PESSOA_(PERFIL_DEPENDENTE).png  PESSOA_(PERFIL_DEPENDENTE).dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PESSOA_(PERFIL_PENSIONISTA).png  PESSOA_(PERFIL_PENSIONISTA).dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PESSOA_(PERFIL_RH).png  PESSOA_(PERFIL_RH).dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PESSOA_ESPECIAL.png  PESSOA_ESPECIAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PESSOA_FISICA_(CREDOR).png  PESSOA_FISICA_(CREDOR).dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PESSOA_JURIDICA_(CREDOR).png  PESSOA_JURIDICA_(CREDOR).dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PLANEJAMENTO_ESTRATEGICO.png  PLANEJAMENTO_ESTRATEGICO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PLANO_CARGOS_CARREIRA_E_REMUNERACAO_PCCR.png  PLANO_CARGOS_CARREIRA_E_REMUNERACAO_PCCR.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PLANO_DE_CONTAS_(DESPESARECEITADESTINACAO_DE_RECURSO).png  PLANO_DE_CONTAS_(DESPESARECEITADESTINACAO_DE_RECURSO).dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PLANO_DE_CONTAS_(PASSOAPASSO).png  PLANO_DE_CONTAS_(PASSOAPASSO).dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PLANO_DE_CONTAS_EXERCICIO.png  PLANO_DE_CONTAS_EXERCICIO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o POLITICA_DE_ESTOQUE.png  POLITICA_DE_ESTOQUE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PONTO_DE_TAXI.png  PONTO_DE_TAXI.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PPA.png  PPA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PPRA.png  PPRA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PREGAO_POR_LOTE_DE_MATERIAL_E_SERVICO.png  PREGAO_POR_LOTE_DE_MATERIAL_E_SERVICO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PREVISAO_INICIAL_DA_RECEITA.png  PREVISAO_INICIAL_DA_RECEITA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PREVISAO_RECEITA_PPA.png  PREVISAO_RECEITA_PPA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PROCESSO_DE_ALTERACAO_DE_VENCIMENTO_DA_PARCELA.png  PROCESSO_DE_ALTERACAO_DE_VENCIMENTO_DA_PARCELA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PROCESSO_DE_ANISTIA.png  PROCESSO_DE_ANISTIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PROCESSO_DE_ATIVACAOINATIVACAO_CADASTRAL_DE_IMOVEL.png  PROCESSO_DE_ATIVACAOINATIVACAO_CADASTRAL_DE_IMOVEL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PROCESSO_DE_BAIXA.png  PROCESSO_DE_BAIXA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PROCESSO_DE_CANCELAMENTO.png  PROCESSO_DE_CANCELAMENTO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PROCESSO_DE_COMPRA.png  PROCESSO_DE_COMPRA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PROCESSO_DE_DACAO.png  PROCESSO_DE_DACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PROCESSO_DE_DECADENCIA.png  PROCESSO_DE_DECADENCIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PROCESSO_DE_DEDUCAO_DE_ACRESCIMOS.png  PROCESSO_DE_DEDUCAO_DE_ACRESCIMOS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PROCESSO_DE_DESISTENCIA.png  PROCESSO_DE_DESISTENCIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PROCESSO_DE_INATIVACAOATIVACAO_CADASTRAL_DE_PESSOA.png  PROCESSO_DE_INATIVACAOATIVACAO_CADASTRAL_DE_PESSOA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PROCESSO_DE_ISENCAO_DE_DEBITOS.png  PROCESSO_DE_ISENCAO_DE_DEBITOS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PROCESSO_DE_ISENCAO_DE_IPTU.png  PROCESSO_DE_ISENCAO_DE_IPTU.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PROCESSO_DE_PRESCRICAO.png  PROCESSO_DE_PRESCRICAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PROCESSO_DE_REMISSAO.png  PROCESSO_DE_REMISSAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PROCESSO_DE_SUBVENCAO.png  PROCESSO_DE_SUBVENCAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PROCESSO_DE_SUSPENSAO.png  PROCESSO_DE_SUSPENSAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PROCESSO_DE_SUSPENSAO__REATIVACAO.png  PROCESSO_DE_SUSPENSAO__REATIVACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PROCESSO_FISCAL.png  PROCESSO_FISCAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PROCESSO_JUDICIAL.png  PROCESSO_JUDICIAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PROCESSO__CRIAR.png  PROCESSO__CRIAR.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PRODUCAO_PROPRIA.png  PRODUCAO_PROPRIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PROFISSAO.png  PROFISSAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PROFISSIONAL_CONFEA.png  PROFISSIONAL_CONFEA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PROGRAMACAO_DA_LICENCA_PREMIO.png  PROGRAMACAO_DA_LICENCA_PREMIO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PROGRAMACAO_DE_COBRANCA.png  PROGRAMACAO_DE_COBRANCA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PROGRAMACAO_DE_FERIAS.png  PROGRAMACAO_DE_FERIAS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PROGRAMACAO_FISCAL.png  PROGRAMACAO_FISCAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PROGRAMAS.png  PROGRAMAS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PROGRESSAO.png  PROGRESSAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PROGRESSAO_PCCR.png  PROGRESSAO_PCCR.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PROJECAO_ATUARIAL.png  PROJECAO_ATUARIAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PROJETOATIVIDADE.png  PROJETOATIVIDADE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PROMOCAO.png  PROMOCAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PROPOSTA_DO_FORNECEDOR.png  PROPOSTA_DO_FORNECEDOR.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PROPOSTA_TECNICA_DO_FORNECEDOR.png  PROPOSTA_TECNICA_DO_FORNECEDOR.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PRORROGACAO.png  PRORROGACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PROTECAO_EPI.png  PROTECAO_EPI.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PROTOCOLO__CRIAR.png  PROTOCOLO__CRIAR.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PROVISAO_MATEMATICA_PREVIDENCIARIA.png  PROVISAO_MATEMATICA_PREVIDENCIARIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PUBLICACAO.png  PUBLICACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o PUBLICO_ALVO.png  PUBLICO_ALVO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o QUADRA.png  QUADRA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o READAPTACAO.png  READAPTACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o READEQUACAO_DA_RECEITA.png  READEQUACAO_DA_RECEITA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o REAJUSTE_DE_ENQUADRAMENTO_PCCR.png  REAJUSTE_DE_ENQUADRAMENTO_PCCR.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o RECEITA_EXTRAORCAMENTARIA.png  RECEITA_EXTRAORCAMENTARIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o RECEITA_REALIZADA.png  RECEITA_REALIZADA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o RECURSOS_DA_LICITACAO.png  RECURSOS_DA_LICITACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o RECURSO_CONCURSO.png  RECURSO_CONCURSO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o RECURSO_DO_SISTEMA.png  RECURSO_DO_SISTEMA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o RECURSO_DO_VINCULO_FP.png  RECURSO_DO_VINCULO_FP.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o RECURSO_FP.png  RECURSO_FP.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o REFERENCIAS_DO_REAJUSTE_MEDIA.png  REFERENCIAS_DO_REAJUSTE_MEDIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o REFERENCIAS_FP.png  REFERENCIAS_FP.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o REFERENCIA_ANUAL.png  REFERENCIA_ANUAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o REFERENCIA_REAJUSTE_APOSENTADORIA.png  REFERENCIA_REAJUSTE_APOSENTADORIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o REGISTRO_DE_OBITO.png  REGISTRO_DE_OBITO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o REINTEGRACAO.png  REINTEGRACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o RELATORIOS_ITEM_DEMONSTRATIVO.png  RELATORIOS_ITEM_DEMONSTRATIVO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o RELATORIO_DE_BENS_PATRIMONIAIS_MOBILIARIOS_POR_GRUPO_DE_OBJETO_DE_COMPRA.png  RELATORIO_DE_BENS_PATRIMONIAIS_MOBILIARIOS_POR_GRUPO_DE_OBJETO_DE_COMPRA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o RELATORIO_DE_LANCAMENTO_GERAL_DE_ISS_FIXO.png  RELATORIO_DE_LANCAMENTO_GERAL_DE_ISS_FIXO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o RELATORIO_DE_LEVANTAMENTO_DE_BENS_MOVEIS.png  RELATORIO_DE_LEVANTAMENTO_DE_BENS_MOVEIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o RELATORIO_DE_LEVANTAMENTO_DE_BENS_MOVEIS_COM_REGISTRO_PATRIMONIAL_REPETIDO.png  RELATORIO_DE_LEVANTAMENTO_DE_BENS_MOVEIS_COM_REGISTRO_PATRIMONIAL_REPETIDO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o RENOVACAO_AUTOMATICA_DE_CONTRATOS_DE_CEASA.png  RENOVACAO_AUTOMATICA_DE_CONTRATOS_DE_CEASA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o RENOVACAO_AUTOMATICA_DE_CONTRATOS_DE_RENDAS_PATRIMONIAIS.png  RENOVACAO_AUTOMATICA_DE_CONTRATOS_DE_RENDAS_PATRIMONIAIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o RENOVACAO_DE_PERMISSAO.png  RENOVACAO_DE_PERMISSAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o RENUNCIA_DA_RECEITA.png  RENUNCIA_DA_RECEITA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o REPACTUACAO_DE_PRECO.png  REPACTUACAO_DE_PRECO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o REQUISICAO_DE_COMPRAS.png  REQUISICAO_DE_COMPRAS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o REQUISICOES.png  REQUISICOES.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o RESERVAS.png  RESERVAS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o RESERVA_DE_DOTACAO.png  RESERVA_DE_DOTACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o RESERVA_DE_DOTACAO_PARA_SOLICITACAO_DE_COMPRA.png  RESERVA_DE_DOTACAO_PARA_SOLICITACAO_DE_COMPRA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o RESPONSAVEL_TECNICOFISCAL.png  RESPONSAVEL_TECNICOFISCAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o RESPONSAVEL_UNIDADE.png  RESPONSAVEL_UNIDADE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o RETENCAO_IRRF.png  RETENCAO_IRRF.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o RETORNO_AO_CARGO_DE_CARREIRA.png  RETORNO_AO_CARGO_DE_CARREIRA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o RETORNO_DAS_CEDENCIAS.png  RETORNO_DAS_CEDENCIAS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o REVERSAO.png  REVERSAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o REVISAO_DE_CALCULO_DE_IPTU.png  REVISAO_DE_CALCULO_DE_IPTU.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o REVISAO_DE_CALCULO_DE_IPTU_POR_LOTE.png  REVISAO_DE_CALCULO_DE_IPTU_POR_LOTE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o REVISOES.png  REVISOES.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o RISCO.png  RISCO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o RISCO_FISCAL.png  RISCO_FISCAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SALDO_CONSTANTE.png  SALDO_CONSTANTE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SECRETARIA.png  SECRETARIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SERIE_DE_NOTA_FISCAL.png  SERIE_DE_NOTA_FISCAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SERVICOS_DE_VISTORIA.png  SERVICOS_DE_VISTORIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SERVICO_URBANO.png  SERVICO_URBANO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SERVICO__CADASTRO.png  SERVICO__CADASTRO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SETOR.png  SETOR.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SEXTA_PARTE.png  SEXTA_PARTE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SICAP.png  SICAP.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SINDICATO.png  SINDICATO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SIPREV.png  SIPREV.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SISTEMA_DE_CADASTRAMENTO_UNIFICADO_DE_FORNECEDORES_�_SICAFRB.png  SISTEMA_DE_CADASTRAMENTO_UNIFICADO_DE_FORNECEDORES_�_SICAFRB.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SITUACAO_ACIDENTE.png  SITUACAO_ACIDENTE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SITUACAO_DO_PARECER.png  SITUACAO_DO_PARECER.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SITUACAO_DO_TRAMITE_JUDICIAL.png  SITUACAO_DO_TRAMITE_JUDICIAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SITUACAO_FUNCIONAL.png  SITUACAO_FUNCIONAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SOLICITACAO_DA_PRORROGACAO_DA_CESSAO_DE_BEM_MOVEL.png  SOLICITACAO_DA_PRORROGACAO_DA_CESSAO_DE_BEM_MOVEL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SOLICITACAO_DE_ADESAO_A_ATA_DE_REGISTRO_DE_PRECO.png  SOLICITACAO_DE_ADESAO_A_ATA_DE_REGISTRO_DE_PRECO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SOLICITACAO_DE_ALIENACAO_DE_BEM_MOVEL.png  SOLICITACAO_DE_ALIENACAO_DE_BEM_MOVEL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SOLICITACAO_DE_BAIXA_DE_BEM_IMOVEL.png  SOLICITACAO_DE_BAIXA_DE_BEM_IMOVEL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SOLICITACAO_DE_BAIXA_DE_BEM_MOVEL.png  SOLICITACAO_DE_BAIXA_DE_BEM_MOVEL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SOLICITACAO_DE_CANCELAMENTO_DE_RESERVA_DE_DOTACAO.png  SOLICITACAO_DE_CANCELAMENTO_DE_RESERVA_DE_DOTACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SOLICITACAO_DE_CESSAO_DE_BEM_MOVEL.png  SOLICITACAO_DE_CESSAO_DE_BEM_MOVEL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SOLICITACAO_DE_COMPRA__LICITACAO.png  SOLICITACAO_DE_COMPRA__LICITACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SOLICITACAO_DE_ESTORNO_DE_TRANSFERENCIA_DE_BENS_IMOVEIS.png  SOLICITACAO_DE_ESTORNO_DE_TRANSFERENCIA_DE_BENS_IMOVEIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SOLICITACAO_DE_ESTORNO_DE_TRANSFERENCIA_DE_BENS_MOVEIS.png  SOLICITACAO_DE_ESTORNO_DE_TRANSFERENCIA_DE_BENS_MOVEIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SOLICITACAO_DE_INCORPORACAO_DE_BEM_MOVEL.png  SOLICITACAO_DE_INCORPORACAO_DE_BEM_MOVEL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SOLICITACAO_DE_REAVALIACAO_DE_BENS_IMOVEIS.png  SOLICITACAO_DE_REAVALIACAO_DE_BENS_IMOVEIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SOLICITACAO_DE_REAVALIACAO_DE_BENS_MOVEIS.png  SOLICITACAO_DE_REAVALIACAO_DE_BENS_MOVEIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SOLICITACAO_DE_REPOSICAO_DE_ESTOQUE.png  SOLICITACAO_DE_REPOSICAO_DE_ESTOQUE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SOLICITACAO_DE_RESPONSAVEL_TECNICOFISCAL.png  SOLICITACAO_DE_RESPONSAVEL_TECNICOFISCAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SOLICITACAO_DE_TRANSFERENCIA_DE_BEM_MOVEL.png  SOLICITACAO_DE_TRANSFERENCIA_DE_BEM_MOVEL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SOLICITACAO_DE_TRANSFERENCIA_DE_BENS_IMOVEIS.png  SOLICITACAO_DE_TRANSFERENCIA_DE_BENS_IMOVEIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SOLICITACAO_DE_TRANSFERENCIA_DE_MOVIMENTOS_DA_PESSOA.png  SOLICITACAO_DE_TRANSFERENCIA_DE_MOVIMENTOS_DA_PESSOA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SOLICITACAO_E_EMISSAO_DE_CERTIDAO_E_DOCUMENTO_OFICIAL.png  SOLICITACAO_E_EMISSAO_DE_CERTIDAO_E_DOCUMENTO_OFICIAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SOLICITACAO_FINANCEIRA.png  SOLICITACAO_FINANCEIRA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SOLICITACOES.png  SOLICITACOES.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o STATUS_DA_LICITACAO.png  STATUS_DA_LICITACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SUBASSUNTO.png  SUBASSUNTO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o SUBFUNCAO.png  SUBFUNCAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TABELA_DE_DIARIAS.png  TABELA_DE_DIARIAS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TAG_OCC.png  TAG_OCC.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TAREFA_DO_AUDITOR_FISCAL.png  TAREFA_DO_AUDITOR_FISCAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TAXAS_DE_VEICULOS.png  TAXAS_DE_VEICULOS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TERMO_DE_DIARIA_DE_COLABORADOR_EVENTUAL.png  TERMO_DE_DIARIA_DE_COLABORADOR_EVENTUAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TIPOS_DE_DENUNCIA.png  TIPOS_DE_DENUNCIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TIPOS_DE_MULTAS.png  TIPOS_DE_MULTAS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TIPOS_DE_OCORRENCIAS.png  TIPOS_DE_OCORRENCIAS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TIPO_CONTA_AUXILIAR.png  TIPO_CONTA_AUXILIAR.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TIPO_DE_ACAO.png  TIPO_DE_ACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TIPO_DE_ADMISSAO_FGTS.png  TIPO_DE_ADMISSAO_FGTS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TIPO_DE_ADMISSAO_RAIS.png  TIPO_DE_ADMISSAO_RAIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TIPO_DE_AFASTAMENTO.png  TIPO_DE_AFASTAMENTO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TIPO_DE_APOSENTADORIA.png  TIPO_DE_APOSENTADORIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TIPO_DE_AREA_RURAL.png  TIPO_DE_AREA_RURAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TIPO_DE_AUTONOMO.png  TIPO_DE_AUTONOMO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TIPO_DE_BAIXA_DE_BENS.png  TIPO_DE_BAIXA_DE_BENS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TIPO_DE_BASE_FP.png  TIPO_DE_BASE_FP.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TIPO_DE_CONCILIACAO.png  TIPO_DE_CONCILIACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TIPO_DE_DEPENDENTE.png  TIPO_DE_DEPENDENTE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TIPO_DE_DIVIDAS_DIVERSAS.png  TIPO_DE_DIVIDAS_DIVERSAS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TIPO_DE_DOCUMENTO.png  TIPO_DE_DOCUMENTO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TIPO_DE_DOCUMENTO_DE_HABILITACAO.png  TIPO_DE_DOCUMENTO_DE_HABILITACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TIPO_DE_DOCUMENTO_FISCAL.png  TIPO_DE_DOCUMENTO_FISCAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TIPO_DE_DOCUMENTO_OFICIAL.png  TIPO_DE_DOCUMENTO_OFICIAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TIPO_DE_EXAME.png  TIPO_DE_EXAME.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TIPO_DE_INGRESSO_BENS.png  TIPO_DE_INGRESSO_BENS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TIPO_DE_INTERVENIENTES.png  TIPO_DE_INTERVENIENTES.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TIPO_DE_ISENCAOIMUNIDADE_DE_ITBI.png  TIPO_DE_ISENCAOIMUNIDADE_DE_ITBI.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TIPO_DE_LOGRADOURO.png  TIPO_DE_LOGRADOURO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TIPO_DE_NEGOCIACAO_DE_ITBI.png  TIPO_DE_NEGOCIACAO_DE_ITBI.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TIPO_DE_PENALIDADE.png  TIPO_DE_PENALIDADE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TIPO_DE_PLANO_DE_CONTAS.png  TIPO_DE_PLANO_DE_CONTAS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TIPO_DE_PONTO_COMERCIAL.png  TIPO_DE_PONTO_COMERCIAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TIPO_DE_PREVIDENCIA.png  TIPO_DE_PREVIDENCIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TIPO_DE_PROVIMENTO.png  TIPO_DE_PROVIMENTO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TIPO_DE_REDUCAO_DE_GRUPO_BEM.png  TIPO_DE_REDUCAO_DE_GRUPO_BEM.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TIPO_DE_REGIME_JURIDICO.png  TIPO_DE_REGIME_JURIDICO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TIPO_DE_SAQUE.png  TIPO_DE_SAQUE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TIPO_DE_VEICULO.png  TIPO_DE_VEICULO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TIPO_DE_VINCULO_DO_BEM.png  TIPO_DE_VINCULO_DO_BEM.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TIPO_PASSIVO_ATUARIAL.png  TIPO_PASSIVO_ATUARIAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TIPO_SEXTA_PARTE.png  TIPO_SEXTA_PARTE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TOMADOR_DE_SERVICO.png  TOMADOR_DE_SERVICO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TRAMITE.png  TRAMITE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TRANSFERENCIAS.png  TRANSFERENCIAS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TRANSFERENCIA_DE_BENS_DE_ESTOQUE.png  TRANSFERENCIA_DE_BENS_DE_ESTOQUE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TRANSFERENCIA_DE_BENS_IMOVEIS.png  TRANSFERENCIA_DE_BENS_IMOVEIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TRANSFERENCIA_DE_BENS_INTANGIVEIS.png  TRANSFERENCIA_DE_BENS_INTANGIVEIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TRANSFERENCIA_DE_BENS_MOVEIS.png  TRANSFERENCIA_DE_BENS_MOVEIS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TRANSFERENCIA_DE_PERMISSAO.png  TRANSFERENCIA_DE_PERMISSAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TRANSFERENCIA_FINANCEIRA.png  TRANSFERENCIA_FINANCEIRA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TRANSFERENCIA_FINANCEIRA_MESMA_UNIDADE.png  TRANSFERENCIA_FINANCEIRA_MESMA_UNIDADE.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TRANSPORTE_DE_CONFIGURACOES_E_OCC.png  TRANSPORTE_DE_CONFIGURACOES_E_OCC.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TRIBUNAL.png  TRIBUNAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TRIBUTO.png  TRIBUTO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o TRIBUTOS_DE_TAXASDIVIDAS_DIVERSAS.png  TRIBUTOS_DE_TAXASDIVIDAS_DIVERSAS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o UNIDADE_DE_MEDIDA.png  UNIDADE_DE_MEDIDA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o UNIDADE_EXTERNA.png  UNIDADE_EXTERNA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o UNIDADE_GESTORA.png  UNIDADE_GESTORA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o UNIDADE_JUDICIARIA.png  UNIDADE_JUDICIARIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o UNIDADE_ORGANIZACIONAL.png  UNIDADE_ORGANIZACIONAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o UNIDADE_ORGANIZACIONAL_GERAL.png  UNIDADE_ORGANIZACIONAL_GERAL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o USUARIO.png  USUARIO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o VALORES_DO_INDICE_ECONOMICO.png  VALORES_DO_INDICE_ECONOMICO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o VARA.png  VARA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o VARA_CIVEL.png  VARA_CIVEL.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o VEICULOS.png  VEICULOS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o VEICULO_DE_PUBLICACAO.png  VEICULO_DE_PUBLICACAO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o VIAGENS.png  VIAGENS.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o VIGILANCIA_SANITARIA.png  VIGILANCIA_SANITARIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o VINCULO_DE_CONTRATO.png  VINCULO_DE_CONTRATO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o VINCULO_EMPREGATICIO_�_CADASTRO.png  VINCULO_EMPREGATICIO_�_CADASTRO.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o VISTORIA.png  VISTORIA.dot
"C:\Program Files (x86)\Graphviz2.38\bin\dot" -T png -o VISTORIA_DE_FISCALIZACAO.png  VISTORIA_DE_FISCALIZACAO.dot
